/* Generated by build.mjs from the Leviathan console registry. Do not edit; rebuild instead. */
globalThis.LV_REGISTRY = {
 "version": "1.0.0",
 "consoleVersion": "1.2.0",
 "compiled": "2026-10-06",
 "wings": [
  {
   "id": "core",
   "label": "Core",
   "mods": [
    "core",
    "hitboard"
   ]
  },
  {
   "id": "legal",
   "label": "Legal",
   "mods": [
    "criminal",
    "criminal_la",
    "injury",
    "injury_la",
    "family",
    "employment"
   ]
  },
  {
   "id": "home",
   "label": "Home services",
   "mods": [
    "hvac",
    "dfw",
    "roofing",
    "plumbing",
    "pest"
   ]
  },
  {
   "id": "health",
   "label": "Healthcare",
   "mods": [
    "oncology",
    "dental",
    "ocular"
   ]
  }
 ],
 "modules": [
  {
   "id": "core",
   "wing": "core",
   "wingLabel": "Core",
   "vertical": "Agency intelligence",
   "short": "OmegaWeapon",
   "name": null,
   "title": "Pulse · OmegaWeapon",
   "sub": "Agency Radar, the Horus lens, the Offshore wing and the Targets wing in one app",
   "navTitle": null,
   "scope": "",
   "facts": [],
   "raw": 11529683,
   "mods": [
    {
     "key": "pulse",
     "num": "01",
     "title": "Pulse",
     "desc": null
    },
    {
     "key": "targets",
     "num": "02",
     "title": "Targets",
     "desc": null
    },
    {
     "key": "horus",
     "num": "03",
     "title": "Horus",
     "desc": null
    },
    {
     "key": "offshore",
     "num": "04",
     "title": "Offshore",
     "desc": null
    },
    {
     "key": "agencies",
     "num": "05",
     "title": "Agencies",
     "desc": null
    },
    {
     "key": "matrix",
     "num": "06",
     "title": "Matrix",
     "desc": null
    },
    {
     "key": "clients",
     "num": "07",
     "title": "Clients",
     "desc": null
    },
    {
     "key": "paid",
     "num": "08",
     "title": "Paid & Social",
     "desc": null
    },
    {
     "key": "gaps",
     "num": "09",
     "title": "Gaps",
     "desc": null
    },
    {
     "key": "compare",
     "num": "10",
     "title": "Compare",
     "desc": null
    },
    {
     "key": "watch",
     "num": "11",
     "title": "Watchlist",
     "desc": null
    },
    {
     "key": "method",
     "num": "12",
     "title": "Method",
     "desc": null
    }
   ]
  },
  {
   "id": "hitboard",
   "wing": "core",
   "wingLabel": "Core",
   "vertical": "Agency displacement",
   "short": "Hit Board",
   "name": "Baba Yaga",
   "title": "Baba Yaga Hit Board",
   "sub": "Client Displacement Command: ten agencies whose client books sit inside your verticals, scored for how takeable each one is, with the campaign to win them",
   "navTitle": null,
   "scope": "",
   "facts": [
    "10 marked agencies",
    "40k+ SMB accounts in the softest four",
    "3 strike waves"
   ],
   "raw": 63888,
   "mods": [
    {
     "key": "command",
     "num": "01",
     "title": "Command",
     "desc": "Campaign Brief: Become the name the agencies warn each other about."
    },
    {
     "key": "ten",
     "num": "02",
     "title": "The Ten",
     "desc": "Target Dossiers: The Ten"
    },
    {
     "key": "road",
     "num": "03",
     "title": "Roadmap",
     "desc": "The Campaign: Six phases to dominance"
    },
    {
     "key": "arsenal",
     "num": "04",
     "title": "Arsenal",
     "desc": "The Arsenal: Every weapon, and where it fires"
    },
    {
     "key": "doctrine",
     "num": "05",
     "title": "Doctrine",
     "desc": "Field Doctrine: The displacement sequence"
    }
   ]
  },
  {
   "id": "criminal",
   "wing": "legal",
   "wingLabel": "Legal",
   "vertical": "Criminal defense",
   "short": "Probable Cause",
   "name": "Probable Cause",
   "title": "Probable Cause Defense Atlas",
   "sub": "Criminal defense intelligence for all 254 Texas counties: arrest records, fourteen case lines, ZIP heatmaps for ads and SEO",
   "navTitle": "Criminal defense · Texas",
   "scope": "Texas",
   "facts": [
    "254 counties",
    "30.19M residents",
    "665k felony and misdemeanor cases added, FY2025"
   ],
   "raw": 7947325,
   "mods": [
    {
     "key": "index",
     "num": "01",
     "title": "Defense Demand Index",
     "desc": "Where criminal cases arise across fourteen case lines, ZIP by ZIP and county by county, for all 254 Texas counties"
    },
    {
     "key": "agencies",
     "num": "02",
     "title": "Agency Ledger",
     "desc": "The police departments, sheriffs and constables behind every count: arrests by line, reporting gaps, trends and the DWI corridors"
    },
    {
     "key": "law",
     "num": "03",
     "title": "Texas Criminal Law",
     "desc": "DWI, drugs, assault and family violence, theft, weapons, juveniles, sentencing, bail, expunction and nondisclosure, and the bar's advertising rules, with intake calculators"
    },
    {
     "key": "drivers",
     "num": "04",
     "title": "Arrest Drivers",
     "desc": "What moves criminal case flow in Texas: income, youth, nightlife, retail, interstates, campuses, and who is arrested, where they live and how"
    },
    {
     "key": "paid",
     "num": "05",
     "title": "Paid Acquisition",
     "desc": "Where an ad dollar reaches the most retained cases: fee pool per click cost, quadrants, tiers and bid modifiers by ZIP"
    },
    {
     "key": "ground",
     "num": "06",
     "title": "Courts and Corrections",
     "desc": "The counted record: criminal cases by county and court level, juries, appointed and retained counsel, state prison receives and custody, DWI arrests and filings, and the federal docket"
    },
    {
     "key": "field",
     "num": "07",
     "title": "Competitive Field",
     "desc": "The defense firms already in the market: offices, reach, case types, Spanish, claims, pressure by ZIP and the whitespace between them"
    },
    {
     "key": "desk",
     "num": "08",
     "title": "Campaign Desk",
     "desc": "Budgets, ZIP targets, keywords, ads with the required statements, and bulk files for six ad platforms"
    },
    {
     "key": "forge",
     "num": "09",
     "title": "Site Forge",
     "desc": "Practice, city, county, DWI corridor and guide pages written from the atlas, linted against the Texas advertising rules and compiled for WordPress"
    },
    {
     "key": "satchel",
     "num": "10",
     "title": "Bar Satchel",
     "desc": "Ads, pages and intake screened against the Texas advertising rules, current Texas criminal law, the FTC and platform policies"
    },
    {
     "key": "regions",
     "num": "11",
     "title": "Texas Regions",
     "desc": "The twelve regions on their own: people, arrests, courts, counsel, corrections, DWI corridors, case flow, competition, media markets and languages"
    },
    {
     "key": "lines",
     "num": "12",
     "title": "Case Lines",
     "desc": "Fourteen case lines resolved to the ZIP: volumes, retained cases, fees, seasons, law, keywords, pressure and bid modifiers"
    },
    {
     "key": "watch",
     "num": "13",
     "title": "Competitor Watch",
     "desc": "What the mapped firms are doing: ads on Meta and Google, results and fee claims, Spanish, coverage by line, with library links and an API bridge"
    },
    {
     "key": "clock",
     "num": "14",
     "title": "Arrest Clock",
     "desc": "When arrests happen, line by line, when the calls should come, and the enforcement campaigns, games and festivals ahead, turned into staffing and an ad schedule"
    },
    {
     "key": "accounts",
     "num": "15",
     "title": "Accounts",
     "desc": "Connect the paid and social accounts, pull what they actually did, and let the actuals correct the models"
    },
    {
     "key": "publish",
     "num": "16",
     "title": "Publish",
     "desc": "Send the pages the Site Forge built, or your own, to WordPress (Elementor or headless), Drupal, Wix, Duda, Webflow, Shopify, HubSpot, Joomla or Ghost"
    }
   ]
  },
  {
   "id": "criminal_la",
   "wing": "legal",
   "wingLabel": "Legal",
   "vertical": "Criminal defense",
   "short": "Probable Cause Louisiana",
   "name": "Probable Cause",
   "title": "Probable Cause Defense Atlas",
   "sub": "Criminal defense intelligence for all 64 Louisiana parishes: arrest records, fourteen case lines, ZIP heatmaps for ads and SEO",
   "navTitle": "Criminal defense · Louisiana",
   "scope": "Louisiana",
   "facts": [
    "64 parishes",
    "4.61M residents",
    "198k criminal filings, 2025"
   ],
   "raw": 3207512,
   "mods": [
    {
     "key": "index",
     "num": "01",
     "title": "Defense Demand Index",
     "desc": "Where criminal cases arise across fourteen case lines, ZIP by ZIP and parish by parish, for all 64 parishes"
    },
    {
     "key": "agencies",
     "num": "02",
     "title": "Agency Ledger",
     "desc": "The police departments and sheriffs behind every count: arrests by line, reporting gaps, trends and the DWI corridors"
    },
    {
     "key": "law",
     "num": "03",
     "title": "Louisiana Criminal Law",
     "desc": "DWI, drugs, battery, theft, weapons, juveniles, sentencing, bail, expungement and the bar's advertising rules, with intake calculators"
    },
    {
     "key": "drivers",
     "num": "04",
     "title": "Arrest Drivers",
     "desc": "What moves criminal case flow in Louisiana: poverty, youth, nightlife, retail, interstates, campuses, and who is arrested, where and how"
    },
    {
     "key": "paid",
     "num": "05",
     "title": "Paid Acquisition",
     "desc": "Where an ad dollar reaches the most retained cases: fee pool per click cost, quadrants, tiers and bid modifiers by ZIP"
    },
    {
     "key": "ground",
     "num": "06",
     "title": "Courts and Corrections",
     "desc": "The counted record: filings by parish and court, jury trials, prison admissions, probation and parole, public defender caseloads, DWI arrests and the federal docket"
    },
    {
     "key": "field",
     "num": "07",
     "title": "Competitive Field",
     "desc": "The defense firms already in the market: offices, reach, case types, Spanish, claims, pressure by ZIP and the whitespace between them"
    },
    {
     "key": "desk",
     "num": "08",
     "title": "Campaign Desk",
     "desc": "Budgets, ZIP targets, keywords, ads with the required statements, and bulk files for six ad platforms"
    },
    {
     "key": "forge",
     "num": "09",
     "title": "Site Forge",
     "desc": "Practice, city, parish, DWI corridor and guide pages written from the atlas, linted against the LSBA rules and compiled for WordPress"
    },
    {
     "key": "satchel",
     "num": "10",
     "title": "Bar Satchel",
     "desc": "Ads, pages and intake screened against the Louisiana advertising rules, 2024 to 2026 Louisiana law, the FTC and platform policies"
    },
    {
     "key": "regions",
     "num": "11",
     "title": "Louisiana Regions",
     "desc": "The nine regions on their own: people, arrests, courts, corrections, DWI corridors, case flow, competition, media markets and languages"
    },
    {
     "key": "lines",
     "num": "12",
     "title": "Case Lines",
     "desc": "Fourteen case lines resolved to the ZIP: volumes, retained cases, fees, seasons, law, keywords, pressure and bid modifiers"
    },
    {
     "key": "watch",
     "num": "13",
     "title": "Competitor Watch",
     "desc": "What the mapped firms are doing: ads on Meta and Google, results and fee claims, Spanish, coverage by line, with library links and an API bridge"
    },
    {
     "key": "clock",
     "num": "14",
     "title": "Arrest Clock",
     "desc": "When arrests happen, line by line, when the calls should come, and the enforcement campaigns, games and festivals ahead, turned into staffing and an ad schedule"
    },
    {
     "key": "accounts",
     "num": "15",
     "title": "Accounts",
     "desc": "Connect the paid and social accounts, pull what they actually did, and let the actuals correct the models"
    },
    {
     "key": "publish",
     "num": "16",
     "title": "Publish",
     "desc": "Send the pages the Site Forge built, or your own, to WordPress (Elementor or headless), Drupal, Wix, Duda, Webflow, Shopify, HubSpot, Joomla or Ghost"
    }
   ]
  },
  {
   "id": "injury",
   "wing": "legal",
   "wingLabel": "Legal",
   "vertical": "Personal injury",
   "short": "Contraflow",
   "name": "Contraflow",
   "title": "Contraflow Injury Atlas",
   "sub": "Personal injury intelligence for all 254 counties: crash corridors, nine practice lines, ZIP heatmaps for ads and SEO",
   "navTitle": "Personal injury · Texas",
   "scope": "Texas",
   "facts": [
    "254 counties",
    "30.19M residents",
    "245k injured in crashes, 2025"
   ],
   "raw": 7536384,
   "mods": [
    {
     "key": "index",
     "num": "01",
     "title": "Case Flow Index",
     "desc": "Where injury claims arise across nine practice lines, ZIP by ZIP, for all 254 counties"
    },
    {
     "key": "corridors",
     "num": "02",
     "title": "Crash Corridors",
     "desc": "Fatal crashes on every interstate, US highway and state route, by five mile stretch, hour and cause"
    },
    {
     "key": "law",
     "num": "03",
     "title": "Texas Law",
     "desc": "Two years to sue, the bar above 50 percent responsibility, paid or incurred medical damages, the malpractice and government caps and the bar's advertising rules, with intake calculators"
    },
    {
     "key": "drivers",
     "num": "04",
     "title": "Injury Drivers",
     "desc": "What moves injury claims in Texas: density, commuting, cars, income, bars, interstates, age, the calendar and the clock"
    },
    {
     "key": "paid",
     "num": "05",
     "title": "Paid Acquisition",
     "desc": "Where an ad dollar reaches the most signed cases: fee pool per click cost, quadrants, tiers and bid modifiers by ZIP"
    },
    {
     "key": "ground",
     "num": "06",
     "title": "Ground Truth",
     "desc": "The 254 counties as observed: crash ledgers, deaths, impaired and commercial crashes, enforcement, suits, hospitals and lawyers"
    },
    {
     "key": "field",
     "num": "07",
     "title": "Competitive Field",
     "desc": "The injury firms already in the market: offices, reach, lines, Spanish, pressure by ZIP and the whitespace between them"
    },
    {
     "key": "desk",
     "num": "08",
     "title": "Campaign Desk",
     "desc": "Budgets, ZIP targets, keywords, ads with the required statements, and bulk files for six ad platforms"
    },
    {
     "key": "forge",
     "num": "09",
     "title": "Site Forge",
     "desc": "Practice, city, county, corridor and guide pages written from the atlas, linted against the Texas advertising rules and compiled for WordPress"
    },
    {
     "key": "satchel",
     "num": "10",
     "title": "Bar Satchel",
     "desc": "Ads, pages and intake screened against the Texas advertising rules and statutes, Texas injury law, the FTC and platform policies"
    },
    {
     "key": "regions",
     "num": "11",
     "title": "Texas Regions",
     "desc": "The twelve regions on their own: people, crash ledgers, corridors, case flow, competition, media markets and languages"
    },
    {
     "key": "lines",
     "num": "12",
     "title": "Practice Lines",
     "desc": "Nine practice lines resolved to the ZIP: pools, cases, fee value, seasons, law, keywords, pressure and bid modifiers"
    },
    {
     "key": "watch",
     "num": "13",
     "title": "Competitor Watch",
     "desc": "What the mapped firms are doing: ads on Meta and Google, results and fee claims, Spanish, coverage by line, with library links and an API bridge"
    },
    {
     "key": "weather",
     "num": "14",
     "title": "Weather Desk",
     "desc": "National Weather Service forecasts, alerts and observations for the twelve Texas regions, turned into a crash risk clock for intake and ad timing"
    },
    {
     "key": "accounts",
     "num": "15",
     "title": "Accounts",
     "desc": "Connect the paid and social accounts, pull what they actually did, and let the actuals correct the models"
    },
    {
     "key": "publish",
     "num": "16",
     "title": "Publish",
     "desc": "Send the pages the Site Forge built, or your own, to WordPress (Elementor or headless), Drupal, Wix, Duda, Webflow, Shopify, HubSpot, Joomla or Ghost"
    }
   ]
  },
  {
   "id": "injury_la",
   "wing": "legal",
   "wingLabel": "Legal",
   "vertical": "Personal injury",
   "short": "Contraflow Louisiana",
   "name": "Contraflow",
   "title": "Contraflow Injury Atlas",
   "sub": "Personal injury intelligence for all 64 Louisiana parishes: crash corridors, nine practice lines, ZIP heatmaps for ads and SEO",
   "navTitle": "Personal injury · Louisiana",
   "scope": "Louisiana",
   "facts": [
    "64 parishes",
    "4.61M residents",
    "59k injured in crashes, 2024"
   ],
   "raw": 3222210,
   "mods": [
    {
     "key": "index",
     "num": "01",
     "title": "Case Flow Index",
     "desc": "Where injury claims arise across nine practice lines, ZIP by ZIP, for all 64 parishes"
    },
    {
     "key": "corridors",
     "num": "02",
     "title": "Crash Corridors",
     "desc": "Fatal crashes on every interstate, US highway and state route, by five mile stretch, hour and cause"
    },
    {
     "key": "law",
     "num": "03",
     "title": "Louisiana Law",
     "desc": "Prescription, the 51% fault bar, no pay no play, medical damages, the malpractice cap and the bar's advertising rules, with intake calculators"
    },
    {
     "key": "drivers",
     "num": "04",
     "title": "Injury Drivers",
     "desc": "What moves injury claims in Louisiana: density, commuting, cars, income, bars, interstates, age, the calendar and the clock"
    },
    {
     "key": "paid",
     "num": "05",
     "title": "Paid Acquisition",
     "desc": "Where an ad dollar reaches the most signed cases: fee pool per click cost, quadrants, tiers and bid modifiers by ZIP"
    },
    {
     "key": "ground",
     "num": "06",
     "title": "Ground Truth",
     "desc": "The 64 parishes as observed: crash ledgers, deaths, impaired and commercial crashes, enforcement, cost, hospitals and lawyers"
    },
    {
     "key": "field",
     "num": "07",
     "title": "Competitive Field",
     "desc": "The injury firms already in the market: offices, reach, lines, Spanish, pressure by ZIP and the whitespace between them"
    },
    {
     "key": "desk",
     "num": "08",
     "title": "Campaign Desk",
     "desc": "Budgets, ZIP targets, keywords, ads with the required statements, and bulk files for six ad platforms"
    },
    {
     "key": "forge",
     "num": "09",
     "title": "Site Forge",
     "desc": "Practice, city, parish, corridor and guide pages written from the atlas, linted against the LSBA rules and compiled for WordPress"
    },
    {
     "key": "satchel",
     "num": "10",
     "title": "Bar Satchel",
     "desc": "Ads, pages and intake screened against the Louisiana advertising rules, 2024 to 2026 Louisiana law, the FTC and platform policies"
    },
    {
     "key": "regions",
     "num": "11",
     "title": "Louisiana Regions",
     "desc": "The nine regions on their own: people, crash ledgers, corridors, case flow, competition, media markets and languages"
    },
    {
     "key": "lines",
     "num": "12",
     "title": "Practice Lines",
     "desc": "Nine practice lines resolved to the ZIP: pools, cases, fee value, seasons, law, keywords, pressure and bid modifiers"
    },
    {
     "key": "watch",
     "num": "13",
     "title": "Competitor Watch",
     "desc": "What the mapped firms are doing: ads on Meta and Google, results and fee claims, Spanish, coverage by line, with library links and an API bridge"
    },
    {
     "key": "weather",
     "num": "14",
     "title": "Weather Desk",
     "desc": "National Weather Service forecasts, alerts and observations for nine Louisiana regions, turned into a crash risk clock for intake and ad timing"
    },
    {
     "key": "accounts",
     "num": "15",
     "title": "Accounts",
     "desc": "Connect the paid and social accounts, pull what they actually did, and let the actuals correct the models"
    },
    {
     "key": "publish",
     "num": "16",
     "title": "Publish",
     "desc": "Send the pages the Site Forge built, or your own, to WordPress (Elementor or headless), Drupal, Wix, Duda, Webflow, Shopify, HubSpot, Joomla or Ghost"
    }
   ]
  },
  {
   "id": "family",
   "wing": "legal",
   "wingLabel": "Legal",
   "vertical": "Family law",
   "short": "Severance",
   "name": "SEVERANCE",
   "title": "Severance",
   "sub": "Texas and Louisiana family law market intelligence · 318 counties and parishes · 36 metros · 2,528 ZIP codes",
   "navTitle": null,
   "scope": "Texas and Louisiana",
   "facts": [
    "318 counties and parishes",
    "36 metros",
    "2,528 ZIP codes"
   ],
   "raw": 20481920,
   "mods": [
    {
     "key": "index",
     "num": "01",
     "title": "Dissolution Index",
     "desc": "Where marriages end and family law matters arise, fourteen lines, every ZIP in Texas and Louisiana"
    },
    {
     "key": "ledger",
     "num": "02",
     "title": "Court Ledger",
     "desc": "Filings by county and parish: divorce, custody, protective orders, modifications, CPS, with trends and clearance"
    },
    {
     "key": "drivers",
     "num": "03",
     "title": "Dissolution Drivers",
     "desc": "What moves divorce and custody demand: marriage cohorts, education, military service, job loss, strain and the calendar"
    },
    {
     "key": "market",
     "num": "04",
     "title": "Marriage Market",
     "desc": "The installed base: married couples in both states, how long, how many times, and the hazard curve that turns them into clients"
    },
    {
     "key": "shock",
     "num": "05",
     "title": "Economic Shock",
     "desc": "Job losses county by county, week by week: claims, unemployment, WARN notices, payrolls, and what they do to filings"
    },
    {
     "key": "ground",
     "num": "06",
     "title": "Ground Truth",
     "desc": "Every county and parish as counted: marriage and divorce, children, poverty, child welfare, jobs and lawyers, plus every city"
    },
    {
     "key": "metros",
     "num": "07",
     "title": "Metro Desk",
     "desc": "All 36 metros and 50 micro areas on their own: matters, lines that run hot, competition, languages and the shock"
    },
    {
     "key": "atlas",
     "num": "08",
     "title": "Metro Atlas",
     "desc": "Sixteen metros at block group resolution, from Houston and Dallas to New Orleans and Alexandria, with courthouses and school districts"
    },
    {
     "key": "lines",
     "num": "09",
     "title": "Practice Lines",
     "desc": "Fourteen practice lines resolved to the ZIP: matters, retained matters, fee value, seasons, law, keywords and bid modifiers"
    },
    {
     "key": "law",
     "num": "10",
     "title": "Family Law",
     "desc": "The law in both states as it reaches marketing and intake: the register, guideline support for each state, waiting periods, deadlines, spousal support and protective order screens, and the bar rules"
    },
    {
     "key": "field",
     "num": "11",
     "title": "Competitive Field",
     "desc": "The family law firms already in both markets: offices, reach, lines, board certification, Spanish pages, pressure by ZIP and the whitespace between them"
    },
    {
     "key": "watch",
     "num": "12",
     "title": "Competitor Watch",
     "desc": "What the mapped family law firms are doing: ads on Meta and Google, results, fee and certification claims, Spanish, coverage by line, with library links and an API bridge"
    },
    {
     "key": "paid",
     "num": "13",
     "title": "Paid Acquisition",
     "desc": "Where an ad dollar reaches the most retained matters: fee pool per click cost, quadrants, tiers and bid modifiers by ZIP, within each state"
    },
    {
     "key": "desk",
     "num": "14",
     "title": "Campaign Desk",
     "desc": "Budgets, ZIP targets, keywords, ads with each state's required statements, and bulk files for six ad platforms"
    },
    {
     "key": "clock",
     "num": "15",
     "title": "Docket Clock",
     "desc": "When family law demand moves: the seasonal index by line, the court and possession calendar for fifteen months, an intake clock, and National Weather Service forecasts and alerts for 27 points"
    },
    {
     "key": "accounts",
     "num": "16",
     "title": "Accounts",
     "desc": "Connect the paid and social accounts, pull what they actually did, and let the actuals correct the models"
    },
    {
     "key": "forge",
     "num": "17",
     "title": "Site Forge",
     "desc": "A family law website planned from the atlas and written page by page for each state: practice pages, county and parish hubs, city and landing pages, guides and Spanish pages, checked against both bars and ready to publish"
    },
    {
     "key": "satchel",
     "num": "18",
     "title": "Bar Satchel",
     "desc": "Ads, pages and intake screened against the Texas and Louisiana advertising rules, current family law in both states, the FTC and platform policies, with findings sorted into what to fix, what to raise and what to keep in house"
    },
    {
     "key": "publish",
     "num": "19",
     "title": "Publish",
     "desc": "Send the pages the Site Forge built, or your own, to WordPress (Elementor or headless), Drupal, Wix, Duda, Webflow, Shopify, HubSpot, Joomla or Ghost"
    },
    {
     "key": "method",
     "num": "20",
     "title": "Method and Sources",
     "desc": "Every source with its date, every formula, the model tables, the two state basis, the judgment calls and the known limits"
    }
   ]
  },
  {
   "id": "employment",
   "wing": "legal",
   "wingLabel": "Legal",
   "vertical": "Employment law",
   "short": "Termination Exposure",
   "name": "The Termination Exposure Atlas",
   "title": "The Termination Exposure Atlas",
   "sub": "Companion to Why Americans Lose Their Jobs · Research Report, September 2026 · employment law marketing platform",
   "navTitle": null,
   "scope": "National",
   "facts": [
    "Eight modules",
    "51 jurisdictions",
    "3,144 counties"
   ],
   "raw": 21269269,
   "mods": [
    {
     "key": "exposure",
     "num": "01",
     "title": "Termination Exposure",
     "desc": "Union coverage, at-will exceptions, remedy floor, UI backstop — the rules a firing happens under"
    },
    {
     "key": "enforce",
     "num": "02",
     "title": "Enforcement & Recovery",
     "desc": "Agency dockets, federal litigation, and what the private bar advertises — what happens after"
    },
    {
     "key": "risk",
     "num": "03",
     "title": "Litigation Risk",
     "desc": "What actually predicts a charge — eleven candidates ranked, and the five-state convergence"
    },
    {
     "key": "paid",
     "num": "04",
     "title": "Paid Acquisition",
     "desc": "Where to buy advertising, resolved to the ZIP code — claimant flow, case value and what it costs to reach"
    },
    {
     "key": "ground",
     "num": "05",
     "title": "Ground Truth",
     "desc": "Counties and cities as observed — benefit receipt, unemployment now, jobs lost, back wages found, suits filed"
    },
    {
     "key": "hiring",
     "num": "06",
     "title": "Hiring Machine",
     "desc": "Staffing agencies, screening vendors and hiring algorithms — where they operate, where they were caught, what they can be sued for"
    },
    {
     "key": "desk",
     "num": "07",
     "title": "Campaign Desk",
     "desc": "Budgets, geo lists, keywords, creative and bulk-upload files for Google, YouTube & Demand Gen, Meta, TikTok and LinkedIn"
    },
    {
     "key": "forge",
     "num": "08",
     "title": "Site Forge",
     "desc": "Practice, state, city, landing and guide pages written from the atlas — Elementor, headless and HTML, deployed to WordPress"
    }
   ]
  },
  {
   "id": "hvac",
   "wing": "home",
   "wingLabel": "Home services",
   "vertical": "HVAC",
   "short": "Thermal Debt",
   "name": "Louisiana Thermal Debt Atlas",
   "title": "Louisiana Thermal Debt Atlas",
   "sub": "Heating and cooling campaign intelligence for all 64 parishes",
   "navTitle": "HVAC · Louisiana",
   "scope": "Louisiana",
   "facts": [
    "1.50M central systems",
    "336k aged 15 or older",
    "85k replacements a year"
   ],
   "raw": 4550458,
   "mods": [
    {
     "key": "index",
     "num": "01",
     "title": "Thermal Debt Index",
     "desc": "Where aging heating and cooling systems are coming due, ZIP by ZIP"
    },
    {
     "key": "replace",
     "num": "02",
     "title": "Replacement Wave",
     "desc": "Replacements and reinstalls, heating and cooling, forecast to 2035"
    },
    {
     "key": "rules",
     "num": "03",
     "title": "Rules and Refrigerants",
     "desc": "R22 to A2L, SEER2, the furnace rule, lapsed credits, rebates, LSLBC licensing, insurance claim rules and permits"
    },
    {
     "key": "drivers",
     "num": "04",
     "title": "Demand Drivers",
     "desc": "What moves HVAC work: heat, freezes, age, storms, and the permit gap"
    },
    {
     "key": "paid",
     "num": "05",
     "title": "Paid Acquisition",
     "desc": "Where an ad dollar reaches the most replacement and repair jobs, resolved to the ZIP"
    },
    {
     "key": "ground",
     "num": "06",
     "title": "Ground Truth",
     "desc": "Parishes and cities as observed: permits, storms, licenses, contractors, housing"
    },
    {
     "key": "supply",
     "num": "07",
     "title": "Supply Line",
     "desc": "The licensed field: LSLBC licensees, HVAC specialists, establishments and the city focus board"
    },
    {
     "key": "desk",
     "num": "08",
     "title": "Campaign Desk",
     "desc": "Budgets, ZIP targets, keywords, creative and bulk files for eight ad platforms"
    },
    {
     "key": "forge",
     "num": "09",
     "title": "Site Forge",
     "desc": "Service, city, parish and guide pages written from the model, linted and compiled for WordPress"
    },
    {
     "key": "satchel",
     "num": "10",
     "title": "Emergency Satchel",
     "desc": "Ads, pages and license claims screened against LSLBC, claims, FTC, Louisiana and platform rules"
    },
    {
     "key": "metros",
     "num": "11",
     "title": "Metro Areas",
     "desc": "Each metro on its own: stock, climate, storms, housing waves, supply, precision and data access"
    },
    {
     "key": "lines",
     "num": "12",
     "title": "Service Lines",
     "desc": "Fourteen HVAC service lines resolved to every Louisiana ZIP: pools, jobs, tickets, seasons, levers, pressure and bid modifiers"
    },
    {
     "key": "watch",
     "num": "13",
     "title": "Competitor Watch",
     "desc": "What the 1,451 licensed HVAC businesses are doing: ads on Meta and Google, offers, financing, memberships and reviews, with library links and an API bridge"
    },
    {
     "key": "weather",
     "num": "14",
     "title": "Weather Desk",
     "desc": "National Weather Service forecasts, alerts, outlooks and observations for each Louisiana metro, turned into hour by hour ad timing"
    },
    {
     "key": "accounts",
     "num": "15",
     "title": "Accounts",
     "desc": "Connect the paid and social accounts, pull what they actually did, and let the actuals correct the models"
    },
    {
     "key": "publish",
     "num": "16",
     "title": "Publish",
     "desc": "Send the pages the Site Forge built, or your own, to WordPress (Elementor or headless), Drupal, Wix, Duda, Webflow, Shopify, HubSpot, Joomla or Ghost"
    }
   ]
  },
  {
   "id": "dfw",
   "wing": "home",
   "wingLabel": "Home services",
   "vertical": "HVAC",
   "short": "DFW Thermal Debt",
   "name": "DFW Thermal Debt Atlas",
   "title": "DFW Thermal Debt Atlas",
   "sub": "Heating and cooling campaign intelligence for the 12 counties of Dallas Fort Worth: demand, service lines, competitors, the website and the accounts",
   "navTitle": "HVAC · Dallas Fort Worth",
   "scope": "Dallas Fort Worth, Texas",
   "facts": [
    "2.86M central systems",
    "533k aged 15 or older",
    "177k replacements a year"
   ],
   "raw": 2645541,
   "mods": [
    {
     "key": "index",
     "num": "01",
     "title": "Thermal Debt Index",
     "desc": "Where aging heating and cooling systems are coming due, ZIP by ZIP"
    },
    {
     "key": "replace",
     "num": "02",
     "title": "Replacement Wave",
     "desc": "Replacements and reinstalls, heating and cooling, forecast to 2035"
    },
    {
     "key": "rules",
     "num": "03",
     "title": "Rules and Refrigerants",
     "desc": "R22 to A2L, SEER2, the furnace rule, lapsed credits, rebates, TDLR licensing and permits"
    },
    {
     "key": "drivers",
     "num": "04",
     "title": "Demand Drivers",
     "desc": "What moves HVAC work: heat, freezes, age, income, and the permit gap"
    },
    {
     "key": "paid",
     "num": "05",
     "title": "Paid Acquisition",
     "desc": "Where an ad dollar reaches the most replacement and repair jobs, resolved to the ZIP"
    },
    {
     "key": "ground",
     "num": "06",
     "title": "Ground Truth",
     "desc": "Counties and cities as observed: permits, hail, licenses, contractors, housing"
    },
    {
     "key": "supply",
     "num": "07",
     "title": "Supply Line",
     "desc": "Contractors, technicians and the 242-location competitive field from the heatmap"
    },
    {
     "key": "desk",
     "num": "08",
     "title": "Campaign Desk",
     "desc": "Budgets, ZIP targets, keywords, creative and bulk files for eight ad platforms"
    },
    {
     "key": "forge",
     "num": "09",
     "title": "Site Forge",
     "desc": "Service, city, county and guide pages written from the model, linted and compiled for WordPress"
    },
    {
     "key": "satchel",
     "num": "10",
     "title": "Emergency Satchel",
     "desc": "Ads, pages and license claims screened against TDLR, FTC, Texas and platform rules"
    },
    {
     "key": "dfw",
     "num": "11",
     "title": "Dallas Fort Worth",
     "desc": "The 12 counties on their own: stock, climate, hail, housing waves, supply, precision and data access"
    },
    {
     "key": "lines",
     "num": "12",
     "title": "Service Lines",
     "desc": "Fourteen HVAC service lines resolved to the ZIP: pools, jobs, tickets, seasons, levers, pressure and bid modifiers"
    },
    {
     "key": "watch",
     "num": "13",
     "title": "Competitor Watch",
     "desc": "What the 242 mapped competitors are doing: ads on Meta and Google, offers, financing, memberships, reviews, with library links and an API bridge"
    },
    {
     "key": "weather",
     "num": "14",
     "title": "Weather Desk",
     "desc": "National Weather Service forecast, alerts, outlooks and observations for DFW, turned into hour by hour ad timing"
    },
    {
     "key": "accounts",
     "num": "15",
     "title": "Accounts",
     "desc": "Connect the paid and social accounts, pull what they actually did, and let the actuals correct the models"
    },
    {
     "key": "publish",
     "num": "16",
     "title": "Publish",
     "desc": "Send the pages the Site Forge built, or your own, to WordPress (Elementor or headless), Drupal, Wix, Duda, Webflow, Shopify, HubSpot, Joomla or Ghost"
    }
   ]
  },
  {
   "id": "roofing",
   "wing": "home",
   "wingLabel": "Home services",
   "vertical": "Roofing",
   "short": "Uplift",
   "name": "Uplift",
   "title": "Uplift Roofing Atlas",
   "sub": "Roofing demand intelligence for all 64 parishes: roof age, storms, eleven service lines, ZIP heatmaps for ads and SEO",
   "navTitle": null,
   "scope": "Louisiana",
   "facts": [
    "64 parishes",
    "1.48M one unit roofs",
    "234k roofs 20+ years old"
   ],
   "raw": 3653371,
   "mods": [
    {
     "key": "index",
     "num": "01",
     "title": "Roof Demand Index",
     "desc": "Where roofing jobs arise across eleven residential and commercial lines, ZIP by ZIP, for all 64 parishes"
    },
    {
     "key": "storms",
     "num": "02",
     "title": "Storm Ledger",
     "desc": "Every hurricane track, hail report, damaging gust and tornado, with modeled roof damage by storm and ZIP"
    },
    {
     "key": "law",
     "num": "03",
     "title": "Code, License and Claims",
     "desc": "Licensing at $7,500, permits for every reroof, the claims and deductible rules, price gouging, FORTIFIED grants and the insurer clock, with screening calculators"
    },
    {
     "key": "drivers",
     "num": "04",
     "title": "Demand Drivers",
     "desc": "What drives roofing demand in Louisiana: hurricanes against hail, income and insurance, roof age, the seasons and the clock"
    },
    {
     "key": "paid",
     "num": "05",
     "title": "Paid Acquisition",
     "desc": "Where an ad dollar reaches the most sold jobs: gross profit pool per click cost, quadrants, tiers and bid modifiers by ZIP"
    },
    {
     "key": "ground",
     "num": "06",
     "title": "Ground Truth",
     "desc": "The 64 parishes as observed: FEMA roof registrations, hail, wind and tornado reports, hurricane records, permits, housing and roofers"
    },
    {
     "key": "field",
     "num": "07",
     "title": "Competitive Field",
     "desc": "The roofing companies already in the market: offices, reach, lines, certifications, the license roster, pressure by ZIP and the whitespace between them"
    },
    {
     "key": "desk",
     "num": "08",
     "title": "Campaign Desk",
     "desc": "Budgets, ZIP targets, keywords, ads with the license number built in, and bulk files for six ad platforms"
    },
    {
     "key": "forge",
     "num": "09",
     "title": "Site Forge",
     "desc": "Service, city, parish, storm and guide pages written from the atlas, linted by the Compliance Satchel and compiled for WordPress"
    },
    {
     "key": "satchel",
     "num": "10",
     "title": "Compliance Satchel",
     "desc": "Ads, pages, scripts and contracts screened against Louisiana licensing, claims and deductible law, the FTC and platform policies"
    },
    {
     "key": "regions",
     "num": "11",
     "title": "Louisiana Regions",
     "desc": "The nine regions on their own: roof stock and age, storm resets, hail, FEMA, competition, media markets and languages"
    },
    {
     "key": "lines",
     "num": "12",
     "title": "Service Lines",
     "desc": "Eleven roofing lines resolved to the ZIP: jobs, jobs open to marketing, gross profit, seasons, rules, keywords, competitors and bid modifiers"
    },
    {
     "key": "watch",
     "num": "13",
     "title": "Competitor Watch",
     "desc": "What the mapped roofing companies are doing: ads on Meta and Google, free, insurance and warranty claims, Spanish, coverage by line, with library links and an API bridge"
    },
    {
     "key": "weather",
     "num": "14",
     "title": "Storm Desk",
     "desc": "National Weather Service forecasts, SPC and NHC outlooks and alerts for nine Louisiana regions, turned into storm triggers for ads and work windows for crews"
    },
    {
     "key": "accounts",
     "num": "15",
     "title": "Accounts",
     "desc": "Connect the paid and social accounts, pull what they actually did, and let the actuals correct the models"
    },
    {
     "key": "publish",
     "num": "16",
     "title": "Publish",
     "desc": "Send the pages the Site Forge built, or your own, to WordPress (Elementor or headless), Drupal, Wix, Duda, Webflow, Shopify, HubSpot, Joomla or Ghost"
    },
    {
     "key": "stock",
     "num": "17",
     "title": "Roof Stock and Materials",
     "desc": "How old Louisiana roofs are, what they are made of, what materials cost and what the code and FORTIFIED require"
    }
   ]
  },
  {
   "id": "plumbing",
   "wing": "home",
   "wingLabel": "Home services",
   "vertical": "Plumbing",
   "short": "Water Hammer",
   "name": "WATER HAMMER",
   "title": "Water Hammer Atlas",
   "sub": "Texas and Louisiana Pipe Debt Atlas · plumbing campaign intelligence for 254 counties and 64 parishes",
   "navTitle": null,
   "scope": "Texas and Louisiana",
   "facts": [
    "12.92M water heaters",
    "939k due a year",
    "741k homes on galvanized, PB or Kitec"
   ],
   "raw": 11830507,
   "mods": [
    {
     "key": "index",
     "num": "01",
     "title": "Pipe Debt Index",
     "desc": "Where water heaters, pipe, drains and sewers are coming due, ZIP by ZIP"
    },
    {
     "key": "replace",
     "num": "02",
     "title": "Replacement Wave",
     "desc": "Water heaters, repipes, cast iron and laterals, forecast to 2035"
    },
    {
     "key": "rules",
     "num": "03",
     "title": "Rules of the Road",
     "desc": "Licensing and ad rules in both states, claims after freezes and floods, the 2029 water heater rule, lead lines"
    },
    {
     "key": "drivers",
     "num": "04",
     "title": "Demand Drivers",
     "desc": "What moves plumbing work: freezes, age, water, clay, floods, and who calls"
    },
    {
     "key": "paid",
     "num": "05",
     "title": "Paid Acquisition",
     "desc": "Where an ad dollar reaches the most plumbing jobs, resolved to the ZIP"
    },
    {
     "key": "ground",
     "num": "06",
     "title": "Ground Truth",
     "desc": "Observed: permits, Uri insured claims, FEMA aid and flood claims by place"
    },
    {
     "key": "supply",
     "num": "07",
     "title": "Supply Line",
     "desc": "The licensed field: Responsible Master Plumbers, journeymen, establishments and the Louisiana gap"
    },
    {
     "key": "desk",
     "num": "08",
     "title": "Campaign Desk",
     "desc": "Budgets, ZIP targets, keywords, creative and bulk files for eight ad platforms"
    },
    {
     "key": "forge",
     "num": "09",
     "title": "Site Forge",
     "desc": "Service, city, county and guide pages written from the model, linted and compiled for WordPress"
    },
    {
     "key": "satchel",
     "num": "10",
     "title": "Emergency Satchel",
     "desc": "Ads, pages and license claims screened against the plumbing boards, claims, FTC, state and platform rules"
    },
    {
     "key": "metros",
     "num": "11",
     "title": "Metro Areas",
     "desc": "Each metro on its own: pipe vintages, water heaters, freezes, floods, water, supply, precision and data access"
    },
    {
     "key": "lines",
     "num": "12",
     "title": "Service Lines",
     "desc": "Seventeen plumbing service lines resolved to every Texas and Louisiana ZIP: pools, jobs, tickets, seasons, levers, pressure and bid modifiers"
    },
    {
     "key": "watch",
     "num": "13",
     "title": "Competitor Watch",
     "desc": "What the 7,992 licensed plumbing companies are doing: ads on Meta and Google, offers, financing, memberships and reviews, with library links and an API bridge"
    },
    {
     "key": "weather",
     "num": "14",
     "title": "Weather Desk",
     "desc": "National Weather Service forecasts, alerts, outlooks and observations for each Texas and Louisiana metro, turned into hour by hour ad timing for freezes, rain and heat"
    },
    {
     "key": "accounts",
     "num": "15",
     "title": "Accounts",
     "desc": "Connect the paid and social accounts, pull what they actually did, and let the actuals correct the models"
    },
    {
     "key": "publish",
     "num": "16",
     "title": "Publish",
     "desc": "Send the pages the Site Forge built, or your own, to WordPress (Elementor or headless), Drupal, Wix, Duda, Webflow, Shopify, HubSpot, Joomla or Ghost"
    }
   ]
  },
  {
   "id": "pest",
   "wing": "home",
   "wingLabel": "Home services",
   "vertical": "Pest control",
   "short": "Swarm Front",
   "name": "Swarm Front Atlas",
   "title": "Swarm Front Atlas",
   "sub": "Pest control demand intelligence for Louisiana and Texas, all 318 parishes and counties",
   "navTitle": null,
   "scope": "Texas and Louisiana",
   "facts": [
    "2,012 residential ZIPs",
    "6.80M structures in very heavy termite zones",
    "20 service lines"
   ],
   "raw": 9399250,
   "mods": [
    {
     "key": "index",
     "num": "01",
     "title": "Pest Demand Index",
     "desc": "Where pest control demand concentrates, ZIP by ZIP across both states"
    },
    {
     "key": "brief",
     "num": "02",
     "title": "Intel Brief",
     "desc": "The judgments, the watch list and every figure, tied to the atlas data"
    },
    {
     "key": "termite",
     "num": "03",
     "title": "Termite Front",
     "desc": "Four termite revenue paths, the swarm clock and the Formosan belt"
    },
    {
     "key": "season",
     "num": "04",
     "title": "Season Clock",
     "desc": "The month by month calendar, zone shifts, the swarm calculator and the rodent clock"
    },
    {
     "key": "vector",
     "num": "05",
     "title": "Vector Watch",
     "desc": "West Nile, typhus and dengue by county, and what they do to demand"
    },
    {
     "key": "drivers",
     "num": "06",
     "title": "Demand Drivers",
     "desc": "Every driver in the workbook, measured where the data allows"
    },
    {
     "key": "rules",
     "num": "07",
     "title": "Rules and Licensing",
     "desc": "Two regulators, the advertising and contract rules, and the licensed supply"
    },
    {
     "key": "paid",
     "num": "08",
     "title": "Paid Acquisition",
     "desc": "Where an ad dollar reaches the most pest control jobs, resolved to the ZIP"
    },
    {
     "key": "ground",
     "num": "09",
     "title": "Ground Truth",
     "desc": "Counties, parishes and ZIPs as observed: sales, permits, storms, claims, businesses, requests"
    },
    {
     "key": "supply",
     "num": "10",
     "title": "Supply Line",
     "desc": "The licensed field, the technician pool and where demand outruns supply"
    },
    {
     "key": "lines",
     "num": "11",
     "title": "Service Lines",
     "desc": "Twenty pest control lines resolved to every ZIP: pools, jobs, tickets, seasons and priority"
    },
    {
     "key": "desk",
     "num": "12",
     "title": "Campaign Desk",
     "desc": "Budgets, ZIP targets, keywords, creative and bulk files for eight ad platforms"
    },
    {
     "key": "forge",
     "num": "13",
     "title": "Site Forge",
     "desc": "Service, city, county or parish and guide pages written from the model, linted and compiled for WordPress"
    },
    {
     "key": "satchel",
     "num": "14",
     "title": "Satchel",
     "desc": "Ads, pages and license claims screened against TDA, LDAF, FTC and platform rules"
    },
    {
     "key": "metros",
     "num": "15",
     "title": "Metro Areas",
     "desc": "Every metro in both states on one page: demand, timing, lines, competition"
    },
    {
     "key": "watch",
     "num": "16",
     "title": "Competitor Watch",
     "desc": "What the 3,811 licensed pest control businesses are doing: ads on Meta and Google, offers, plans and claims, with library links and an API bridge"
    },
    {
     "key": "weather",
     "num": "17",
     "title": "Weather Desk",
     "desc": "NWS forecasts read for swarms, rain, cold fronts and storms, hour by hour"
    },
    {
     "key": "accounts",
     "num": "18",
     "title": "Accounts",
     "desc": "Connect the paid and social accounts, pull what they actually did, and let the actuals correct the models"
    },
    {
     "key": "publish",
     "num": "19",
     "title": "Publish",
     "desc": "Send the pages the Site Forge built, or your own, to WordPress (Elementor or headless), Drupal, Wix, Duda, Webflow, Shopify, HubSpot, Joomla or Ghost"
    }
   ]
  },
  {
   "id": "oncology",
   "wing": "health",
   "wingLabel": "Healthcare",
   "vertical": "Oncology",
   "short": "Oncogene",
   "name": "Oncogene",
   "title": "Oncogene Atlas",
   "sub": "Oncology demand intelligence for Texas and Louisiana: registry rates to the ZIP code, exposure corridors, workforce risk, markets, campaigns and compliance",
   "navTitle": null,
   "scope": "Texas and Louisiana",
   "facts": [
    "318 counties and parishes",
    "34.78M residents",
    "191k new diagnoses, 2026"
   ],
   "raw": 5786440,
   "mods": [
    {
     "key": "index",
     "num": "01",
     "title": "Patient Flow Index",
     "desc": "Where new cancer patients come from across nine service lines, ZIP by ZIP, for all 254 Texas counties and 64 Louisiana parishes"
    },
    {
     "key": "hotspots",
     "num": "02",
     "title": "Hot Spots",
     "desc": "ZIPs, counties and Louisiana census tracts where cancer runs above what age, sex and race explain, by site, with trends and investigations"
    },
    {
     "key": "workforce",
     "num": "03",
     "title": "Workforce Risk",
     "desc": "Twenty two occupations with documented excess cancer, mapped to the ZIPs where those workers live and the counties where they work, with reach plans"
    },
    {
     "key": "exposure",
     "num": "04",
     "title": "Exposure Map",
     "desc": "Air toxics cancer risk to the census block, 1,215 industrial facilities releasing carcinogens, and what exposure does and does not explain"
    },
    {
     "key": "drivers",
     "num": "05",
     "title": "Cancer Drivers",
     "desc": "What moves observed cancer rates across 318 counties and Louisiana neighborhoods: age, smoking, obesity, screening, income, coverage, air and work"
    },
    {
     "key": "ground",
     "num": "06",
     "title": "Ground Truth",
     "desc": "The registry record: 24 cancer sites in both states against the nation, ranks, stage, survival, 25 year trends and a ledger for every county and parish"
    },
    {
     "key": "paid",
     "num": "07",
     "title": "Paid Acquisition",
     "desc": "Where an ad dollar reaches the most new patient value: efficiency, quadrants, bid tiers and modifiers for every scored ZIP"
    },
    {
     "key": "field",
     "num": "08",
     "title": "Competitive Field",
     "desc": "Every Medicare enrolled oncologist and practice site in both states: organizations, footprints, market concentration, supply gaps and the whitespace between them"
    },
    {
     "key": "desk",
     "num": "09",
     "title": "Campaign Desk",
     "desc": "Budgets, ZIP targets, keywords, negatives, compliant ads in English and Spanish, schedules and bulk files for Google, Microsoft and Meta"
    },
    {
     "key": "forge",
     "num": "10",
     "title": "Site Forge",
     "desc": "Service line, city, county, workforce and screening pages written from the atlas, linted against Texas and Louisiana rules, checked against your sitemap and compiled for any CMS"
    },
    {
     "key": "satchel",
     "num": "11",
     "title": "Compliance Satchel",
     "desc": "Ads, pages, posts and scripts screened against Texas and Louisiana health advertising law, HIPAA, the FTC and Google and Meta health policies"
    },
    {
     "key": "markets",
     "num": "12",
     "title": "Markets",
     "desc": "The hospital referral regions that cover Texas and Louisiana, each on its own: demand, supply, concentration, payers, languages and workforces"
    },
    {
     "key": "lines",
     "num": "13",
     "title": "Service Lines",
     "desc": "Nine service lines resolved to the ZIP: volumes, excess, stage, survival, seasons, keywords, workforces, unit economics and bid targets"
    },
    {
     "key": "law",
     "num": "14",
     "title": "Law and Policy",
     "desc": "The rules that govern oncology marketing in Texas and Louisiana: advertising, solicitation, testimonials, AI, privacy, tracking pixels, language access and platform health policies"
    },
    {
     "key": "calendar",
     "num": "15",
     "title": "Season Desk",
     "desc": "Awareness months, payer enrollment windows, hurricane season and each service line's calendar, turned into a twelve month content and campaign plan"
    },
    {
     "key": "accounts",
     "num": "16",
     "title": "Accounts",
     "desc": "Connect the paid and social accounts, pull what they actually did, and let the actuals correct the models"
    },
    {
     "key": "publish",
     "num": "17",
     "title": "Publish",
     "desc": "Send the pages the Site Forge built, or your own, to WordPress (Elementor or headless), Drupal, Wix, Duda, Webflow, Shopify, HubSpot, Joomla or Ghost"
    }
   ]
  },
  {
   "id": "dental",
   "wing": "health",
   "wingLabel": "Healthcare",
   "vertical": "Dental",
   "short": "Dental Divide",
   "name": "The Dental Divide Atlas",
   "title": "The Dental Divide Atlas",
   "sub": "Companion to The Dental Divide · Research Report, September 2026 · dental marketing platform",
   "navTitle": null,
   "scope": "National",
   "facts": [
    "Ten modules",
    "51 jurisdictions",
    "3,144 counties"
   ],
   "raw": 21987071,
   "mods": [
    {
     "key": "divide",
     "num": "01",
     "title": "The Dental Divide",
     "desc": "Visits, tooth loss, dentists per 100,000, shortage areas and payer rules — the 51-jurisdiction index"
    },
    {
     "key": "policy",
     "num": "02",
     "title": "Payer & Policy",
     "desc": "Medicaid adult dental tiers 2021–25, fees, participation, fluoridation, dental therapy — and the 2012–2024 trends"
    },
    {
     "key": "drivers",
     "num": "03",
     "title": "Demand Drivers",
     "desc": "What actually predicts a dental visit — state and individual-level models, the Medicaid natural experiment, fluoride"
    },
    {
     "key": "paid",
     "num": "04",
     "title": "Paid Acquisition",
     "desc": "Where to buy dental advertising, resolved to the ZIP code — patient mass, case value, competition, what it costs to reach"
    },
    {
     "key": "ground",
     "num": "05",
     "title": "Ground Truth",
     "desc": "Counties and cities as observed — PLACES visits and tooth loss, NPI dentists, HPSA scores, spatial clusters, dental deserts"
    },
    {
     "key": "supply",
     "num": "06",
     "title": "Supply Line",
     "desc": "Dentists, hygienists, wages, shortage designations and Medicaid participation — where the chairs are and are not"
    },
    {
     "key": "desk",
     "num": "07",
     "title": "Campaign Desk",
     "desc": "Budgets, geo lists, keywords, creative and bulk-upload files for Google Search, LSA, YouTube & Demand Gen, Meta, TikTok, Microsoft, Nextdoor and LinkedIn"
    },
    {
     "key": "forge",
     "num": "08",
     "title": "Site Forge",
     "desc": "Service, city, landing and guide pages written from the atlas — Elementor, headless and HTML, deployed to WordPress"
    },
    {
     "key": "satchel",
     "num": "09",
     "title": "Emergency Satchel",
     "desc": "The statute book and the screener — dental board rules, FTC, HIPAA, Reg Z, platform policy; every finding disposed, controlled and routed"
    },
    {
     "key": "texas",
     "num": "10",
     "title": "Texas Dental Statistics",
     "desc": "The Texas record by itself — 254 counties, the workforce, Medicaid/CHIP, coverage, surveillance, and the 177-source inventory"
    }
   ]
  },
  {
   "id": "ocular",
   "wing": "health",
   "wingLabel": "Healthcare",
   "vertical": "Eye care",
   "short": "Ocular Health",
   "name": "The Ocular Health Targeting Atlas",
   "title": "The Ocular Health Targeting Atlas",
   "sub": "Companion to Ocular Health in the United States: Causes, Statistics and Demographic Propensity · Intelligence brief, September 2026",
   "navTitle": null,
   "scope": "National",
   "facts": [
    "Eight modules",
    "51 jurisdictions",
    "3,144 counties"
   ],
   "raw": 16445383,
   "mods": [
    {
     "key": "burden",
     "num": "01",
     "title": "Vision Burden",
     "desc": "VEHSS acuity and disease models, PLACES behaviour, ACS demographics and optometry supply — the state picture"
    },
    {
     "key": "propensity",
     "num": "02",
     "title": "Propensity Engine",
     "desc": "Age, sex, race, income, comorbidity and lifestyle — the multipliers, pools, barriers, seasons and segment scores behind every buy"
    },
    {
     "key": "risk",
     "num": "03",
     "title": "Risk Anatomy",
     "desc": "Race, sex, age, income, education, institution, comorbidity, habit, medication and family history — who is more prone, by how much, and how to reach them compliantly"
    },
    {
     "key": "injury",
     "num": "04",
     "title": "Injury Watch",
     "desc": "Workplace, home, sports and fireworks — who gets hurt, when, in which trades, and where the exposed workforce lives"
    },
    {
     "key": "ground",
     "num": "05",
     "title": "Ground Truth",
     "desc": "Counties and cities as observed — vision disability, diabetes, coverage, disease models, demographics and the offices that serve them"
    },
    {
     "key": "paid",
     "num": "06",
     "title": "Paid Acquisition",
     "desc": "Where to buy, resolved to the ZIP code — unserved demand, value, competition, tiers, bid modifiers and the message each ZIP should hear"
    },
    {
     "key": "desk",
     "num": "07",
     "title": "Campaign Desk",
     "desc": "Budgets, segments, platform mix, geo lists, keywords, creative, compliance lint and bulk-upload files for Google, Meta, YouTube and LinkedIn"
    },
    {
     "key": "forge",
     "num": "08",
     "title": "Site Forge",
     "desc": "The practice website built from the atlas — service pages, state hubs, city pages, Spanish landing pages and guides, compiled to Elementor, HTML and JSON-LD and deployed through the FORGE bridge"
    }
   ]
  }
 ],
 "ext": [
  {
   "file": "Leviathan-data.js",
   "ids": [
    "family",
    "dental",
    "ocular"
   ]
  },
  {
   "file": "Leviathan-data-2.js",
   "ids": [
    "employment"
   ]
  }
 ],
 "views": [
  {
   "route": "command",
   "title": "Command Deck",
   "sub": "The console home: every wing and atlas at a glance"
  },
  {
   "route": "convergence",
   "title": "Convergence",
   "sub": "Every vertical read together on one ZIP map"
  },
  {
   "route": "agencies",
   "title": "Agency Field",
   "sub": "The agencies across the atlases"
  }
 ]
};
