/* ==== content ==== */
"use strict";
/* ============================ service-line angles (shared by modules 5, 8, 9, 10) ============================ */
/* Every string that can leave the atlas as copy obeys house style: no hyphens or dashes, no meta notes. */
const MED = { inc: median(ZR.map(z => z.inc)), value: median(ZR.map(z => z.value)) };
const ANGLES = [
  { id: 'repair', short: 'AC Repair', label: 'Air conditioning repair', line: 'repair', path: '/ac-repair', lsa: ['AC repair', 'AC not cooling', 'Thermostat repair'], trig: z => true, why: 'Core line; every ZIP.',
    kw: ['ac repair', 'air conditioning repair', 'ac repair near me', 'ac not cooling', 'air conditioner not working', 'hvac repair', 'ac service', 'emergency ac repair', 'ac repair {city}', 'air conditioner repair {city}'],
    kwq: ['why is my ac blowing warm air', 'ac not turning on', 'how much is ac repair', 'ac making noise', 'ac frozen coil'],
    h: ['AC Repair in {city}', 'Same Day AC Repair', 'Cooling Fixed Today', 'TDLR Lic {lic}', 'Upfront Repair Pricing', 'Local {city} HVAC Techs', 'Open 7 Days a Week', 'Call {brand} Today', 'AC Not Cooling?', 'Repairs on All Brands', 'Local Trucks in {city}', 'Honest Repair Advice'],
    d: ['Licensed technicians diagnose it, price it before work starts and aim to fix it on the first visit. Lic {lic}.', 'Warm air, strange noises or no power: we diagnose it and quote it before we start. Serving {city} and nearby.', 'Local {county} County team. Call for same day service or book online in two minutes.', 'We repair every major brand and tell you honestly when a repair is not worth it.'],
    es: { h: ['Reparación de AC en {city}', 'Servicio el Mismo Día', 'Técnicos con Licencia', 'Precio Claro Antes', 'Llame a {brand} Hoy'], d: ['Técnicos con licencia en Texas reparan su aire acondicionado. Precio claro antes de empezar. Lic {lic}.', 'Servimos {city} y el condado de {county}. Llame hoy o reserve en línea.'] },
    meta: { p: 'When the AC quits in a {city} summer, you need a straight answer fast. Our licensed techs diagnose it, price it upfront and aim to fix it on the first visit.', h: 'AC repair in {city}, done right', d: 'Licensed. Upfront pricing.' } },
  { id: 'replace', short: 'AC Replacement', label: 'Air conditioner and system replacement', line: 'replace', path: '/ac-replacement', lsa: ['AC installation', 'AC replacement', 'HVAC system installation'], trig: z => z.ge15_sh >= 19 || z.rep_per1k >= 62, why: 'Systems 15+ years at or above 19%, or high replacement rate.',
    kw: ['ac replacement', 'new ac unit', 'ac installation', 'hvac replacement', 'central air replacement', 'new hvac system', 'ac unit replacement cost', 'hvac system replacement {city}', 'ac installation {city}', 'replace ac unit {city}'],
    kwq: ['how much is a new ac unit', 'should i repair or replace my ac', 'how long does an ac unit last in texas', 'what size ac do i need', 'best time to replace ac'],
    h: ['New AC in {city}', 'AC Replacement Quotes', 'Matched Systems Installed', 'Financing Available', 'TDLR Lic {lic}', 'Repair or Replace Advice', 'Installed by Our Own Crew', 'Free Replacement Estimate', 'Systems Sized for Your Home', 'Local {county} Installers', 'Clean, Careful Installs', 'Book a Home Visit Today'],
    d: ['Past 15 years, your AC is past the typical Texas life. Get a written quote for a matched system for your {city} home.', 'We size every system to your house, not a rule of thumb, and install it with our own licensed crew. Lic {lic}.', 'Straight advice on repair or replace, a written price, and a clean install. Serving {county} County.', 'Ask about financing options. Terms and approval apply; see details before you buy.'],
    es: { h: ['Aire Nuevo en {city}', 'Cotización Gratis', 'Instalación con Licencia', 'Financiamiento Disponible', 'Llame a {brand}'], d: ['Instalamos sistemas completos del tamaño correcto para su casa. Precio por escrito. Lic {lic}.', 'Consejo honesto: reparar o reemplazar. Servimos {city} y {county}.'] },
    meta: { p: 'Is your AC past 15 years? Half of Texas systems are replaced by then. Get a written quote for a matched system, sized to your {city} home and installed by our own licensed crew.', h: 'A new AC, quoted in writing', d: 'Matched systems. Licensed crew.' } },
  { id: 'firstwave', short: 'Builder System', label: 'First replacement of the builder\'s original system', line: 'replace', path: '/ac-replacement', lsa: ['AC replacement', 'HVAC system installation'], trig: z => z.origwin_sh >= 15, why: 'Original builder systems aged 10 to 25 at or above 15%.',
    kw: ['replace builder grade ac', 'original ac unit replacement', 'ac replacement {city}', 'new ac for {city} home', 'hvac upgrade {city}', 'ac unit replacement near me'],
    kwq: ['is my builder grade ac oversized', 'how long do builder grade ac units last', 'why is my upstairs so hot'],
    h: ['Still on the Builder AC?', 'Upgrade Your Original AC', 'Fix Hot Upstairs Rooms', 'Sized Right This Time', 'AC Replacement {city}', 'TDLR Lic {lic}', 'Free Home Comfort Visit', 'Quotes in Writing'],
    d: ['Homes in {city} built in the 2000s and 2010s are reaching their first AC replacement. We size the new one to the house.', 'Builder systems are often oversized. We measure, fix the duct runs and install a matched system. Lic {lic}.'],
    es: { h: ['¿Su AC es el Original?', 'Cambie su Sistema', 'Instalación con Licencia'], d: ['Las casas de {city} de los años 2000 llegan a su primer cambio de aire. Lo medimos bien. Lic {lic}.'] },
    meta: { p: 'If your {city} home came with its original AC, it is probably reaching its first replacement. This time, size it to the house and fix the hot rooms while you are at it.', h: 'Your first AC replacement', d: 'Sized right. Licensed crew.' } },
  { id: 'r22', short: 'R22 System', label: 'R22 system replacement', line: 'replace', path: '/r22-replacement', lsa: ['AC replacement'], trig: z => z.r22_sh >= 16.5, why: 'R22 era systems at or above 16.5%.',
    kw: ['r22 ac replacement', 'r22 freon replacement', 'replace r22 unit', 'r22 ac unit {city}', 'old freon ac replacement', 'r22 refrigerant cost'],
    kwq: ['can i still get r22 freon', 'is my ac r22', 'how much to recharge r22', 'what replaces r22'],
    h: ['Is Your AC on R22?', 'R22 Systems Replaced', 'Stop Paying for R22', 'Old Freon AC? Call Us', 'TDLR Lic {lic}', 'Written Replacement Quote', 'Serving {city} Homes'],
    d: ['R22 has not been produced since 2020. If your AC leaks, a recharge costs more every year. Get a replacement quote.', 'We check your label, tell you what refrigerant you have, and price a matched system in writing. Lic {lic}.'],
    es: { h: ['¿Su AC Usa R22?', 'Reemplazo de R22'], d: ['El R22 ya no se produce. Le damos una cotización por escrito para un sistema nuevo. Lic {lic}.'] },
    meta: { p: 'Systems installed before 2010 in {city} usually run on R22, which has not been produced since 2020. When yours leaks, a recharge is money into a system with no future. We will check your label for free.', h: 'Still running R22?', d: 'Free label check.' } },
  { id: 'furnace', short: 'Furnace', label: 'Furnace replacement and heating safety', line: 'heat', path: '/furnace-replacement', lsa: ['Furnace installation', 'Furnace repair', 'Heating system repair'], trig: z => z.furn20_sh >= 13.5 && z.gas_sh >= 35, why: 'Gas furnaces 20+ at or above 13.5% where gas heat is at least 35%.',
    kw: ['furnace replacement', 'new furnace', 'furnace repair', 'gas furnace installation', 'heater repair', 'furnace replacement {city}', 'furnace repair {city}', 'furnace inspection'],
    kwq: ['how long does a furnace last', 'furnace smells like gas', 'furnace not igniting', 'is my furnace safe'],
    h: ['Furnace Repair {city}', 'Furnace Safety Check', 'New Gas Furnace Quotes', 'Heat Back On Today', 'TDLR Lic {lic}', 'Is Your Furnace 20+?', 'Local {county} Techs'],
    d: ['Furnaces over 20 years old deserve a safety check before the first cold night. Licensed techs in {city}. Lic {lic}.', 'No heat, short cycling or a burner that will not light: we fix it or quote a replacement in writing.'],
    es: { h: ['Reparación de Calefacción', 'Revisión de Seguridad'], d: ['Revisamos su calefacción antes del frío. Técnicos con licencia en {city}. Lic {lic}.'] },
    meta: { p: 'If your furnace is past 20, have it checked before the first cold snap. Our licensed techs inspect burners, flame sensors and the heat exchanger and tell you straight what it needs.', h: 'Furnace check before winter', d: 'Licensed. Honest advice.' } },
  { id: 'heatpump', short: 'Heat Pump', label: 'Heat pump repair and replacement', line: 'replace', path: '/heat-pump', lsa: ['Heat pump installation', 'Heat pump repair'], trig: z => z.hp_sh >= 35, why: 'Heat pump share at or above 35%.',
    kw: ['heat pump repair', 'heat pump replacement', 'heat pump installation', 'heat pump not heating', 'heat pump {city}', 'heat pump service near me'],
    kwq: ['why is my heat pump blowing cold air', 'heat pump vs furnace texas', 'how long do heat pumps last'],
    h: ['Heat Pump Repair {city}', 'Heat Pump Replacement', 'Heating and Cooling in One', 'TDLR Lic {lic}', 'Defrost Problems Fixed', 'Written Quotes'],
    d: ['Heat pumps work year round in Texas and wear faster. We repair every brand and quote replacements in writing. Lic {lic}.', 'Cold air in heat mode, icing or strip heat bills: our {city} techs find the cause.'],
    es: { h: ['Bomba de Calor', 'Reparación y Cambio'], d: ['Reparamos y cambiamos bombas de calor en {city}. Lic {lic}.'] },
    meta: { p: 'Your heat pump cools all summer and heats all winter, so it wears faster than a plain AC. If yours is struggling, our licensed techs will tell you whether it needs a fix or a replacement.', h: 'Heat pump trouble?', d: 'Repair or replace, in writing.' } },
  { id: 'hail', short: 'Hail Damage', label: 'Hail damaged condenser and insurance replacement', line: 'replace', path: '/hail-damage-ac', lsa: ['AC repair', 'AC replacement'], trig: z => z.hail175_8km >= 10 || z.hail_recent >= 6, why: 'Large hail within 8 km at or above 10 reports a decade, or 6+ since 2023.',
    kw: ['hail damage ac unit', 'hail damaged condenser', 'ac hail damage insurance', 'hail damage hvac {city}', 'condenser coil hail damage'],
    kwq: ['does insurance cover hail damage to ac', 'can hail damage an ac unit', 'how to tell if ac has hail damage'],
    h: ['Hail Hit Your AC?', 'Hail Damage Inspections', 'Condenser Coil Checks', 'Damage Photos for Your Insurer', 'TDLR Lic {lic}', 'Serving {city} After Storms'],
    d: ['Hail flattens condenser fins and cuts efficiency. We inspect, photograph and document the damage for your claim. Lic {lic}.', 'Storm in {city}? Book a condenser inspection. Your insurer decides coverage; we give you the documentation.'],
    es: { h: ['¿Granizo Dañó su AC?', 'Inspección por Granizo'], d: ['Inspeccionamos y documentamos daño por granizo para su reclamo. Lic {lic}.'] },
    meta: { p: 'Hail can crush the fins on your outdoor unit and cut its efficiency. After a storm in {city}, we inspect, photograph and document the damage so you can decide on a claim.', h: 'After the hail, check the AC', d: 'Inspection and photos.' } },
  { id: 'duct', short: 'Ductwork', label: 'Ductwork replacement and full system reinstall', line: 'replace', path: '/ductwork', lsa: ['Duct repair', 'Duct installation'], trig: z => z.yb_duct >= 40, why: 'Homes built 1980 to 1999 at or above 40%.',
    kw: ['duct replacement', 'ductwork replacement', 'air duct repair', 'duct sealing', 'new ductwork {city}', 'hvac duct replacement cost'],
    kwq: ['how long does ductwork last', 'signs of leaky ducts', 'why are some rooms hotter'],
    h: ['Ductwork Replaced Right', 'Leaky Ducts Fixed', 'Even Cooling Room to Room', 'Full System Reinstalls', 'TDLR Lic {lic}', 'Serving {city} Homes'],
    d: ['Attic ducts from the 1980s and 1990s are past their life. We replace, seal and balance them with your new system. Lic {lic}.', 'Hot rooms and high bills often start in the attic. Our {city} crew tests and fixes the duct system.'],
    es: { h: ['Ductos Nuevos', 'Reparación de Ductos'], d: ['Cambiamos y sellamos ductos viejos en {city}. Lic {lic}.'] },
    meta: { p: 'If your {city} home was built in the 80s or 90s, the ducts in the attic are likely original. We test them, replace what is failing and balance the system so every room cools.', h: 'Hot rooms start in the attic', d: 'Duct testing and replacement.' } },
  { id: 'landlord', short: 'Rental Homes', label: 'Landlord and property manager service', line: 'b2b', path: '/property-managers', lsa: ['AC repair', 'AC replacement'], trig: z => z.rent_sf_sh >= 30, why: 'Rented share of single-family homes at or above 30%.',
    kw: ['hvac for property managers', 'rental property ac repair', 'landlord hvac service', 'property management hvac {city}'],
    kwq: ['who pays for ac repair in a rental', 'hvac contract for rental properties'],
    h: ['HVAC for Rental Homes', 'Property Manager Service', 'Fast Tenant Response', 'One Invoice, Many Homes', 'TDLR Lic {lic}'],
    d: ['We handle AC calls for rental homes across {county} County with fast tenant response and clear invoices. Lic {lic}.'],
    es: { h: ['Servicio para Rentas'], d: ['Servicio de aire para casas de renta en {county}. Lic {lic}.'] },
    meta: { p: 'Managing rental homes in {city}? We handle tenant AC calls fast, send one clear invoice and tell you straight when a system should be replaced.', h: 'HVAC for rental homes', d: 'Fast response. Clear invoices.' } },
  { id: 'newowner', short: 'New Homeowner', label: 'New homeowner system checkup', line: 'maint', path: '/home-buyers', lsa: ['AC maintenance'], trig: z => z.own_recent_sh >= 22, why: 'Owners who moved in since 2020 at or above 22%.',
    kw: ['hvac inspection new home', 'ac inspection', 'hvac checkup', 'ac tune up {city}', 'hvac inspection {city}'],
    kwq: ['how old is my ac unit', 'how to read ac serial number age'],
    h: ['New Home? Check the AC', 'System Age and Health Check', 'Know What You Bought', 'TDLR Lic {lic}'],
    d: ['Just moved to {city}? We tell you how old your system is, what shape it is in and what to budget for. Lic {lic}.'],
    es: { h: ['¿Casa Nueva?', 'Revisión del Sistema'], d: ['Le decimos la edad y el estado de su aire en {city}. Lic {lic}.'] },
    meta: { p: 'New to your {city} home? Find out how old the AC and furnace are, what condition they are in and what to plan for, before the first hot week.', h: 'Know your system', d: 'Age and health check.' } },
  { id: 'premium', short: 'High Efficiency', label: 'Variable speed and high efficiency systems', line: 'replace', path: '/high-efficiency', lsa: ['AC installation', 'Heat pump installation'], trig: z => (z.value || 0) >= 500000 || (z.inc || 0) >= 150000, why: 'Median value at or above $500,000 or income at or above $150,000.',
    kw: ['variable speed ac', 'high efficiency ac', 'two stage ac', 'quiet ac system', 'high efficiency hvac {city}'],
    kwq: ['is a variable speed ac worth it', 'what seer rating is best for texas'],
    h: ['Variable Speed Comfort', 'Quiet High Efficiency AC', 'Even Temperatures, Lower Bills', 'TDLR Lic {lic}', 'Premium Installs in {city}'],
    d: ['Variable speed systems hold temperature and humidity steady in a Texas summer. Sized and installed by our own crew. Lic {lic}.'],
    es: { h: ['Alta Eficiencia'], d: ['Sistemas de velocidad variable para {city}. Lic {lic}.'] },
    meta: { p: 'A variable speed system runs longer at low speed, so it is quieter, pulls more humidity and keeps upstairs and downstairs closer together. Ask for a written quote.', h: 'Quieter, steadier cooling', d: 'Variable speed systems.' } },
  { id: 'financing', short: 'Financing', label: 'Replacement with financing', line: 'replace', path: '/financing', lsa: ['AC replacement'], trig: z => (z.inc || 0) < MED.inc && z.own_sf_sh >= 50, why: 'Income below the metro ZIP median with owner single-family at or above 50%.',
    kw: ['ac financing', 'hvac financing', 'finance new ac unit', 'ac payment plans {city}'],
    kwq: ['can i finance a new ac', 'hvac financing bad credit'],
    h: ['Financing for a New AC', 'Monthly Payment Options', 'Apply in Minutes Online', 'TDLR Lic {lic}'],
    d: ['Financing options for new systems, subject to credit approval. See terms, APR and conditions before you buy. Lic {lic}.'],
    es: { h: ['Financiamiento para su AC'], d: ['Opciones de pago sujetas a aprobación de crédito. Vea términos y APR. Lic {lic}.'] },
    meta: { p: 'A new AC should not wait for savings to catch up. Ask about financing options for your {city} home; approval, terms and APR apply and are shown before you sign.', h: 'Financing options', d: 'Terms shown upfront.' } },
  { id: 'maint', short: 'Maintenance Plan', label: 'Maintenance plans and tune ups', line: 'maint', path: '/maintenance-plan', lsa: ['AC maintenance', 'Furnace maintenance'], trig: z => z.own65_sh >= 30 || z.own_sf_sh >= 70, why: 'Owners 65+ at or above 30% or owner single-family at or above 70%.',
    kw: ['ac tune up', 'hvac maintenance plan', 'ac maintenance', 'furnace tune up', 'hvac service plan {city}'],
    kwq: ['how often should ac be serviced', 'is an hvac maintenance plan worth it'],
    h: ['Twice a Year Tune Ups', 'Maintenance Plan Members', 'Priority Service in Summer', 'TDLR Lic {lic}'],
    d: ['Spring AC and fall furnace tune ups with priority scheduling when the heat hits. Serving {city}. Lic {lic}.'],
    es: { h: ['Plan de Mantenimiento'], d: ['Mantenimiento dos veces al año y prioridad en verano. Lic {lic}.'] },
    meta: { p: 'Two visits a year, priority scheduling in the first heat wave and a written record of your system. That is our maintenance plan for {city} homes.', h: 'Beat the first heat wave', d: 'Priority scheduling.' } },
  { id: 'iaq', short: 'Indoor Air', label: 'Indoor air quality: filtration, purification and humidity control', line: 'iaq', path: '/indoor-air-quality', lsa: ['AC maintenance'], trig: z => (z.own_sf_sh || 0) >= 40, why: 'Owner single-family at or above 40%; strongest in cedar and oak season.',
    kw: ['indoor air quality', 'whole home air purifier', 'hvac air filtration system', 'uv light for hvac', 'whole house dehumidifier', 'air scrubber for hvac', 'indoor air quality {city}', 'whole home air purifier {city}'],
    kwq: ['does a whole house air purifier help with allergies', 'what is a media air cleaner', 'how to reduce dust in house hvac', 'is a uv light in hvac worth it'],
    h: ['Cleaner Air, Whole Home', 'Cedar Season Relief', 'Media Filters and UV', 'Less Dust, Fewer Allergens', 'Indoor Air Quality {city}', 'TDLR Lic {lic}', 'Humidity Under Control', 'Installed With Your System', 'Ask About Air Cleaning', 'Breathe Easier at Home'],
    d: ['Media air cleaners, UV lights and dehumidifiers for the system you own. Lic {lic}.', 'Cedar, oak and ragweed hit hardest indoors. Filtration sized to your {city} system.', 'Cleaner coil, tighter filtration, steadier humidity. Priced first. Lic {lic}.', 'We tell you what each device will and will not do. No cure claims, just cleaner air.'],
    es: { h: ['Aire Más Limpio en Casa', 'Filtros y Luz UV', 'Menos Polvo y Alergias'], d: ['Purificadores y filtros instalados en su sistema. Servimos {city}. Lic {lic}.'] },
    meta: { p: 'When cedar season hits {city}, the air inside the house is where you spend the night. Media air cleaners, UV and dehumidification, installed in the system you already have and explained without exaggeration.', h: 'Cleaner air, whole home', d: 'Filtration and UV, explained plainly.' } },
  { id: 'ductless', short: 'Ductless', label: 'Ductless mini split systems for rooms the ducts never reached', line: 'ductless', path: '/ductless-mini-split', lsa: ['AC installation'], trig: z => ((z.yb ? (z.yb[7] + z.yb[8] + z.yb[9]) : 0) / Math.max(1, z.hu || 1)) >= 0.08 || (z.br4p_sh || 0) >= 35, why: 'Homes built before 1960 at or above 8% of units, or four bedroom homes at or above 35%.',
    kw: ['ductless mini split installation', 'mini split installation', 'ductless ac', 'garage ac unit installed', 'mini split for garage', 'ductless air conditioner {city}', 'mini split installation {city}'],
    kwq: ['how much does a mini split cost installed', 'is a mini split good for a garage', 'mini split vs window unit', 'can a mini split heat and cool'],
    h: ['Ductless Mini Splits', 'Cool the Garage Gym', 'Rooms the Ducts Missed', 'One Unit, Several Rooms', 'Mini Splits in {city}', 'TDLR Lic {lic}', 'Heats and Cools Year Round', 'Installed and Permitted', 'Quiet Room by Room Comfort', 'Written Quote in a Day'],
    d: ['Sunroom, garage, addition or a home without ducts. Permitted install. Lic {lic}.', 'One outdoor unit, several rooms, each with its own control. Quoted in writing.', 'Ductless heat pumps cool in August and heat in January. In {city}. Lic {lic}.', 'Licensed crew, permit pulled, line set and circuit included in the written price.'],
    es: { h: ['Mini Split Sin Ductos', 'Fresco en el Garaje', 'Instalación con Licencia'], d: ['Sistemas mini split instalados con permiso en {city}. Lic {lic}.'] },
    meta: { p: 'The garage gym, the sunroom, the addition, the {city} house built before ducts were standard. A ductless mini split cools and heats the room the system never reached, installed by a licensed crew.', h: 'Rooms the ducts never reached', d: 'Ductless, installed and permitted.' } },
  { id: 'commercial', short: 'Light Commercial', label: 'Light commercial HVAC for small buildings and rooftop units', line: 'commercial', path: '/commercial-hvac', lsa: [], trig: z => (z.density || 0) >= 1500 || (z.est_8km || 0) >= 40, why: 'Housing density at or above 1,500 units a square mile or 40 or more HVAC establishments within 8 km, as a proxy for business density.',
    kw: ['commercial hvac repair', 'commercial ac repair', 'rooftop unit replacement', 'commercial hvac maintenance contract', 'commercial hvac {city}', 'commercial ac repair {city}', 'rtu replacement {city}'],
    kwq: ['how long do rooftop units last', 'commercial hvac maintenance cost', 'who repairs rooftop ac units'],
    h: ['Commercial HVAC Service', 'Rooftop Units Replaced', 'Maintenance Contracts', 'Response in Hours', 'Commercial HVAC {city}', 'TDLR Lic {lic}', 'Small Buildings, Big Rooftops', 'Quotes by Tonnage', 'Keep Tenants Comfortable', 'Licensed Commercial Techs'],
    d: ['Rooftop units repaired and replaced for offices, retail and restaurants. Lic {lic}.', 'Maintenance contracts priced per unit with a written report after every visit.', 'Quotes by tonnage, crane and permit included. Licensed commercial techs. Lic {lic}.', 'Response time in writing. A restaurant without cooling in July is a closure.'],
    es: { h: ['HVAC Comercial', 'Unidades de Techo'], d: ['Servicio HVAC comercial en {city}. Lic {lic}.'] },
    meta: { p: 'A rooftop unit that quits in July costs a {city} business more than the repair. We service and replace commercial systems with response times in writing and maintenance contracts priced per unit.', h: 'Commercial HVAC, in writing', d: 'Rooftop units and contracts.' } },
  { id: 'recruit', short: 'Technician Jobs', label: 'Recruiting HVAC technicians', line: 'recruit', path: '/careers', lsa: [], trig: z => false, why: 'Recruiting line; used when the plan line is recruiting.',
    kw: ['hvac technician jobs', 'hvac installer jobs', 'hvac jobs {city}', 'ac technician jobs near me'],
    kwq: [],
    h: ['HVAC Technicians Wanted', 'Install and Service Roles', 'Pay Range Posted: {pay}', 'Company Truck and Tools', 'Grow With a Local Team'],
    d: ['Registered or certified HVAC techs: pay range {pay}, company truck, training and a real schedule. Apply online.'],
    es: { h: ['Buscamos Técnicos HVAC'], d: ['Técnicos HVAC: rango de pago {pay}, camioneta y entrenamiento.'] },
    meta: { p: 'We are hiring HVAC technicians and installers in {county} County. Pay range {pay}, company truck, tools and training. Apply in two minutes.', h: 'HVAC techs wanted', d: 'Pay range posted.' } },
];
const ANG = {}; ANGLES.forEach(a => ANG[a.id] = a);
const LINES = {
  replace: { l: 'Replacements and reinstalls', angles: ['replace', 'firstwave', 'r22', 'heatpump', 'hail', 'duct', 'premium', 'financing'], obj: 'leads' },
  repair: { l: 'Cooling repair', angles: ['repair', 'hail'], obj: 'calls' },
  heat: { l: 'Heating repair and furnace replacement', angles: ['furnace', 'heatpump'], obj: 'calls' },
  maint: { l: 'Maintenance plans', angles: ['maint', 'newowner'], obj: 'leads' },
  b2b: { l: 'Landlords and property managers', angles: ['landlord'], obj: 'leads' },
  recruit: { l: 'Recruiting technicians', angles: ['recruit'], obj: 'applications' },
  iaq: { l: 'Indoor air quality', angles: ['iaq', 'maint'], obj: 'leads' },
  ductless: { l: 'Ductless mini splits', angles: ['ductless', 'premium'], obj: 'leads' },
  commercial: { l: 'Light commercial HVAC', angles: ['commercial'], obj: 'leads' },
  blend: { l: 'Full service blend', angles: ['repair', 'replace', 'firstwave', 'r22', 'furnace', 'heatpump', 'hail', 'duct', 'maint'], obj: 'calls' },
};
const anglesFor = z => ANGLES.filter(a => a.id !== 'recruit' && a.trig(z));
const NEG_CUSTOMER = ['jobs', 'job', 'hiring', 'careers', 'salary', 'school', 'training', 'certification', 'course', 'diy', 'how to install', 'youtube', 'reddit', 'parts', 'supply', 'wholesale', 'amazon', 'home depot', 'lowes', 'walmart', 'window unit', 'portable ac', 'car ac', 'auto ac', 'rv ac', 'free', 'manual', 'wiring diagram', 'lawsuit', 'recall'];
const NEG_RECRUIT = ['repair', 'near me ac', 'cost', 'price', 'replacement', 'install my', 'financing', 'coupon'];
function fillCopy(t, ctx, limit) {
  let s = String(t).replace(/\{(\w+)\}/g, (m, k) => ctx[k] != null ? ctx[k] : m);
  s = houseClean(s);
  if (limit && s.length > limit) { const alt = String(t).replace(/\{city\}/g, ctx.short || ctx.county || 'DFW').replace(/\{(\w+)\}/g, (m, k) => ctx[k] != null ? ctx[k] : m); s = houseClean(alt); if (s.length > limit) return null; }
  return /\{\w+\}/.test(s) ? null : s;
}
