/* ==== satchel_rules ==== */
"use strict";
/* ============================ EMERGENCY SATCHEL: HVAC rule pack (shared by modules 8, 9, 10) ============================ */
/* Each rule: id, fam (enforcer family), sev (block | warn | note), test(text, ctx) -> evidence string or null, cite, v (✔ read this build, ◐ memory or secondary), fix, route */
const SAT = {
  version: '2026-09-25', vertical: 'HVAC, Dallas Fort Worth',
  rules: [
    { id: 'TDLR1', fam: 'TDLR', sev: 'block', name: 'License number missing from advertising', cite: '16 TAC §75.71(h)', v: '✔', scope: 'asset', test: (t, c) => c && c.needLic && !/TAC\s?L\s?[A-Z]\s?\d{4,}/i.test(t) && !(c.lic && t.includes(c.lic)) ? 'No TDLR license number (TACLA or TACLB format) found in the asset set' : null, fix: 'Add the affiliated licensee\'s number, for example "Lic TACLA12345C", to at least one description or the page footer.', route: 'TDLR complaint (competitor) or remediation ticket (self)' },
    { id: 'TDLR2', fam: 'TDLR', sev: 'note', name: 'TDLR consumer notice on proposals, invoices, contracts and signage', cite: '16 TAC §75.71(i)', v: '✔', scope: 'page', test: (t, c) => c && c.page && /(proposal|estimate|invoice|contract|financ)/i.test(t) && !/Texas Department of Licensing and Regulation/i.test(t) ? 'Page discusses proposals or contracts without the TDLR regulated-by notice' : null, fix: 'Add: Regulated by The Texas Department of Licensing and Regulation, P.O. Box 12157, Austin, Texas 78711, 1 800 803 9202, 512 463 6599.', route: 'Remediation (self); intelligence only (competitor)' },
    { id: 'TAX1', fam: 'FTC / DTPA', sev: 'block', name: 'Lapsed federal tax credit advertised', cite: 'IRS 25C (property placed in service after Dec 31, 2025 excluded); FTC Act §5; DTPA §17.46(b)', v: '✔', test: t => { const hit = String(t).split(/[.!?]\s+/).find(x => /(tax credit|25C|federal rebate|IRA rebate|inflation reduction act)/i.test(x) && !/(ended|expired|lapsed|no longer|not available|terminated|does not qualify|did not survive)/i.test(x)); if (!hit) return null; const m = hit.match(/(tax credit|25C|federal rebate|IRA rebate|inflation reduction act)/i); return `"${m[0]}"`; }, fix: 'Remove credit language for 2026 installs. Mention Oncor\'s program only with the current program year\'s terms.', route: 'Texas AG Consumer Protection (DTPA) or FTC (competitor)' },
    { id: 'REGZ1', fam: 'CFPB / FTC', sev: 'block', name: 'Credit trigger term without required disclosures', cite: 'Regulation Z, 12 CFR §1026.24(d)', v: '◐', test: t => { const m = t.match(/(\b\d{1,3}\s*(monthly\s*)?payments?\b|\$\s?\d[\d,]*\s*(\/|a|per)\s*(mo|month)\b|\d+(\.\d+)?%\s*(apr|interest|financing)|\b0%\s*(apr|interest|financing)|down payment|no interest|interest free|\d+\s*months?\s*(no|0%|same as cash))/i); if (!m) return null; return /\bAPR\b.*\b(terms|approval)\b|\b(terms|approval)\b.*\bAPR\b/i.test(t) ? null : `"${m[0]}" without APR, terms and repayment disclosure`; }, fix: 'State the APR, the terms of repayment and the down payment, or drop the specific term and say "Financing options available, subject to credit approval."', route: 'FTC or CFPB (competitor); remediation (self)' },
    { id: 'FREE1', fam: 'FTC', sev: 'note', name: '"Free" offer: conditions must be clear', cite: '16 CFR Part 251 (Guide Concerning Use of the Word Free)', v: '◐', test: t => { const m = t.match(/\bfree\b[^.]{0,40}/i); return m ? `"${m[0].trim()}"` : null; }, fix: 'State every condition next to the offer (for example "free estimate on system replacement; service calls billed").', route: 'Intelligence' },
    { id: 'GUAR1', fam: 'FTC / DTPA', sev: 'warn', name: 'Guarantee or warranty claim without stated terms', cite: 'FTC Act §5; 16 CFR Part 239 (Guides for Advertising Warranties and Guarantees); DTPA §17.46(b)(20)', v: '◐', test: t => { const m = t.match(/\b(guarantee[ds]?|guaranteed|warrant(y|ies)|lifetime (warranty|guarantee|coverage|protection|service))\b[^.]{0,40}/i); return m && !/(terms|details|see|conditions)/i.test(t) ? `"${m[0].trim()}"` : null; }, fix: 'Say what is guaranteed, for how long, and how to claim it, or link the terms beside the claim.', route: 'Intelligence; DTPA if material' },
    { id: 'SUP1', fam: 'FTC / NAD', sev: 'warn', name: 'Superiority or price claim needs substantiation', cite: 'FTC Policy Statement on Substantiation; DTPA §17.46(b)(5),(7)', v: '◐', test: t => { const m = t.match(/(#\s?1\b|number one|best (hvac|ac|price|in )|lowest price|cheapest|top rated|highest rated|most trusted|beat any price)/i); return m ? `"${m[0]}"` : null; }, fix: 'Cite the basis (for example "4.9 stars from 708 Google reviews, Sep 2026") or remove the claim.', route: 'Intelligence; NAD challenge if a competitor relies on it' },
    { id: 'REV1', fam: 'FTC', sev: 'warn', name: 'Review or rating claim must match real reviews', cite: 'FTC Trade Regulation Rule on Consumer Reviews and Testimonials, 16 CFR Part 465 (effective Oct 21, 2024)', v: '◐', test: t => { const m = t.match(/(\d[\d,]{2,}\+?\s*(five|5)\s*star|\b[45](\.\d)?\s*stars?\b|five star rated|5 star rated)/i); return m ? `"${m[0]}"` : null; }, fix: 'Match the count and rating to the live profile and date it; never gate or buy reviews.', route: 'FTC (competitor, fabricated reviews only)' },
    { id: 'URG1', fam: 'FTC / DTPA', sev: 'warn', name: 'False urgency or countdown', cite: 'FTC Act §5 (dark patterns); DTPA §17.46(b)(9),(11)', v: '◐', test: t => { const m = t.match(/(only \d+ (spots|slots|units|left)|offer ends in|today only|act now|last chance|expires tonight)/i); return m ? `"${m[0]}"` : null; }, fix: 'Use a real end date or remove the deadline.', route: 'Intelligence' },
    { id: 'R22A', fam: 'EPA / DTPA', sev: 'warn', name: 'Misstated R22 or refrigerant rule', cite: 'EPA Section 605 phaseout; Technology Transitions rule as amended May 26, 2026', v: '◐', test: t => { const m = t.match(/(r[\s-]?22|r[\s-]?410a|freon)[^.]{0,40}(illegal|banned to use|must be replaced|outlawed|no longer legal)/i); return m ? `"${m[0]}"` : null; }, fix: 'Operating an R22 or R410A system is legal. Say what is true: R22 is no longer produced, and new split systems use A2L refrigerants.', route: 'Intelligence; DTPA if used to force a sale' },
    { id: 'INS1', fam: 'TDI / DTPA', sev: 'warn', name: 'Contractor offering to handle or negotiate an insurance claim', cite: 'Tex. Ins. Code ch. 4102 (a contractor may not act or advertise as a public adjuster, §4102.163); Tex. Ins. Code ch. 707 (paying or waiving a deductible)', v: '◐', test: t => { const m = t.match(/(we (will |can |)(handle|negotiate|manage|settle) (your |the )?(insurance )?claim|deal with your insurance( company)?|work(s)? directly with your insurance|we'?ll handle the claim|free roof|waive (your )?deductible|pay (your )?deductible)/i); return m ? `"${m[0]}"` : null; }, fix: 'Offer inspection, photos and a written quote; say the claim is between the homeowner and the insurer. Never offer to waive or pay a deductible.', route: 'Texas Department of Insurance complaint (competitor); remediation (self)' },
    { id: 'EFF1', fam: 'FTC / DOE', sev: 'note', name: 'Efficiency rating claim', cite: 'FTC Energy Labeling Rule, 16 CFR Part 305; AHRI certified ratings', v: '◐', test: t => { const m = t.match(/\b(seer2?|eer2?|hspf2?|afue)\b\s*(of|rating of|:)?\s*\d{1,2}(\.\d)?(?!\d)|\b\d{1,2}(\.\d)?\s*(seer2?|eer2?|hspf2?)\b/i); return m ? `"${m[0]}"` : null; }, fix: 'Quote the AHRI certified rating of the matched system (condenser plus coil or air handler), not the condenser alone.', route: 'Intelligence' },
    { id: 'ES1', fam: 'EPA / DOE', sev: 'warn', name: 'ENERGY STAR mark use', cite: 'ENERGY STAR Identity Guidelines', v: '◐', test: t => /energy\s?star/i.test(t) ? '"ENERGY STAR" mentioned' : null, fix: 'Use the mark only for certified models and never as a company endorsement.', route: 'Intelligence' },
    { id: 'LIC2', fam: 'TDLR / DTPA', sev: 'note', name: '"Licensed and insured", "bonded" or "certified" claims', cite: 'DTPA §17.46(b)(5); EPA 40 CFR Part 82 Subpart F for Section 608', v: '◐', test: t => { const m = t.match(/(licensed (and|&) insured|bonded|nate certified|epa certified|factory authori[sz]ed|elite dealer|diamond contractor)/i); return m ? `"${m[0]}"` : null; }, fix: 'Keep proof on file: certificate of insurance, NATE or 608 cards, the manufacturer dealer letter.', route: 'Intelligence' },
    { id: 'AVL1', fam: 'DTPA', sev: 'note', name: 'Availability claim (24/7, same day)', cite: 'DTPA §17.46(b)(9)', v: '◐', test: t => { const m = t.match(/(24\/7|24 hours|around the clock|same day|open 7 days)/i); return m ? `"${m[0]}"` : null; }, fix: 'Only if staffed. Same day claims need a stated cutoff time.', route: 'Intelligence' },
    { id: 'SMS1', fam: 'FCC / Texas', sev: 'warn', name: 'Texting without documented consent', cite: 'TCPA 47 U.S.C. §227; Texas Bus. & Com. Code ch. 302 as amended by SB 140 (Sep 1, 2025)', v: '◐', test: t => { const m = t.match(/(text you|we'?ll text|send you texts|sms updates|text message offers)/i); return m && !/(consent|stop to opt out|reply stop|not a condition)/i.test(t) ? `"${m[0]}"` : null; }, fix: 'Unchecked consent box, disclosure that consent is not a condition of purchase, STOP instructions; register under chapter 302 if the exemption does not apply.', route: 'Intelligence; private DTPA action risk' },
    { id: 'GGL1', fam: 'Google Ads', sev: 'warn', name: 'Editorial: exclamation or gimmicky capitals in a headline', cite: 'Google Ads Editorial policy', v: '◐', scope: 'headline', test: t => /!/.test(t) ? 'exclamation mark' : /\b[A-Z]{5,}\b/.test(t.replace(/\b(HVAC|TDLR|SEER|AFUE|HSPF|ENERGY|STAR|NATE|TACLA|TACLB)\b/g, '')) ? 'all capitals word' : null, fix: 'Remove the exclamation mark or recase the word.', route: 'Ad disapproval (self)' },
    { id: 'GGL2', fam: 'Google Ads', sev: 'note', name: 'Phone number inside ad text', cite: 'Google Ads Editorial policy (use call assets)', v: '◐', test: t => /\(?\d{3}\)?[\s.]\d{3}[\s.]\d{4}/.test(t) ? 'phone number in text' : null, fix: 'Move the number to a call asset.', route: 'Ad disapproval (self)' },
    { id: 'META1', fam: 'Meta', sev: 'warn', name: 'Personal attribute assertion', cite: 'Meta Advertising Standards, personal attributes', v: '◐', test: t => { const m = t.match(/(your (credit|debt|finances)|bad credit|are you (broke|struggling)|behind on bills)/i); return m ? `"${m[0]}"` : null; }, fix: 'Describe the offer, not the person.', route: 'Ad rejection (self)' },
    { id: 'META2', fam: 'Meta', sev: 'note', name: 'Financing offer may require the Financial products special ad category', cite: 'Meta special ad categories (Financial products and services, 2025)', v: '◐', scope: 'meta', test: t => /(financ|monthly payment|apr|credit approval)/i.test(t) ? 'financing language in a Meta asset' : null, fix: 'Run financing creative in a separate campaign under the special ad category (15 mile radius minimum, no ZIP, age or gender targeting) or remove financing from ZIP-targeted ad sets.', route: 'Account restriction risk (self)' },
    { id: 'HOUSE1', fam: 'House style', sev: 'block', name: 'Hyphen or dash in copy', cite: 'House style: no hyphens or dashes of any kind in copy', v: '✔', scope: 'copy', test: t => { const m = t.match(/\S*[‐-―−-]\S*/); return m && !/^https?:|^\/|@/.test(m[0]) ? `"${m[0]}"` : null; }, fix: 'Rewrite without the hyphen or dash (the desk and forge clean their own copy; pasted copy is checked here).', route: 'Remediation (self)' },
    { id: 'HOUSE2', fam: 'House style', sev: 'block', name: 'Meta note or placeholder left in copy', cite: 'House style: no explanatory or meta notes inside a deliverable', v: '✔', scope: 'copy', test: t => { const m = t.match(/(\[[^\]]*\]|\bTBD\b|lorem ipsum|as an ai|note to (self|editor)|placeholder|insert (here|name)|\{\w+\})/i); return m ? `"${m[0]}"` : null; }, fix: 'Remove the note or fill the placeholder.', route: 'Remediation (self)' },
  ],
  web: [
    { id: 'WEB1', sev: 'warn', name: 'Tracking pixel without a privacy notice link', cite: 'Texas Data Privacy and Security Act (Bus. & Com. Code ch. 541), notice duties; platform terms', v: '◐', test: h => /(fbevents\.js|googletagmanager|gtag\(|tiktok|clarity\.ms)/i.test(h) && !/privacy/i.test(h) ? 'pixel or tag manager present, no privacy link found' : null, fix: 'Link a privacy notice in the footer that names the data collected and how to opt out.' },
    { id: 'WEB2', sev: 'warn', name: 'Pre-checked consent box', cite: 'TCPA; Texas SB 140', v: '◐', test: h => /<input[^>]*type=["']?checkbox[^>]*checked/i.test(h) ? 'checkbox rendered checked' : null, fix: 'Leave consent unchecked and optional.' },
    { id: 'WEB3', sev: 'warn', name: 'Self-serving aggregateRating in schema', cite: 'Google structured data review snippet guidelines; FTC 16 CFR 465 if fabricated', v: '◐', test: h => /"aggregateRating"/i.test(h) ? 'aggregateRating in JSON-LD' : null, fix: 'Remove self-served ratings from LocalBusiness schema; show real reviews with a dated source instead.' },
    { id: 'WEB4', sev: 'block', name: 'No license number anywhere on the page', cite: '16 TAC §75.71(h)', v: '✔', test: h => /TAC\s?L\s?[A-Z]\s?\d{4,}/i.test(h) ? null : 'no TACLA or TACLB number in the page source', fix: 'Put the license number in the site footer so every page carries it.' },
  ],
  controls: [
    ['licVerified', 'License number verified on the TDLR search (name and number match)', ['TDLR1', 'WEB4']],
    ['finTerms', 'Financing terms, APR and approval language appear on the landing page beside the offer', ['REGZ1', 'META2']],
    ['reviewsLive', 'Review counts and ratings match the live Google profile on a stated date', ['REV1', 'SUP1']],
    ['offerTerms', 'Every offer and "free" item has its conditions on the page', ['FREE1', 'GUAR1', 'URG1']],
    ['availability', 'Stated hours and same day service are actually staffed', ['AVL1']],
    ['certs', 'Certificates on file: insurance, NATE or 608, dealer status, ENERGY STAR model numbers', ['LIC2', 'ES1', 'EFF1']],
    ['smsConsent', 'SMS consent flow reviewed: unchecked box, STOP language, chapter 302 status', ['SMS1', 'WEB2']],
  ],
};
function satchelLint(text, ctx) {
  ctx = ctx || {}; const out = [];
  SAT.rules.forEach(r => { if (ctx.web && /^(Google Ads|Meta)$/.test(r.fam)) return; if (r.scope === 'headline' && !ctx.headline) return; if (r.scope === 'meta' && ctx.platform !== 'meta') return; if (r.scope === 'page' && !ctx.page) return; if (r.scope === 'asset' && !ctx.needLic) return; if (r.scope === 'copy' && ctx.noHouse) return; try { const ev = r.test(text, ctx); if (ev) out.push({ rule: r, ev }); } catch (e) { } });
  return out;
}
