/* ==== forge_copy ==== */
"use strict";
/* ============================ Site Forge: HVAC copy library ============================ */
/* Service page copy per angle (ids match ANGLES), city, county, home and about templates, data guides and Spanish fragments.
   Placeholders are filled by FORGE.vars(); every string that reaches a page passes houseClean (no hyphens or dashes, no meta notes). */
const FCOPY = (() => {
  const STEPS = {
    repair: [
      { title: 'Book a visit', text: 'Call {phone} or use the form. Tell us what the system is doing and we give you an arrival window.' },
      { title: 'Diagnosis first', text: 'The technician tests the system, shows you what failed and gives you the price in writing before any repair starts.' },
      { title: 'The repair', text: 'Most repairs are finished on the first visit from parts on the truck. If a part has to be ordered, you get the date.' },
      { title: 'A straight answer on age', text: 'If the system is old enough that a repair is poor value, we tell you, and we price both options so you can choose.' }],
    replace: [
      { title: 'A home visit', text: 'We measure the house, look at the ducts, the attic, the electrical service and the heating side, and ask how each room feels.' },
      { title: 'Sizing by calculation', text: 'A room by room load calculation sets the size. Bigger is not better: an oversized system short cycles and leaves the house clammy.' },
      { title: 'Written options', text: 'Two or three matched systems, each priced in writing with what is included: equipment, coil, line set, pad, thermostat, permit and removal of the old system.' },
      { title: 'Installation and permit', text: 'Our own crew installs it, usually in one day, and we pull the city permit. You get the permit number and the model and serial numbers for your records.' }],
    heat: [
      { title: 'Book a visit', text: 'Call {phone} or use the form. If you smell gas or a carbon monoxide alarm sounds, leave the house and call 911 first.' },
      { title: 'Safety first', text: 'Every heating visit checks the heat exchanger, the venting and the gas pressure, and tests for carbon monoxide at the supply air.' },
      { title: 'The repair, priced first', text: 'Igniters, flame sensors, pressure switches and control boards are common repairs; you get the price before the work.' },
      { title: 'Keep or replace', text: 'On a furnace past 20 years, we tell you what we found and price the replacement next to the repair.' }],
    hail: [
      { title: 'Book an inspection', text: 'Call {phone} or use the form after the storm. Take your own dated photos of the unit from all four sides.' },
      { title: 'Measure and photograph', text: 'We measure the flattened share of each coil face, check the fan and cabinet and read the system pressures.' },
      { title: 'Written documentation', text: 'You get the photos, the measurements and a written repair or replacement quote for your records and your insurer.' },
      { title: 'Repair or replace', text: 'Once you decide, our crew does the work and pulls the city permit for any replacement.' }],
    duct: [
      { title: 'A home visit and test', text: 'We look at the attic, measure airflow room by room and test the duct system for leakage.' },
      { title: 'A plan for each room', text: 'Supply and return sized for each room, so the fix is aimed at the rooms that run hot or cold.' },
      { title: 'Written quote', text: 'Duct work alone, or a full reinstall with the equipment, coil and line set, each priced in writing.' },
      { title: 'Install and balance', text: 'New duct is sealed at every joint and the system is balanced, then airflow is measured again.' }],
    check: [
      { title: 'Book the check', text: 'Call {phone} or use the form. Have the home inspection report handy if you have one.' },
      { title: 'Ages and refrigerant', text: 'We read the data plates on the outdoor unit, the coil and the furnace for age and refrigerant.' },
      { title: 'Performance and safety', text: 'Temperature split, pressures, electrical readings, drains, and a carbon monoxide test on gas heat.' },
      { title: 'A written report', text: 'You get the ages, the condition and a realistic budget for the next few years.' }],
    maint: [
      { title: 'Join the plan', text: 'Call {phone} or use the form. We schedule the next visit for the coming season.' },
      { title: 'Spring cooling visit', text: 'Coil cleaning, electrical readings, capacitor test, refrigerant pressures and a drain flush.' },
      { title: 'Fall heating visit', text: 'Burners, igniter, flame sensor, heat exchanger, venting and a carbon monoxide test.' },
      { title: 'Records and priority', text: 'Every reading is kept, and members are scheduled first on the busiest days.' }],
    b2b: [
      { title: 'Send the property list', text: 'Addresses, tenant contacts, known system ages and your approval limit.' },
      { title: 'Tenant scheduling', text: 'We contact the tenant, confirm access and report back after every visit.' },
      { title: 'Approval above your limit', text: 'Repairs above the limit wait for your approval with photos and a written price.' },
      { title: 'Replacement planning', text: 'A list of systems likely to need replacement soon, so it can be budgeted.' }],
    fin: [
      { title: 'A home visit and quote', text: 'We size the system and price each option in writing, with the cash price shown.' },
      { title: 'Apply with the lender', text: 'A short application with a third party lender, subject to credit approval.' },
      { title: 'Read the terms', text: 'APR, length, payment and any promotional conditions are shown in writing before you sign.' },
      { title: 'Installation', text: 'Our crew installs the system and pulls the city permit.' }],
    hire: [
      { title: 'Apply', text: 'Two minutes: your name, contact details, license or registration and experience.' },
      { title: 'A phone call', text: 'We call qualified applicants within two business days.' },
      { title: 'A ride along', text: 'Meet the team and see the work before you decide.' },
      { title: 'Start', text: 'Truck, tools and training for the role, with the pay range posted up front.' }],
  };

  const AC = {
    repair: { slug: 'ac-repair', h1n: 'AC Repair Across Dallas Fort Worth', h1: 'AC Repair in {city}, TX', eyebrow: 'Air conditioning repair',
      lede: 'Warm air, no air, water on the floor or a unit that will not start. A TDLR licensed technician finds the cause, prices the fix in writing and aims to finish it on the first visit.',
      answer: 'Most AC failures in North Texas come from a short list: a failed capacitor or contactor at the outdoor unit, a refrigerant leak, a frozen coil from a clogged filter or weak airflow, a blocked condensate drain that trips the safety switch, or a tripped breaker. A technician tests each one, shows you what failed and gives you the price before any work starts. When a system is old enough that a repair is poor value, we say so and price the replacement next to it.',
      facts: ['c_ge15', 'ac_life', 'd100', 'c_medyr'],
      what: '<p>What a repair visit covers:</p><ul><li><strong>Electrical parts:</strong> capacitors, contactors, fan motors and wiring at the outdoor unit, the parts that fail most in a hot summer.</li><li><strong>Refrigerant problems:</strong> leak search, repair and recharge, with the refrigerant on the data plate checked first. R22 systems are handled differently because R22 is no longer produced.</li><li><strong>Airflow:</strong> filters, blower motors, frozen coils and crushed or disconnected ducts.</li><li><strong>Drains and safety switches:</strong> cleared lines, float switches and pans, the usual cause of water in the attic or closet.</li><li><strong>Thermostats and controls:</strong> wiring, settings and replacement.</li></ul>',
      who: '<p>Before the visit, check the breaker and the thermostat setting, and replace the filter if it is dirty. If the outdoor unit hums but the fan does not spin, turn the system off at the thermostat to protect the compressor. If you see ice on the refrigerant lines, switch the system to fan only until the technician arrives. The data plate on the outdoor unit shows the model and serial number, which tell us the age.</p>',
      steps: 'repair',
      faq: [
        { q: 'How much does AC repair cost?', a: 'It depends on the part and the time. Common repairs such as a capacitor or contactor cost far less than a compressor or a coil. The technician gives you the price in writing after the diagnosis and before the repair.' },
        { q: 'Why is my AC blowing warm air?', a: 'The usual causes are a failed capacitor or fan motor outside, low refrigerant from a leak, a frozen coil or a tripped safety switch. Turn the system off if the outdoor fan is not spinning and call for a diagnosis.' },
        { q: 'Should I repair or replace my AC?', a: 'Age and the size of the repair decide it. A Texas air conditioner at 12 years has about {mrl12} years of life left on average, and one at 15 about {mrl15}. A small repair is almost always worth it; a compressor or coil on a system past 12 often is not. We price both options so you can compare.' },
        { q: 'Do you repair all brands?', a: 'Yes. We repair every major brand of central air conditioner, heat pump and furnace.' },
        { q: 'Is it safe to keep running an AC that is icing up?', a: 'No. Switch it to fan only so the ice melts, replace the filter and call for service. Running a frozen system can damage the compressor.' }],
      related: ['replace', 'maint', 'heatpump'] },

    replace: { slug: 'ac-replacement', h1n: 'AC and Heating System Replacement', h1: 'AC Replacement in {city}, TX', eyebrow: 'System replacement · cooling and heating',
      lede: 'A new system sized to your house by calculation, quoted in writing with everything included, and installed by our own crew with the city permit pulled.',
      answer: 'Replacing a central system means a new outdoor unit and a matched indoor coil or air handler, usually with the furnace or heat pump that shares the same ducts, sized by a room by room load calculation. Half of Texas central air conditioners are replaced by about {ac_med} years, and in {city} an estimated {c_ge15_sh} of systems are already 15 or older. We give you two or three written options that list the equipment, coil, line set, pad, thermostat, permit and removal of the old system, so quotes can be compared line by line.',
      facts: ['c_ge15', 'ac_life', 'ticket', 'a2l'],
      what: '<p>The options a replacement quote compares:</p><ul><li><strong>Matched split system:</strong> a new condenser with a matched coil and your existing furnace, or a new furnace too. Since January 2025, new condensers use A2L refrigerants, so the coil has to match.</li><li><strong>Heat pump system:</strong> one outdoor unit that cools in summer and heats in winter, with electric strip heat as backup.</li><li><strong>Single stage, two stage or variable speed:</strong> each step up runs longer at lower output, holds humidity better and costs more.</li><li><strong>Full reinstall:</strong> new equipment plus a new line set and, where the attic ducts are failing, new ductwork sealed and balanced to the new system.</li></ul><p>Every option comes with its price, what is included and the warranty terms in writing.</p>',
      who: '<p>Bring a few recent summer electric bills if you have them, and a list of rooms that run hot or cold. Ask every contractor the same questions: what size, by what calculation, which coil, whether the line set and pad are replaced, who pulls the permit, and what the labor warranty covers, for how long and on what terms. If your current system runs R22, the old refrigerant has to be recovered by a certified technician.</p>',
      steps: 'replace',
      faq: [
        { q: 'How much does a new AC system cost in Dallas Fort Worth?', a: 'Declared values on {t_n} full system replacement permits in Irving from 2022 to 2025 had a median of {t_med}, and half fell between {t_p25} and {t_p75}. Your price depends on the size, the efficiency, whether the furnace or air handler is replaced, and the ducts. We quote it in writing after a home visit.' },
        { q: 'How long does an AC last in Texas?', a: 'Half of Texas central air conditioners are replaced by about {ac_med} years, and about seven in ten by 20 years, based on the U.S. Energy Information Administration survey of Texas homes. Long run hours, hot attics and dust shorten the life of the outdoor unit.' },
        { q: 'Can I replace only the outdoor unit?', a: 'Rarely, now. New condensers made since January 2025 use A2L refrigerants and need a matched indoor coil. Older R410A stock can still be installed while it lasts, but a mismatched coil costs efficiency and can conflict with the manufacturer\'s warranty terms.' },
        { q: 'Do I need a permit to replace my AC?', a: 'Yes, in most cities in Dallas Fort Worth. A mechanical permit is required for an AC, furnace or heat pump changeout, and the licensed contractor pulls it. Ask for the permit number; the city inspection is an independent second check on the installation.' },
        { q: 'How long does installation take?', a: 'Most straightforward replacements are finished in one day. A full reinstall with new ductwork, or a change from gas heat to a heat pump, can take two.' }],
      related: ['firstwave', 'r22', 'duct', 'financing'] },

    firstwave: { slug: 'builder-ac-replacement', h1n: 'Replacing the Builder Original AC', h1: 'Builder Original AC Replacement in {city}', eyebrow: 'First replacement · homes built 2000 to 2016',
      lede: 'If your home still has the system the builder installed, it is reaching the age when most Texas systems are replaced. This time, size it to the house and fix the rooms that never cooled.',
      answer: 'Homes built from about 2000 to 2016 are reaching their first system replacement now. In {city}, an estimated {c_origwin_sh} of central systems are still the builder original and between 10 and 25 years old. Builder systems were often sized by rule of thumb and installed with long duct runs to upstairs rooms, which is why second floors run hot. A replacement is the moment to measure the house, correct the size and rebalance the ducts.',
      facts: ['c_origwin', 'c_medyr', 'ac_life', 'c_ge15'],
      what: '<p>What changes when the builder system is replaced:</p><ul><li><strong>Sizing:</strong> a room by room load calculation instead of a rule of thumb. Oversizing is common in builder installs, and an oversized system short cycles.</li><li><strong>Two story homes:</strong> zoning, a second system for the upstairs, or duct changes so the upstairs gets its share of air.</li><li><strong>Refrigerant:</strong> most systems from this era run R410A; the new system uses an A2L refrigerant with a matched coil.</li><li><strong>Drains and platforms:</strong> the attic drain pan, float switch and platform are replaced with the equipment.</li></ul>',
      who: '<p>Find the install date: the serial number on the outdoor unit usually encodes the manufacture year, and many homes still have the builder paperwork. Note which rooms run hot, whether the upstairs lags in the afternoon, and how long the system runs on a hot day. Ask for the load calculation in writing with the quote.</p>',
      steps: 'replace',
      faq: [
        { q: 'How do I know if my AC is the original?', a: 'Compare the manufacture year on the outdoor unit\'s data plate with the year the house was built. If they are within a year, it is almost certainly the builder original.' },
        { q: 'Why is my upstairs so hot?', a: 'The attic sits right above the second floor, and builder duct layouts often send too little air upstairs. Duct changes, zoning or a separate upstairs system fix it; a bigger single system usually does not.' },
        { q: 'Should I replace my system before it fails?', a: 'Replacing on your schedule gives you time to compare written quotes instead of taking the first available install in August. On a builder original past 15 years, it is worth pricing now.' },
        { q: 'Will a new system lower my bills?', a: 'A correctly sized system with a higher efficiency rating uses less electricity for the same cooling, and sealed ducts stop paying to cool the attic. How much depends on the old system and the house; the quote shows the rating difference.' },
        { q: 'Do I need to replace the furnace too?', a: 'Not always. If the furnace is sound and its blower suits the new coil, it can stay. Many builder furnaces from this era are about the same age as the AC, so we price both ways.' }],
      related: ['replace', 'duct', 'premium', 'financing'] },

    r22: { slug: 'r22-ac-replacement', h1n: 'R22 AC Replacement', h1: 'R22 System Replacement in {city}', eyebrow: 'R22 systems · installed before 2010',
      lede: 'R22 has not been produced or imported in the United States since 2020. If your system uses it, every leak costs more to fix. We check the data plate, tell you what you have and price the options in writing.',
      answer: 'Systems installed before about 2010 usually run on R22. Running one is legal, but R22 production and import ended on January 1, 2020, so service depends on recovered and reclaimed refrigerant and a recharge costs far more than it used to. In {city}, an estimated {c_r22} systems are old enough to be R22 era. If yours is leaking, a replacement quote next to the repair quote shows whether another recharge is worth it.',
      facts: ['c_r22', 'r22stop', 'a2l', 'ac_life'],
      what: '<p>The options for an R22 system:</p><ul><li><strong>Repair and recharge:</strong> fix the leak and recharge with R22, sensible for a small, found leak on a system you plan to keep a short time.</li><li><strong>Full system replacement:</strong> a new matched system on an A2L refrigerant, the usual answer for a system this age.</li><li><strong>Replacement with duct work:</strong> systems this old often sit on original ducts that are due as well.</li></ul><p>The old refrigerant is recovered by a technician certified under EPA Section 608; it is never vented.</p>',
      who: '<p>Look at the data plate on the outdoor unit: it lists the refrigerant, often as R22 or HCFC22. If the system needs refrigerant every summer, it has a leak. Ask how many pounds a recharge would take and what that costs, then compare it with the replacement quote.</p>',
      steps: 'replace',
      faq: [
        { q: 'Is it illegal to use an R22 air conditioner?', a: 'No. You can keep running and repairing an R22 system. What ended in 2020 was the production and import of new R22, so the remaining supply is recovered and reclaimed refrigerant.' },
        { q: 'How much does R22 cost now?', a: 'More every year, because the supply only shrinks. We quote the refrigerant by the pound before any recharge, so you can weigh it against a new system.' },
        { q: 'Can I put a different refrigerant in my R22 system?', a: 'Some replacement refrigerants are sold for R22 systems, but they change how the system performs and do not fix a leak. For most systems this age, a matched new system is the better use of the money.' },
        { q: 'How old is an R22 system?', a: 'New R22 equipment stopped being manufactured in 2010, so an R22 system in 2026 is typically 16 years old or more.' },
        { q: 'What refrigerant will my new system use?', a: 'New split systems made since January 1, 2025 use A2L refrigerants such as R454B or R32. Some R410A equipment made before 2025 may still be installed while stock lasts.' }],
      related: ['replace', 'repair', 'financing'] },

    furnace: { slug: 'furnace-repair-replacement', h1n: 'Furnace Repair and Replacement', h1: 'Furnace Repair and Replacement in {city}', eyebrow: 'Gas heat · repair, safety checks and replacement',
      lede: 'No heat, a burner that will not light or a furnace past 20 years. A licensed technician checks the burners, flame sensor, venting and heat exchanger and tells you plainly what it needs.',
      answer: 'Gas furnaces in North Texas run fewer hours than air conditioners and last longer: in Texas survey data, half are replaced by about {furn_med} years. In {city}, {c_gas} of homes heat with gas and an estimated {c_furn20} furnaces are 20 years or older. The common winter calls are a dirty flame sensor, a failed igniter, a pressure switch or a clogged filter. On an older furnace, the heat exchanger and venting are checked on every visit.',
      facts: ['c_gas', 'c_furn20', 'furn_life', 'uri'],
      what: '<p>What a heating visit covers:</p><ul><li><strong>No heat:</strong> igniter, flame sensor, gas valve, pressure switch, limit switch and control board.</li><li><strong>Safety:</strong> heat exchanger inspection, venting and draft, gas pressure and a carbon monoxide test at the supply air.</li><li><strong>Replacement:</strong> an 80 percent furnace in the attic or closet, or a 95 percent condensing furnace where the venting and drain allow it. The federal rule that would require condensing furnaces is back before the courts, so both are still sold.</li><li><strong>Heat pump conversion:</strong> where the AC is due too, a heat pump can take over most of the heating.</li></ul>',
      who: '<p>If a carbon monoxide alarm sounds or you smell gas, leave the house and call 911 or your gas utility from outside before you call us. For no heat, check the thermostat mode and batteries, the switch beside the furnace and the filter. Note any code flashing on the furnace control board; the technician will ask.</p>',
      steps: 'heat',
      faq: [
        { q: 'How long does a furnace last in Texas?', a: 'Half of Texas gas furnaces are replaced by about {furn_med} years. Mild winters mean fewer run hours, so many last longer, but a furnace past 20 should have its heat exchanger and venting checked every year.' },
        { q: 'Why does my furnace turn on and then shut off?', a: 'Short cycling is often a dirty flame sensor, a clogged filter or an overheating limit switch. It is a quick diagnosis and usually a small repair.' },
        { q: 'Is my old furnace safe?', a: 'Age alone does not make it unsafe. Cracks in the heat exchanger, poor venting and incomplete combustion do. A safety check looks for each one and measures carbon monoxide.' },
        { q: 'Should I replace my furnace and AC together?', a: 'If both are near the same age, replacing them together saves labor and gets a matched blower and coil. If the furnace is young and sound, it can stay.' },
        { q: 'Do you install 95 percent furnaces?', a: 'Yes, where the home can vent and drain one. In many North Texas attic installs an 80 percent furnace is the practical choice; the quote shows both where both fit.' }],
      related: ['heatpump', 'maint', 'replace'] },

    heatpump: { slug: 'heat-pump', h1n: 'Heat Pump Repair and Replacement', h1: 'Heat Pump Service in {city}', eyebrow: 'Heat pumps · cooling and heating in one system',
      lede: 'A heat pump cools all summer and heats all winter, so it works more hours than a plain AC. We repair every brand and quote replacements in writing.',
      answer: 'A heat pump moves heat out of the house in summer and into it in winter, with electric strip heat as backup on the coldest nights. Because it runs in both seasons, it wears faster than an air conditioner: in Texas survey data, half are replaced by about {hp_med} years. In {city}, about {c_hp} of homes rely on a heat pump. Common calls are cold air in heat mode, an outdoor unit iced over, a reversing valve that sticks and high winter bills from strip heat doing the work.',
      facts: ['c_hp', 'hp_life', 'c_ge15', 'uri'],
      what: '<p>Heat pump work we do:</p><ul><li><strong>Defrost and icing:</strong> sensors, defrost boards and airflow problems that leave the outdoor coil encased in ice.</li><li><strong>Reversing valves and controls:</strong> the parts that switch the system between heating and cooling.</li><li><strong>Strip heat:</strong> elements and sequencers, and thermostat settings that call for strip heat too often.</li><li><strong>Replacement:</strong> a matched heat pump system, or a dual fuel setup that pairs a heat pump with a gas furnace for the coldest days.</li></ul>',
      who: '<p>Steam rising from the outdoor unit on a cold, damp morning is the defrost cycle and is normal. A unit covered in solid ice for hours is not. If your winter bill jumped, check whether the thermostat shows auxiliary or emergency heat running.</p>',
      steps: 'repair',
      faq: [
        { q: 'Why is my heat pump blowing cold air?', a: 'During defrost it briefly blows cooler air, which is normal. If it blows cold air for long stretches, the cause may be low refrigerant, a stuck reversing valve or a failed defrost control.' },
        { q: 'Is a heat pump a good choice in North Texas?', a: 'For most homes, yes. Winters are mild enough that a heat pump handles most heating hours, with strip heat or a gas furnace for the few very cold nights.' },
        { q: 'How long do heat pumps last?', a: 'Half of Texas heat pumps are replaced by about {hp_med} years, earlier than air conditioners, because they run in both seasons.' },
        { q: 'What is dual fuel?', a: 'A heat pump paired with a gas furnace. The heat pump heats on mild days and the furnace takes over when it gets very cold.' },
        { q: 'Why is my electric bill so high in winter?', a: 'Often strip heat is running more than it should, because of a thermostat setting, a low refrigerant charge or a defrost problem. A service visit finds which.' }],
      related: ['furnace', 'replace', 'premium'] },

    hail: { slug: 'hail-damaged-ac', h1n: 'Hail Damaged AC Inspection and Replacement', h1: 'Hail Damaged AC in {city}', eyebrow: 'After the storm · condenser inspection',
      lede: 'Hail flattens the fins on your outdoor unit and can dent the coil beneath them. After a storm we inspect, photograph and document the damage, and quote the repair or replacement in writing.',
      answer: 'Large hail can bend or flatten the aluminum fins that wrap the outdoor coil. Flattened fins restrict airflow, which raises pressures and running costs, and a hard strike can damage the coil itself. {county} County has had {k_hail} hail reports of one inch or larger since 2016. After a storm we inspect the unit, photograph the damage with measurements and give you a written repair or replacement quote. Your insurer decides coverage; we provide the documentation for your claim.',
      facts: ['k_hail', 'k_hail175', 'k_big', 'c_ge15'],
      what: '<p>What a hail inspection covers:</p><ul><li><strong>Coil and fins:</strong> the share of each coil face flattened, measured and photographed on every side.</li><li><strong>Cabinet and fan:</strong> dents, cracked fan blades and a bent fan guard.</li><li><strong>Performance:</strong> pressures and temperature split, to show whether the damage is cosmetic or is costing capacity.</li><li><strong>Options:</strong> fin combing for light damage, a coil replacement, or a new condenser with a matched coil where the old one cannot be matched.</li></ul>',
      who: '<p>Take your own photos of the unit from all four sides after the storm, with the date. Keep the old unit until the insurer has seen it or waived an inspection. Read your policy for the deductible and whether it pays replacement cost or actual cash value.</p>',
      steps: 'hail',
      faq: [
        { q: 'Does homeowners insurance cover hail damage to an AC?', a: 'Many policies cover hail damage to the outdoor unit, subject to the deductible. Your policy and your insurer decide; we provide photos, measurements and a written quote.' },
        { q: 'How can I tell if my AC has hail damage?', a: 'Look for flattened fins on the coil faces, dents in the cabinet and a cracked fan guard or blades. Damage can be hard to see on a dirty coil, which is why we photograph it close up.' },
        { q: 'Can hail damaged fins be repaired?', a: 'Light damage can be straightened with a fin comb. Heavy flattening across the coil face usually means a new coil or condenser.' },
        { q: 'Will you talk to my insurance company for me?', a: 'We give you the documentation and the quote. The claim itself is between you and your insurer.' },
        { q: 'How soon after a storm should I call?', a: 'As soon as you can. Policies set deadlines for claims, and damage is easier to tie to a dated storm while the date is recent.' }],
      related: ['replace', 'repair', 'financing'] },

    duct: { slug: 'ductwork-replacement', h1n: 'Ductwork Replacement and Full System Reinstall', h1: 'Ductwork Replacement in {city}', eyebrow: 'Ducts · testing, sealing, replacement and full reinstalls',
      lede: 'Hot rooms and high bills often start in the attic. We test the duct system, replace what has failed and balance the air so every room gets its share.',
      answer: 'Attic ducts in North Texas sit in heat well above 120 degrees for months every year, and duct installed in the 1980s and 1990s is often at the end of its life: jackets crack, insulation sags and joints pull apart, so you pay to cool the attic. In {city}, {c_duct} of homes were built between 1980 and 1999. A full reinstall replaces the equipment, line set and ductwork together, sized and balanced to the new system.',
      facts: ['c_duct', 'c_medyr', 'c_ge15', 'ac_life'],
      what: '<p>Duct work we do:</p><ul><li><strong>Testing:</strong> a duct leakage test and room by room airflow readings, so the fix is aimed at the problem.</li><li><strong>Sealing and repair:</strong> mastic on joints and boots, new connections at the plenum, replaced sections where the jacket has failed.</li><li><strong>Replacement:</strong> new insulated duct laid out and sized for the rooms it serves, with return air where rooms were starved of it.</li><li><strong>Full reinstall:</strong> equipment, coil, line set and ducts replaced together, the complete system matched and balanced.</li></ul>',
      who: '<p>Note which rooms run hot or cold, and whether any vent has weak airflow. Dust streaks around ceiling vents are a sign of leaks. If your system was replaced in the last few years and the hot rooms stayed hot, the ducts are the likely cause.</p>',
      steps: 'duct',
      faq: [
        { q: 'How long does ductwork last?', a: 'Flexible duct in a hot attic commonly lasts 15 to 25 years before the jacket and insulation break down. Metal trunk lines last longer but leak at the joints.' },
        { q: 'What are signs of leaky ducts?', a: 'Rooms that never reach the set temperature, a dusty house, high bills and a system that runs long on mild days.' },
        { q: 'Should I replace ducts with a new system?', a: 'If the ducts are original to a house built before 2000, or were never sized for the rooms, doing both at once saves labor and lets the new system reach its rating.' },
        { q: 'How long does a duct replacement take?', a: 'Most homes take one to two days, depending on attic access and the number of runs.' },
        { q: 'Will new ducts make my house quieter?', a: 'Often, yes. Correctly sized ducts and returns move the same air at lower speed, which cuts the rush of air at the vents.' }],
      related: ['replace', 'firstwave', 'premium'] },

    landlord: { slug: 'rental-property-hvac', h1n: 'HVAC Service for Rental Homes', h1: 'Rental Property HVAC in {city}', eyebrow: 'Landlords and property managers',
      lede: 'Tenant calls answered fast, one clear invoice per property and a straight recommendation when a system should be replaced rather than repaired again.',
      answer: '{brand} services heating and cooling in rental homes across {county} County for owners and property managers. In {city}, {c_rent} of single family homes are rented. We schedule directly with tenants, send photos and a written price before any repair above the approval limit you set, and keep a record of every system so replacements can be planned instead of forced in July.',
      facts: ['c_rent', 'c_ge15', 'ac_life', 'ticket'],
      what: '<p>How we work with rental portfolios:</p><ul><li><strong>Tenant scheduling:</strong> we contact the tenant, confirm access and report back.</li><li><strong>Approval limits:</strong> repairs under your limit proceed; anything above waits for your approval with photos and a price.</li><li><strong>System records:</strong> age, model, refrigerant and service history for each property.</li><li><strong>Replacement planning:</strong> a list of systems likely to need replacement in the next year or two, so it can be budgeted.</li></ul>',
      who: '<p>Send a property list with addresses, tenant contacts and any known system ages. Tell us your approval limit and how you want invoices grouped.</p>',
      steps: 'b2b',
      faq: [
        { q: 'Do you work directly with tenants?', a: 'Yes. We schedule with the tenant and report to you after every visit.' },
        { q: 'Can you invoice by property?', a: 'Yes. Each property gets its own invoice, with photos and the work described.' },
        { q: 'Do you service vacant homes between tenants?', a: 'Yes. A turnover check before a new tenant moves in avoids a breakdown call in the first week.' },
        { q: 'How do you decide repair or replace on a rental?', a: 'We give you the age, the repair price and the replacement price side by side. The decision is yours.' }],
      related: ['maint', 'repair', 'replace'] },

    newowner: { slug: 'new-homeowner-hvac-check', h1n: 'HVAC Check for New Homeowners', h1: 'New Homeowner HVAC Check in {city}', eyebrow: 'Just moved in · know your system',
      lede: 'Find out how old your AC and furnace are, what shape they are in and what to budget for, before the first hot week.',
      answer: 'A home inspection gives the system a quick look; it does not tell you how many years it has left. Our check reads the data plates for age and refrigerant, measures how the system is performing and inspects the heating side for safety. In {city}, an estimated {c_ge15_sh} of central systems are 15 or older, so many buyers inherit a system near the end of its life. You leave with the ages, the condition and a realistic budget.',
      facts: ['c_ge15', 'c_r22', 'ac_life', 'furn_life'],
      what: '<ul><li><strong>Age and refrigerant:</strong> read from the outdoor unit, the coil and the furnace.</li><li><strong>Performance:</strong> temperature split, refrigerant pressures, airflow and electrical readings.</li><li><strong>Heating safety:</strong> burners, venting and a carbon monoxide test on gas systems.</li><li><strong>Drains and attic:</strong> the drain pan, float switch and platform, where water damage starts.</li></ul>',
      who: '<p>Have the home inspection report and any seller paperwork on hand. If the sale came with a home warranty, bring its terms; some cover repairs but limit replacements.</p>',
      steps: 'check',
      faq: [
        { q: 'How do I tell how old my AC is?', a: 'The serial number on the outdoor unit\'s data plate usually encodes the year of manufacture. We read it for you during the check.' },
        { q: 'What should I budget for?', a: 'It depends on age. A system under 10 years usually needs maintenance and the occasional repair. One past 15 should have a replacement in the budget.' },
        { q: 'Do you check the furnace too?', a: 'Yes. Gas furnaces get a safety inspection that includes a carbon monoxide test.' },
        { q: 'Should I join a maintenance plan?', a: 'If you want spring and fall visits and priority scheduling, yes. It also keeps a service record that helps when you sell.' }],
      related: ['maint', 'repair', 'replace'] },

    premium: { slug: 'variable-speed-ac', h1n: 'Variable Speed and High Efficiency Systems', h1: 'High Efficiency AC in {city}', eyebrow: 'Variable speed · quieter, steadier comfort',
      lede: 'A variable speed system runs longer at low speed. It is quieter, pulls more humidity out of the air and keeps upstairs and downstairs closer together.',
      answer: 'Single stage systems run at full output or not at all. Two stage and variable speed systems adjust, running long, quiet cycles at part load most of the day. In a Texas summer that means steadier temperatures, better humidity control and lower bills for the same comfort. They cost more to buy, so the quote shows the certified efficiency rating of each matched system and the price difference, and you decide whether it pays for your house.',
      facts: ['c_ge15', 'ac_life', 'd100', 'cdd'],
      what: '<ul><li><strong>Two stage:</strong> a low setting for most days and full output for the hottest afternoons.</li><li><strong>Variable speed:</strong> the compressor and blower adjust in small steps to match the load.</li><li><strong>Communicating controls:</strong> the thermostat, indoor unit and outdoor unit share data for diagnostics and tuning.</li><li><strong>Zoning:</strong> dampers and thermostats for separate floors or wings.</li></ul>',
      who: '<p>Ask for the AHRI certified rating of the complete matched system, not the outdoor unit alone. Ask how the system handles humidity at low speed, and what the controls need to work as designed.</p>',
      steps: 'replace',
      faq: [
        { q: 'Is a variable speed AC worth it?', a: 'In homes with long cooling seasons, comfort complaints or high humidity, often yes. We show the rating difference and the price difference so you can judge.' },
        { q: 'What efficiency rating should I look for?', a: 'Ratings are now stated as SEER2. Compare the certified rating of the matched system, and weigh the price difference against how many hours a year it will run.' },
        { q: 'Are variable speed systems harder to repair?', a: 'They have more electronics, so diagnosis needs the manufacturer\'s tools and training. We service the brands we install.' },
        { q: 'Will it fix my hot upstairs?', a: 'Longer, slower cycles help, but a hot upstairs is often a duct problem. We check both.' }],
      related: ['replace', 'duct', 'financing'] },

    financing: { slug: 'hvac-financing', h1n: 'Financing for a New AC or Furnace', h1: 'HVAC Financing in {city}', eyebrow: 'Replacement with financing options',
      lede: 'A failed system cannot wait for savings to catch up. Financing options are available on new systems, subject to credit approval, with the APR and terms shown before you sign.',
      answer: 'Financing lets you replace a failed or failing system now and pay over time. Options are available through third party lenders, subject to credit approval. The APR, the terms of repayment and any promotional conditions are shown in writing before you sign, next to the cash price of the same system.',
      facts: ['ticket', 'c_ge15', 'ac_life', 'a2l'],
      what: '<ul><li><strong>Apply at the quote:</strong> a short application with the lender, often decided during the visit.</li><li><strong>Compare with cash:</strong> the same system priced both ways.</li><li><strong>Read the terms:</strong> APR, length, payment and any promotional period, and what happens when it ends.</li></ul>',
      who: '<p>Know the monthly amount that fits your budget, and ask for the cash price too. Read the promotional terms: some plans charge deferred interest if the balance is not paid by the end of the promotion.</p>',
      steps: 'fin',
      faq: [
        { q: 'Can I finance a new AC?', a: 'Yes. Financing options are available on new systems, subject to credit approval. We show the APR and terms in writing before you sign.' },
        { q: 'Does applying affect my credit?', a: 'The lender explains how the application is checked before you apply. Ask whether it starts with a soft inquiry.' },
        { q: 'Is there a different price for paying cash?', a: 'Ask at the quote. We show the cash price and the financed price for the same system.' },
        { q: 'Can I finance a repair?', a: 'Financing is usually offered on system replacements. Ask the technician about options for larger repairs.' }],
      related: ['replace', 'r22', 'hail'] },

    maint: { slug: 'maintenance-plan', h1n: 'AC and Furnace Maintenance Plan', h1: 'HVAC Maintenance Plan in {city}', eyebrow: '{plan} · spring and fall visits',
      lede: 'Two visits a year, priority scheduling when the first heat wave hits and a written record of your system.',
      answer: '{plan} members get a cooling visit in spring and a heating visit in fall. Each visit cleans and checks the parts that fail most in North Texas: capacitors, contactors, drains, coils, burners and flame sensors. Members get priority scheduling on busy days and a record of every reading, which shows how the system is aging and when to plan a replacement.',
      facts: ['c_ge15', 'd100', 'ac_life', 'furn_life'],
      what: '<ul><li><strong>Spring cooling visit:</strong> coil cleaning, electrical readings, capacitor test, refrigerant pressures, drain line flush and float switch check.</li><li><strong>Fall heating visit:</strong> burners, igniter and flame sensor, heat exchanger inspection, venting and a carbon monoxide test.</li><li><strong>Priority:</strong> members are scheduled first on the busiest days.</li><li><strong>Records:</strong> every reading kept, so changes over the years are visible.</li></ul>',
      who: '<p>Ask what the plan costs, what each visit includes and what member pricing applies to repairs. The terms are in the plan agreement.</p>',
      steps: 'maint',
      faq: [
        { q: 'How often should an AC be serviced in Texas?', a: 'Once a year before summer for cooling, and once before winter for gas heat. Long cooling seasons and dust make the spring visit the one that matters most.' },
        { q: 'Is a maintenance plan worth it?', a: 'If you would book the visits anyway, a plan bundles them with priority scheduling. The biggest value is catching a weak capacitor or a clogged drain before it fails in July.' },
        { q: 'What does a tune up include?', a: 'Cleaning, electrical and refrigerant checks, drain service and a written report of the readings.' },
        { q: 'Can the plan move with me if I sell my home?', a: 'Transfer terms are set out in the plan agreement; ask when you join.' }],
      related: ['repair', 'newowner', 'furnace'] },

    iaq: { slug: 'indoor-air-quality', h1n: 'Indoor Air Quality Across Dallas Fort Worth', h1: 'Indoor Air Quality in {city}, TX', eyebrow: 'Filtration, purification and humidity',
      lede: 'Cedar in winter, oak in spring, ragweed in fall and ozone all summer. The air inside a {city} home is filtered by the system it already has, and that system can do more.',
      answer: 'Indoor air quality work happens inside the heating and cooling system. A media air cleaner replaces the one inch filter with a deep pleated cartridge that catches far more without choking airflow. A UV light at the coil keeps the wet surfaces clean. A whole home dehumidifier holds the house at a humidity the air conditioner alone cannot reach on a muggy day, which is why the air feels cooler at the same temperature. We size each device to the system and tell you what it will and will not do; no device cures an allergy, and we do not say it does.',
      facts: ['cdd', 'd100', 'c_ge15', 'ac_life'],
      what: '<p>What we install and service:</p><ul><li><strong>Media air cleaners:</strong> four to five inch cartridges rated MERV 11 to 16, changed once or twice a year.</li><li><strong>UV coil lights:</strong> mounted at the indoor coil to keep the wet surfaces free of growth.</li><li><strong>Whole home dehumidifiers:</strong> ducted units that hold humidity steady when the air conditioner cycles off.</li><li><strong>Ventilation and fresh air:</strong> controlled outdoor air for tight newer homes.</li><li><strong>Duct sealing:</strong> the dust in the house usually enters through leaks in the attic ducts.</li></ul>',
      who: '<p>Tell us what you notice: dust that returns a day after cleaning, a musty smell when the system starts, sneezing that follows the pollen calendar, or a house that feels clammy at 74 degrees. Each points to a different fix, and the first step is a look at the filter slot, the coil and the ducts.</p>',
      steps: 'maint',
      faq: [
        { q: 'Will an air cleaner help with cedar fever?', a: 'A media air cleaner captures most of the pollen that reaches the return, and a tighter house with sealed ducts lets less in. It reduces what you breathe indoors; it does not treat the allergy itself.' },
        { q: 'What MERV rating should I use?', a: 'A one inch filter above MERV 8 usually restricts airflow. A four or five inch media cabinet lets the system run MERV 11 to 16 without the penalty. We check the static pressure before we recommend one.' },
        { q: 'Is a UV light worth it?', a: 'It keeps the indoor coil and drain pan clean, which helps airflow and odor. It does not filter dust or pollen; that is the media cleaner\'s job.' },
        { q: 'Why does my house feel clammy?', a: 'An oversized or single stage air conditioner cools the air before it removes enough moisture. A whole home dehumidifier, or a variable speed system at replacement, fixes it.' }],
      related: ['maint', 'replace', 'duct'] },
    ductless: { slug: 'ductless-mini-split', h1n: 'Ductless Mini Split Systems Across Dallas Fort Worth', h1: 'Ductless Mini Splits in {city}, TX', eyebrow: 'Rooms the ducts never reached',
      lede: 'The garage gym, the sunroom, the addition over the garage, the {city} house built before ducts were standard. A ductless mini split cools and heats the room the system never reached.',
      answer: 'A ductless mini split pairs a small outdoor unit with one or more indoor heads mounted on the wall or ceiling, connected by a refrigerant line through a three inch hole. Each head has its own remote and its own temperature, and most models are heat pumps, so they heat in January as well as they cool in August. In North Texas they solve three problems: a room the central system cannot keep up with, a space that was never ducted, and an older home where adding ducts means opening walls. Installed and permitted by a licensed crew, with the line set, the pad and the electrical circuit included in the written price.',
      facts: ['c_medyr', 'd100', 'cdd', 'hp_life'],
      what: '<p>Where ductless systems earn their keep:</p><ul><li><strong>Garages and workshops:</strong> a single zone unit sized for the heat load of an uninsulated space.</li><li><strong>Additions and sunrooms:</strong> added rooms that the original ducts were never sized for.</li><li><strong>Older homes without ducts:</strong> multi zone systems serving three to five rooms from one outdoor unit.</li><li><strong>Upstairs hot rooms:</strong> a dedicated head instead of an undersized duct run.</li><li><strong>Guest suites and rentals:</strong> independent control and independent bills.</li></ul>',
      who: '<p>Bring the room\'s dimensions, what it is used for and how it is insulated. A garage gym and a nursery of the same size need very different equipment. We measure, check the electrical panel for a spare circuit and quote the installed system in writing.</p>',
      steps: 'replace',
      faq: [
        { q: 'How much does a mini split cost installed?', a: 'A single zone system for one room costs a fraction of a central replacement; multi zone systems scale with the number of heads. Every quote is in writing with equipment, line set, pad, circuit and permit listed.' },
        { q: 'Can a mini split heat as well as cool?', a: 'Most are heat pumps and heat well in a Texas winter, including the cold snaps. Some models keep full heating output well below freezing.' },
        { q: 'Do mini splits work in a garage?', a: 'Yes, when the unit is sized for an uninsulated space and the garage door seals reasonably well. Insulating the door pays for itself.' },
        { q: 'Do I need a permit?', a: 'Yes. Ductless installations are mechanical and electrical work, and we pull the permit for you.' }],
      related: ['replace', 'premium', 'repair'] },
    commercial: { slug: 'commercial-hvac', h1n: 'Light Commercial HVAC Across Dallas Fort Worth', h1: 'Commercial HVAC in {city}, TX', eyebrow: 'Rooftop units, small buildings, maintenance contracts',
      lede: 'Offices, retail, restaurants, churches and small warehouses in {city}: rooftop units repaired and replaced, and maintenance contracts that keep tenants comfortable and the owner off the phone.',
      answer: 'Light commercial work is a different trade from residential: packaged rooftop units, split systems with long line sets, economizers, building controls and gas heat sections that serve open spaces with heavy occupancy. We service and replace units from three to twenty five tons, quote replacements by tonnage with crane and permit included, and write maintenance contracts priced per unit with a report after each visit. Response times are stated in the contract, because a restaurant with no cooling in July is not a service call, it is a closure.',
      facts: ['d100', 'cdd', 'k_tech', 'k_sys'],
      what: '<p>What the commercial team handles:</p><ul><li><strong>Rooftop unit repair:</strong> compressors, condenser fans, economizers, gas heat sections and controls.</li><li><strong>Rooftop unit replacement:</strong> like for like changeouts and curb adapters, crane and permit included.</li><li><strong>Split systems and mini splits:</strong> server rooms, offices and tenant spaces.</li><li><strong>Maintenance contracts:</strong> quarterly or semiannual visits priced per unit, filters and belts included.</li><li><strong>Tenant finish and remodels:</strong> duct changes and thermostat zoning for new layouts.</li></ul>',
      who: '<p>Have the unit count, tonnage and the building\'s hours ready, and the name of the person who approves work. For a contract, we walk the roof, photograph every unit and tag it with its model, serial and age before the price is set.</p>',
      steps: 'repair',
      faq: [
        { q: 'How long does a rooftop unit last?', a: 'Fifteen to twenty years with maintenance, less on a roof that bakes at 140 degrees every summer. Units past fifteen are quoted for replacement alongside any major repair.' },
        { q: 'What does a maintenance contract include?', a: 'Scheduled visits, filters and belts, coil cleaning, electrical and refrigerant checks and a written report per unit. Repairs are priced separately unless the contract says otherwise.' },
        { q: 'How fast can you respond?', a: 'The response time is written into the contract. Contract customers are scheduled ahead of one time calls.' },
        { q: 'Do you handle permits and cranes?', a: 'Yes. Replacement quotes include the crane, the permit and the curb adapter when one is needed.' }],
      related: ['repair', 'maint', 'landlord'] },
    recruit: { slug: 'careers', h1n: 'HVAC Technician and Installer Jobs', h1: 'HVAC Jobs in {city}', eyebrow: 'Careers · service technicians and installers', recruit: true,
      lede: 'We are hiring HVAC technicians and installers. Pay range {pay}, a company truck, tools and training.',
      answer: '{brand} is hiring service technicians and installers in {county} County. The posted pay range is {pay}, depending on license, experience and role. Service technicians need a TDLR technician registration or certification and EPA Section 608 certification; installers can start as registered technicians and train up.',
      facts: ['k_tech', 'm_rep', 'm_ge15', 'd100'],
      what: '<ul><li><strong>Service technician:</strong> diagnosis and repair on cooling and heating systems.</li><li><strong>Installer:</strong> replacements and full reinstalls with our own crews.</li><li><strong>Maintenance technician:</strong> spring and fall plan visits, a good start for newer technicians.</li></ul>',
      who: '<p>Requirements: a valid driver license, a TDLR technician registration or certification, EPA Section 608 certification for refrigerant work or the willingness to get it, and care for customers and their homes.</p>',
      steps: 'hire',
      faq: [
        { q: 'What does the job pay?', a: 'The posted range is {pay}, depending on license, experience and role.' },
        { q: 'Do I need a license?', a: 'Technicians in Texas must hold a TDLR registration or certification. We help registered technicians progress to certified.' },
        { q: 'Is there a company truck?', a: 'Yes, for service technicians and installers, along with tools.' },
        { q: 'How fast do you hire?', a: 'We call qualified applicants within two business days.' }],
      related: [] },
  };

  const HOME_FAQ = [
    { q: 'What areas do you serve?', a: 'Homes across Dallas Fort Worth from our base in {officeCity}, including {areaList}.' },
    { q: 'Are you licensed?', a: 'Yes. {brand} holds TDLR Air Conditioning and Refrigeration Contractor License {lic}. You can check any contractor on the TDLR license search.' },
    { q: 'Do you give written quotes?', a: 'Yes. Every repair is priced before work starts, and every replacement is quoted in writing with what is included.' },
    { q: 'What brands do you work on?', a: 'We repair all major brands of air conditioners, heat pumps and furnaces, and install {brands}.' },
    { q: 'When are you open?', a: '{hours}.' },
    { q: 'Do you offer financing?', a: 'Financing options are available on new systems, subject to credit approval, with the APR and terms shown before you sign.' }];

  const CITY_FAQ = [
    { q: 'How old is the average AC in {city}?', a: 'An estimated {c_ge15_sh} of central systems in {city} homes are 15 years or older, based on Census housing data and Texas equipment age survey data. Half of Texas systems are replaced by about {ac_med} years.' },
    { q: 'Is my {city} home\'s AC on R22?', a: 'If it was installed before 2010, probably. The data plate on the outdoor unit lists the refrigerant. About {c_r22} systems in {city} are old enough to be R22 era.' },
    { q: 'Do I need a permit to replace my AC in {city}?', a: 'In most Dallas Fort Worth cities, yes: a mechanical permit is required for an AC, furnace or heat pump changeout, and the licensed contractor pulls it. We pull the permit wherever the city requires one and give you the number.' },
    { q: 'What does a new AC system cost?', a: 'Declared values on full system replacement permits in Irving from 2022 to 2025 had a median of {t_med}, with half between {t_p25} and {t_p75}. Your price depends on size, efficiency, the heating side and the ducts, and we quote it in writing.' },
    { q: 'Do you serve homes near {city}?', a: 'Yes. We also serve {nearby}.' },
    { q: 'Where are you based?', a: '{officeLine}' }];

  const COUNTY_FAQ = [
    { q: 'Which cities in {county} County do you serve?', a: 'Homes across the county, including {countyCities}.' },
    { q: 'How old are HVAC systems in {county} County?', a: 'An estimated {k_ge15_sh} of central systems in {county} County homes are 15 years or older, and about {k_r22} were installed before 2010.' },
    { q: 'Does {county} County get a lot of hail?', a: 'It has logged {k_hail} hail reports of one inch or larger since 2016 in the NOAA Storm Events database. After a storm, have the outdoor unit inspected.' },
    { q: 'How many AC contractors are licensed in {county} County?', a: 'The TDLR file lists {k_lic} active air conditioning contractor licenses with a {county} County address. Check any contractor\'s number on the TDLR license search.' }];

  /* data guides: scope metro (one page), city (per plan city) or county (per plan county where the numbers call for it) */
  const GUIDES = [
    { id: 'aclife', scope: 'metro', label: 'How long an AC lasts in Texas',
      h1: 'How Long Does an AC Last in Texas? What Dallas Fort Worth Data Shows', title: 'How Long Does an AC Last in Texas?',
      meta: 'Half of Texas central air conditioners are replaced by about {ac_med} years. What the survey data shows, why DFW summers wear systems and how to plan ahead.',
      answer: 'Half of Texas central air conditioners are replaced by about {ac_med} years, and about seven in ten by 20, based on a fit to the U.S. Energy Information Administration\'s 2020 survey of Texas homes. Across Dallas Fort Worth, an estimated {m_ge15} central systems are already 15 or older.',
      facts: ['ac_life', 'm_ge15', 'd100', 'hp_life'],
      body: ['<p>The Energy Information Administration asks households how old their central air conditioner is. Fitting a lifetime curve to the Texas answers gives a median age at replacement of about {ac_med} years. Heat pumps, which also heat, are replaced sooner, at about {hp_med} years; gas furnaces later, at about {furn_med}.</p><p>A system at 12 years has about {mrl12} years left on average; at 15, about {mrl15}. Those are averages across many homes: a well kept system in a shaded yard can run past 20, and one in a hot attic with a dirty coil can fail at 10.</p>',
        '<p>Texas air conditioners run many more hours a year than systems further north, and 2026 has had {d100} days at 100 degrees or more at DFW Airport through {through}, against about {d100n} in a normal year. Long run hours wear compressors and fan motors, attic heat stresses indoor coils and drains, and cottonwood and dust clog outdoor coils.</p>',
        '<p>Know the age of your system: the outdoor unit\'s data plate shows the model and serial number, and the serial usually encodes the year. Keep a maintenance record. Past 12 years, price a replacement before the next big repair, so the decision is made on your schedule and not in the first heat wave. Get written quotes that list the equipment, coil, line set, permit and the labor warranty terms.</p>'],
      faq: [
        { q: 'What shortens the life of an AC in Texas?', a: 'Long run hours, a hot attic, dirty coils and filters, low refrigerant from leaks and a system sized larger than the house needs.' },
        { q: 'Can an AC last 20 years?', a: 'Some do. About one in four Texas systems is still running at 20.' },
        { q: 'Is it better to replace before it fails?', a: 'Replacing on your schedule lets you compare quotes and choose the system, instead of taking the first available install during a heat wave.' },
        { q: 'How do I find my AC\'s age?', a: 'Read the serial number on the outdoor unit\'s data plate. Most brands encode the year of manufacture in it.' }] },
    { id: 'repairreplace', scope: 'metro', label: 'Repair or replace', table: 'mrl',
      h1: 'Repair or Replace Your AC? A Dallas Fort Worth Guide', title: 'Repair or Replace Your AC? A DFW Guide',
      meta: 'How to decide between repairing and replacing an air conditioner in Dallas Fort Worth: age, the life left, the size of the repair and what local permits show.',
      answer: 'Weigh the repair against the life the system has left. A Texas AC at 12 years has about {mrl12} years left on average, and at 15 about {mrl15}. A small repair on a young system is almost always worth it; a compressor or coil on a system past 12 often is not. Irving replacement permits from 2022 to 2025 had a median declared value of {t_med}.',
      facts: ['ac_life', 'mrl15', 'ticket', 'm_rep'],
      body: ['<p>The table shows how Texas air conditioners age, from a lifetime curve fitted to the Energy Information Administration survey. By 15 years, half have been replaced. The average life left falls every year, but more slowly than people expect, because the systems that survive to a given age tend to be the sturdier ones.</p>',
        '<p>One way to compare: divide the repair price by the average years left, and compare it with a new system\'s price divided by its expected life. If a repair buys each year at close to the cost of a year of a new system, replacing is the better value. Refrigerant matters too: an R22 system with a leak will need expensive refrigerant again, and a new condenser now needs a matched coil.</p>',
        '<p>Ask for both prices in writing on any large repair to a system past 10 years. Ask what failed, whether it is likely to recur and what the replacement includes. A contractor who quotes only a replacement, or only a repair, is giving you half the picture.</p>'],
      faq: [
        { q: 'Is it worth repairing a 15 year old AC?', a: 'For a small repair such as a capacitor, usually yes. For a compressor, a coil or a refrigerant leak, usually not: the average Texas system at 15 has about {mrl15} years left.' },
        { q: 'What does a new AC system cost in DFW?', a: 'Declared values on full system replacement permits in Irving from 2022 to 2025 had a median of {t_med}, with half between {t_p25} and {t_p75}.' },
        { q: 'Why did my repair quote include a replacement price?', a: 'Because the decision depends on both numbers. We show both so you can choose.' },
        { q: 'Does a new AC need a new furnace?', a: 'Not always. If the furnace is sound and its blower suits the new coil, it can stay.' }] },
    { id: 'heat', scope: 'metro', label: 'The 2026 summer and your AC',
      h1: 'The 2026 DFW Summer and Your AC: {d100} Days at 100 Degrees', title: 'The 2026 DFW Summer and Your AC',
      meta: '2026 has brought {d100} days at 100 degrees or more at DFW Airport through {through}. What a hot summer does to an AC and how to get yours through it.',
      answer: '2026 has had {d100} days at 100 degrees or more at DFW Airport through {through}, against about {d100n} in a normal year, {rank100}. Cooling demand is running {cddpct} above normal. In Fort Worth\'s permit records from 2012 to 2026, each extra 100 cooling degree days in a month came with about {fwheat} more HVAC permits.',
      facts: ['d100', 'cdd', 'fwheat', 'm_ge15'],
      body: ['<p>{d100} days at 100 degrees or hotter at DFW Airport so far in 2026 compares with about {d100n} in an average year. The record is {recd100} days, set in {recyr}. The hottest reading this year has been {tmax26} degrees.</p>',
        '<p>Heat does not break air conditioners on its own. It finds the weak part: a capacitor near the end of its life, a coil caked with dust, a system low on refrigerant. Long hot stretches mean long run times, and the calls pile up in the first heat wave and again late in summer, when worn parts finally give out.</p>',
        '<p>Change the filter monthly in peak summer. Keep the outdoor unit clear and rinse the coil gently with a hose, power off. Set the thermostat a few degrees higher when you are away rather than off. If the system runs constantly and cannot hold the setting after sunset, or ice forms on the lines, switch it off and call before the compressor is damaged.</p>'],
      faq: [
        { q: 'Why can my AC not keep up on 100 degree days?', a: 'Systems are sized for a design day, which in Dallas Fort Worth is close to 100 degrees. Above that, even a sound system can run constantly and drift a few degrees. If it cannot hold the setting after sunset, have it checked.' },
        { q: 'What temperature should I set in a heat wave?', a: 'A steady setting you can live with, raised a few degrees when you are away. Large setbacks make the system run for hours to recover.' },
        { q: 'Does a hot summer mean I need a new AC?', a: 'No. It means a weak part is more likely to fail. Maintenance catches most of them first.' },
        { q: 'Should I hose off my outdoor unit?', a: 'A gentle rinse from the inside out, with the power off, helps. Do not use a pressure washer on the fins.' }] },
    { id: 'r22guide', scope: 'metro', label: 'R22 in 2026',
      h1: 'R22 in 2026: What DFW Owners of Older AC Systems Should Know', title: 'R22 in 2026: What DFW Owners Should Know',
      meta: 'An estimated {m_r22} Dallas Fort Worth systems were installed before 2010 and likely run on R22. What the end of R22 production means for repairs and replacement.',
      answer: 'R22 production and import ended on January 1, 2020, so repairs on R22 systems depend on recovered and reclaimed refrigerant. An estimated {m_r22} systems across Dallas Fort Worth were installed before 2010, the R22 era. Running one is legal; recharging one keeps getting more expensive.',
      facts: ['m_r22', 'r22stop', 'a2l', 'ac_life'],
      body: ['<p>Systems installed before about 2010 were designed for R22. Across the 12 counties in and around Dallas Fort Worth, an estimated {m_r22} are still running, about {m_r22_sh} of all central systems. Every one of them is now 16 years old or more.</p>',
        '<p>The Clean Air Act phaseout ended R22 production and import in 2020. What remains is recovered from old systems and reclaimed, a supply that only shrinks. New systems changed twice: to R410A around 2010, and from January 1, 2025, to A2L refrigerants such as R454B and R32 for new split systems. An R22 condenser cannot simply be swapped for a new one without replacing the indoor coil and usually the line set.</p>',
        '<p>If your R22 system is sound, keep it maintained and budget for its replacement. If it leaks, get the recharge price by the pound and a replacement quote side by side. Never let anyone vent the old refrigerant; it must be recovered by a technician certified under EPA Section 608.</p>'],
      faq: [
        { q: 'How do I know if my AC uses R22?', a: 'Check the data plate on the outdoor unit. It lists the refrigerant, often as R22 or HCFC22.' },
        { q: 'Can I still buy R22?', a: 'Only recovered and reclaimed R22, charged by certified technicians. The price reflects a shrinking supply.' },
        { q: 'Do I have to replace my R22 system?', a: 'No. You can keep running and repairing it. Many owners replace it when a leak or a compressor failure makes the next repair poor value.' },
        { q: 'Will a new condenser work with my old coil?', a: 'No. New condensers need a matched indoor coil rated for their refrigerant.' }] },
    { id: 'buildyear', scope: 'city', label: 'Build year and your AC',
      h1: 'What Your {city} Home\'s Build Year Says About Its AC', title: '{city} Home Age and Your AC',
      meta: 'The median {city} home was built in {c_medyr}. What that means for the age of your AC and furnace, your refrigerant and when to plan a replacement.',
      answer: 'The median home in {city} was built in {c_medyr}. An estimated {c_ge15_sh} of the city\'s central systems are 15 or older, {c_r22_sh} date from before 2010 and likely run on R22, and {c_origwin_sh} are the builder\'s original system, now 10 to 25 years old.',
      facts: ['c_medyr', 'c_ge15', 'c_r22', 'c_origwin'],
      body: ['<p>{ybSentence}</p>',
        '<p>A home\'s build year sets the timeline for its systems. Homes built since 2016 mostly still have their first system. Homes built from 2000 to 2016 are in their first replacement wave now. Homes built before 2000 have usually replaced the original system at least once, and many still have original attic ducts. Systems installed before 2010 are likely on R22.</p>',
        '<p>Find your system\'s age on the outdoor unit\'s data plate and compare it with your home\'s build year. If the system is the original and past 12 years, plan the replacement. If the ducts are original to a house built before 2000, have them tested with the next system.</p>'],
      faq: [
        { q: 'How old is the average AC in {city}?', a: 'An estimated {c_ge15_sh} of central systems in {city} are 15 or older, based on Census housing data and Texas equipment age survey data.' },
        { q: 'Is my {city} home\'s AC on R22?', a: 'If it was installed before 2010, probably. The data plate on the outdoor unit says which refrigerant it uses.' },
        { q: 'Do newer {city} homes need replacements too?', a: 'Homes built from 2000 to 2016 are reaching their first replacement now, as builder systems pass 10 to 25 years.' },
        { q: 'When should I replace the ducts?', a: 'Test them with the next system if they are original to a home built before 2000, or if rooms never cool evenly.' }] },
    { id: 'hail', scope: 'county', label: 'Hail and your AC', need: k => (k.hail1_2016 || 0) >= 100,
      h1: 'Hail and Your AC in {county} County', title: 'Hail Damage to AC Units in {county} County',
      meta: '{county} County has had {k_hail} hail reports of one inch or larger since 2016. How hail damages outdoor AC units, what to check after a storm and how claims work.',
      answer: '{county} County has had {k_hail} hail reports of one inch or larger since 2016, {k_hail175} of them 1.75 inches or larger. Hail that size flattens the fins on outdoor AC units and can dent the coil. After a storm, photograph the unit, book an inspection and read your policy before you file.',
      facts: ['k_hail', 'k_hail175', 'k_big', 'k_sys'],
      body: ['<p>{k_hail} reports of hail one inch or larger have been logged in {county} County since 2016 in the NOAA Storm Events database, {k_hail175} of them golf ball size or larger. {k_bigSentence}</p>',
        '<p>The outdoor unit\'s coil is wrapped in thin aluminum fins. Hail flattens them, which blocks airflow across the coil, raises pressures and makes the compressor work harder. Heavy strikes can puncture tubing or crack the fan blades. Damage is easy to miss on a dusty coil, so it is best checked close up.</p>',
        '<p>After a storm, photograph the unit from all four sides with the date. Book an inspection; we measure and photograph the damage and give you a written repair or replacement quote. Your insurer decides coverage, so read your policy for the deductible and whether it pays replacement cost.</p>'],
      faq: [
        { q: 'Does insurance cover hail damage to an AC unit?', a: 'Many homeowners policies do, subject to the deductible. Your policy and your insurer decide.' },
        { q: 'Can I run my AC after hail?', a: 'Usually, if it starts and cools normally. If the fins are heavily flattened, the system works harder until it is repaired.' },
        { q: 'How long do I have to file a hail claim?', a: 'Policies set their own deadlines. Check yours and file promptly while the storm date is recent.' },
        { q: 'Can hail guards protect my AC?', a: 'Some guards reduce damage but can also restrict airflow if poorly designed. Ask before installing one.' }] },
    { id: 'furnace', scope: 'county', label: 'Furnace age and safety', need: k => (k.gas_sh || 0) >= 30 && (k.furn20 || 0) >= 1000,
      h1: 'Is Your Furnace Due? Gas Heat in {county} County', title: 'Furnace Age and Safety in {county} County',
      meta: '{k_gas} of {county} County homes heat with gas, and an estimated {k_furn20} furnaces are 20 or older. What that means for safety, repairs and replacement.',
      answer: '{k_gas} of homes in {county} County heat with natural gas, and an estimated {k_furn20} gas furnaces there are 20 years or older. Half of Texas gas furnaces are replaced by about {furn_med} years. An older furnace is not unsafe by age alone, but its heat exchanger and venting should be checked every fall.',
      facts: ['k_gas', 'k_furn20', 'furn_life', 'uri'],
      body: ['<p>North Texas winters are short, so furnaces run fewer hours and last longer than air conditioners. Even so, an estimated {k_furn20} furnaces in {county} County are 20 or older. Cold snaps still happen: during Winter Storm Uri, DFW Airport fell to 2 degrees below zero on February 16, 2021.</p>',
        '<p>What wears out is the heat exchanger, which keeps combustion gases out of the air you breathe, along with igniters, flame sensors, inducer motors and control boards. Cracks and poor venting are the safety issues; the rest are repairs.</p>',
        '<p>Have gas heat checked each fall, including a carbon monoxide test, and keep a working carbon monoxide alarm on every level of the house. If the furnace is past 20 and needs a major part, price a replacement too, and consider whether a heat pump should take over part of the heating when the AC is replaced.</p>'],
      faq: [
        { q: 'How long does a gas furnace last in Texas?', a: 'Half are replaced by about {furn_med} years. Many run longer because Texas winters are mild.' },
        { q: 'How do I know if my furnace is safe?', a: 'A safety check inspects the heat exchanger and venting and measures carbon monoxide. Keep working carbon monoxide alarms in the house.' },
        { q: 'Should I replace my furnace when I replace my AC?', a: 'If both are near the same age, doing both at once saves labor and matches the blower to the new coil.' },
        { q: 'What is a 95 percent furnace?', a: 'A condensing furnace that captures more of the heat from the gas. It needs plastic venting and a condensate drain, which not every attic installation can take.' }] },
  ];

  const ES = {
    cta: { label: 'Pida su cotización', phone_label: 'Llame al {phone}' },
    form: { button: 'Enviar solicitud', fields: [{ id: 'name', label: 'Nombre completo', type: 'text', required: true }, { id: 'phone', label: 'Teléfono', type: 'tel', required: true }, { id: 'email', label: 'Correo electrónico', type: 'email', required: true }, { id: 'message', label: 'Cuéntenos qué pasa con su sistema', type: 'textarea', required: false }],
      consent: 'Al enviar, acepta que podamos contactarle por teléfono, mensaje de texto o correo electrónico sobre su solicitud. Pueden aplicarse tarifas de mensajes y datos. El consentimiento no es una condición de compra. Responda STOP para dejar de recibir mensajes.' },
    trust: ['Licencia TDLR {lic}', 'Precio por escrito antes de empezar', '{hoursEs}'],
    facts: { ge15: 'de los sistemas en {city} tienen 15 años o más', written: 'precio y opciones antes de empezar', lic: 'licencia de contratista de aire acondicionado del estado de Texas' },
    features: [{ title: 'Precio por escrito', text: 'Cada opción con su precio antes de empezar el trabajo.' }, { title: 'Técnicos con licencia', text: 'Licencia TDLR {lic}.' }, { title: 'Nuestro propio equipo', text: 'Instalamos con nuestro propio equipo y tramitamos el permiso de la ciudad.' }],
    aq: '¿Qué pasa en la visita?',
    faq: [{ q: '¿Cuánto cuesta?', a: 'Depende del equipo y del trabajo. Le damos el precio por escrito antes de empezar.' }, { q: '¿Tienen licencia?', a: 'Sí. Licencia TDLR {lic}. Puede verificarla en la búsqueda de licencias de TDLR.' }, { q: '¿Atienden en {city}?', a: 'Sí. Atendemos {city} y el condado de {county} desde nuestra oficina en {officeCity}.' }],
    answer: { cool: 'Un técnico con licencia TDLR revisa el sistema, le explica qué falla y le da el precio por escrito antes de empezar. Si el equipo ya tiene muchos años, le damos también el precio de un sistema nuevo para que pueda comparar.', heat: 'Revisamos quemadores, sensor de llama, ventilación e intercambiador de calor, y medimos el monóxido de carbono. Le damos el precio por escrito antes de cualquier reparación y, si el equipo ya tiene más de 20 años, también el de uno nuevo.', hail: 'Inspeccionamos la unidad exterior, tomamos fotos y medidas del daño y le damos una cotización por escrito. Su aseguradora decide la cobertura; nosotros le damos la documentación.', duct: 'Probamos los ductos, medimos el aire en cada cuarto y le damos el precio por escrito para reparar o reemplazar, solo los ductos o el sistema completo.' },
    formHead: 'Pida una visita', band: { heading: '¿Necesita servicio en {city}? Llámenos hoy.', text: 'Precio por escrito antes de empezar.' },
    notice: 'Regulado por The Texas Department of Licensing and Regulation, P.O. Box 12157, Austin, Texas 78711, 1 800 803 9202, 512 463 6599.',
    breadcrumbs: 'Inicio',
  };
  const CONSENT = 'By submitting, you agree that we may contact you by phone, text or email about your request. Message and data rates may apply. Consent is not a condition of purchase. Reply STOP to opt out of texts.';
  const NOTICE = 'Regulated by The Texas Department of Licensing and Regulation, P.O. Box 12157, Austin, Texas 78711, 1 800 803 9202, 512 463 6599.';
  return { STEPS, AC, HOME_FAQ, CITY_FAQ, COUNTY_FAQ, GUIDES, ES, CONSENT, NOTICE };
})();
