/* ==== m05_paid ==== */
"use strict";
/* ============================ Module 5: Paid Acquisition ============================ */
const QN = ['Anchor', 'Whitespace', 'Niche', 'Avoid'];
const QD = ['High opportunity, high competition: expensive because valuable', 'High opportunity, competition below the 60th percentile: buy first', 'Lower opportunity, low competition: cheap, small, often profitable', 'Lower opportunity, crowded: spend elsewhere'];
const TIERS = ['A+', 'A', 'B', 'C', 'D', 'E'];
registerModule({
  key: 'paid', num: '05', title: 'Paid Acquisition', desc: 'Where an ad dollar reaches the most replacement and repair jobs, resolved to the ZIP',
  mount(root) {
    const st = { layer: 'effb', sel: null, county: '', quad: '', angle: '', cpc: 9.68, share: 15, cvr: 6.6, prep: 22, rep$: 13800, fix$: 450, srch: 200000, n: 40, sortK: 'effb' };
    const PL = { effb: { l: 'Efficiency percentile (opportunity per relative click cost)', ramp: 'ember', f: v => D(v, 0), g: 'C' }, oppb: { l: 'Opportunity percentile (job value, radius blended)', ramp: 'ember', f: v => D(v, 0), g: 'C' }, opp_usd: { l: 'Annual job value pool ($)', ramp: 'ember', f: v => MM(v), g: 'C' }, mass: { l: 'Job mass (replacement equivalents a year)', ramp: 'ember', f: v => N(v), g: 'B' }, value_idx: { l: 'Case value index (100 = metro median ticket)', ramp: 'teal', f: v => D(v, 0), g: 'C' }, comp_pct: { l: 'Competition percentile', ramp: 'blue', f: v => D(v, 0), g: 'C' }, cpc_rel: { l: 'Relative click cost (index)', ramp: 'blue', f: v => D(v, 2) + '×', g: 'D' }, quad: { l: 'Quadrant', cat: true, g: 'C' }, tier: { l: 'Tier and starting bid modifier', cat: true, g: 'C' } };
    root.innerHTML = mastHTML({ eyebrow: 'Module 05 · Paid Acquisition', title: 'Paid Acquisition', dek: 'Where a DFW contractor should buy advertising, resolved to the ZIP code: built from the replacements coming due, the repair calls an aging fleet throws off, what a job is worth in that house, and how many review-heavy competitors are already standing in the Local Pack.',
      meta: [`<b>${N(ZR.length)}</b> buyable ZIPs`, `<b>${MM(META.opp_usd)}</b> annual job value pool (modeled)`, `<b>${N(sum(ZR.map(z => z.repairs)))}</b> paid repair calls a year (est.)`, '<b>No keyword tool queried</b> · benchmarks grade C'],
      bar: 'Paid Acquisition', barsub: 'Opportunity, competition, cost · 8 km radius blend', actions: [{ id: 'a5G', label: '↓ Google Ads CSV' }, { id: 'a5M', label: '↓ Meta ZIP CSV' }, { id: 'a5All', label: '↓ Full data' }, { id: 'a5Desk', label: 'Campaign Desk ↗' }, { id: 'a5Forge', label: 'Site Forge ↗' }, { id: 'a5Lines', label: 'Service Lines ↗', title: 'The same ZIPs split into fourteen service lines (module 12)' }, { id: 'a5Watch', label: 'Competitor Watch ↗', title: 'What the competitors near these ZIPs are advertising (module 13)' }] }) +
      `<div class="wrap">
      ${callout('', 'Read this first: what this module claims and does not', `Modules 01 and 02 asked where the equipment is aging. This one asks a buying question: <b>where does an ad dollar reach the most jobs a contractor can win and get paid for, before a competitor does.</b> It multiplies real counts (modeled replacements by who decides, a repair-call rate by system age, tickets from Irving permit valuations) by stated assumptions, and divides by competition measured from the 241 mapped competitor locations and Census contractor counts. Two inputs are benchmarks, not measurements: cost per click and conversion rate come from LocaliQ's 2025 home services report (air conditioning installation and repair $9.68 a click and 6.56% conversion; heating and furnaces $9.30 and 7.48%; 3,211 campaigns, grade C). Search volume is an order-of-magnitude assumption (grade D), no keyword tool was queried and no Ahrefs units were spent. Read the coherence check: this map disagrees with module 01 on purpose, because debt and payable demand are different things.`)}
      <div class="kpis" id="a5Kpis"></div>
      <div class="grid2">
        <div class="card mapcard"><div class="controls" style="margin:0;border:0;border-bottom:1px solid var(--line);border-radius:var(--r) var(--r) 0 0">
          <div class="ctl" style="flex:1 1 220px"><label class="fl" for="a5Layer">Layer</label><select id="a5Layer">${Object.entries(PL).map(([k, o]) => `<option value="${k}">${esc(o.l)}</option>`).join('')}</select></div>
          <div class="ctl"><label class="fl" for="a5Cty">County</label><select id="a5Cty"><option value="">All</option>${CO.map(c => `<option value="${c.fips}">${c.name}</option>`).join('')}</select></div>
          <div class="ctl"><label class="fl" for="a5Q">Quadrant</label><select id="a5Q"><option value="">All</option>${QN.map((q, i) => `<option value="${i}">${q}</option>`).join('')}</select></div>
          <div class="ctl"><label class="fl" for="a5Ang">Angle</label><select id="a5Ang"><option value="">Any</option>${ANGLES.filter(a => a.id !== 'recruit').map(a => `<option value="${a.id}">${a.short}</option>`).join('')}</select></div>
          <label class="chk"><input type="checkbox" id="a5Comp"> competitors</label></div>
          <div id="a5Map"></div><div class="legend" id="a5Leg"></div></div>
        <div class="stack"><div class="card"><div class="card-h"><h3 id="a5Name">No ZIP selected</h3><p id="a5Sub">Click a ZIP on the map or a row below</p></div><div class="card-b" id="a5Det"><p class="mini">Every ZIP carries its job mass, case value, competition reading, relative click cost, the bid modifier and angles the model suggests, and the Google location ID the exports use.</p></div></div></div>
      </div>
      <div class="split">
        ${card('The four quadrants', 'Opportunity is the job value a ZIP generates, blended with its 8 km neighborhood. Competition is review mass plus contractor density. Crossing them is the honest way to read a paid map: the most valuable ZIPs are crowded because they are valuable.', '<div class="qbox" id="a5Quads"></div><div id="a5Sc" style="margin-top:12px"></div><p class="mini">Each point is one ZIP. Crosshairs at the 65th percentile of opportunity and the 60th of competition.</p>')}
        ${card('What a ZIP costs to own', 'The model gives relative click cost, not dollars. Enter what your account pays and converts; every figure recalculates.', `<div class="plan">
          <div class="f"><label class="fl" for="a5Cpc">Average CPC ($)</label><input type="number" id="a5Cpc" value="9.68" step="0.1" min="0.5"></div>
          <div class="f"><label class="fl" for="a5Share">Click share you want (%)</label><input type="number" id="a5Share" value="15" min="1" max="90"></div>
          <div class="f"><label class="fl" for="a5Cvr">Click to booked job (%)</label><input type="number" id="a5Cvr" value="6.6" step="0.1" min="0.1" max="60"></div>
          <div class="f"><label class="fl" for="a5Prep">Booked jobs that become replacements (%)</label><input type="number" id="a5Prep" value="22" min="0" max="100"></div>
          <div class="f"><label class="fl" for="a5Rep">Replacement ticket ($)</label><input type="number" id="a5Rep" value="13800" step="100"></div>
          <div class="f"><label class="fl" for="a5Fix">Repair ticket ($)</label><input type="number" id="a5Fix" value="450" step="25"></div>
          <div class="f"><label class="fl" for="a5Srch">DFW HVAC searches a month</label><input type="number" id="a5Srch" value="200000" step="10000"></div>
          <div class="f"><label class="fl" for="a5N">ZIPs in the buy</label><input type="number" id="a5N" value="40" min="1" max="263"></div></div>
          <div id="a5Bud" style="margin-top:12px"></div>
          ${callout('judg tight', 'Judgment call: none of these defaults is a forecast', 'The $9.68 CPC and 6.6% conversion are LocaliQ 2025 national home services benchmarks for air conditioning installation and repair (fetched this build, grade C); DFW auctions for "ac repair near me" in July run well above the annual average. The 22% replacement share and the $450 repair ticket are stated assumptions (grade D). 200,000 monthly searches is an order of magnitude used only to spread demand across ZIPs in proportion to job mass; it scales every search figure linearly and nothing else. Use your own account\'s numbers.')}`)}
      </div>
      ${card('Coherence check: this map disagrees with module 01, on purpose', 'ZIP-level correlations between the paid model and the Thermal Debt Index, and where the two part company.', '<div id="a5Coh"></div>', 'mt')}
      <div class="card mt"><div class="card-h" style="display:flex;gap:12px;align-items:baseline;flex-wrap:wrap"><h3 style="flex:1;min-width:160px">Ranked ZIPs: <span id="a5TblN"></span></h3><label class="fl" for="a5Sort">Sort</label><select id="a5Sort"><option value="effb">Efficiency</option><option value="oppb">Opportunity</option><option value="opp_usd">Job value pool</option><option value="mass">Job mass</option><option value="value_idx">Case value</option><option value="comp_pct">Competition (low first)</option><option value="cpc_rel">Click cost (low first)</option></select></div><div class="tscroll" id="a5Tbl"></div></div>
      <div class="split">
        ${card('County rollup: where the money sits', 'Job value pool and efficiency by county. Job value per household is the rate that survives size.', '<div class="tscroll short" id="a5Co"></div>')}
        ${card('City rollup', 'Cities of 20,000 or more, modeled outputs apportioned by 2020 block housing counts.', '<div class="tscroll short" id="a5Ci"></div>')}
      </div>
      ${card('How the model is built', 'Four layers, each a real count times a published rate or a stated assumption.', '<ol class="meth" id="a5Meth"></ol>', 'mt')}
      <div class="split">
        ${card('Judgment calls', 'Seven places where the model had to choose.', '<div id="a5Judg"></div>')}
        ${card('What this module deliberately does not use', '', '<div id="a5Not"></div>')}
      </div>
      <div class="split">${card('Caveats', '', '<div id="a5Cav"></div>')}${card('Source register', '', '<div id="a5Src"></div>')}</div>
      <div class="foot">DFW Thermal Debt Atlas, module 05. A cold-start prior for a media buy. No geographic model beats your own cost per booked job after sixty to ninety days of data.</div></div>`;
    const inScope = z => (!st.county || z.fips === st.county) && (st.quad === '' || String(z.quad) === st.quad) && (!st.angle || ANG[st.angle].trig(z));
    const map = new ZipMap($('#a5Map', root), { onSelect: z => { st.sel = st.sel === z ? null : z; render(); }, onHover: (zip, e) => { const z = ZI[zip]; if (!z || z.occ < 200) return; showTip(`<div class="tt">${z.zip} · ${esc(z.city)}</div><div class="ts">${QN[z.quad]} · tier ${z.tier} · bid ${S(z.bid, 0)}%</div>${tipRow('Efficiency', D(z.effb, 0))}${tipRow('Opportunity', D(z.oppb, 0))}${tipRow('Job value pool', MM(z.opp_usd))}${tipRow('Competition', D(z.comp_pct, 0))}${tipRow('Relative click cost', D(z.cpc_rel, 2) + '×')}`, e); }, onPin: id => goModule('supply', { comp: +id }) });
    const QC = () => [cssv('--s7'), cssv('--s3'), cssv('--ink-3'), cssv('--critical')];
    const TC = () => ramp('ember').slice(2).reverse().concat([cssv('--sunk-2')]);
    function render() {
      const o = PL[st.layer]; let f;
      if (st.layer === 'quad') { const q = QC(); f = z => q[z.quad]; $('#a5Leg', root).innerHTML = `<div class="catleg">${QN.map((n, i) => `<span><i style="background:${q[i]}"></i>${n} (${ZR.filter(z => z.quad === i).length})</span>`).join('')}</div><div class="dn">${G('C')} Opportunity 65th and competition 60th percentile thresholds.</div>`; }
      else if (st.layer === 'tier') { const t = TC(); f = z => t[TIERS.indexOf(z.tier)]; $('#a5Leg', root).innerHTML = `<div class="catleg">${TIERS.map((n, i) => `<span><i style="background:${t[i]}"></i>${n} ${S([45, 30, 15, 0, -20, -40][i], 0)}%</span>`).join('')}</div><div class="dn">${G('C')} Efficiency percentile bands mapped to starting bid modifiers.</div>`; }
      else { const dir = (st.layer === 'comp_pct' || st.layer === 'cpc_rel') ? 1 : 1; const sc = qScale(ZR.map(z => z[st.layer]), o.ramp, dir); f = z => sc.f(z[st.layer]); const v = ZR.map(z => z[st.layer]).filter(isN); $('#a5Leg', root).innerHTML = legendHTML({ title: o.l, R: sc.R, lo: o.f(Math.min(...v)), hi: o.f(Math.max(...v)), note: `Quantile classes. ${G(o.g)} ${st.layer === 'comp_pct' || st.layer === 'cpc_rel' ? 'Darker blue means more crowded or dearer.' : 'Darker means more to win.'}` }); }
      map.fill(zip => { const z = ZI[zip]; if (!z || z.occ < 200 || !isN(z.effb)) return null; return f(z); });
      const scope = new Set(ZR.filter(inScope).map(z => z.zip)); map.dim(st.county || st.quad !== '' || st.angle ? scope : null); map.select(st.sel);
      map.pins($('#a5Comp', root).checked ? COMP.map((l, i) => ({ id: i, lat: l.lat, lon: l.lon, r: l.tier === 'bench' ? 7.5 : l.tier === 'top40' ? 4.2 + Math.log10((l.reviews || 0) + 1) : 2.6, fill: l.tier === 'bench' ? cssv('--bench') : l.tier === 'top40' ? cssv('--s1') : cssv('--ink-3'), shape: l.tier === 'bench' ? 'diamond' : '' })) : []);
      kpis(); detail(); table(); budget();
    }
    function kpis() {
      const q = [0, 1, 2, 3].map(i => ZR.filter(z => z.quad === i).length);
      $('#a5Kpis', root).innerHTML = kpiHTML([
        { l: 'Buyable ZIPs', g: 'A', v: N(ZR.length), d: `of ${N(Z.length)}; the rest have under 200 households` },
        { l: 'Job value pool', g: 'C', v: MM(sum(ZR.map(z => z.opp_usd))), d: 'weighted replacements plus repairs, a year' },
        { l: 'Job mass', g: 'B', v: K(sum(ZR.map(z => z.mass))), d: 'replacement equivalents a year, by who decides' },
        { l: 'Paid repair calls', g: 'D', v: K(sum(ZR.map(z => z.repairs))), d: 'a year, from system age (10% to 45% a year by age band)' },
        { l: 'Anchor ZIPs', g: 'C', v: N(q[0]), d: 'high opportunity, high competition' },
        { l: 'Whitespace ZIPs', g: 'C', v: N(q[1]), d: 'high opportunity, competition below median' },
        { l: 'Median click cost index', g: 'D', v: D(median(ZR.map(z => z.cpc_rel)), 2) + '×', d: 'relative to a flat CPC; range 0.55 to 2.10' },
      ]);
      $('#a5Quads', root).innerHTML = QN.map((n, i) => `<div class="qb"><div class="qt"><span class="sev" style="background:${QC()[i]}"></span>${n}</div><div class="qv">${N(q[i])}</div><div class="qd">${QD[i]} · ${MM(sum(ZR.filter(z => z.quad === i).map(z => z.opp_usd)))} a year</div></div>`).join('');
      const pts = ZR.map(z => ({ x: z.comp_pct, y: z.oppb, c: QC()[z.quad], r: 4.2, tip: `<div class="tt">${z.zip} · ${esc(z.city)}</div>${tipRow('Opportunity', D(z.oppb, 0))}${tipRow('Competition', D(z.comp_pct, 0))}${tipRow('Quadrant', QN[z.quad])}`, onClick: () => { st.sel = z.zip; render(); } }));
      scatter($('#a5Sc', root), { pts, x: { label: 'Competition percentile', min: 0, max: 100, fmt: v => D(v, 0) }, y: { label: 'Opportunity percentile', min: 0, max: 100, fmt: v => D(v, 0) }, fit: false, hlines: [{ y: 65 }], vlines: [{ x: 60 }], H: 320 });
    }
    function nearComp(z, n) { return COMP.map((l, i) => ({ l, i, d: 12742 * Math.asin(Math.sqrt(0.5 - Math.cos((l.lat - z.lat) * Math.PI / 180) / 2 + Math.cos(z.lat * Math.PI / 180) * Math.cos(l.lat * Math.PI / 180) * (1 - Math.cos((l.lon - z.lon) * Math.PI / 180)) / 2)) })).filter(x => x.l.tier !== 'bench').sort((a, b) => a.d - b.d).slice(0, n); }
    function detail() {
      const z = st.sel ? ZI[st.sel] : null; if (!z || z.occ < 200) { $('#a5Name', root).textContent = 'No ZIP selected'; $('#a5Sub', root).textContent = 'Click a ZIP on the map or a row below'; return; }
      $('#a5Name', root).textContent = `${z.zip} · ${z.city}`; $('#a5Sub', root).textContent = `${z.cty} County · ${QN[z.quad]} · tier ${z.tier}`;
      const an = anglesFor(z); const nc = nearComp(z, 4);
      $('#a5Det', root).innerHTML = `<div style="display:flex;gap:18px;flex-wrap:wrap"><div><div class="big">${D(z.effb, 0)}</div><div class="mini">efficiency percentile</div></div><div><div class="big">${D(z.oppb, 0)}</div><div class="mini">opportunity</div></div><div><div class="big" style="color:${z.bid >= 0 ? 'var(--heat)' : 'var(--cool)'}">${S(z.bid, 0)}%</div><div class="mini">starting bid modifier</div></div></div>
        <div class="dsec">Job mass (a year)</div>
        <div class="rowl"><span>Replacements: owner single-family</span><b>${N(z.rep_ownsf)}</b></div><div class="rowl"><span>Replacements: rented single-family (×0.6)</span><b>${N(z.rep_rentsf)}</b></div><div class="rowl"><span>Replacements: apartments (×0.25)</span><b>${N(z.rep_mf)}</b></div><div class="rowl"><span>Paid repair calls (est.)</span><b>${N(z.repairs)}</b></div><div class="rowl"><span>Job value pool</span><b>${MM(z.opp_usd)}</b></div>
        <div class="dsec">Value and competition</div>
        <div class="rowl"><span>Ticket here · value index</span><b>${M$(z.ticket)} · ${D(z.value_idx, 0)}</b></div><div class="rowl"><span>Competition percentile · click cost index</span><b>${D(z.comp_pct, 0)} · ${D(z.cpc_rel, 2)}×</b></div><div class="rowl"><span>Mapped competitors within 8 km</span><b>${N(z.comp_n8)} (${N(z.comp_top8)} deep dive)</b></div><div class="rowl"><span>HVAC establishments within 8 km (CBP)</span><b>${N(z.est_8km)}</b></div><div class="rowl"><span>Distance to the benchmark (Mesquite)</span><b>${D(z.km_bench, 0)} km</b></div>
        <div class="mini" style="margin-top:6px">Nearest: ${nc.map(x => `${esc(x.l.name)} (${D(x.d, 1)} km, ${N(x.l.reviews)} reviews)`).join('; ')}</div>
        <div class="dsec">Angles this ZIP triggers</div><div>${an.map(a => `<span class="tag on" title="${esc(a.why)}">${a.short}</span>`).join('')}${z.span_sh >= 20 ? '<span class="tag on">Spanish build</span>' : ''}</div>
        <div class="dsec">Targeting</div><div class="rowl"><span>Google location</span><b class="mono">${z.zip}, Texas, United States</b></div><div class="rowl"><span>Google criterion ID</span><b class="mono">${z.gid || 'resolve by name'}</b></div><div class="rowl"><span>Meta ZIP key</span><b class="mono">US:${z.zip}</b></div>
        <div class="btnrow" style="display:flex;gap:8px;margin-top:10px;flex-wrap:wrap"><button class="btn sm" id="a5One">Send to Campaign Desk</button><button class="btn sec sm" id="a5Rep">Replacement ledger</button></div>`;
      $('#a5One', root).onclick = () => goModule('desk', { zips: [z.zip] }); $('#a5Rep', root).onclick = () => goModule('replace', { zip: z.zip });
    }
    function table() {
      const rows = ZR.filter(inScope); $('#a5TblN', root).textContent = `${rows.length} ZIPs in scope`;
      const k = $('#a5Sort', root).value; const asc = k === 'comp_pct' || k === 'cpc_rel'; const host = $('#a5Tbl', root); host._st = { k, dir: asc ? 1 : -1 };
      dataTable(host, [{ k: 'zip', h: 'ZIP', l: 1, f: v => `<b>${v}</b>` }, { k: 'city', h: 'City', l: 1 }, { k: 'tier', h: 'Tier', l: 1, f: v => `<span class="tier t${v === 'A+' ? 'Ap' : v}">${v}</span>` }, { k: 'quad', h: 'Quadrant', l: 1, f: v => `<span class="q${v}">${QN[v]}</span>` }, { k: 'effb', h: 'Eff.', f: v => D(v, 0) }, { k: 'oppb', h: 'Opp.', f: v => D(v, 0) }, { k: 'opp_usd', h: 'Value pool', f: v => MM(v) }, { k: 'mass', h: 'Job mass', f: v => N(v) }, { k: 'value_idx', h: 'Value idx', f: v => D(v, 0) }, { k: 'comp_pct', h: 'Comp.', f: v => D(v, 0) }, { k: 'cpc_rel', h: 'CPC idx', f: v => D(v, 2) }, { k: 'bid', h: 'Bid', f: v => S(v, 0) + '%' }], rows, { id: r => r.zip, onClick: z => { st.sel = z; map.fitTo([z]); render(); }, rowClass: r => r.zip === st.sel ? 'sel' : '' });
    }
    function econ(z) { const mz = z.mass / Math.max(1, sum(ZR.map(q => q.mass))); const srch = st.srch * mz; const clicks = srch * st.share / 100; const cost = clicks * st.cpc * z.cpc_rel; const booked = clicks * st.cvr / 100; const val = booked * (st.prep / 100 * st.rep$ * z.value_idx / 100 + (1 - st.prep / 100) * st.fix$); return { srch, clicks, cost, booked, val }; }
    function budget() {
      const rows = ZR.filter(inScope).sort((a, b) => b.effb - a.effb).slice(0, st.n); const e = rows.map(z => ({ z, ...econ(z) }));
      const T = { srch: sum(e.map(x => x.srch)), clicks: sum(e.map(x => x.clicks)), cost: sum(e.map(x => x.cost)), booked: sum(e.map(x => x.booked)), val: sum(e.map(x => x.val)) };
      $('#a5Bud', root).innerHTML = `<div class="qbox"><div class="qb"><div class="qt">Monthly media</div><div class="qv">${M$(T.cost)}</div><div class="qd">to hold ${D(st.share, 0)}% click share in the top ${rows.length} ZIPs by efficiency</div></div><div class="qb"><div class="qt">Booked jobs a month</div><div class="qv">${D(T.booked, 0)}</div><div class="qd">${N(T.clicks)} clicks at ${D(st.cvr, 1)}%</div></div><div class="qb"><div class="qt">Cost per booked job</div><div class="qv">${M$(T.cost / Math.max(1e-9, T.booked))}</div><div class="qd">before call handling and close rate</div></div><div class="qb"><div class="qt">Job value booked</div><div class="qv">${MM(T.val)}</div><div class="qd">a month, ${D(st.prep, 0)}% replacements; ${D(T.val / Math.max(1, T.cost), 1)}× media</div></div></div>
        <div class="tscroll short" style="margin-top:10px"><table><thead><tr><th class="l">ZIP</th><th class="l">City</th><th>Searches/mo</th><th>Clicks</th><th>Media/mo</th><th>Booked</th><th>Cost/booked</th></tr></thead><tbody>${e.slice(0, 25).map(x => `<tr><td class="l">${x.z.zip}</td><td class="l">${esc(x.z.city)}</td><td>${N(x.srch)}</td><td>${N(x.clicks)}</td><td>${M$(x.cost)}</td><td>${D(x.booked, 1)}</td><td>${M$(x.cost / Math.max(1e-9, x.booked))}</td></tr>`).join('')}</tbody></table></div>`;
    }
    // coherence
    const coh = DATA.index.coh; const dis = ZR.map(z => ({ z, d: z.oppb - z.idx })).sort((a, b) => b.d - a.d);
    $('#a5Coh', root).innerHTML = `<div class="split" style="margin-top:0"><div><p class="body">Opportunity and debt share a direction (r = ${D(coh.r_idx_opp, 2)} across 263 ZIPs) and part company where money and competition intervene. Case value is only loosely tied to debt (r = ${D(coh.r_idx_value, 2)}): the oldest fleets sit in the lowest-value housing, where tickets are smaller and financing matters. Opportunity and competition travel together (r = ${D(coh.r_opp_comp, 2)}), which is why the quadrants exist.</p><p class="body"><b>Where debt outruns payable demand</b> (debt far above opportunity) the right buy is financing and repair, not premium replacement. <b>Where opportunity outruns debt</b> the stock is newer but large, valuable and owner occupied: fewer failures, bigger tickets, and the builder wave arriving.</p></div>
      <div><table><thead><tr><th class="l">Opportunity well above debt</th><th>Opp.</th><th>Debt</th></tr></thead><tbody>${dis.slice(0, 6).map(x => `<tr><td class="l">${x.z.zip} ${esc(x.z.city)}</td><td>${D(x.z.oppb, 0)}</td><td>${D(x.z.idx, 0)}</td></tr>`).join('')}</tbody></table><table style="margin-top:10px"><thead><tr><th class="l">Debt well above opportunity</th><th>Opp.</th><th>Debt</th></tr></thead><tbody>${dis.slice(-6).reverse().map(x => `<tr><td class="l">${x.z.zip} ${esc(x.z.city)}</td><td>${D(x.z.oppb, 0)}</td><td>${D(x.z.idx, 0)}</td></tr>`).join('')}</tbody></table></div></div>`;
    // rollups
    const coRows = CO.map(c => { const zs = ZR.filter(z => z.fips === c.fips); return { name: c.name, occ: c.occ, opp: c.opp_usd, perhh: c.opp_usd / c.occ, eff: median(zs.map(z => z.effb)), comp: median(zs.map(z => z.comp_pct)), anchors: zs.filter(z => z.quad === 0).length, white: zs.filter(z => z.quad === 1).length }; });
    dataTable($('#a5Co', root), [{ k: 'name', h: 'County', l: 1 }, { k: 'opp', h: 'Value pool', f: v => MM(v) }, { k: 'perhh', h: 'Per household', f: v => M$(v) }, { k: 'eff', h: 'Median eff.', f: v => D(v, 0) }, { k: 'comp', h: 'Median comp.', f: v => D(v, 0) }, { k: 'anchors', h: 'Anchor', f: v => N(v) }, { k: 'white', h: 'Whitespace', f: v => N(v) }], coRows, { sortKey: 'opp' });
    dataTable($('#a5Ci', root), [{ k: 'name', h: 'City', l: 1 }, { k: 'cty', h: 'County', l: 1 }, { k: 'pop', h: 'Population', f: v => N(v) }, { k: 'opp_usd', h: 'Value pool', f: v => MM(v) }, { k: 'rep', h: 'Replacements', f: v => N(v) }, { k: 'inc', h: 'Income', f: v => M$(v) }], CITIES.filter(c => c.pop >= 20000), { sortKey: 'opp_usd' });
    $('#a5Meth', root).innerHTML = [
      `<b>Layer one: job mass ${G('B')}</b>. Each ZIP's expected 2026 system replacements (module 02) are weighted by who decides: owner-occupied single-family at 1.0, rented single-family at 0.6 (landlords answer ads, institutional owners mostly do not), apartments at 0.25 (property managers buy on contract). Paid repair calls come from the modeled age mix at 10%, 18%, 28%, 38% and 45% a year for systems aged 0 to 4, 5 to 9, 10 to 14, 15 to 19 and 20 plus (grade D), counted at the repair ticket over the replacement ticket.`,
      `<b>Layer two: case value ${G('C')}</b>. The replacement ticket starts at ${M$(13800)} (Irving permit median carried to 2026) and scales with the square root of the ZIP's median rooms and the 0.15 power of its median home value: a ZIP with twice the median value is worth about 11% more a job, not twice. Expressed as an index where 100 is the metro median ticket.`,
      `<b>Layer three: competition and cost ${G('C')}</b>. Competition is 60% the percentile of proximity-weighted Google review mass of the 241 mapped competitor locations (e-fold 12 km, the heatmap's Local Pack proxy) and 40% the percentile of HVAC establishments within 8 km per system (County Business Patterns 2023). Relative click cost is 0.55 plus 1.55 times (0.6 competition percentile plus 0.4 value percentile), bounded 0.55 to 2.10: auctions are dearer where contractors are dense and houses are expensive.`,
      `<b>Opportunity and efficiency</b>. Opportunity is the annual job value pool; efficiency is that pool over relative click cost. Both are percentile ranked and blended 65/35 with the same measure summed over an 8 km radius, because search is bought in radii and service areas, and a strong ZIP surrounded by weak ones is worth less than its polygon.`,
      `<b>Search demand ${G('D')}</b>. A stated DFW monthly total (default 200,000 commercial-intent HVAC searches) is spread across ZIPs by job mass. Replace it from Keyword Planner inside your account.`,
      `<b>Tiers and bid modifiers</b>. Efficiency percentile bands map to A+ (95 and up) through E (below 30) and to starting bid modifiers of +45% to −40%. A cold-start prior, replaced by observed cost per booked job after sixty to ninety days.`
    ].map(x => `<li>${x}</li>`).join('');
    $('#a5Judg', root).innerHTML = judgList([
      ['Who decides is weighted, not excluded', 'Rented homes and apartments are real replacements, bought by someone who does not click a homeowner ad. Weights of 0.6 and 0.25 keep them visible without letting apartment corridors dominate.'],
      ['Repair calls ride on age', 'The repair rates by age band are assumptions; the ranking barely moves if they are halved because replacements carry most of the value.'],
      ['Reviews are the competition', 'Google review mass is the best public proxy for Local Pack strength. It misses competitors that only buy ads, which the heatmap flagged as "ad signals".'],
      ['The benchmark is not a competitor to itself', 'The benchmark location is excluded from competition so its own reviews do not push its home ZIPs down.'],
      ['8 km radius', 'About 5 miles, the service radius most DFW LSA profiles and radius campaigns use inside the loop; exurban contractors often run 25 miles, which would flatten the map.'],
      ['Benchmarks are national', 'LocaliQ\'s CPC and conversion rates average the country and the year. DFW summer CPCs for emergency terms run higher.'],
      ['One ticket curve', 'Ticket scales gently with size and value; premium brands and variable-speed mixes are not modeled by ZIP.']]);
    $('#a5Not', root).innerHTML = proseTable([['Keyword volumes', 'No Ahrefs or Keyword Planner pull was made for this build. Search figures are a stated total spread by job mass.'], ['Google Local Services pricing', 'LSA cost per lead varies by job type and week; no LSA data was requested.'], ['Competitor ad spend', 'The heatmap\'s Ahrefs paid keyword counts exclude Local Services Ads and are not used as a spend estimate.'], ['Customer data', 'No CRM, call tracking or first-party audience data.'], ['Protected characteristics', 'No race, ethnicity or age targeting. The Spanish build keys off language spoken at home, a market fact, and is always paired with an English campaign.']]);
    $('#a5Cav', root).innerHTML = proseTable([['Relative, not absolute', 'The model ranks ZIPs. Dollar outputs are only as good as the CPC and conversion rate you type.'], ['Competition is a snapshot', 'Reviews and rosters are as of August 18, 2026.'], ['Radius blending smooths edges', 'A great ZIP next to a lake or an airport reads lower than its polygon; check the unblended pool column.'], ['No seasonality here', 'These are annual averages; module 08 paces them by month.']]);
    $('#a5Src', root).innerHTML = srcRows([['Job mass', 'Module 02 replacement model (ACS, RECS, BPS)', 'B', '2026', ''], ['Tickets', 'City of Irving residential mechanical permits', 'B', '2022 to 2025', ''], ['Competitors', 'DFW HVAC Competitive Heatmap, August 18, 2026 (Google Business Profile reviews)', 'C', 'Aug 2026', ''], ['Contractor density', 'ZIP Code Business Patterns 2023, NAICS 238220', 'B', '2023', 'https://www2.census.gov/programs-surveys/cbp/datasets/2023/'], ['Click cost and conversion', 'LocaliQ, 2025 Search Ad Benchmarks for Home Services (3,211 campaigns, Apr 2024 to Mar 2025)', 'C', '2025', 'https://localiq.com/blog/home-services-search-advertising-benchmarks/'], ['Google location IDs', 'Google Ads geotargets carried from the Dental Divide Atlas ZIP table (259 of 277 ZIPs); the rest resolve by name', 'B', '2026', '']]);
    // wiring
    $('#a5Layer', root).onchange = e => { st.layer = e.target.value; render(); };
    $('#a5Cty', root).onchange = e => { st.county = e.target.value; if (st.county) map.fitTo(Z.filter(z => z.fips === st.county).map(z => z.zip)); else map.reset(); render(); };
    $('#a5Q', root).onchange = e => { st.quad = e.target.value; render(); };
    $('#a5Ang', root).onchange = e => { st.angle = e.target.value; render(); };
    $('#a5Comp', root).onchange = render; $('#a5Sort', root).onchange = table;
    [['#a5Cpc', 'cpc'], ['#a5Share', 'share'], ['#a5Cvr', 'cvr'], ['#a5Prep', 'prep'], ['#a5Rep', 'rep$'], ['#a5Fix', 'fix$'], ['#a5Srch', 'srch'], ['#a5N', 'n']].forEach(([s, k]) => $(s, root).addEventListener('input', debounce(e => { st[k] = +e.target.value || st[k]; budget(); }, 200)));
    const scoped = () => ZR.filter(inScope).sort((a, b) => b.effb - a.effb);
    $('#a5G', root).onclick = () => { const H = ['Campaign', 'Location', 'ID', 'Bid Modifier', 'Criterion Type', 'Status']; const rows = scoped().slice(0, 400).map(z => ['DFW HVAC Search', `${z.zip}, Texas, United States`, z.gid || '', (z.bid >= 0 ? '+' : '') + z.bid + '%', 'Location', 'Enabled']); saveFile('google-ads-locations-dfw-hvac.csv', toCSV(H, rows)); };
    $('#a5M', root).onclick = () => { const rows = scoped().slice(0, 400).map(z => ['US:' + z.zip, z.zip, z.city, z.tier, QN[z.quad]]); saveFile('meta-zip-targets-dfw-hvac.csv', toCSV(['Zip', 'zip', 'city', 'tier', 'quadrant'], rows, 'Meta Ads Manager accepts US:ZIP keys in the Zip column. Ads that promote financing may fall under the Financial products and services special ad category, which forbids ZIP targeting (15 mile radius minimum): keep financing offers out of ZIP-targeted ad sets.')); };
    $('#a5All', root).onclick = () => { const keys = ['zip', 'city', 'cty', 'occ', 'rep', 'rep_ownsf', 'rep_rentsf', 'rep_mf', 'repairs', 'mass', 'ticket', 'value_idx', 'opp_usd', 'opp8', 'comp_mass', 'est_8km', 'comp_pct', 'cpc_rel', 'eff_usd', 'oppb', 'effb', 'quad', 'tier', 'bid', 'gid', 'span_sh']; saveFile('dfw-paid-acquisition-by-zip.csv', toCSV(keys, ZR.map(z => keys.map(k => k === 'quad' ? QN[z.quad] : z[k])), 'DFW Thermal Debt Atlas, module 05. Relative model; CPC and conversion benchmarks grade C, search volume grade D.')); };
    $('#a5Desk', root).onclick = () => goModule('desk', { zips: st.sel ? [st.sel] : scoped().slice(0, 40).map(z => z.zip) });
    $('#a5Forge', root).onclick = () => goModule('forge', { zips: st.sel ? [st.sel] : scoped().slice(0, 20).map(z => z.zip) });
    $('#a5Lines', root).onclick = () => goModule('lines', st.sel ? { zip: st.sel } : { county: st.county });
    $('#a5Watch', root).onclick = () => goModule('watch', st.sel ? { zip: st.sel } : {});
    BUS.on('theme', render);
    this.receive = p => { if (p && p.zip && ZI[p.zip]) { st.sel = p.zip; render(); } };
    render();
  }
});
