/* ==== m08_desk ==== */
"use strict";
/* ============================ Module 8: Campaign Desk ============================ */
const PLATS = ['google', 'lsa', 'dg', 'meta', 'microsoft', 'nextdoor', 'yelp', 'linkedin'];
const PLAB = { google: 'Google Search', lsa: 'Local Services Ads', dg: 'YouTube and Demand Gen', meta: 'Meta', microsoft: 'Microsoft Advertising', nextdoor: 'Nextdoor', yelp: 'Yelp Ads', linkedin: 'LinkedIn' };
const ASM0 = {
  google: { basis: 'CPC', cost: 9.68, ctr: 6.43, cvr: 6.56, min: 20, g: 'C', src: 'LocaliQ 2025, air conditioning installation and repair' },
  lsa: { basis: 'CPL', cost: 65, ctr: 0, cvr: 100, min: 20, g: 'D', src: 'Assumption; HVAC lead prices vary by job type and week' },
  dg: { basis: 'CPM', cost: 12, ctr: 0.6, cvr: 2.0, min: 15, g: 'D', src: 'Assumption' },
  meta: { basis: 'CPM', cost: 14, ctr: 1.1, cvr: 4.0, min: 10, g: 'D', src: 'Assumption; lead form objective' },
  microsoft: { basis: 'CPC', cost: 6.5, ctr: 5.0, cvr: 5.5, min: 10, g: 'D', src: 'Assumption; roughly two thirds of Google CPC' },
  nextdoor: { basis: 'CPM', cost: 10, ctr: 0.5, cvr: 2.0, min: 10, g: 'D', src: 'Assumption' },
  yelp: { basis: 'CPC', cost: 8, ctr: 3.0, cvr: 9.0, min: 10, g: 'D', src: 'Assumption; request a quote leads' },
  linkedin: { basis: 'CPC', cost: 6, ctr: 0.5, cvr: 8.0, min: 10, g: 'D', src: 'Assumption; applications' },
};
const MIX0 = { replace: { google: 44, lsa: 16, dg: 8, meta: 16, microsoft: 6, nextdoor: 6, yelp: 4, linkedin: 0 }, repair: { google: 46, lsa: 28, dg: 0, meta: 8, microsoft: 8, nextdoor: 4, yelp: 6, linkedin: 0 }, heat: { google: 46, lsa: 26, dg: 0, meta: 10, microsoft: 8, nextdoor: 4, yelp: 6, linkedin: 0 }, maint: { google: 30, lsa: 0, dg: 12, meta: 34, microsoft: 4, nextdoor: 16, yelp: 4, linkedin: 0 }, b2b: { google: 52, lsa: 0, dg: 0, meta: 10, microsoft: 12, nextdoor: 0, yelp: 0, linkedin: 26 }, recruit: { google: 30, lsa: 0, dg: 0, meta: 30, microsoft: 0, nextdoor: 0, yelp: 0, linkedin: 40 }, blend: { google: 42, lsa: 20, dg: 6, meta: 14, microsoft: 6, nextdoor: 6, yelp: 6, linkedin: 0 }, iaq: { google: 18, lsa: 0, dg: 22, meta: 40, microsoft: 4, nextdoor: 16, yelp: 0, linkedin: 0 }, ductless: { google: 40, lsa: 10, dg: 10, meta: 24, microsoft: 6, nextdoor: 10, yelp: 0, linkedin: 0 }, commercial: { google: 50, lsa: 0, dg: 6, meta: 8, microsoft: 14, nextdoor: 0, yelp: 4, linkedin: 18 } };
const PBOOK = {
  google: { geo: 'ZIP, city and county criteria with bid modifiers; Google criterion IDs carried for 259 of 277 ZIPs, the rest resolve by name', bulk: 'Google Ads Editor CSV: Account, Import, From file. Every object is paused.', limits: { h: 30, d: 90, path: 15 }, policy: ['HVAC is not a restricted vertical in the United States; Advanced Verification applies to locksmiths and garage door services, not HVAC (read this build).', 'Misrepresentation policy: offers and prices must match the landing page; "free" needs its conditions.', 'Editorial: no exclamation marks in headlines, no gimmicky capitals, no phone numbers in ad text (use call assets).', 'TDLR: the license number goes in every ad (16 TAC §75.71(h)); the desk puts it in a description line of every responsive search ad.'] },
  lsa: { geo: 'Service area by ZIP list per business profile', bulk: 'No bulk upload. Build sheet: profile, license and insurance documents, service ZIPs, job types, weekly budget, hours, Spanish toggle.', limits: { bio: 500 }, policy: ['Google screens HVAC providers: business registration, TDLR license, insurance and background checks before the Google badge shows.', 'Leads are charged per call, message or booking; dispute wrong-service or spam leads within the console window.', 'Ranking follows responsiveness, reviews and proximity; answer rate matters more than budget.'] },
  dg: { geo: 'Same Google criteria; YouTube placements and custom segments', bulk: 'Build sheet plus custom segment term lists.', limits: { h: 40, lh: 90, d: 90, biz: 25 }, policy: ['Custom segments from the keyword desk terms; in-market Home Services audiences.', 'Video creative shows real crews and trucks with the license number on the door (TDLR vehicle rule).'] },
  meta: { geo: 'ZIP keys (US:75150) for ordinary campaigns; financing creative requires the Financial products special ad category: 15 mile radius minimum, no ZIP, age or gender targeting', bulk: 'Ads Manager, Import and Export: CSV with Campaign Name, Objective, Ad Set Name, Zip, Ad Name, Title, Body, Link, Call to Action.', limits: { p: 125, h: 40, d: 30 }, policy: ['Personal attributes: describe the offer, never the person\'s finances or situation.', 'Financing mentions move an ad into the special ad category; the desk keeps financing out of ZIP ad sets.', 'Lead forms: consent language for calls and texts, unchecked.'] },
  microsoft: { geo: 'ZIP and city by name', bulk: 'Import from Google Ads, or the same Editor CSV with campaign names suffixed _MS.', limits: { h: 30, d: 90 }, policy: ['Same editorial practice as Google; audience network off at launch.'] },
  nextdoor: { geo: 'ZIP lists and neighborhoods', bulk: 'Build sheet for Nextdoor Ads Manager.', limits: { h: 60, b: 300 }, policy: ['Business page must match the advertiser; neighborhood targeting is thin in exurban ZIPs.', 'Limits are assumptions to verify in Ads Manager (grade D).'] },
  yelp: { geo: 'Service area by city and ZIP', bulk: 'Build sheet for Yelp Ads (Request a Quote enabled).', limits: { h: 40 }, policy: ['Never ask for or incentivize reviews on Yelp; Yelp posts consumer alerts on businesses that do.'] },
  linkedin: { geo: 'Metro and city by name', bulk: 'Campaign Manager bulk CSV for recruiting campaigns only.', limits: { i: 600, h: 70 }, policy: ['Employment ads must not signal age or gender; post a pay range.', 'Recruiting only; no customer advertising on LinkedIn in this desk.'] },
};
registerModule({
  key: 'desk', num: '08', title: 'Campaign Desk', desc: 'Budgets, ZIP targets, keywords, creative and bulk files for eight ad platforms',
  mount(root) {
    const defaults = () => ({ line: 'replace', budget: 15000, start: '2026-10-01', weeks: 13, scope: 'top', counties: [], picks: [], n: 30, minhh: 2000, alpha: 1.2, spanTh: 20, angles: LINES.replace.angles.slice(), brand: BRAND.short || 'Your Company', lic: BRAND.lic || 'TACLA12345C', phone: BRAND.phone || '', url: BRAND.url || 'https://www.example.com', city: BRAND.city || 'Dallas', pay: '$26 to $42 an hour', bookRate: 55, jobVal: 3400, mix: { ...MIX0.replace }, asm: JSON.parse(JSON.stringify(ASM0)), remarket: true });
    let P = Object.assign(defaults(), store.get('tda.desk.v1', {}) || {});
    P.asm = Object.assign(JSON.parse(JSON.stringify(ASM0)), P.asm || {}); P.mix = Object.assign({ ...MIX0[P.line] }, P.mix || {});
    const save = () => store.set('tda.desk.v1', P);
    const bidOf = z => (P.bids && isN(P.bids[z.zip])) ? +P.bids[z.zip] : z.bid;   // per line bid modifiers sent from module 12 override the paid model's
    let UI = { plat: 'google', angle: null, lang: 'en', tab: 'markets' };
    root.innerHTML = mastHTML({ eyebrow: 'Module 08 · Campaign Desk', title: 'Campaign Desk', dek: 'The atlas\'s ZIPs turned into media buys for a DFW heating and cooling contractor: a budget allocated by ZIP and platform and paced to the heat, targeting lists with each platform\'s own identifiers, keyword and negative sets, creative written to every platform\'s limits and to TDLR\'s advertising rule, and a bulk file or build sheet for every ads manager. Nothing here connects to a platform, and every number is a stated assumption you can change.',
      meta: [`<b>${N(ZR.length)}</b> ZIPs available as markets`, `<b>${N(Z.filter(z => z.gid).length)}</b> with Google criterion IDs`, `<b>8</b> platforms · <b>${ANGLES.length}</b> service angles · English and Spanish`, '<b>No keyword volumes pulled</b>'],
      bar: 'Campaign Desk', barsub: 'Plan, build, export', actions: [['dkPlanX', '↓ Plan'], ['dkG', '↓ Google'], ['dkL', '↓ LSA'], ['dkDg', '↓ Demand Gen'], ['dkM', '↓ Meta'], ['dkMs', '↓ Microsoft'], ['dkNd', '↓ Nextdoor'], ['dkY', '↓ Yelp'], ['dkLi', '↓ LinkedIn'], ['dkCr', '↓ Creative'], ['dkKw', '↓ Keywords'], ['dkSave', '⤓ Save'], ['dkLoad', '⤒ Load']].map(([id, label]) => ({ id, label })) }) +
      `<div class="wrap">
      ${callout('', 'Read this first: what the desk does and does not do', `Set a service line, a budget and a market scope. The desk picks ZIPs from the atlas's paid model, splits the money across Google Search, Local Services, YouTube and Demand Gen, Meta, Microsoft, Nextdoor, Yelp and (for recruiting) LinkedIn, paces it to the months when changeouts actually happen, forecasts clicks, leads and booked jobs from benchmarks you can edit, and writes the structure each platform expects: location targets with bid modifiers, keywords with match types and negatives, responsive search ads with the city filled in, social and video copy, and build sheets. Every ad carries the TDLR license number (16 TAC §75.71(h)) and passes the Emergency Satchel's lint; copy has no hyphens or dashes. It connects to no platform, pulls no keyword volumes and spends no Ahrefs units. Exports set every object to paused.`)}
      <div class="card mt"><div class="card-h"><h3>The plan</h3><p>Change anything; the desk rebuilds. The fields open prefilled with the benchmark client from the heatmap; replace them with any contractor.</p></div><div class="card-b"><div class="plan">
        <div class="f"><label class="fl" for="dkLine">Service line</label><select id="dkLine">${Object.entries(LINES).map(([k, v]) => `<option value="${k}">${esc(v.l)}</option>`).join('')}</select></div>
        <div class="f"><label class="fl" for="dkBud">Monthly budget ($)</label><input type="number" id="dkBud" min="500" step="500"><span class="hint">Media only.</span></div>
        <div class="f"><label class="fl" for="dkStart">Flight start · weeks</label><div style="display:flex;gap:6px"><input type="date" id="dkStart"><input type="number" id="dkWeeks" min="2" max="52" style="width:70px"></div></div>
        <div class="f"><label class="fl" for="dkScope">Market scope</label><select id="dkScope"><option value="top">Top ZIPs by efficiency, metro</option><option value="county">Top ZIPs in selected counties</option><option value="picks">Hand-picked ZIPs</option></select></div>
        <div class="f"><label class="fl" for="dkCounties">Counties (for county scope)</label><select id="dkCounties" multiple size="4">${CO.map(c => `<option value="${c.fips}">${c.name}</option>`).join('')}</select></div>
        <div class="f"><label class="fl" for="dkPicks">Hand-picked ZIPs</label><input type="text" id="dkPicks" placeholder="75150, 75149, 75181"><span class="hint">Other modules send ZIPs here.</span></div>
        <div class="f"><label class="fl" for="dkN">ZIPs to buy · min households</label><div style="display:flex;gap:6px"><input type="number" id="dkN" min="1" max="263" style="width:80px"><select id="dkMin"><option value="0">any</option><option value="1000">1,000+</option><option value="2000">2,000+</option><option value="5000">5,000+</option><option value="10000">10,000+</option></select></div></div>
        <div class="f"><label class="fl" for="dkAlpha">Concentration α <span id="dkAlphaV"></span></label><input type="range" id="dkAlpha" min="0.5" max="2.5" step="0.1"><span class="hint">1 spends in proportion to opportunity; 2 concentrates on the best ZIPs.</span></div>
        <div class="f"><label class="fl" for="dkSpan">Spanish build where Spanish-speaking households ≥ (%)</label><input type="number" id="dkSpan" min="0" max="100"></div>
        <div class="f"><label class="fl" for="dkBrand">Business name (Google ≤ 25)</label><input type="text" id="dkBrand" maxlength="40"></div>
        <div class="f"><label class="fl" for="dkLic">TDLR license number</label><input type="text" id="dkLic" placeholder="TACLA12345C"><span class="hint">Required in every ad by 16 TAC §75.71(h).</span></div>
        <div class="f"><label class="fl" for="dkPhone">Call asset phone</label><input type="tel" id="dkPhone"></div>
        <div class="f"><label class="fl" for="dkUrl">Landing URL base</label><input type="url" id="dkUrl"></div>
        <div class="f"><label class="fl" for="dkCity">Home city (copy fallback)</label><input type="text" id="dkCity"></div>
        <div class="f"><label class="fl" for="dkPay">Recruiting pay range</label><input type="text" id="dkPay"></div>
        <div class="f"><label class="fl" for="dkBook">Lead to booked job (%) · value per booked job ($)</label><div style="display:flex;gap:6px"><input type="number" id="dkBook" min="1" max="100" style="width:70px"><input type="number" id="dkVal" min="50" step="50" style="width:100px"></div><span class="hint">Grade D defaults; value blends repairs and replacements.</span></div>
        <div class="f wide"><label class="fl">Service angles</label><div class="chips" id="dkAngles"></div><span class="hint">Pre-selected by line; each ZIP runs only the angles its own data triggers.</span></div>
      </div>
      <div class="dsec" style="margin-top:16px">Platform mix (% of budget)</div><div class="mix" id="dkMix"></div><div style="margin-top:8px;display:flex;gap:8px;flex-wrap:wrap"><button class="btn sec sm" id="dkMixReset">Reset mix to line default</button></div>
      <div class="dsec" style="margin-top:16px">Assumptions (editable)</div><div class="xscroll" id="dkAsm"></div></div></div>
      <div class="kpis" id="dkKpis"></div>
      <div class="grid2">
        <div class="card mapcard"><div class="card-h"><h3>Markets in the buy</h3><p>Shaded by monthly allocation. Click a ZIP to add or drop it (switches scope to hand-picked).</p></div><div id="dkMap"></div><div class="legend" id="dkLeg"></div></div>
        <div class="card"><div class="card-h"><h3>Plan summary</h3></div><div class="card-b"><div class="ptabs" id="dkTabs"><button data-v="markets" aria-pressed="true">Markets</button><button data-v="platforms" aria-pressed="false">Platforms</button><button data-v="flight" aria-pressed="false">Flight and pacing</button><button data-v="objects" aria-pressed="false">Campaign objects</button></div><div id="dkTab"></div></div></div>
      </div>
      <div class="card mt"><div class="card-h"><h3>Platform builders: what will be created, and the file that creates it</h3><p>Structure, targeting, creative for the selected angle with character counts and Satchel lint, and the rules that bind this buy.</p></div><div class="card-b"><div class="ptabs" id="dkPTabs">${PLATS.map((p, i) => `<button data-v="${p}" aria-pressed="${i === 0}">${PLAB[p]}</button>`).join('')}</div>
        <div style="display:flex;gap:10px;flex-wrap:wrap;margin-bottom:10px"><div class="ctl"><label class="fl" for="dkAng">Creative angle</label><select id="dkAng"></select></div><div class="ctl"><label class="fl">Language</label><div class="seg" id="dkLang"><button data-v="en" aria-pressed="true">English</button><button data-v="es" aria-pressed="false">Spanish</button></div></div><div class="ctl"><label class="fl" for="dkPrev">Preview market</label><select id="dkPrev"></select></div></div><div id="dkBuild"></div></div></div>
      <div class="split">
        ${card('Keyword desk: Google Search and Microsoft', 'Angle keywords with match types, question terms, and the geo-modified variants the export writes for each market city. Price the set in Keyword Planner inside the account; nothing here was priced by a keyword tool.', '<div class="ctl" style="margin-bottom:8px"><select id="dkKwA"></select></div><div id="dkKwOut"></div>')}
        ${card('Measurement, naming and operating rules', 'Conversion actions, UTM and naming scheme, and the pacing and kill rules derived from the assumptions.', '<div id="dkMeas"></div>')}
      </div>
      ${card('Compliance: platforms, TDLR and the statutes behind the lint', 'What binds this buy. ✔ primary text read this build; ◐ secondary or memory, verify before launch.', '<div id="dkComp"></div>', 'mt')}
      <div class="split">
        ${card('How the desk is built', '', '<ol class="meth" id="dkHow"></ol>')}
        ${card('Judgment calls', 'Ten places where the desk had to choose.', '<div id="dkJudg"></div>')}
      </div>
      <div class="foot">DFW Thermal Debt Atlas, module 08. Media plans are cold-start priors built from public data and stated benchmarks. Replace every assumption with account data after the first thirty days.</div></div>`;
    // ---------- model ----------
    function markets() {
      let pool = ZR.filter(z => z.occ >= P.minhh);
      if (P.scope === 'county' && P.counties.length) pool = pool.filter(z => P.counties.includes(z.fips));
      if (P.scope === 'picks') { const s = new Set(P.picks); pool = ZR.filter(z => s.has(z.zip)); }
      else pool = pool.sort((a, b) => b.effb - a.effb).slice(0, P.n);
      const w = pool.map(z => Math.pow(Math.max(1, z.opp_usd), P.alpha)); const ws = sum(w) || 1;
      return pool.map((z, i) => ({ z, share: w[i] / ws, spend: P.budget * w[i] / ws, es: z.span_sh >= P.spanTh, angles: anglesFor(z).filter(a => P.angles.includes(a.id)) }));
    }
    function forecast(M) {
      const out = {}; PLATS.forEach(p => { const A = P.asm[p]; const spend = P.budget * (P.mix[p] || 0) / 100; if (!spend) { out[p] = { spend: 0, clicks: 0, leads: 0, booked: 0 }; return; }
        const cm = sum(M.map(m => m.share * m.z.cpc_rel)) || 1; let clicks = 0, leads = 0;
        if (A.basis === 'CPC') { clicks = spend / (A.cost * (p === 'google' || p === 'microsoft' ? cm : 1)); leads = clicks * A.cvr / 100; }
        else if (A.basis === 'CPM') { const imp = spend / A.cost * 1000; clicks = imp * A.ctr / 100; leads = clicks * A.cvr / 100; }
        else { leads = spend / A.cost; clicks = leads; }
        const book = p === 'lsa' ? Math.min(90, P.bookRate * 1.3) : p === 'linkedin' ? 0 : P.bookRate;
        out[p] = { spend, clicks, leads, booked: leads * book / 100 }; });
      return out;
    }
    function ctxFor(z, lang) { const city = (z && z.city) || P.city; return { city, short: city.length > 12 ? city.split(' ')[0] : city, county: (z && z.cty) || '', brand: P.brand.slice(0, 25), lic: P.lic, pay: P.pay, phone: phoneFmt(P.phone) }; }
    function rsaFor(a, z, lang) {
      const ctx = ctxFor(z, lang); const src = lang === 'es' && a.es ? a.es : a;
      const hs = [], seen = new Set(); (src.h || []).concat(lang === 'es' ? ['Técnicos con Licencia', 'Llame Hoy', 'Servicio en {county}'] : ['Call {brand}', 'Serving {county} County', 'Licensed HVAC Team']).forEach(h => { const t = fillCopy(h, ctx, 30); if (t && !seen.has(t.toLowerCase()) && hs.length < 15) { seen.add(t.toLowerCase()); hs.push(t); } });
      const ds = []; (src.d || []).forEach(d => { const t = fillCopy(d, ctx, 90); if (t && !ds.includes(t) && ds.length < 4) ds.push(t); });
      if (!ds.some(d => d.includes(P.lic))) { const t = fillCopy(lang === 'es' ? 'Contratista con licencia en Texas. Lic {lic}.' : 'Licensed Texas air conditioning contractor. Lic {lic}.', ctx, 90); if (t) { if (ds.length >= 4) ds[3] = t; else ds.push(t); } }
      return { h: hs, d: ds };
    }
    const lint = (txt, extra) => satchelLint(txt, Object.assign({ lic: P.lic }, extra || {}));
    const lintSet = (texts, plat) => { const all = texts.join(' \n '); const f = lint(all, { needLic: true, platform: plat }); texts.forEach(t => lint(t, { headline: true }).forEach(x => { if (x.rule.id === 'GGL1') f.push(x); })); return f; };
    // ---------- render ----------
    let MKT = [], FC = {};
    function syncUI() {
      $('#dkLine', root).value = P.line; $('#dkBud', root).value = P.budget; $('#dkStart', root).value = P.start; $('#dkWeeks', root).value = P.weeks; $('#dkScope', root).value = P.scope;
      $$('#dkCounties option', root).forEach(o => o.selected = P.counties.includes(o.value)); $('#dkPicks', root).value = P.picks.join(', '); $('#dkN', root).value = P.n; $('#dkMin', root).value = String(P.minhh);
      $('#dkAlpha', root).value = P.alpha; $('#dkAlphaV', root).textContent = D(P.alpha, 1); $('#dkSpan', root).value = P.spanTh; $('#dkBrand', root).value = P.brand; $('#dkLic', root).value = P.lic; $('#dkPhone', root).value = P.phone; $('#dkUrl', root).value = P.url; $('#dkCity', root).value = P.city; $('#dkPay', root).value = P.pay; $('#dkBook', root).value = P.bookRate; $('#dkVal', root).value = P.jobVal;
      const fires = new Set(); ZR.forEach(z => anglesFor(z).forEach(a => fires.add(a.id)));
      $('#dkAngles', root).innerHTML = ANGLES.map(a => `<span class="chip ${fires.has(a.id) || a.id === 'recruit' ? '' : 'dim'}" data-a="${a.id}" aria-pressed="${P.angles.includes(a.id)}" title="${esc(a.why)}">${a.short}</span>`).join('');
      $$('#dkAngles .chip', root).forEach(c => c.onclick = () => { const id = c.dataset.a; P.angles = P.angles.includes(id) ? P.angles.filter(x => x !== id) : P.angles.concat(id); rebuild(); syncUI(); });
    }
    function mixUI() {
      const tot = sum(PLATS.map(p => P.mix[p] || 0));
      $('#dkMix', root).innerHTML = PLATS.map(p => `<div class="m"><span>${PLAB[p]}</span><input type="range" min="0" max="80" step="1" value="${P.mix[p] || 0}" data-p="${p}" aria-label="${PLAB[p]} share"><b>${D(P.mix[p] || 0, 0)}%</b><span class="usd">${M$(P.budget * (P.mix[p] || 0) / Math.max(1, tot))}</span></div>`).join('') + `<div class="mini">Total ${D(tot, 0)}%${Math.abs(tot - 100) > 0.5 ? ' (shares are rescaled to 100%)' : ''}</div>`;
      $$('#dkMix input', root).forEach(i => i.oninput = () => { P.mix[i.dataset.p] = +i.value; rebuild(true); });
    }
    function asmUI() {
      $('#dkAsm', root).innerHTML = `<table><thead><tr><th class="l">Platform</th><th class="l">Basis</th><th>Cost</th><th>CTR %</th><th>Lead CVR %</th><th>Min $/day</th><th class="l">Grade</th><th class="l">Source</th></tr></thead><tbody>${PLATS.map(p => { const A = P.asm[p]; return `<tr><td class="l">${PLAB[p]}</td><td class="l">${A.basis}</td><td><input type="number" step="0.1" data-p="${p}" data-k="cost" value="${A.cost}" style="width:72px"></td><td><input type="number" step="0.1" data-p="${p}" data-k="ctr" value="${A.ctr}" style="width:64px"></td><td><input type="number" step="0.1" data-p="${p}" data-k="cvr" value="${A.cvr}" style="width:64px"></td><td><input type="number" step="1" data-p="${p}" data-k="min" value="${A.min}" style="width:56px"></td><td class="l">${G(A.g)}</td><td class="l wrap mini">${esc(A.src)}</td></tr>`; }).join('')}</tbody></table><div style="margin-top:6px"><button class="btn sec sm" id="dkAsmReset">Reset to benchmarks</button></div>`;
      $$('#dkAsm input', root).forEach(i => i.oninput = debounce(() => { P.asm[i.dataset.p][i.dataset.k] = +i.value; rebuild(true); }, 250));
      $('#dkAsmReset', root).onclick = () => { P.asm = JSON.parse(JSON.stringify(ASM0)); asmUI(); rebuild(); };
    }
    const map = new ZipMap($('#dkMap', root), { onSelect: zip => { const z = ZI[zip]; if (!z || z.occ < 200) return; const cur = new Set(MKT.map(m => m.z.zip)); if (cur.has(zip)) cur.delete(zip); else cur.add(zip); P.scope = 'picks'; P.picks = [...cur]; rebuild(); syncUI(); }, onHover: (zip, e) => { const m = MKT.find(x => x.z.zip === zip); const z = ZI[zip]; if (!z || z.occ < 200) return; showTip(`<div class="tt">${z.zip} · ${esc(z.city)}</div>${m ? tipRow('Monthly allocation', M$(m.spend)) + tipRow('Angles', m.angles.map(a => a.short).join(', ') || 'core') + (m.es ? tipRow('Spanish build', 'yes') : '') : tipRow('Not in the buy', 'click to add')}${tipRow('Efficiency', D(z.effb, 0))}`, e); } });
    function rebuild(light) {
      MKT = markets(); FC = forecast(MKT); save();
      const T = { spend: sum(PLATS.map(p => FC[p].spend)), clicks: sum(PLATS.map(p => FC[p].clicks)), leads: sum(PLATS.map(p => FC[p].leads)), booked: sum(PLATS.map(p => FC[p].booked)) };
      const objs = countObjects();
      $('#dkKpis', root).innerHTML = kpiHTML([
        { l: 'Monthly media', g: 'D', v: M$(T.spend), d: `${LINES[P.line].l}; ${P.weeks} weeks from ${P.start}` },
        { l: 'Markets bought', g: 'C', v: N(MKT.length), d: `${MKT.filter(m => m.es).length} with a Spanish build · ${N(sum(MKT.map(m => m.z.occ)))} households` },
        { l: 'Clicks a month', g: 'D', v: N(T.clicks), d: 'CPC platforms scaled by each ZIP\'s relative click cost' },
        { l: 'Leads a month', g: 'D', v: N(T.leads), d: 'calls, forms and LSA leads' },
        { l: 'Booked jobs', g: 'D', v: N(T.booked), d: `at ${D(P.bookRate, 0)}% lead to booked (LSA higher)` },
        { l: 'Cost per booked job', g: 'D', v: M$(T.spend / Math.max(1e-9, T.booked)), d: `${MM(T.booked * P.jobVal)} booked value a month` },
        { l: 'Campaign objects', g: '', v: N(objs.total), d: `${objs.camps} campaigns · ${objs.groups} ad groups · ${objs.ads} ads` },
      ]);
      const mx = Math.max(...MKT.map(m => m.spend), 1); const R = ramp('ember');
      map.fill(zip => { const m = MKT.find(x => x.z.zip === zip); if (m) return R[Math.min(7, 2 + Math.floor(5.99 * m.spend / mx))]; const z = ZI[zip]; return z && z.occ >= 200 ? cssv('--sunk') : null; });
      $('#dkLeg', root).innerHTML = legendHTML({ title: 'Monthly allocation', R: R.slice(2), lo: M$(Math.min(...MKT.map(m => m.spend))), hi: M$(mx), note: `Allocation proportional to job value pool to the power α = ${D(P.alpha, 1)}. Light gray ZIPs are available but not bought.` });
      if (!light) { mixUI(); }
      else $$('#dkMix .m', root).forEach((row, i) => { const p = PLATS[i]; const tot = sum(PLATS.map(q => P.mix[q] || 0)); row.querySelector('b').textContent = D(P.mix[p] || 0, 0) + '%'; row.querySelector('.usd').textContent = M$(P.budget * (P.mix[p] || 0) / Math.max(1, tot)); });
      tab(); builder(); kwDesk(); meas();
      const pv = $('#dkPrev', root); pv.innerHTML = MKT.slice(0, 60).map(m => `<option value="${m.z.zip}">${m.z.zip} ${esc(m.z.city)}${m.es ? ' (ES)' : ''}</option>`).join('');
    }
    function countObjects() { let camps = 0, groups = 0, ads = 0; PLATS.forEach(p => { if (!FC[p] || !FC[p].spend) return; const langs = 1 + (MKT.some(m => m.es) ? 1 : 0); const ang = new Set(MKT.flatMap(m => m.angles.map(a => a.id))).size || 1; if (p === 'google' || p === 'microsoft') { camps += langs; groups += langs * ang * 3; ads += langs * ang * 3; } else if (p === 'lsa') { camps += 1; } else { camps += 1; groups += ang; ads += ang * langs * 2; } }); return { camps, groups, ads, total: camps + groups + ads }; }
    function monthsOf() { const s = new Date(P.start + 'T12:00:00'); const out = []; const end = new Date(s.getTime() + P.weeks * 7 * 864e5); let d = new Date(s); while (d < end) { const m = d.getMonth(); const nx = new Date(d.getFullYear(), m + 1, 1); const segEnd = nx < end ? nx : end; const days = Math.round((segEnd - d) / 864e5); out.push({ m, y: d.getFullYear(), days }); d = nx; } return out; }
    function pacing() { const slSeas = (typeof SLM !== 'undefined' && SLM.seasonFor) ? SLM.seasonFor(P.line) : null; const seas = slSeas || (P.line === 'heat' ? DATA.climate.normals.hdd.map(v => 40 + v / 5) : P.line === 'maint' ? [110, 100, 120, 130, 110, 80, 70, 70, 90, 120, 110, 90] : META.season_fw); const mm = monthsOf(); const w = mm.map(x => seas[x.m] * x.days); const ws = sum(w) || 1; const total = P.budget * P.weeks / 4.345; return mm.map((x, i) => ({ ...x, idx: seas[x.m], spend: total * w[i] / ws })); }
    function tab() {
      const t = UI.tab; const host = $('#dkTab', root);
      if (t === 'markets') { host.innerHTML = '<div class="tscroll short" id="dkMk"></div>'; dataTable($('#dkMk', root), [{ k: 'zip', h: 'ZIP', l: 1, v: m => m.z.zip }, { k: 'city', h: 'City', l: 1, v: m => m.z.city }, { k: 'tier', h: 'Tier', l: 1, v: m => m.z.tier }, { k: 'bid', h: 'Bid', v: m => bidOf(m.z), f: v => S(v, 0) + '%' }, { k: 'spend', h: '$/mo', f: v => M$(v) }, { k: 'es', h: 'ES', l: 1, f: v => v ? 'yes' : '' }, { k: 'ang', h: 'Angles', l: 1, v: m => m.angles.map(a => a.short).join(', ') }], MKT, { sortKey: 'spend' }); }
      else if (t === 'platforms') { host.innerHTML = `<table><thead><tr><th class="l">Platform</th><th>$/mo</th><th>Clicks</th><th>Leads</th><th>Booked</th><th>Cost/booked</th></tr></thead><tbody>${PLATS.filter(p => FC[p].spend > 0).map(p => `<tr><td class="l">${PLAB[p]}</td><td>${M$(FC[p].spend)}</td><td>${N(FC[p].clicks)}</td><td>${N(FC[p].leads)}</td><td>${D(FC[p].booked, 1)}</td><td>${FC[p].booked > 0 ? M$(FC[p].spend / FC[p].booked) : '—'}</td></tr>`).join('')}</tbody></table>${PLATS.filter(p => FC[p].spend > 0 && FC[p].spend / 30.4 < P.asm[p].min).map(p => callout('judg tight', 'Below the daily minimum', `${PLAB[p]} gets ${M$(FC[p].spend / 30.4)} a day, under the ${M$(P.asm[p].min)} floor you set; the export groups all markets into one campaign so the platform can learn.`)).join('')}`; }
      else if (t === 'flight') { const pc = pacing(); const mo = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']; host.innerHTML = `<div id="dkFl"></div><table style="margin-top:8px"><thead><tr><th class="l">Month</th><th>Days</th><th>Seasonal index</th><th>Media</th></tr></thead><tbody>${pc.map(x => `<tr><td class="l">${mo[x.m]} ${x.y}</td><td>${x.days}</td><td>${D(x.idx, 0)}</td><td>${M$(x.spend)}</td></tr>`).join('')}</tbody></table><p class="chartnote">The flight spends ${M$(sum(pc.map(x => x.spend)))} across ${P.weeks} weeks, weighted by ${P.line === 'heat' ? 'heating degree day normals' : P.line === 'maint' ? 'a spring and fall tune up curve' : 'the Fort Worth changeout seasonal index'}. Heat wave rule: when DFW forecasts three or more 100°F days, lift Search and LSA budgets 25% for the week (the permit elasticity is about 7% a month per 100 CDD above normal).</p>`; barChart($('#dkFl', root), { cats: pc.map(x => mo[x.m] + ' ' + String(x.y).slice(2)), series: [{ name: 'Media', color: cssv('--accent'), values: pc.map(x => x.spend) }], H: 180, fmt: v => MM(v) }); }
      else { const o = countObjects(); host.innerHTML = `<p class="body">${o.camps} campaigns, ${o.groups} ad groups and ${o.ads} ads across ${PLATS.filter(p => FC[p].spend > 0).length} platforms. Search campaigns run one per language with three ad groups per angle (Core in exact and phrase, Questions in phrase, Local with city names in phrase), each with one responsive search ad of up to 15 headlines and 4 descriptions. Social and video run one campaign per platform with an ad set per angle.</p>`; }
    }
    function builder() {
      const p = UI.plat; const langs = MKT.some(m => m.es) ? ['en', 'es'] : ['en'];
      const angs = [...new Set(MKT.flatMap(m => m.angles.map(a => a.id)))].map(id => ANG[id]).filter(Boolean); const list = angs.length ? angs : [ANG[P.line === 'recruit' ? 'recruit' : 'repair']];
      const sel = $('#dkAng', root); if (!UI.angle || !list.find(a => a.id === UI.angle)) UI.angle = list[0].id; sel.innerHTML = list.map(a => `<option value="${a.id}" ${a.id === UI.angle ? 'selected' : ''}>${a.short}</option>`).join('');
      const a = ANG[UI.angle]; const pz = ZI[$('#dkPrev', root).value] || (MKT[0] && MKT[0].z); const lang = UI.lang; const ctx = ctxFor(pz, lang); const B = PBOOK[p];
      let creative = '';
      if (p === 'google' || p === 'microsoft') { const r = rsaFor(a, pz, lang); const f = lintSet(r.h.concat(r.d), p); creative = `<div class="dsec">Responsive search ad</div>${r.h.map(h => `<div class="asset"><span class="cnt">${h.length}/30</span>${esc(h)}</div>`).join('')}${r.d.map(d => `<div class="asset"><span class="cnt">${d.length}/90</span>${esc(d)}</div>`).join('')}${lintBlock(f)}`; }
      else if (p === 'meta' || p === 'nextdoor' || p === 'yelp' || p === 'dg') { const src = a.meta; const pt = fillCopy(lang === 'es' && a.es ? (a.es.d[0] || src.p) : src.p, ctx); const hl = fillCopy(src.h, ctx, p === 'meta' ? 40 : 60); const ds = fillCopy(src.d, ctx, 30) || ''; const withLic = (pt || '') + ' Lic ' + P.lic + '.'; const f = lint(withLic + ' ' + (hl || '') + ' ' + ds, { needLic: true, platform: p }); creative = `<div class="dsec">${p === 'dg' ? 'Video and Demand Gen asset text' : 'Ad copy'}</div><div class="asset"><span class="cnt">${withLic.length}/${p === 'meta' ? '125 visible' : '300'}</span>${esc(withLic)}</div><div class="asset"><span class="cnt">${(hl || '').length}</span>${esc(hl || '')}</div><div class="asset"><span class="cnt">${ds.length}</span>${esc(ds)}</div>${p === 'dg' ? `<div class="asset">Script (15 seconds): open on the condenser in a ${esc(ctx.city)} backyard at noon; tech with license number on the truck door; one line: "${esc(fillCopy(a.meta.h, ctx) || '')}"; end card with ${esc(P.brand)} and Lic ${esc(P.lic)}.</div>` : ''}${lintBlock(f)}`; }
      else if (p === 'lsa') { creative = `<div class="dsec">Build sheet</div><table class="prose"><tbody><tr><td>Business name</td><td>${esc(P.brand)}</td></tr><tr><td>License</td><td>${esc(P.lic)} (TDLR, upload in the console)</td></tr><tr><td>Job types</td><td>${esc([...new Set(list.flatMap(x => x.lsa))].join(', ') || 'AC repair')}</td></tr><tr><td>Service ZIPs</td><td class="mono">${MKT.map(m => m.z.zip).join(', ')}</td></tr><tr><td>Weekly budget</td><td>${M$(FC.lsa.spend / 4.345)}</td></tr><tr><td>Bio (≤ 500)</td><td>${esc(fillCopy(`${P.brand} is a licensed Texas air conditioning and heating contractor serving {county} County. We diagnose, price upfront and install matched systems with our own crew. Lic {lic}.`, ctx) || '')}</td></tr><tr><td>Spanish</td><td>${MKT.some(m => m.es) ? 'Enable Spanish; answer in Spanish' : 'Off'}</td></tr></tbody></table>`; }
      else if (p === 'linkedin') { creative = `<div class="dsec">Recruiting ad</div><div class="asset">${esc(fillCopy(ANG.recruit.meta.p, ctx) || '')}</div><div class="asset">${esc(fillCopy(ANG.recruit.h[0], ctx) || '')}</div>`; }
      $('#dkBuild', root).innerHTML = `<div class="split" style="margin-top:0"><div><div class="dsec">Structure</div><p class="body">${esc(B.bulk)}</p><div class="dsec">Targeting</div><p class="body">${esc(B.geo)}</p><div class="dsec">Rules that bind this buy</div><ul class="body" style="padding-left:18px;margin:0">${B.policy.map(x => `<li>${esc(x)}</li>`).join('')}</ul><div class="rowl" style="margin-top:8px"><span>Monthly media on this platform</span><b>${M$(FC[p].spend)}</b></div></div><div>${creative}</div></div>`;
    }
    function lintBlock(f) { if (!f.length) return '<div class="msg ok">Satchel lint: no findings.</div>'; return f.map(x => `<div class="asset ${x.rule.sev === 'block' ? 'bad' : 'warn'}"><b>${esc(x.rule.name)}</b> <span class="mini">${esc(x.rule.cite)} ${x.rule.v}</span><span class="why">${esc(x.ev)}: ${esc(x.rule.fix)}</span></div>`).join(''); }
    function kwDesk() {
      const angs = [...new Set(MKT.flatMap(m => m.angles.map(a => a.id)))]; const list = (angs.length ? angs : ['repair']).map(id => ANG[id]); const sel = $('#dkKwA', root); const cur = sel.value; sel.innerHTML = list.map(a => `<option value="${a.id}">${a.short}</option>`).join(''); if (cur && list.find(a => a.id === cur)) sel.value = cur;
      const a = ANG[sel.value] || list[0]; const cities = [...new Set(MKT.map(m => m.z.city))].slice(0, 12);
      const core = a.kw.filter(k => !k.includes('{city}')), geo = a.kw.filter(k => k.includes('{city}'));
      const neg = P.line === 'recruit' ? NEG_RECRUIT : NEG_CUSTOMER;
      $('#dkKwOut', root).innerHTML = `<div class="kwcol">${core.map(k => `<div>[${esc(k)}] <span class="mt2">exact</span></div><div>"${esc(k)}" <span class="mt2">phrase</span></div>`).join('')}${a.kwq.map(k => `<div>"${esc(k)}" <span class="mt2">question</span></div>`).join('')}${geo.flatMap(k => cities.slice(0, 6).map(c => `<div>"${esc(k.replace('{city}', c.toLowerCase()))}" <span class="mt2">local</span></div>`)).join('')}</div><div class="dsec">Negatives (campaign level)</div><div class="neg">${neg.map(n => `<code>${esc(n)}</code>`).join('')}</div><div style="margin-top:8px;display:flex;gap:8px"><button class="btn sec sm" id="dkKwCopy">Copy keywords</button><button class="btn sec sm" id="dkNegCopy">Copy negatives</button></div>`;
      $('#dkKwCopy', root).onclick = () => copyText(core.map(k => `[${k}]\n"${k}"`).concat(a.kwq.map(k => `"${k}"`)).concat(geo.flatMap(k => cities.map(c => `"${k.replace('{city}', c.toLowerCase())}"`))).join('\n'));
      $('#dkNegCopy', root).onclick = () => copyText(neg.join('\n'));
    }
    function meas() {
      const tgt = P.jobVal * 0.18;
      $('#dkMeas', root).innerHTML = `<table class="prose"><tbody><tr><td>Conversion actions</td><td>Calls from ads of 60 seconds or more; calls from the website number (forwarding); form submits on the thank-you page; LSA leads; booked jobs imported from the field system weekly as offline conversions with job value.</td></tr><tr><td>Naming</td><td class="mono">DFW_${P.line.toUpperCase()}_{PLATFORM}_{GEO}_{LANG}_${P.start.replace(/-/g, '')}</td></tr><tr><td>UTM</td><td class="mono">utm_source={platform}&amp;utm_medium=cpc&amp;utm_campaign={campaign}&amp;utm_content={angle}&amp;utm_term={keyword}</td></tr><tr><td>Target cost per booked job</td><td>${M$(tgt)} (18% of booked value). Pause an ad group after 40 clicks with no booked job, or when cost per booked job runs above ${M$(tgt * 2)} for two weeks.</td></tr><tr><td>Heat wave rule</td><td>Three or more forecast 100°F days: lift Search and LSA 25% for the week; first heat wave of the season: add maintenance plan members to the call queue first.</td></tr><tr><td>Freeze rule</td><td>Forecast low of 20°F or less: switch heating repair ads on across all markets for 72 hours; replacements wait.</td></tr><tr><td>Bid modifiers</td><td>Start from the atlas tiers (A+ +45% to E −40%); after 60 to 90 days replace with observed cost per booked job by ZIP.</td></tr></tbody></table>`;
    }
    // compliance block (static)
    $('#dkComp', root).innerHTML = proseTable(SAT.rules.map(r => [esc(r.name), `<span class="mono">${esc(r.cite)}</span> ${r.v}`, esc(r.fix)]), ['Rule', 'Cite', 'What the desk does or you must do']);
    $('#dkHow', root).innerHTML = [`<b>Markets</b>. ZIPs come from module 05 ranked by efficiency (or your counties or picks), filtered by households.`, `<b>Weights</b>. Each market's share is its annual job value pool to the power α, normalized.`, `<b>Costs</b>. CPC platforms scale the base CPC by each market's relative click cost; CPM platforms convert impressions to clicks by CTR; LSA converts spend to leads at the stated cost per lead.`, `<b>Forecast</b>. Leads times your lead to booked rate (LSA leads count 1.3 times, capped at 90%) gives booked jobs; booked value uses your blended job value.`, `<b>Pacing</b>. The flight spreads the budget across its months by the Fort Worth changeout seasonal index (cooling and replacement lines), heating degree day normals (heating) or a tune up curve (maintenance).`, `<b>Creative</b>. Every asset is filled from the angle library with the market's city and county, cut to the platform's limits, cleaned of hyphens and dashes, given the license number, and linted by the Satchel rule pack.`, `<b>Exports</b>. One file per platform in the format its bulk tool takes, every object paused.`].map(x => `<li>${x}</li>`).join('');
    $('#dkJudg', root).innerHTML = judgList([['The license number is mandatory, so it is automatic', 'TDLR\'s rule covers "all advertising"; the desk adds it to a description line of every RSA and to every social ad rather than trusting the writer.'], ['Financing stays out of ZIP-targeted Meta ad sets', 'Meta treats financing offers as a financial products special ad category, which forbids ZIP targeting.'], ['No tax credit language', 'The 25C credit ended with 2025 installs; the lint blocks it.'], ['LSA leads convert better', 'Call leads from Local Services book more often than clicks; the 1.3 multiplier is an assumption.'], ['Spanish is additive', 'Spanish campaigns run alongside English ones in qualifying ZIPs, never instead of them.'], ['Search partners and display off', 'Launch on Google Search only; add partners once cost per booked job is known.'], ['Remarketing on', 'HVAC is not a sensitive category; site visitors from the last 30 days are a remarketing list, except in special ad category campaigns.'], ['Benchmarks are national', 'The CPC and conversion defaults are LocaliQ national averages; DFW July auctions run hotter.'], ['Default client', 'The desk opens with the heatmap\'s benchmark client so the output is realistic; nothing is sent anywhere.'], ['Paused exports', 'Every exported object is paused so nothing spends before a person reviews it.']]);
    // ---------- exports ----------
    const camp = (p, lang) => `DFW_${P.line.toUpperCase()}_${p.toUpperCase()}_${lang.toUpperCase()}_${P.start.replace(/-/g, '')}`;
    const endDate = () => { const s = new Date(P.start + 'T12:00:00'); const e = new Date(s.getTime() + P.weeks * 7 * 864e5); return e.toISOString().slice(0, 10); };
    const GH = ['Campaign', 'Campaign Type', 'Networks', 'Budget', 'Budget type', 'Languages', 'Bid Strategy Type', 'Start Date', 'End Date', 'Campaign Status', 'Location', 'ID', 'Bid Modifier', 'Criterion Type', 'Status', 'Ad Group', 'Ad Group Type', 'Max CPC', 'Ad Group Status', 'Keyword', 'Ad type'].concat([...Array(15)].map((_, i) => 'Headline ' + (i + 1))).concat([...Array(4)].map((_, i) => 'Description ' + (i + 1))).concat(['Path 1', 'Path 2', 'Final URL', 'Callout text', 'Sitelink text', 'Description line 1', 'Description line 2', 'Sitelink final URL', 'Header', 'Snippet values', 'Phone number', 'Country code']);
    function searchRows(p) {
      const rows = []; const langs = ['en'].concat(MKT.some(m => m.es) ? ['es'] : []); const spend = FC[p].spend;
      langs.forEach(lang => { const ms = lang === 'es' ? MKT.filter(m => m.es) : MKT; if (!ms.length) return; const c = camp(p, lang) + (p === 'microsoft' ? '_MS' : ''); const monthly = lang === 'es' ? spend * 0.3 : spend * (langs.length > 1 ? 0.7 : 1);
        rows.push({ 'Campaign': c, 'Campaign Type': 'Search', 'Networks': 'Google search', 'Budget': (monthly / 30.4).toFixed(2), 'Budget type': 'Daily', 'Languages': lang === 'es' ? 'Spanish' : 'English', 'Bid Strategy Type': 'Maximize conversions', 'Start Date': P.start, 'End Date': endDate(), 'Campaign Status': 'Paused' });
        ms.forEach(m => rows.push({ 'Campaign': c, 'Location': `${m.z.zip}, Texas, United States`, 'ID': p === 'google' ? (m.z.gid || '') : '', 'Bid Modifier': (bidOf(m.z) >= 0 ? '+' : '') + bidOf(m.z) + '%', 'Criterion Type': 'Location', 'Status': 'Enabled' }));
        (P.line === 'recruit' ? NEG_RECRUIT : NEG_CUSTOMER).forEach(k => rows.push({ 'Campaign': c, 'Keyword': k, 'Criterion Type': 'Negative Phrase', 'Status': 'Enabled' }));
        (lang === 'es' ? ['Técnicos con Licencia', 'Precio Claro', 'Servicio Local'] : ['Licensed Texas Contractor', 'Upfront Pricing', 'Local Crews', 'Matched Systems']).forEach(t => rows.push({ 'Campaign': c, 'Callout text': houseClean(t), 'Status': 'Enabled' }));
        const angs = [...new Set(ms.flatMap(m => m.angles.map(a => a.id)))].map(id => ANG[id]).filter(Boolean);
        angs.slice(0, 4).forEach(a => rows.push({ 'Campaign': c, 'Sitelink text': a.short.slice(0, 25), 'Description line 1': lang === 'es' ? 'Técnicos con licencia' : 'Licensed Texas crews', 'Description line 2': lang === 'es' ? 'Precio por escrito' : 'Written quotes', 'Sitelink final URL': P.url.replace(/\/$/, '') + a.path, 'Status': 'Enabled' }));
        rows.push({ 'Campaign': c, 'Header': lang === 'es' ? 'Servicios' : 'Services', 'Snippet values': angs.slice(0, 8).map(a => a.short).join('; '), 'Status': 'Enabled' });
        if (P.phone) rows.push({ 'Campaign': c, 'Phone number': phoneFmt(P.phone), 'Country code': 'US', 'Status': 'Enabled' });
        const z0 = ms[0].z; const maxcpc = (P.asm[p].cost * (z0.cpc_rel || 1)).toFixed(2);
        angs.forEach(a => { const src = a; const groups = [[a.short + ' Core', src.kw.filter(k => !k.includes('{city}')), ['Exact', 'Phrase']], [a.short + ' Questions', src.kwq, ['Phrase']], [a.short + ' Local', src.kw.filter(k => k.includes('{city}')).flatMap(k => [...new Set(ms.map(m => m.z.city))].slice(0, 10).map(cc => k.replace('{city}', cc.toLowerCase()))), ['Phrase']]];
          groups.forEach(([ag, kws, mts]) => { if (!kws.length) return; rows.push({ 'Campaign': c, 'Ad Group': ag, 'Ad Group Type': 'Standard', 'Max CPC': maxcpc, 'Ad Group Status': 'Enabled' }); const seen = new Set(); kws.forEach(k => { const kk = k.toLowerCase().trim(); if (seen.has(kk)) return; seen.add(kk); mts.forEach(mt => rows.push({ 'Campaign': c, 'Ad Group': ag, 'Keyword': kk, 'Criterion Type': mt, 'Status': 'Enabled' })); });
            const r = rsaFor(a, ag.endsWith('Local') ? z0 : null, lang); const o = { 'Campaign': c, 'Ad Group': ag, 'Ad type': 'Responsive search ad', 'Path 1': a.path.split('/')[1].slice(0, 15), 'Path 2': (z0.city || '').toLowerCase().replace(/[^a-z]/g, '').slice(0, 15), 'Final URL': P.url.replace(/\/$/, '') + a.path + `?utm_source=${p}&utm_medium=cpc&utm_campaign=${encodeURIComponent(c)}&utm_content=${a.id}`, 'Status': 'Paused' }; r.h.forEach((h, i) => o['Headline ' + (i + 1)] = h); r.d.forEach((d, i) => o['Description ' + (i + 1)] = d); rows.push(o); }); }); });
      return rows;
    }
    $('#dkG', root).onclick = () => saveFile(`google-ads-editor_${P.line}_${P.start}.csv`, toCSV(GH, searchRows('google')));
    $('#dkMs', root).onclick = () => saveFile(`microsoft-ads_${P.line}_${P.start}.csv`, toCSV(GH, searchRows('microsoft')));
    $('#dkL', root).onclick = () => { const angs = [...new Set(MKT.flatMap(m => m.angles.map(a => a.id)))].map(id => ANG[id]); const rows = [['Business name', P.brand], ['TDLR license', P.lic], ['Phone', phoneFmt(P.phone)], ['Weekly budget', Math.round(FC.lsa.spend / 4.345)], ['Job types', [...new Set(angs.flatMap(a => a.lsa))].join('; ')], ['Service ZIPs', MKT.map(m => m.z.zip).join(' ')], ['Spanish', MKT.some(m => m.es) ? 'on' : 'off'], ['Documents to upload', 'TDLR license, certificate of general liability insurance, business registration'], ['Hours', 'set to the hours actually staffed']]; saveFile(`lsa-build-sheet_${P.start}.csv`, toCSV(['Field', 'Value'], rows)); };
    const socialRows = p => { const rows = []; const angs = [...new Set(MKT.flatMap(m => m.angles.map(a => a.id)))].map(id => ANG[id]).filter(Boolean); angs.forEach(a => ['en'].concat(MKT.some(m => m.es) ? ['es'] : []).forEach(lang => { const ms = lang === 'es' ? MKT.filter(m => m.es) : MKT; const ctx = ctxFor(ms[0] && ms[0].z, lang); const fin = /financ/i.test(a.meta.p) || a.id === 'financing'; const body = (fillCopy(lang === 'es' && a.es ? a.es.d[0] : a.meta.p, ctx) || '') + ' Lic ' + P.lic + '.'; rows.push({ 'Campaign Name': camp(p, lang) + (fin ? '_SAC' : ''), 'Campaign Objective': 'Leads', 'Special Ad Categories': fin && p === 'meta' ? 'Financial products and services' : '', 'Ad Set Name': a.short + ' ' + lang.toUpperCase(), 'Zip': fin && p === 'meta' ? '' : ms.map(m => 'US:' + m.z.zip).join(', '), 'Radius': fin && p === 'meta' ? '15 mi around ' + (P.city || 'Dallas') + ', TX' : '', 'Ad Name': a.short + ' ' + lang.toUpperCase(), 'Title': fillCopy(a.meta.h, ctx, 40) || a.short, 'Body': body, 'Link': P.url.replace(/\/$/, '') + a.path, 'Call to Action': 'Get Quote', 'Status': 'Paused' }); })); return rows; };
    $('#dkM', root).onclick = () => { const R = socialRows('meta'); saveFile(`meta-ads-import_${P.start}.csv`, toCSV(Object.keys(R[0] || { 'Campaign Name': '' }), R)); };
    $('#dkDg', root).onclick = () => { const R = socialRows('dg'); saveFile(`demand-gen-build-sheet_${P.start}.csv`, toCSV(Object.keys(R[0] || { 'Campaign Name': '' }), R)); };
    $('#dkNd', root).onclick = () => { const R = socialRows('nextdoor'); saveFile(`nextdoor-build-sheet_${P.start}.csv`, toCSV(Object.keys(R[0] || { 'Campaign Name': '' }), R)); };
    $('#dkY', root).onclick = () => { const R = socialRows('yelp'); saveFile(`yelp-build-sheet_${P.start}.csv`, toCSV(Object.keys(R[0] || { 'Campaign Name': '' }), R)); };
    $('#dkLi', root).onclick = () => { const ctx = ctxFor(MKT[0] && MKT[0].z, 'en'); saveFile(`linkedin-recruiting_${P.start}.csv`, toCSV(['Campaign Group', 'Campaign', 'Objective', 'Locations', 'Job titles', 'Intro text', 'Headline', 'Status'], [['DFW Recruiting', camp('linkedin', 'en'), 'Job applicants', 'Dallas Fort Worth Area', 'HVAC Technician; HVAC Installer; Service Technician; Refrigeration Technician', fillCopy(ANG.recruit.meta.p, ctx) || '', fillCopy(ANG.recruit.h[0], ctx) || '', 'Paused']])); };
    $('#dkCr', root).onclick = () => { const rows = []; [...new Set(MKT.flatMap(m => m.angles.map(a => a.id)))].map(id => ANG[id]).forEach(a => ['en', 'es'].forEach(lang => { const r = rsaFor(a, MKT[0] && MKT[0].z, lang); r.h.forEach(h => rows.push([a.short, lang, 'headline', h, h.length])); r.d.forEach(d => rows.push([a.short, lang, 'description', d, d.length])); })); saveFile(`creative-library_${P.start}.csv`, toCSV(['angle', 'language', 'type', 'text', 'chars'], rows, 'House style: no hyphens or dashes. Every description set includes the TDLR license number.')); };
    $('#dkKw', root).onclick = () => { const rows = []; [...new Set(MKT.flatMap(m => m.angles.map(a => a.id)))].map(id => ANG[id]).forEach(a => { a.kw.filter(k => !k.includes('{city}')).forEach(k => { rows.push([a.short, k, 'Exact']); rows.push([a.short, k, 'Phrase']); }); a.kwq.forEach(k => rows.push([a.short, k, 'Phrase'])); }); NEG_CUSTOMER.forEach(k => rows.push(['Negatives', k, 'Negative Phrase'])); saveFile('keyword-desk.csv', toCSV(['ad_group', 'keyword', 'match_type'], rows, 'No volumes: price in Keyword Planner.')); };
    $('#dkPlanX', root).onclick = () => saveFile(`campaign-plan_${P.line}_${P.start}.csv`, toCSV(['zip', 'city', 'county', 'tier', 'bid_modifier', 'monthly_usd', 'spanish', 'angles'], MKT.map(m => [m.z.zip, m.z.city, m.z.cty, m.z.tier, bidOf(m.z), Math.round(m.spend), m.es ? 'yes' : '', m.angles.map(a => a.short).join('; ')])));
    $('#dkSave', root).onclick = () => saveFile('campaign-desk-plan.json', JSON.stringify(P, null, 1));
    $('#dkLoad', root).onclick = () => { const i = el('input', { type: 'file', accept: '.json,application/json' }); i.onchange = () => { const f = i.files[0]; if (!f) return; const rd = new FileReader(); rd.onload = () => { try { const o = JSON.parse(rd.result); P = Object.assign(defaults(), o); syncUI(); asmUI(); rebuild(); toast('Plan loaded'); } catch (e) { toast('That file is not a desk plan'); } }; rd.readAsText(f); }; i.click(); };
    // ---------- wiring ----------
    const bind = (id, k, num, ev) => $('#' + id, root).addEventListener(ev || 'change', e => { P[k] = num ? +e.target.value : e.target.value; if (k === 'line') { P.mix = { ...MIX0[P.line] }; P.angles = LINES[P.line].angles.slice(); syncUI(); } if (k === 'alpha') $('#dkAlphaV', root).textContent = D(P.alpha, 1); rebuild(); });
    bind('dkLine', 'line'); bind('dkBud', 'budget', 1); bind('dkStart', 'start'); bind('dkWeeks', 'weeks', 1); bind('dkScope', 'scope'); bind('dkN', 'n', 1); bind('dkMin', 'minhh', 1); bind('dkAlpha', 'alpha', 1, 'input'); bind('dkSpan', 'spanTh', 1); bind('dkBrand', 'brand'); bind('dkLic', 'lic'); bind('dkPhone', 'phone'); bind('dkUrl', 'url'); bind('dkCity', 'city'); bind('dkPay', 'pay'); bind('dkBook', 'bookRate', 1); bind('dkVal', 'jobVal', 1);
    $('#dkCounties', root).onchange = e => { P.counties = [...e.target.selectedOptions].map(o => o.value); if (P.counties.length) P.scope = 'county'; syncUI(); rebuild(); };
    $('#dkPicks', root).onchange = e => { P.picks = e.target.value.split(/[\s,;]+/).filter(z => ZI[z]); P.scope = 'picks'; syncUI(); rebuild(); };
    $('#dkMixReset', root).onclick = () => { P.mix = { ...MIX0[P.line] }; rebuild(); };
    $$('#dkTabs button', root).forEach(b => b.onclick = () => { $$('#dkTabs button', root).forEach(x => x.setAttribute('aria-pressed', String(x === b))); UI.tab = b.dataset.v; tab(); });
    $$('#dkPTabs button', root).forEach(b => b.onclick = () => { $$('#dkPTabs button', root).forEach(x => x.setAttribute('aria-pressed', String(x === b))); UI.plat = b.dataset.v; builder(); });
    $('#dkAng', root).onchange = e => { UI.angle = e.target.value; builder(); }; $('#dkPrev', root).onchange = builder; wireSeg($('#dkLang', root), v => { UI.lang = v; builder(); }); $('#dkKwA', root).onchange = kwDesk;
    this.receive = p => { if (!p) return; if (p.zips && p.zips.length) { P.scope = 'picks'; P.picks = p.zips.filter(z => ZI[z]); P.bids = p.bids && typeof p.bids === 'object' ? p.bids : null; } if (p.line && LINES[p.line]) { P.line = p.line; P.mix = { ...MIX0[P.line] }; P.angles = LINES[P.line].angles.slice(); } syncUI(); rebuild(); toast(`${P.picks.length} ZIPs received`); };
    this.plan = () => Object.assign(JSON.parse(JSON.stringify(P)), { zips: MKT.map(m => m.z.zip) });
    this.feed = () => { const out = []; [...new Set(MKT.flatMap(m => m.angles.map(a => a.id)))].map(id => ANG[id]).forEach(a => ['en'].concat(MKT.some(m => m.es) ? ['es'] : []).forEach(lang => { const r = rsaFor(a, MKT[0] && MKT[0].z, lang); out.push({ label: `Google RSA · ${a.short} · ${lang}`, text: r.h.concat(r.d).join('\n'), plat: 'google' }); const ctx = ctxFor(MKT[0] && MKT[0].z, lang); out.push({ label: `Meta · ${a.short} · ${lang}`, text: (fillCopy(lang === 'es' && a.es ? a.es.d[0] : a.meta.p, ctx) || '') + ' Lic ' + P.lic + '.', plat: 'meta' }); })); return out; };
    BUS.on('theme', () => rebuild());
    syncUI(); asmUI(); rebuild();
  }
});
