/* ==== m12_lines ==== */
"use strict";
/* ============================ Module 12: Service Lines ============================ */
registerModule({
  key: 'lines', num: '12', title: 'Service Lines', desc: 'Fourteen HVAC service lines resolved to the ZIP: pools, jobs, tickets, seasons, levers, pressure and bid modifiers',
  mount(root) {
    const st = { line: 'replace', layer: 'pri', county: '', n: 40, sel: null, month: -1, budget: SLM.A.budget, alpha: SLM.A.alpha, chart: ['repair', 'replace', 'heat', 'maint'] };
    const L = () => SLM.LI[st.line]; const A = () => SLM.A;
    const scoped = () => ZR.filter(z => !st.county || z.fips === st.county);
    const rowsFor = id => scoped().map(z => SLM.SLZ[z.zip][id]).sort((a, b) => b.pri - a.pri);
    const MO = SLM.MONTHS; const C = SLM.CLIM; const NM = SLM.NORM;
    const PL = { pri: { l: 'Campaign priority (percentile)', ramp: 'ember', f: v => D(v, 0), g: 'C', k: r => r.pri, note: 'Gross profit pool per relative click cost, discounted by competitor paid pressure for this line. Percentile across the buyable ZIPs.' }, jobs: { l: 'Jobs a year', ramp: 'ember', f: v => N(v), g: 'B', k: r => r.jobs, note: 'Expected jobs of this kind in twelve months, from the pool and a stated rate.' }, gp: { l: 'Gross profit pool ($ a year)', ramp: 'ember', f: v => MM(v), g: 'C', k: r => r.gp, note: 'Jobs times ticket times the line\'s gross margin.' }, pool: { l: 'Addressable pool (units)', ramp: 'teal', f: v => N(v), g: 'A', k: r => r.pool, note: 'The homes or systems that can buy this line.' }, press: { l: 'Competitor paid pressure (percentile)', ramp: 'blue', f: v => D(v, 0), g: 'C', k: r => r.presspct, note: 'Mapped competitors within 20 km that sell this line, weighted by distance, paid search, tracking numbers, reviews and any ads logged in Competitor Watch.' }, bid: { l: 'Starting bid modifier (%)', ramp: 'ember', f: v => S(v, 0) + '%', g: 'C', k: r => r.bid, note: 'Priority bands mapped to Google location bid adjustments: +45, +30, +15, 0, minus 20, minus 40.' }, quiet: { l: 'Quiet auction (yes or no)', cat: true, g: 'C', k: r => r.quiet ? 1 : 0, note: 'Top 40% of gross profit pool with paid pressure in the bottom 45%.' }, lev_es: { l: 'Suggested Spanish budget share (%)', ramp: 'teal', f: v => P(v, 0), g: 'B', k: r => SLM.LEV[r.z.zip].es, note: 'Limited English Spanish speaking households times 1.5 plus a quarter of Spanish speaking households.' }, lev_fin: { l: 'Payment led score', ramp: 'teal', f: v => D(v, 0), g: 'C', k: r => SLM.LEV[r.z.zip].fin, note: 'Above 60 lead with monthly payment creative (Meta special ad category); below 40 lead with the system.' }, lev_cash: { l: 'Cash and premium score', ramp: 'teal', f: v => D(v, 0), g: 'C', k: r => SLM.LEV[r.z.zip].cash, note: 'High income share, half million dollar homes, owners 65 and over.' }, lev_dom: { l: 'Dominant audience lever', cat: true, g: 'C', k: r => SLM.LEV[r.z.zip].dominant, note: 'The lever whose standardized score is highest in the ZIP.' } };
    const LEVN = { fin: 'Payment led', cash: 'Cash and premium', es: 'Spanish build', senior: 'Senior households', newowner: 'New owners', landlord: 'Rented single family', multisys: 'Multi system homes' };
    root.innerHTML = mastHTML({ eyebrow: 'Module 12 · Service Lines · fourteen lines, 263 ZIPs', title: 'Service Lines', dek: 'Module 05 says where an ad dollar reaches the most HVAC jobs. This module says which jobs: air conditioning repair, full replacements, the builder\'s first replacement, R22 changeouts, heating repair, furnaces, heat pumps, ductwork, maintenance plans, indoor air, ductless, hail, light commercial and rental homes. Each line gets its own pool, jobs a year, ticket, margin, season, channel fit, competitor pressure, priority and starting bid modifier in every ZIP, plus the audience levers the ZIP carries: Spanish build, payment led or cash, seniors, new owners, landlords, multi system homes.',
      meta: [`<b>${SLM.LINES.length}</b> service lines · <b>${SLM.BASE.length}</b> additive, <b>${SLM.LINES.length - SLM.BASE.length}</b> lenses on replacement`, `<b>${MM(sum(SLM.BASE.map(l => SLM.AGG[l.id].gp)))}</b> gross profit pool a year (modeled)`, `<b>${N(ZR.length)}</b> ZIPs × ${SLM.LINES.length} lines = <b>${N(ZR.length * SLM.LINES.length)}</b> campaign cells`, '<b>No keyword tool queried</b> · benchmarks grade D, editable'],
      bar: 'Service Lines', barsub: 'Pools, jobs, seasons, economics, levers, pressure', actions: [{ id: 'l12Long', label: '↓ Line × ZIP CSV', title: 'One row per ZIP per line' }, { id: 'l12Wide', label: '↓ Priority matrix' }, { id: 'l12G', label: '↓ Google locations', title: 'Location bid modifiers for the selected line' }, { id: 'l12M', label: '↓ Meta ZIPs', title: 'Ad set ZIP list for the selected line' }, { id: 'l12Cal', label: '↓ Flight calendar' }, { id: 'l12Asm', label: '↓ Assumptions' }, { id: 'l12Desk', label: 'Campaign Desk ↗', title: 'Send the selected line\'s top ZIPs and bid modifiers to the desk' }, { id: 'l12Watch', label: 'Competitor Watch ↗' }] }) +
      `<div class="wrap">
      ${callout('', 'Read this first: what a service line is here, and what the numbers are', `A <b>line</b> is a campaign you would actually build: its own keywords, creative, landing page, budget and season. The atlas already knows the installed base by age, fuel, ownership and hail exposure, so each line's <b>pool</b> is a real count (Census and the RECS calibrated renewal model, grades A and B). The <b>jobs a year</b> apply a stated rate to that pool: fitted lifetimes for replacements and furnaces (grade B), the atlas's age based call rate for repairs (grade D), and plain stated rates for maintenance take up, duct, indoor air, ductless, hail, commercial and rental work (grade D, editable below). <b>Tickets</b> come from ${N(DATA.tickets.n)} Irving replacement permits where a replacement is involved (median ${M$(SLM.TICK_MED)}, grade B) and from stated figures elsewhere (grade D). <b>Seasons</b> come from ${N(DATA.ts['Fort Worth'].series.length)} months of Fort Worth permits and the NWS degree day normals (grades B and A), and from published calendars for pollen, hail and tune ups (grade C). <b>Pressure</b> counts the mapped competitors that sell each line near each ZIP, and rises when Competitor Watch logs their ads. Three lines are <b>lenses</b> on replacement (builder first, R22, heat pump): they rank ZIPs for targeting but their jobs are already inside the replacement line, so the portfolio table allocates only across the eleven additive lines.`)}
      <div class="kpis" id="l12Kpis"></div>
      <div class="card mt"><div class="card-b" style="display:flex;flex-direction:column;gap:12px">
        <div><div class="fl" style="margin-bottom:6px">Service line</div><div class="chips" id="l12Lines"></div></div>
        <div style="display:flex;gap:12px;flex-wrap:wrap;align-items:flex-end">
          <div class="ctl" style="flex:1 1 260px"><label class="fl" for="l12Layer">Map layer</label><select id="l12Layer">${Object.entries(PL).map(([k, o]) => `<option value="${k}">${esc(o.l)}</option>`).join('')}</select></div>
          <div class="ctl"><label class="fl" for="l12Cty">County</label><select id="l12Cty"><option value="">All 12 counties</option>${CO.map(c => `<option value="${c.fips}">${c.name}</option>`).join('')}</select></div>
          <div class="ctl"><label class="fl" for="l12N">ZIPs in the buy</label><input type="number" id="l12N" value="40" min="5" max="263" style="width:90px"></div>
          <div class="ctl"><label class="fl" for="l12Find">Find a ZIP or city</label><input type="search" id="l12Find" placeholder="75150 or Mesquite" autocomplete="off"></div>
          <label class="chk"><input type="checkbox" id="l12Comp"> competitors selling this line</label>
        </div></div></div>
      <div class="grid2">
        <div class="stack">
          <div class="card mapcard"><div id="l12Map"></div><div class="legend" id="l12Leg"></div></div>
          <div class="card"><div class="card-h"><h3>Ranked ZIPs: <span id="l12TblN"></span></h3><p>Priority first. Click a row to open the ZIP's campaign card; the top ZIPs in the buy are what the exports and the desk receive.</p></div><div class="tscroll" id="l12Tbl"></div></div>
        </div>
        <div class="card"><div class="card-h" style="display:flex;justify-content:space-between;gap:10px;align-items:flex-start"><div><h3 id="l12BName"></h3><p id="l12BSub"></p></div><span class="pill" id="l12BPill"></span></div><div class="card-b" id="l12Brief"></div></div>
      </div>
      <div class="split">
        <div class="card"><div class="card-h"><h3 id="l12ZName">ZIP campaign card</h3><p id="l12ZSub">Click a ZIP on the map or in the ranking</p></div><div class="card-b" id="l12Zip"></div></div>
        <div class="card"><div class="card-h"><h3>Unit economics: <span id="l12EName"></span></h3><p>Edit the line's assumptions; the whole module recomputes and the values persist in this browser. Grade D unless noted.</p></div><div class="card-b" id="l12Econ"></div></div>
      </div>
      ${card('The year, line by line', 'Season indices with mean 100. Toggle lines. The permit line is what the city of Fort Worth actually issued, month by month, 2012 to 2026; the others are degree days, freezes, hail, pollen and the tune up calendar.', '<div class="chips" id="l12ChartChips" style="margin-bottom:10px"></div><div id="l12Season"></div><p class="chartnote" id="l12SeasonN"></p><div class="dsec">Calendar: every line by month</div><div id="l12CalTbl"></div>', 'mt')}
      <div class="split">
        ${card('Weather triggers: thirty seasons of climatology', `Monthly odds from the ${C.years} seasons ${1996} to ${2025} in the atlas weather file (DFW Airport): the chance of at least one 100°F or 95°F day, the average count, the chance of a hard freeze, and the month the first 100°F day arrived.`, '<div class="tscroll short" id="l12Trig"></div><p class="chartnote" id="l12TrigN"></p>')}
        ${card('When to open and close each flight', 'Heavy months (season index 110 or more), light months (75 or less) and the weather rules that move budget inside the month.', '<div id="l12Rules"></div>')}
      </div>
      ${card('Portfolio: where a month of media should go', 'Eleven additive lines compete for one budget. Each line\'s weight is its gross profit pool in scope (pipeline included), times its season index for the month, times gross profit per lead dollar, raised to the concentration power: 1 spends in proportion to value, below 1 spreads the buy across lines, above 1 concentrates it. Leads and jobs follow the blended cost per lead below.', `<div class="controls" style="margin-top:0"><div class="ctl"><label class="fl" for="l12Bud">Monthly media ($)</label><input type="number" id="l12Bud" min="1000" step="1000" style="width:120px"></div><div class="ctl"><label class="fl" for="l12Mo">Month</label><select id="l12Mo"><option value="-1">Annual average</option>${MO.map((m, i) => `<option value="${i}">${m}</option>`).join('')}</select></div><div class="ctl"><label class="fl" for="l12Alpha">Concentration α <span id="l12AlphaV"></span></label><input type="range" id="l12Alpha" min="0.5" max="2.5" step="0.1"></div><div class="ctl"><label class="fl" for="l12Cpc">Account average CPC ($)</label><input type="number" id="l12Cpc" min="1" step="0.25" style="width:90px"></div><button class="btn sec sm" id="l12Reset">Reset every assumption</button></div><div class="tscroll" id="l12Port" style="margin-top:12px"></div><div class="dsec">Twelve months of suggested media by line</div><div id="l12PortChart"></div><p class="chartnote" id="l12PortN"></p>`, 'mt')}
      <div class="split">
        ${card('Audience and creative levers', 'Seven levers computed for every ZIP from Census shares. A lever changes the creative, the language build, the platform mix or the call to action; it does not change who is allowed to be reached.', '<div id="l12Lev"></div>')}
        ${card('Competitive pressure by line', 'How many of the 241 mapped competitors sell each line, how many of those showed paid search in Ahrefs (August 2026), and how many ZIPs are contested or quiet for the line.', '<div class="tscroll short" id="l12Press"></div><p class="mini" style="margin-top:8px">Pressure rises as observations are logged in Competitor Watch; the module recomputes on every save.</p>')}
      </div>
      ${card('Dayparting and device templates', 'Starting bid adjustments by day and hour block for the selected line, and the mobile share to expect. Grade C templates from home services patterns; replace them with the account\'s hour of day report after thirty days.', '<div id="l12Day"></div>', 'mt')}
      ${card('How the model is built', 'Eight steps, each a real count times a stated rate or a published season.', '<ol class="meth" id="l12Meth"></ol>', 'mt')}
      <div class="split">${card('Judgment calls', 'Nine places where the model had to choose.', '<div id="l12Judg"></div>')}${card('Caveats and gaps', '', '<div id="l12Cav"></div>')}</div>
      ${card('Source register', '', '<div id="l12Src"></div>', 'mt')}
      <div class="foot">DFW Thermal Debt Atlas, module 12. Service line pools are measured; job rates, tickets and benchmarks are stated where no measurement exists, graded, and editable. Replace them with the account's own cost per booked job by line after sixty days.</div></div>`;
    /* ---------- map ---------- */
    const map = new ZipMap($('#l12Map', root), { onSelect: zip => { st.sel = st.sel === zip ? null : zip; render(); }, onHover: (zip, e) => { const z = ZI[zip]; const r = SLM.SLZ[zip] && SLM.SLZ[zip][st.line]; if (!z || !r) return; const Lv = SLM.LEV[zip]; showTip(`<div class="tt">${zip} · ${esc(z.city)}</div><div class="ts">${esc(L().short)} · priority ${D(r.pri, 0)} · bid ${S(r.bid, 0)}%</div>${tipRow('Jobs a year', N(r.jobs))}${tipRow('Gross profit pool', MM(r.gp))}${tipRow('Paid pressure', D(r.presspct, 0))}${tipRow('Spanish share', P(Lv.es, 0))}${tipRow('Top line here', esc(SLM.lineName(z.sl_top)))}<div class="tf">${r.quiet ? 'Quiet auction · ' : ''}Click for the campaign card</div>`, e); }, onPin: id => goModule('watch', { comp: +id }), onPinHover: (id, e) => { const l = COMP[+id]; showTip(`<div class="tt">${esc(l.name)}</div><div class="ts">${esc(l.city)} · ${l.rating || '—'}★ · ${N(l.reviews)} reviews${(l.paid_kw || 0) > 0 ? ' · paid search' : ''}</div><div class="tf">Click to open in Competitor Watch</div>`, e); } });
    const QC = () => [cssv('--sunk-2'), cssv('--s3')];
    const LEVC = () => ({ fin: cssv('--s2'), cash: cssv('--s7'), es: cssv('--s4'), senior: cssv('--s5'), newowner: cssv('--s3'), landlord: cssv('--s1'), multisys: cssv('--s8') });
    function drawMap() {
      const o = PL[st.layer]; const rows = ZR.map(z => SLM.SLZ[z.zip][st.line]);
      if (st.layer === 'quiet') { const q = QC(); map.fill(zip => { const r = SLM.SLZ[zip]; return r ? q[r[st.line].quiet ? 1 : 0] : null; }); $('#l12Leg', root).innerHTML = `<div class="catleg"><span><i style="background:${q[1]}"></i>Quiet auction (${rows.filter(r => r.quiet).length})</span><span><i style="background:${q[0]}"></i>Other</span></div><div class="dn">${G(o.g)} ${esc(o.note)}</div>`; }
      else if (st.layer === 'lev_dom') { const c = LEVC(); map.fill(zip => SLM.LEV[zip] ? c[SLM.LEV[zip].dominant] : null); $('#l12Leg', root).innerHTML = `<div class="catleg">${Object.keys(LEVN).map(k => `<span><i style="background:${c[k]}"></i>${LEVN[k]} (${ZR.filter(z => SLM.LEV[z.zip].dominant === k).length})</span>`).join('')}</div><div class="dn">${G(o.g)} ${esc(o.note)}</div>`; }
      else { const vals = rows.map(o.k); const sc = qScale(vals, o.ramp, 1); map.fill(zip => { const r = SLM.SLZ[zip]; return r ? sc.f(o.k(r[st.line])) : null; }); const v = vals.filter(isN); $('#l12Leg', root).innerHTML = legendHTML({ title: `${L().short}: ${o.l}`, R: sc.R, lo: o.f(Math.min(...v)), hi: o.f(Math.max(...v)), note: `Eight quantile classes across ${N(ZR.length)} ZIPs. ${G(o.g)} ${esc(o.note)}` }); }
      map.dim(st.county ? new Set(Z.filter(z => z.fips === st.county).map(z => z.zip)) : null); map.select(st.sel);
      const svc = L().svc.map(s => s.toLowerCase());
      map.pins($('#l12Comp', root).checked ? COMP.map((l, i) => ({ l, i })).filter(x => x.l.tier !== 'bench' && (x.l.services || []).some(s => svc.includes(s.toLowerCase()))).map(({ l, i }) => ({ id: i, lat: l.lat, lon: l.lon, r: 2.4 + Math.log10((l.reviews || 0) + 1) * 1.1, fill: (l.paid_kw || 0) > 0 ? cssv('--critical') : cssv('--ink-3'), op: .85 })) : []);
    }
    /* ---------- chips ---------- */
    function chips() {
      $('#l12Lines', root).innerHTML = SLM.LINES.map(l => `<span class="chip ${l.kind === 'lens' ? 'lens' : ''}" data-l="${l.id}" aria-pressed="${l.id === st.line}" title="${esc(l.name)}${l.kind === 'lens' ? ' (lens on replacement)' : ''}">${l.short}${l.kind === 'lens' ? ' ◌' : ''}</span>`).join('');
      $$('#l12Lines .chip', root).forEach(c => c.onclick = () => { st.line = c.dataset.l; render(); });
      $('#l12ChartChips', root).innerHTML = SLM.LINES.map(l => `<span class="chip" data-l="${l.id}" aria-pressed="${st.chart.includes(l.id)}">${l.short}</span>`).join('');
      $$('#l12ChartChips .chip', root).forEach(c => c.onclick = () => { const id = c.dataset.l; st.chart = st.chart.includes(id) ? st.chart.filter(x => x !== id) : st.chart.concat(id); chips(); season(); });
    }
    /* ---------- KPIs ---------- */
    function kpis() {
      const base = SLM.BASE.map(l => ({ l, a: SLM.AGG[l.id] })).sort((a, b) => b.a.gp - a.a.gp);
      const seasonal = SLM.LINES.filter(l => l.id !== 'hail').map(l => ({ l, r: Math.max(...l.months) / Math.max(1, Math.min(...l.months)) })).sort((a, b) => b.r - a.r)[0];
      const bestC = {}; ZR.forEach(z => bestC[z.sl_best] = (bestC[z.sl_best] || 0) + 1); const bestTop = Object.entries(bestC).sort((a, b) => b[1] - a[1]); const quietZ = ZR.filter(z => z.sl_quiet >= 3).length; const esZ = ZR.filter(z => SLM.LEV[z.zip].es >= 30).length;
      $('#l12Kpis', root).innerHTML = kpiHTML([
        { l: 'Gross profit pool', g: 'C', v: MM(sum(base.map(b => b.a.gp))), d: 'eleven additive lines, a year, metro' },
        { l: 'Largest line', g: 'C', v: esc(base[0].l.short), d: `${MM(base[0].a.gp)} · ${N(base[0].a.jobs)} jobs a year` },
        { l: 'Second line', g: 'C', v: esc(base[1].l.short), d: `${MM(base[1].a.gp)} · ${N(base[1].a.jobs)} jobs a year` },
        { l: 'Most seasonal', g: 'B', v: esc(seasonal.l.short), d: `peak month ${D(seasonal.r, 1)}× the trough; hail is event driven and sits outside this comparison` },
        { l: 'Comparative advantage', g: 'C', v: esc(SLM.lineName(bestTop[0][0])), d: `the line in which the most ZIPs rank highest against the metro: ${bestTop.slice(0, 3).map(([k, v]) => `${SLM.lineName(k)} ${v}`).join(', ')}` },
        { l: 'Quiet auction ZIPs', g: 'C', v: N(quietZ), d: 'three or more lines with high pool and low paid pressure' },
        { l: 'Spanish first ZIPs', g: 'B', v: N(esZ), d: 'suggested Spanish share of 30% or more' },
      ]);
    }
    /* ---------- brief ---------- */
    const spark = (months, w, h) => { w = w || 240; h = h || 44; const mxv = Math.max(...months), bw = w / 12; return `<svg viewBox="0 0 ${w} ${h + 14}" width="100%" style="max-width:${w}px;display:block" aria-label="season by month">${months.map((v, i) => `<rect x="${(i * bw + 1).toFixed(1)}" y="${(h - v / mxv * h).toFixed(1)}" width="${(bw - 2).toFixed(1)}" height="${(v / mxv * h).toFixed(1)}" rx="1.5" fill="${v >= 110 ? cssv('--heat') : v <= 75 ? cssv('--cool') : cssv('--ink-3')}"><title>${MO[i]} ${D(v, 0)}</title></rect>`).join('')}${MO.map((m, i) => `<text x="${(i * bw + bw / 2).toFixed(1)}" y="${h + 11}" font-size="8.5" text-anchor="middle" fill="${cssv('--ink-3')}" font-family="${cssv('--sans')}">${m[0]}</text>`).join('')}</svg>`; };
    const fitBars = fit => `<div class="fitrow">${SLM.PLAT_FIT_KEYS.map(p => `<div class="fitc" title="${SLM.PLAT_LABEL[p]}: fit ${fit[p] || 0} of 3"><span>${SLM.PLAT_LABEL[p].replace('YouTube and Demand Gen', 'YouTube').replace('Local Services Ads', 'LSA').replace('Google Search', 'Search')}</span><i>${[1, 2, 3].map(k => `<b class="${(fit[p] || 0) >= k ? 'on' : ''}"></b>`).join('')}</i></div>`).join('')}</div>`;
    function brief() {
      const l = L(), a = SLM.AGG[l.id], rows = rowsFor(l.id), inScope = scoped().length; const sc = { pool: sum(rows.map(r => r.pool)), jobs: sum(rows.map(r => r.jobs)), rev: sum(rows.map(r => r.rev)), gp: sum(rows.map(r => r.gp)) };
      $('#l12BName', root).textContent = l.name; $('#l12BSub', root).textContent = l.intent; $('#l12BPill', root).textContent = l.kind === 'lens' ? 'Lens on replacement' : 'Additive line';
      const peak = l.months.map((v, i) => [v, i]).sort((a, b) => b[0] - a[0]); const heavy = l.months.map((v, i) => v >= 110 ? MO[i] : null).filter(Boolean), light = l.months.map((v, i) => v <= 75 ? MO[i] : null).filter(Boolean);
      $('#l12Brief', root).innerHTML = `<div class="dsec">Scope: ${st.county ? CNAME(st.county) + ' County' : 'metro'} · ${N(inScope)} ZIPs</div>
        <div class="rowl"><span>${esc(l.poolL)} ${G(l.g === 'D' ? 'D' : 'A/B')}</span><b>${N(sc.pool)}</b></div><div class="rowl"><span>${esc(l.jobsL)}</span><b>${N(sc.jobs)}</b></div><div class="rowl"><span>Average ticket</span><b>${M$(sc.rev / Math.max(1, sc.jobs))}</b></div><div class="rowl"><span>Revenue pool a year</span><b>${MM(sc.rev)}</b></div><div class="rowl"><span>Gross profit pool (${D(A().lines[l.id].margin, 0)}% margin)</span><b>${MM(sc.gp)}</b></div><div class="rowl"><span>Quiet auction ZIPs in scope</span><b>${N(rows.filter(r => r.quiet).length)}</b></div><div class="rowl"><span>Competitors selling this line · running paid search</span><b>${N(a.compN)} · ${N(a.compPaid)}</b></div>
        <div class="dsec">Season ${G(l.g)}</div>${spark(l.months)}<p class="mini">Peak ${MO[peak[0][1]]} (${D(peak[0][0], 0)}), trough ${MO[peak[11][1]]} (${D(peak[11][0], 0)}). Heavy: ${heavy.join(', ') || 'none'}. Light: ${light.join(', ') || 'none'}. ${esc(l.seasonSrc)}.</p>
        <div class="dsec">Channel fit</div>${fitBars(l.fit)}<p class="mini">Mobile share to expect: about ${l.mobile}%. Dayparts: ${l.dayparts} template (below).</p>
        <div class="dsec">Creative hooks</div><ul class="hooks">${l.hooks.map(h => `<li>${esc(h)}</li>`).join('')}</ul>
        <div class="dsec">Weather and calendar triggers</div><ul class="hooks">${l.triggers.map(h => `<li>${esc(h)}</li>`).join('')}</ul>
        <div class="dsec">Negatives beyond the customer list</div><div class="neg">${l.negs.map(n => `<code>${esc(n)}</code>`).join('')}</div>
        <div style="display:flex;gap:8px;margin-top:12px;flex-wrap:wrap"><button class="btn sm" id="l12BDesk">Build this line in the Campaign Desk</button><button class="btn sec sm" id="l12BWatch">Who is advertising it</button></div>`;
      $('#l12BDesk', root).onclick = () => toDesk(); $('#l12BWatch', root).onclick = () => goModule('watch', { line: l.id });
    }
    function toDesk() { const l = L(); const rows = rowsFor(l.id).slice(0, st.n); const bids = {}; rows.forEach(r => bids[r.z.zip] = r.bid); goModule('desk', { zips: rows.map(r => r.z.zip), line: LINES[l.desk] ? l.desk : 'replace', bids }); }
    /* ---------- table ---------- */
    function table() {
      const l = L(); const rows = rowsFor(l.id); $('#l12TblN', root).textContent = `${l.short}, ${st.county ? CNAME(st.county) + ' County' : 'metro'}`;
      dataTable($('#l12Tbl', root), [{ k: 'rank', h: '#', v: r => rows.indexOf(r) + 1 }, { k: 'zip', h: 'ZIP', l: 1, v: r => r.z.zip, f: v => `<b>${esc(v)}</b>` }, { k: 'city', h: 'City', l: 1, v: r => r.z.city }, { k: 'pri', h: 'Priority', f: v => D(v, 0) }, { k: 'jobs', h: 'Jobs/yr', f: v => N(v) }, { k: 'ticket', h: 'Ticket', f: v => M$(v) }, { k: 'gp', h: 'GP pool', f: v => MM(v) }, { k: 'presspct', h: 'Pressure', f: v => D(v, 0) }, { k: 'cost', h: 'Cost idx', f: v => D(v, 2) + '×' }, { k: 'bid', h: 'Bid', f: v => S(v, 0) + '%' }, { k: 'es', h: 'ES %', v: r => SLM.LEV[r.z.zip].es, f: v => D(v, 0) }, { k: 'lev', h: 'Levers', l: 1, v: r => SLM.LEV[r.z.zip].tags.filter(t => !/^Spanish/.test(t)).slice(0, 2).join(', ') }], rows, { sortKey: 'pri', id: r => r.z.zip, onClick: zip => { st.sel = zip; render(); }, rowClass: r => (r.z.zip === st.sel ? 'sel ' : '') + (r.quiet ? 'quiet' : ''), limit: 120 });
    }
    /* ---------- ZIP card ---------- */
    function zipCard() {
      const z = st.sel ? ZI[st.sel] : null; if (!z || !SLM.SLZ[z.zip]) { $('#l12ZName', root).textContent = 'ZIP campaign card'; $('#l12ZSub', root).textContent = 'Click a ZIP on the map or in the ranking'; $('#l12Zip', root).innerHTML = `<p class="mini">Every ZIP carries all ${SLM.LINES.length} lines with jobs, gross profit pool, pressure, priority and bid modifier, the audience levers, a suggested monthly budget and the competitors advertising nearby.</p>`; return; }
      const Lv = SLM.LEV[z.zip]; const rows = SLM.LINES.map(l => ({ l, r: SLM.SLZ[z.zip][l.id] })).sort((a, b) => b.r.gp - a.r.gp);
      const gpScope = sum(scoped().map(x => sum(SLM.BASE.map(l => SLM.SLZ[x.zip][l.id].gp)))) || 1; const gpZip = sum(SLM.BASE.map(l => SLM.SLZ[z.zip][l.id].gp)); const share = gpZip / gpScope; const zipBudget = st.budget * Math.pow(share, 1) * scoped().length / Math.max(1, st.n) ;
      const near = (SLM.NEAR[z.zip] || []).filter(x => x.d <= 8).sort((a, b) => a.d - b.d); const adv = near.filter(x => (x.c.l.paid_kw || 0) > 0 || SLM.adSignal(x.c.l));
      $('#l12ZName', root).textContent = `${z.zip} · ${z.city}`; $('#l12ZSub', root).innerHTML = `${esc(z.cty)} County · ${N(z.occ)} households · ${N(z.sys)} systems · Google criterion ID ${z.gid || 'by name'}`;
      $('#l12Zip', root).innerHTML = `<div class="dsec">Lines ranked by gross profit pool · best ranked line here: <b>${esc(SLM.lineName(z.sl_best))}</b> (${D(SLM.SLZ[z.zip][z.sl_best].pri, 0)}th percentile)</div><div class="xscroll"><table class="kwtab"><thead><tr><th class="l">Line</th><th>Jobs/yr</th><th>GP pool</th><th>Pressure</th><th>Priority</th><th>Bid</th></tr></thead><tbody>${rows.map(({ l, r }, i) => `<tr class="${l.id === st.line ? 'sel' : ''}"><td class="l">${i < 3 ? '<b>' : ''}${esc(l.short)}${l.kind === 'lens' ? ' ◌' : ''}${i < 3 ? '</b>' : ''}${r.quiet ? ' <span class="pill" style="font-size:9px;padding:0 5px">quiet</span>' : ''}</td><td>${N(r.jobs)}</td><td>${MM(r.gp)}</td><td>${D(r.presspct, 0)}</td><td>${D(r.pri, 0)}</td><td>${S(r.bid, 0)}%</td></tr>`).join('')}</tbody></table></div>
        <div class="dsec">Audience levers</div><div>${Lv.tags.length ? Lv.tags.map(t => `<span class="tag on">${esc(t)}</span>`).join('') : '<span class="mini">No lever stands out; the metro defaults apply.</span>'}</div>
        <div class="rowl" style="margin-top:6px"><span>Payment led score · cash and premium score</span><b>${Lv.fin} · ${Lv.cash}</b></div><div class="rowl"><span>Suggested Spanish share of the ZIP budget</span><b>${P(Lv.es, 0)}</b></div><div class="rowl"><span>Dominant lever</span><b>${LEVN[Lv.dominant]}</b></div>${Lv.permitgap != null ? `<div class="rowl"><span>Permit capture (observed over modeled replacements)</span><b>${P((z.perm_cap || 0) * 100, 0)}${Lv.permitgap ? ' · permit gap' : ''}</b></div>` : ''}
        <div class="dsec">Suggested media at ${M$(st.budget)} a month across the top ${N(st.n)} ZIPs</div><div class="rowl"><span>This ZIP's share of the scoped gross profit pool</span><b>${P(share * 100, 2)}</b></div><div class="rowl"><span>Indicative monthly media if it makes the buy</span><b>${M$(Math.min(st.budget, zipBudget))}</b></div>
        <div class="dsec">Advertisers within 8 km (${N(adv.length)} of ${N(near.length)} mapped competitors show paid signals)</div>${near.slice(0, 8).map(x => `<div class="rowl"><span>${esc(x.c.l.name)} <span class="mini">${D(x.d, 1)} km${(x.c.l.paid_kw || 0) > 0 ? ' · paid search' : ''}${SLM.adSignal(x.c.l) ? ' · tracking' : ''}</span></span><b>${N(x.c.l.reviews)} rev</b></div>`).join('') || '<p class="mini">No mapped competitor within 8 km.</p>'}
        <div style="display:flex;gap:8px;margin-top:12px;flex-wrap:wrap"><button class="btn sm" id="l12ZDesk">Campaign Desk: ${esc(L().short)} in ${esc(z.zip)}</button><button class="btn sec sm" id="l12ZWatch">Competitor Watch</button><button class="btn sec sm" id="l12ZIdx">Thermal Debt ledger</button></div>`;
      $('#l12ZDesk', root).onclick = () => { const r = SLM.SLZ[z.zip][st.line]; goModule('desk', { zips: [z.zip], line: LINES[L().desk] ? L().desk : 'replace', bids: { [z.zip]: r.bid } }); };
      $('#l12ZWatch', root).onclick = () => goModule('watch', { zip: z.zip }); $('#l12ZIdx', root).onclick = () => goModule('index', { zip: z.zip });
    }
    /* ---------- economics ---------- */
    function econ() {
      const l = L(), Ln = A().lines[l.id]; $('#l12EName', root).textContent = l.short;
      const u = SLM.unitEcon(l, st.sel && SLM.SLZ[st.sel] ? ZI[st.sel] : null); const cpl = SLM.cplByPlatform(l, st.sel && ZI[st.sel] ? ZI[st.sel].cpc_rel : null);
      const fld = (k, lab, step, hint) => `<div class="f"><label class="fl" for="l12E_${k}">${lab}</label><input type="number" id="l12E_${k}" data-k="${k}" value="${Ln[k] == null ? '' : Ln[k]}" step="${step}" ${Ln[k] == null && k === 'ticket' ? 'placeholder="from permits by ZIP"' : ''}>${hint ? `<span class="hint">${hint}</span>` : ''}</div>`;
      $('#l12Econ', root).innerHTML = `<div class="plan">${fld('ticket', 'Ticket ($)', 50, Ln.ticket == null ? 'Blank: the ZIP\'s permit ticket (median ' + M$(SLM.TICK_MED) + ')' : 'Scaled by the ZIP\'s ticket index')}${fld('margin', 'Gross margin (%)', 1)}${fld('cpcMult', 'CPC multiple vs account average', 0.05, 'Emergency intent bids high, maintenance low')}${fld('cvr', 'Search click to lead (%)', 0.5)}${fld('close', 'Lead to booked job (%)', 1)}${fld('pipe', 'Jobs that become a replacement sale within a year (%)', 1, l.id === 'replace' || l.kind === 'lens' ? 'Zero: this is the replacement' : 'Credits the line with replacement gross profit')}${fld('lsaCpl', 'LSA cost per lead ($)', 5, l.fit.lsa ? '' : 'Line not offered on LSA')}${fld('metaCpl', 'Meta cost per lead ($)', 5)}</div>
        <div class="dsec" style="margin-top:14px">Cost per lead by platform ${st.sel ? `for ${st.sel}` : 'at the metro median click cost'}</div><div class="xscroll"><table class="kwtab"><thead><tr><th class="l">Platform</th><th>Fit</th><th>Weight</th><th>Cost per lead</th></tr></thead><tbody>${SLM.PLAT_FIT_KEYS.map(p => { const part = u.parts.find(x => x.p === p); return `<tr><td class="l">${SLM.PLAT_LABEL[p]}</td><td>${l.fit[p] || 0}</td><td>${part ? P(part.share * 100, 0) : '—'}</td><td>${isN(cpl[p]) ? M$(cpl[p]) : '—'}</td></tr>`; }).join('')}</tbody></table></div>
        <div class="qbox" style="margin-top:12px"><div class="qb"><div class="qt">Blended cost per lead</div><div class="qv">${M$(u.cpl)}</div><div class="qd">fit squared weights</div></div><div class="qb"><div class="qt">Cost per booked job</div><div class="qv">${M$(u.cac)}</div><div class="qd">at ${D(u.close, 0)}% close</div></div><div class="qb"><div class="qt">Gross profit per job</div><div class="qv">${M$(u.gpPerJob)}</div><div class="qd">${M$(u.ticket)} × ${D(u.margin, 0)}%${u.gpPipe ? ` + ${M$(u.gpPipe)} pipeline` : ''}</div></div><div class="qb"><div class="qt">Break even cost per lead</div><div class="qv">${M$(u.beCpl)}</div><div class="qd">${u.cpl && u.cpl > u.beCpl ? '<span style="color:var(--critical)">above break even at these assumptions</span>' : 'room to bid up'}</div></div><div class="qb"><div class="qt">Revenue per media dollar</div><div class="qv">${D(u.roas, 1)}×</div><div class="qd">gross profit ${D(u.gpRoas, 2)}× media</div></div></div>
        ${callout('judg tight', 'Judgment call: the benchmarks are starting points', `Search CPC is the account average (${M$(A().cpc)}, module 05's LocaliQ 2025 anchor) times a line multiple and the ZIP's relative click cost; LSA and Meta lead costs are stated. Repair, heating, furnace, duct, maintenance, indoor air and rental jobs are credited with the share that turns into a replacement sale within the year (the pipeline field), valued at the ZIP's replacement ticket and margin; without it the portfolio would buy replacement alone.`)}`;
      $$('#l12Econ input[data-k]', root).forEach(i => i.onchange = () => { const k = i.dataset.k; const v = i.value === '' ? null : +i.value; if (k !== 'ticket' && k !== 'lsaCpl' && !isN(v)) return; SLM.set({ lines: { [l.id]: { [k]: v } } }); });
    }
    /* ---------- season chart & calendar ---------- */
    function season() {
      const cols = CAT(); const sel = SLM.LINES.filter(l => st.chart.includes(l.id));
      lineChart($('#l12Season', root), { H: 300, series: sel.map((l, i) => ({ name: l.short, color: cols[i % cols.length], pts: l.months.map((v, m) => [m, v]), width: l.id === st.line ? 3 : 1.8 })), x: { min: 0, max: 11, ticks: MO.map((_, i) => i), fmt: v => MO[v] }, y: { min: 0, fmt: v => D(v, 0), label: 'Season index, mean 100' }, aria: 'Season index by month and line', tipTitle: m => MO[m] });
      $('#l12SeasonN', root).innerHTML = legendRow(sel.map((l, i) => ({ name: l.short, color: cols[i % cols.length] }))) + `Repair climbs with cooling degree days and spikes with 100°F days; replacement follows what the permit desks actually saw, peaking in July at ${D(SLM.SEASONS.permit[6], 0)}; heating repair mirrors heating degree days and the hard freeze odds; maintenance lives in the shoulders. A line that is flat is a line whose season the atlas does not know, not a line without one.`;
      const T = SLM.LINES; const cell = v => { const t = clamp((v - 100) / 80, -1, 1); const bg = `color-mix(in srgb, ${t >= 0 ? cssv('--heat') : cssv('--cool')} ${Math.round(Math.abs(t) * 75)}%, ${cssv('--card')})`; return `<td style="background:${bg};color:${Math.abs(t) > .6 ? '#fff' : 'inherit'}">${D(v, 0)}</td>`; };
      $('#l12CalTbl', root).innerHTML = `<div class="xscroll"><table class="cm"><thead><tr><th></th>${MO.map(m => `<th>${m}</th>`).join('')}<th>Peak/trough</th></tr></thead><tbody>${T.map(l => `<tr><th class="rh">${esc(l.short)}${l.kind === 'lens' ? ' ◌' : ''}</th>${l.months.map(cell).join('')}<td>${D(Math.max(...l.months) / Math.max(1, Math.min(...l.months)), 1)}×</td></tr>`).join('')}</tbody></table></div>`;
    }
    /* ---------- triggers & rules ---------- */
    function triggers() {
      const first = C.first100; const fTot = sum(first) || 1;
      $('#l12Trig', root).innerHTML = `<table><thead><tr><th class="l">Month</th><th>≥1 day 100°F</th><th>100°F days</th><th>≥1 day 95°F</th><th>95°F days</th><th>Hard freeze ≤20°F</th><th>≤25°F</th><th>Avg max</th><th>Avg min</th><th>First 100°F</th><th>CDD</th><th>HDD</th><th>Large hail</th></tr></thead><tbody>${MO.map((m, i) => `<tr><td class="l">${m}</td><td>${P(C.p100[i], 0)}</td><td>${D(C.m100[i], 1)}</td><td>${P(C.p95[i], 0)}</td><td>${D(C.m95[i], 1)}</td><td>${P(C.pfr20[i], 0)}</td><td>${P(C.pfr25[i], 0)}</td><td>${D(C.tmax[i], 0)}°</td><td>${D(C.tmin[i], 0)}°</td><td>${first[i] ? P(first[i] / fTot * 100, 0) : '—'}</td><td>${N(NM.cdd[i])}</td><td>${N(NM.hdd[i])}</td><td>${SLM.HAIL_OBS[i] || '—'}</td></tr>`).join('')}</tbody></table>`;
      const cur = DATA.climate.ytd; $('#l12TrigN', root).innerHTML = `${G('A')} DFW Airport daily records aggregated by month in the atlas weather file. Read the odds as planning rules: a June flight has a coin flip's chance of a 100°F day and near certainty of 95°F; July and August carry ${D(C.m100[6], 0)} and ${D(C.m100[7], 0)} hundred degree days on average; the first 100°F day arrived in June or July in ${P((first[5] + first[6]) / fTot * 100, 0)} of seasons. Hard freezes (20°F) are a January phenomenon (${P(C.pfr20[0], 0)}) with December and February close behind. ${String(cur.through).slice(0, 4)} has already logged ${cur.d100} days at 100°F against a normal of ${cur.norm_d100}. Large hail: the 25 biggest reports in the file, by month.`;
      $('#l12Rules', root).innerHTML = `<div class="tscroll" style="max-height:560px"><table class="prose"><thead><tr><th class="l">Line</th><th class="l">Heavy months</th><th class="l">Light months</th><th class="l">Inside the month</th></tr></thead><tbody>${SLM.LINES.map(l => { const heavy = l.months.map((v, i) => v >= 110 ? MO[i] : null).filter(Boolean), light = l.months.map((v, i) => v <= 75 ? MO[i] : null).filter(Boolean); return `<tr><td>${esc(l.short)}${l.kind === 'lens' ? ' ◌' : ''}</td><td>${heavy.join(', ') || 'flat'}</td><td>${light.join(', ') || 'flat'}</td><td>${l.triggers.map(t => esc(t)).join('<br>')}</td></tr>`; }).join('')}</tbody></table></div>`;
    }
    /* ---------- portfolio ---------- */
    function portfolio() {
      $('#l12Bud', root).value = st.budget; $('#l12Alpha', root).value = st.alpha; $('#l12AlphaV', root).textContent = D(st.alpha, 1); $('#l12Cpc', root).value = A().cpc; $('#l12Mo', root).value = String(st.month);
      const rows = SLM.allocate(st.budget, st.month < 0 ? null : st.month, scoped(), null, st.alpha);
      const tot = { b: sum(rows.map(r => r.budget)), leads: sum(rows.map(r => r.leads)), jobs: sum(rows.map(r => r.jobs)), rev: sum(rows.map(r => r.rev)), gp: sum(rows.map(r => r.gpOut)) };
      $('#l12Port', root).innerHTML = `<table><thead><tr><th class="l">Line</th><th>Season</th><th>GP pool in scope</th><th>Media</th><th>Share</th><th>Cost/lead</th><th>Leads</th><th>Jobs</th><th>Revenue</th><th>Gross profit</th><th>GP ÷ media</th><th>Share of scope jobs that month</th></tr></thead><tbody>${rows.map(r => `<tr class="${r.line.id === st.line ? 'sel' : ''}"><td class="l"><b>${esc(r.line.short)}</b></td><td>${D(r.season, 0)}</td><td>${MM(r.gp)}</td><td>${M$(r.budget)}</td><td>${P(r.budget / tot.b * 100, 0)}</td><td>${M$(r.u.cpl)}</td><td>${N(r.leads)}</td><td>${D(r.jobs, 1)}</td><td>${M$(r.rev)}</td><td>${M$(r.gpOut)}</td><td>${D(r.gpOut / Math.max(1, r.budget), 2)}×</td><td>${P(r.share * 100, 2)}</td></tr>`).join('')}<tr><td class="l"><b>Total</b></td><td></td><td>${MM(sum(rows.map(r => r.gp)))}</td><td><b>${M$(tot.b)}</b></td><td>100%</td><td>${M$(tot.b / Math.max(1, tot.leads))}</td><td><b>${N(tot.leads)}</b></td><td><b>${D(tot.jobs, 1)}</b></td><td><b>${M$(tot.rev)}</b></td><td><b>${M$(tot.gp)}</b></td><td><b>${D(tot.gp / Math.max(1, tot.b), 2)}×</b></td><td></td></tr></tbody></table>`;
      const monthly = MO.map((_, m) => SLM.allocate(st.budget, m, scoped(), null, st.alpha)); const ann = {}; monthly.forEach(a => a.forEach(r => ann[r.line.id] = (ann[r.line.id] || 0) + r.budget)); const order = Object.entries(ann).sort((a, b) => b[1] - a[1]).map(x => x[0]); const top = order.slice(0, 6), rest = order.slice(6); const cols = CAT();
      const series = top.map((id, i) => ({ name: SLM.lineName(id), color: cols[i % cols.length], values: monthly.map(a => (a.find(r => r.line.id === id) || {}).budget || 0) })); if (rest.length) series.push({ name: 'Other lines', color: cssv('--ink-3'), values: monthly.map(a => sum(a.filter(r => rest.includes(r.line.id)).map(r => r.budget))) });
      barChart($('#l12PortChart', root), { cats: MO, series, stacked: true, H: 280, fmt: v => MM(v), aria: 'Suggested media by month and line' });
      $('#l12PortN', root).innerHTML = legendRow(series.map(s => ({ name: s.name, color: s.color, sq: true }))) + `The same monthly budget, re-split each month by season. Repair and heating trade places between July and January; replacement holds the middle; maintenance and indoor air take the shoulders. ${MM(tot.b * 12)} a year at ${M$(st.budget)} a month.`;
    }
    /* ---------- levers & pressure ---------- */
    function levers() {
      const cnt = k => ZR.filter(z => { const Lv = SLM.LEV[z.zip]; return k === 'fin' ? Lv.fin >= 60 : k === 'cash' ? Lv.cash >= 60 : k === 'es' ? Lv.es >= 15 : !!Lv[k]; }).length;
      $('#l12Lev', root).innerHTML = `<div class="xscroll"><table class="prose"><thead><tr><th class="l">Lever</th><th class="l">ZIPs</th><th class="l">What it changes</th></tr></thead><tbody>${SLM.LEVER_DEFS.map(([k, name, def]) => `<tr><td><span class="sev" style="background:${LEVC()[k]}"></span>${name}</td><td>${N(cnt(k))}</td><td>${esc(def)}</td></tr>`).join('')}</tbody></table></div><p class="mini" style="margin-top:8px">Also flagged per ZIP: apartment heavy (units in buildings of two or more at 45% or above: property manager buying), heat vulnerable (owners 65 and over at 25% with pre 1980 stock at 40%: heat safety creative and maintenance plans) and permit gap (observed permits under 15% of modeled replacements in the three permit cities: "permitted and inspected" is a differentiator there). Map layer: Dominant audience lever.</p>`;
      $('#l12Press', root).innerHTML = `<table><thead><tr><th class="l">Line</th><th>Sell it</th><th>Paid search</th><th>Contested ZIPs</th><th>Quiet ZIPs</th><th>Median pressure</th></tr></thead><tbody>${SLM.LINES.map(l => { const a = SLM.AGG[l.id]; const rows = ZR.map(z => SLM.SLZ[z.zip][l.id]); return `<tr class="${l.id === st.line ? 'sel' : ''}"><td class="l">${esc(l.short)}</td><td>${N(a.compN)}</td><td>${N(a.compPaid)}</td><td>${N(rows.filter(r => r.presspct >= 60 && r.gppct >= 60).length)}</td><td>${N(a.quiet)}</td><td>${D(median(rows.map(r => r.press)), 2)}</td></tr>`; }).join('')}</tbody></table>`;
    }
    function dayparts() {
      const l = L(); const grid = SLM.DAYPARTS[l.dayparts]; const cell = v => { const t = clamp(v / 50, -1, 1); return `<td style="background:color-mix(in srgb, ${t >= 0 ? cssv('--heat') : cssv('--cool')} ${Math.round(Math.abs(t) * 80)}%, ${cssv('--card')});color:${Math.abs(t) > .55 ? '#fff' : 'inherit'}">${S(v, 0)}%</td>`; };
      $('#l12Day', root).innerHTML = `<div class="split21"><div class="xscroll"><table class="cm"><thead><tr><th></th>${SLM.BLOCKS.map(b => `<th>${b}</th>`).join('')}</tr></thead><tbody>${SLM.DAYS.map((d, i) => `<tr><th class="rh">${d}</th>${grid[i].map(cell).join('')}</tr>`).join('')}</tbody></table></div><div><div class="rowl"><span>Template</span><b>${l.dayparts}</b></div><div class="rowl"><span>Mobile share to expect</span><b>${l.mobile}%</b></div><div class="rowl"><span>Primary conversion</span><b>${l.mobile >= 70 ? 'Phone call' : l.mobile >= 55 ? 'Call and form' : 'Form and quote request'}</b></div><p class="mini" style="margin-top:8px">${l.dayparts === 'emergency' ? 'Emergency lines convert on the evening the system quits and all weekend; never pause overnight in July and August, when a 2 a.m. call is a booked job. Calls beat forms three to one.' : l.dayparts === 'considered' ? 'Considered purchases are researched on weekday evenings and weekend afternoons, often on a desktop after a mobile search. Quote forms and callback requests matter as much as calls; retargeting carries the two to six week decision.' : l.dayparts === 'daytime' ? 'Low urgency lines book during business hours, when the office can pick up. Seniors and stay at home decision makers skew the daytime; keep phone assets on and video off overnight.' : 'Business buyers act during business hours from a desktop. Weekends and nights are wasted spend; LinkedIn and Microsoft carry more weight than in any consumer line.'}</p></div></div>`;
    }
    /* ---------- prose ---------- */
    function prose() {
      $('#l12Meth', root).innerHTML = [
        `<b>Pool.</b> Each line names the homes or systems that can buy it, straight from the ZIP ledger: systems for repair, systems 15 or older for replacement, the builder's original systems aged 10 to 25 for the first wave, R22 era systems, gas furnaces past 20, heat pumps, owner occupied single family homes for maintenance and indoor air, homes built 1980 to 1999 for ducts, homes built before 1960 (plus half the four bedroom homes) for ductless, systems weighted by large hail reports, rented single family homes for landlords, and a business proxy for commercial (population times the metro business rate, adjusted for density).`,
        `<b>Jobs a year.</b> Replacements, first replacements, furnace replacements and heat pump replacements are the fitted Weibull renewals from module 02. Repairs use module 05's call rate by system age. Everything else is a stated rate: R22 hazard ${SLM.A.rates.r22Hazard}, duct ${SLM.A.rates.ductRate} of the duct generation plus ${SLM.A.rates.ductAttach} attached to each replacement, maintenance take up ${SLM.A.rates.maintTake}, indoor air ${SLM.A.rates.iaqRate} plus ${SLM.A.rates.iaqAttach} attach, ductless ${SLM.A.rates.ductlessOld} of old stock plus ${SLM.A.rates.ductlessAdd} of owner homes, hail ${SLM.A.rates.hailRate} of systems per large hail report a year within 8 km, commercial ${SLM.A.rates.bizJobs} jobs per business, rental homes ${SLM.A.rates.landlordRate} jobs each.`,
        `<b>Ticket, margin and pipeline.</b> Replacement lines take the ZIP's permit ticket (Irving valuations apportioned by home value, module 05). Stated tickets for the rest are scaled by the ZIP's ticket index within stated bounds. Gross margin is stated by line. A stated share of repair, heating, furnace, duct, maintenance, indoor air and rental jobs becomes a replacement sale within the year and is credited at the ZIP's replacement ticket and margin. Gross profit pool is jobs times (direct gross profit plus pipeline gross profit), the quantity everything else optimizes.`,
        `<b>Season.</b> Twelve indices with mean 100 per line: the weighted permit season for replacement lines, cooling degree days plus 100°F days for repair, heating degree days plus hard freeze odds for heating, hail climatology blended with the file's 25 largest reports, and stated calendars for maintenance, indoor air and ducts. Lenses inherit their parent's season; heat pumps blend permits and heating 70/30.`,
        `<b>Paid pressure.</b> For every ZIP, each mapped competitor within 20 km contributes exp(minus distance over 8 km) times an advertiser weight (paid keywords in Ahrefs, tracking numbers on the site, deep dive tier, review mass) times 1 if it sells the line and 0.35 if not. Observations logged in Competitor Watch add up to 2 to the weight of that company. Ranked to a percentile within the line.`,
        `<b>Priority.</b> Gross profit pool divided by the ZIP's relative click cost times the line's CPC multiple, discounted by (0.55 + 0.9 × pressure percentile). Ranked to a percentile within the line and mapped to starting bid modifiers (+45 above the 90th, then +30, +15, 0, minus 20, minus 40). A quiet auction is a ZIP in the top 40% of the line's gross profit pool with pressure in the bottom 45%.`,
        `<b>Economics.</b> Cost per lead by platform: search is account CPC times the line multiple times relative click cost over the click to lead rate; Microsoft two thirds of search; LSA and Meta stated; YouTube, Nextdoor and Yelp derived. Blended by the square of channel fit. Cost per booked job divides by the close rate; break even cost per lead is gross profit per job times the close rate.`,
        `<b>Levers.</b> Payment led score from the replacement ticket against household income, less the high income share; cash and premium from the high income share, half million dollar homes and owners 65 and over; Spanish share from limited English Spanish speaking households; thresholds for seniors, new owners, rented single family, multi system homes, apartment heavy, heat vulnerable and permit gap. The dominant lever is the highest standardized score.`,
      ].map(x => `<li>${x}</li>`).join('');
      $('#l12Judg', root).innerHTML = judgList([
        ['Lenses are not added twice', 'Builder first, R22 and heat pump are ways to target and write the replacement campaign; their jobs sit inside the replacement count, so the portfolio allocates across eleven additive lines and the lenses only rank ZIPs.'],
        ['Repairs and replacements are both lines', 'A repair call is often the replacement lead; the desk and this module keep them separate because the auction, the creative and the daypart are different, and the repair or replace decision belongs to the technician on site.'],
        ['Hail is an expected value', 'The hail line is averaged over a decade. In practice it arrives in two or three storms a year; the line\'s rule is to spend nothing until a storm hits, then spend the year\'s share in three weeks inside the swath.'],
        ['Commercial rides a proxy', 'The file has HVAC establishments by ZIP, not businesses of every kind. Population times the metro business rate is a placeholder; the commercial line is grade D until a ZIP Business Patterns all industry count is loaded.'],
        ['Maintenance is priced at its first ticket', 'The plan ticket alone never pays for its media. Contractors buy it for the replacement pipeline and the summer schedule; that value is described, not counted.'],
        ['Financing is a lever, not a line', 'The payment led score decides whether replacement creative leads with a monthly payment; on Meta that moves the ad into the Financial products special ad category (15 mile radius, no ZIP targeting), which is why it is a creative decision and not a ZIP list.'],
        ['Pressure is about lines, not brands', 'A plumber that also sells AC repair counts for the repair line and barely for ductless. Service lists come from the August 2026 heatmap roster and are as good as the websites they were read from.'],
        ['Dayparts are templates', 'Four templates cover fourteen lines. They are the shape of home services demand, not this account\'s; the account report replaces them.'],
        ['Seasons are indices, not forecasts', 'A season index of 143 in July means July carries 1.43 times the average month over a decade, not that next July will.'],
      ]);
      $('#l12Cav', root).innerHTML = judgList([
        ['No search volume by line', 'Nothing here was priced by a keyword tool. Search demand is assumed proportional to jobs; the keyword desk in module 08 lists the terms to price inside the account.'],
        ['Rates are stated', 'Maintenance take up, indoor air attach, ductless, hail, commercial and rental job rates are stated (grade D) and editable. They set the size of a line, not its geography, which the pools carry.'],
        ['Tickets outside replacement are stated', 'Only replacement lines have a measured ticket (permits). Repair, furnace, duct, maintenance, indoor air, ductless, commercial and rental tickets are stated for 2026 DFW and scaled by the ZIP ticket index.'],
        ['Competitor service lists are partial', 'Roster companies (191 of 242) carry short service lists; deep dive companies carry fuller ones. Pressure is therefore firmer where the deep dive companies operate.'],
        ['One season per line for the whole metro', 'Fort Worth\'s permit season is applied to Rockwall. The three permit cities agree closely (module 04), but no exurban city has a permit file in the atlas.'],
        ['Levers are thresholds on Census shares', 'A ZIP at 27.9% owners over 65 is not flagged senior and one at 28.0% is; read the scores, not just the tags.'],
      ]);
      $('#l12Src', root).innerHTML = srcRows([['Pools and levers', 'ACS 2020 to 2024 five year (B25034, B25032, B25040, B25007, B25038, B19013, B25077, C16002) through the ZIP ledger', 'A', '2024', 'https://www.census.gov/programs-surveys/acs'], ['Renewals and lifetimes', 'EIA RECS 2020 Texas microdata, fitted Weibull lifetimes (module 02)', 'B', '2020', 'https://www.eia.gov/consumption/residential/data/2020/'], ['Replacement tickets', `Irving mechanical permit valuations, ${N(DATA.tickets.n)} replacements 2022 to 2025 (module 05)`, 'B', '2025', ''], ['Permit season', 'Fort Worth, Dallas and Irving monthly HVAC permits (module 04 regressions)', 'B', '2026', ''], ['Climatology', 'DFW Airport daily records 1953 to 2026 aggregated monthly; NWS 1991 to 2020 normals', 'A', 'Sep 2026', 'https://www.weather.gov/fwd/dfwannual'], ['Heat wave surge', 'ServiceTitan heat wave analysis, about 800 shops, 2019 to 2021 (+20% calls, +25% jobs)', 'B', '2022', ''], ['Hail', 'NOAA Storm Events 2016 to 2026; North Texas hail climatology', 'C', '2026', 'https://www.ncdc.noaa.gov/stormevents/'], ['Pollen and ozone', 'North Texas allergy calendar (cedar, oak, ragweed); American Lung Association State of the Air (27.8 unhealthy ozone days a year)', 'C', '2026', 'https://www.lung.org/research/sota'], ['Benchmarks', 'LocaliQ 2025 home services (CPC anchor); stated line multiples, lead costs, close rates and margins', 'D', '2025', 'https://localiq.com/blog/search-advertising-benchmarks/'], ['Competitors', 'DFW HVAC Competitive Heatmap roster, August 18, 2026 (module 07)', 'C', 'Aug 2026', '']]);
    }
    /* ---------- render ---------- */
    function render() { chips(); kpis(); drawMap(); brief(); table(); zipCard(); econ(); levers(); dayparts(); portfolio(); }
    season(); triggers(); prose(); render();
    /* ---------- wiring ---------- */
    $('#l12Layer', root).onchange = e => { st.layer = e.target.value; drawMap(); };
    $('#l12Cty', root).onchange = e => { st.county = e.target.value; st.sel = null; if (st.county) map.fitTo(Z.filter(z => z.fips === st.county).map(z => z.zip)); else map.reset(); render(); };
    $('#l12N', root).onchange = e => { st.n = clamp(+e.target.value || 40, 5, 263); render(); };
    $('#l12Comp', root).onchange = () => drawMap();
    $('#l12Find', root).addEventListener('input', debounce(e => { const q = e.target.value.trim().toLowerCase(); if (!q) return; const hit = ZR.find(z => z.zip.startsWith(q)) || ZR.find(z => z.city.toLowerCase().startsWith(q)); if (hit) { st.sel = hit.zip; map.fitTo([hit.zip]); render(); } }, 250));
    $('#l12Bud', root).onchange = e => { st.budget = Math.max(1000, +e.target.value || 25000); SLM.set({ budget: st.budget }); portfolio(); zipCard(); };
    $('#l12Mo', root).onchange = e => { st.month = +e.target.value; portfolio(); };
    $('#l12Alpha', root).addEventListener('input', e => { st.alpha = +e.target.value; $('#l12AlphaV', root).textContent = D(st.alpha, 1); }); $('#l12Alpha', root).onchange = e => { st.alpha = +e.target.value; SLM.set({ alpha: st.alpha }); portfolio(); };
    $('#l12Cpc', root).onchange = e => { const v = +e.target.value; if (isN(v) && v > 0) SLM.set({ cpc: v }); };
    $('#l12Reset', root).onclick = () => { SLM.reset(); st.budget = SLM.A.budget; st.alpha = SLM.A.alpha; toast('Assumptions reset to the build defaults'); };
    $('#l12Long', root).onclick = () => saveFile('dfw-service-lines-by-zip.csv', SLM.matrixLong(scoped()));
    $('#l12Wide', root).onclick = () => saveFile('dfw-service-line-priority-matrix.csv', SLM.matrixWide(scoped()));
    $('#l12G', root).onclick = () => saveFile(`google-ads-locations_${st.line}.csv`, SLM.googleLocations(st.line, scoped(), st.n));
    $('#l12M', root).onclick = () => saveFile(`meta-zips_${st.line}.csv`, SLM.metaZips(st.line, scoped(), st.n));
    $('#l12Cal', root).onclick = () => saveFile('dfw-service-line-flight-calendar.csv', SLM.calendar(st.budget, scoped()));
    $('#l12Asm', root).onclick = () => saveFile('service-line-assumptions.json', JSON.stringify({ saved: new Date().toISOString(), assumptions: SLM.A, seasons: Object.fromEntries(SLM.LINES.map(l => [l.id, l.months])), climatology: SLM.CLIM }, null, 2));
    $('#l12Desk', root).onclick = () => toDesk(); $('#l12Watch', root).onclick = () => goModule('watch', { line: st.line });
    BUS.on('theme', () => { drawMap(); season(); portfolio(); dayparts(); }); BUS.on('sl', () => { kpis(); drawMap(); brief(); table(); zipCard(); econ(); levers(); portfolio(); });
    this.receive = p => { if (!p) return; if (p.line && SLM.LI[p.line]) st.line = p.line; if (p.county != null && (p.county === '' || COI[p.county])) { st.county = p.county; $('#l12Cty', root).value = p.county; } if (p.zip && ZI[p.zip]) { st.sel = p.zip; map.fitTo([p.zip]); } render(); };
  }
});
