/* ==== m13_watch ==== */
"use strict";
/* ============================ Module 13: Competitor Watch ============================ */
registerModule({
  key: 'watch', num: '13', title: 'Competitor Watch', desc: 'What the 242 mapped competitors are doing: ads on Meta and Google, offers, financing, memberships, reviews, with library links and an API bridge',
  mount(root) {
    const W = WATCH; const st = { sel: null, q: '', city: '', line: '', tier: '', act: '', sort: 'score', view: 'cards', edit: null, formComp: '', zip: null, geoLayer: 'effb' };
    const cities = [...new Set(W.COMPANIES.flatMap(c => c.cities))].sort();
    const lineOpts = sel => `<option value="">Any line</option>${SLM.LINES.map(l => `<option value="${l.id}" ${l.id === sel ? 'selected' : ''}>${l.short}</option>`).join('')}`;
    root.innerHTML = mastHTML({ eyebrow: 'Module 13 · Competitor Watch · the field, observed', title: 'Competitor Watch', dek: 'Module 07 counts the competitors. This module watches them: which ones are running ads on Meta and Google, what they offer, what they charge for a tune up, how they talk about financing, which memberships they sell, and where. It keeps a structured ledger of observations, opens each company\'s page in the Meta Ad Library and the Google Ads Transparency Center with the right parameters, imports the Meta Ad Library API\'s answers, screens every offer against the Emergency Satchel\'s rules, and feeds what it learns back into the pressure readings in module 12.',
      meta: [`<b>${N(W.COMPANIES.filter(c => !W.isBench(c)).length)}</b> companies · <b>${N(COMP.length)}</b> locations`, `<b>${N(W.COMPANIES.filter(c => c.paid_kw > 0).length)}</b> with paid search in Ahrefs (${esc(W.ROSTER_DATE)})`, '<b>Ledger</b> stored in this browser · JSON and CSV round trip', '<b>Libraries</b> Meta Ad Library · Google Ads Transparency Center'],
      bar: 'Competitor Watch', barsub: 'Board, ledger, libraries, analytics, sweeps', actions: [{ id: 'w13Csv', label: '↓ Ledger CSV' }, { id: 'w13Json', label: '↓ Ledger JSON', title: 'Full backup: observations, IDs, sweep dates' }, { id: 'w13Sweep', label: '↓ Sweep checklist' }, { id: 'w13Roster', label: '↓ Watchlist CSV' }, { id: 'w13Import', label: '⤒ Import', title: 'Load a ledger JSON or CSV file' }, { id: 'w13Sat', label: 'Satchel ↗' }, { id: 'w13Desk', label: 'Campaign Desk ↗' }] }) +
      `<div class="wrap">
      ${callout('', 'Read this first: what the two libraries show, and what this tab does with them', `The <b>Meta Ad Library</b> shows every ad currently running from any Facebook or Instagram Page in the United States, with the creative, the start date, the platforms and a Library ID; inactive ads and spend appear only for political and social issue ads, and for ads delivered in the European Union. Its <b>API</b> is narrower: in the United States it returns political and social issue ads and the special ad categories (housing, employment and <b>credit</b>, which is where a competitor's financing ads may sit); ordinary HVAC ads are web only. The <b>Google Ads Transparency Center</b> shows ads from verified advertisers by advertiser name or website, with format, date range and the regions shown, and no spend for commercial ads; it has no API. So this tab does three honest things: it <b>links</b> every company into both libraries with the right parameters, it <b>imports</b> what the Meta API can return and what you paste from either library, and it <b>keeps the ledger</b> of what you saw, dated, typed and screened. The ledger opens seeded with the August 2026 website intel (promos, financing, memberships, tracking numbers) so the board is not empty; the seed is marked and can be cleared.`)}
      <div class="kpis" id="w13Kpis"></div>
      ${card('What they are doing right now', 'Plain sentences computed from the ledger and the roster. They change as you log.', '<ul class="digest" id="w13Digest"></ul>', 'mt')}
      <div class="card mt"><div class="card-b"><div style="display:flex;gap:12px;flex-wrap:wrap;align-items:flex-end">
        <div class="ctl" style="flex:1 1 200px"><label class="fl" for="w13Q">Search</label><input type="search" id="w13Q" placeholder="company, domain, brand, service"></div>
        <div class="ctl"><label class="fl" for="w13City">City</label><select id="w13City"><option value="">All cities</option>${cities.map(c => `<option>${esc(c)}</option>`).join('')}</select></div>
        <div class="ctl"><label class="fl" for="w13Line">Sells the line</label><select id="w13Line">${lineOpts('')}</select></div>
        <div class="ctl"><label class="fl" for="w13Tier">Tier</label><select id="w13Tier"><option value="">All</option><option value="top40">Deep dive (50)</option><option value="roster">Roster</option></select></div>
        <div class="ctl"><label class="fl" for="w13Act">Activity</label><select id="w13Act"><option value="">Any</option><option value="live">Ads live on record</option><option value="paid">Paid search (Ahrefs)</option><option value="fin">Advertises financing</option><option value="mem">Sells a membership</option><option value="promo">Has a promo on record</option><option value="none">Nothing observed yet</option><option value="lint">Trips a Satchel rule</option></select></div>
        <div class="ctl"><label class="fl" for="w13Sort">Sort</label><select id="w13Sort"><option value="score">Activity score</option><option value="reviews">Reviews</option><option value="dr">Domain rating</option><option value="paid">Paid keywords</option><option value="live">Live ads on record</option><option value="checked">Least recently checked</option><option value="name">Name</option></select></div>
        <div class="seg" id="w13View"><button data-v="cards" aria-pressed="true">Cards</button><button data-v="table" aria-pressed="false">Table</button></div>
      </div></div></div>
      <div id="w13Board" class="wboard"></div><div id="w13Table" class="card mt" hidden><div class="tscroll tall" id="w13Tbl"></div></div>
      <div class="split">
        <div class="card"><div class="card-h" style="display:flex;justify-content:space-between;gap:10px;align-items:flex-start"><div><h3 id="w13DName">Select a company</h3><p id="w13DSub">Click a card. IDs you record here build the exact library links and travel with the ledger.</p></div><span class="pill" id="w13DPill"></span></div><div class="card-b" id="w13Detail"></div></div>
        <div class="stack">
          <div class="card"><div class="card-h"><h3 id="w13FTitle">Log an observation</h3><p>An ad seen in a library, an offer on a site or mailer, a review count, an event such as an acquisition. The copy is screened against the Satchel rules as you type.</p></div><div class="card-b" id="w13Form"></div></div>
          <div class="card"><div class="card-h"><h3>Bring things in</h3><p>Paste a Meta Ad Library API response (JSON), library links (Meta Library IDs, Google advertiser and creative links), or a ledger CSV. Rows attach to the company selected in the form.</p></div><div class="card-b"><textarea id="w13Paste" class="code" style="min-height:110px" placeholder='{"data":[{"id":"...","page_name":"..."}]}  or  https://www.facebook.com/ads/library/?id=1234567890'></textarea><div style="display:flex;gap:8px;margin-top:8px;flex-wrap:wrap;align-items:center"><button class="btn sm" id="w13PasteGo">Import pasted text</button><label class="btn sec sm" for="w13File" style="cursor:pointer">Import a file</label><input type="file" id="w13File" accept=".json,.csv,.txt" style="display:none"><span class="mini" id="w13PasteNote"></span></div></div></div>
        </div>
      </div>
      ${card('Meta Ad Library API bridge', 'Build the ads_archive request. With a token, the request runs here when the page is opened outside the Claude viewer (its network rules block platform calls); inside the viewer, or without a token, copy the URL, open it in a new tab and paste the JSON answer into the import box above. Coverage in the United States: political and issue ads plus the housing, employment and credit special ad categories; every ad in the European Union.', `<div class="plan">
        <div class="f"><label class="fl" for="w13Tok">Access token</label><input type="password" id="w13Tok" placeholder="from a Meta for Developers app (Graph API Explorer)" autocomplete="off"><span class="hint"><label class="chk"><input type="checkbox" id="w13Keep"> keep the token in this browser</label></span></div>
        <div class="f"><label class="fl" for="w13Terms">Search terms</label><input type="text" id="w13Terms" value="air conditioning repair Dallas"><span class="hint">Keyword search across page names and creative; unordered match.</span></div>
        <div class="f"><label class="fl" for="w13Pages">Page IDs (comma separated)</label><input type="text" id="w13Pages" placeholder="recorded Page IDs fill in from the detail panel"><span class="hint">Search by Page instead of terms.</span></div>
        <div class="f"><label class="fl" for="w13Type">Ad type</label><select id="w13Type"><option value="ALL">ALL (US returns special categories only)</option><option value="CREDIT_ADS">CREDIT_ADS (financing offers)</option><option value="HOUSING_ADS">HOUSING_ADS</option><option value="EMPLOYMENT_ADS">EMPLOYMENT_ADS (recruiting)</option><option value="POLITICAL_AND_ISSUE_ADS">POLITICAL_AND_ISSUE_ADS</option></select></div>
        <div class="f"><label class="fl" for="w13Status">Status</label><select id="w13Status"><option value="ACTIVE">ACTIVE</option><option value="ALL">ALL</option><option value="INACTIVE">INACTIVE</option></select></div>
        <div class="f"><label class="fl" for="w13Since">Delivered since</label><input type="date" id="w13Since"></div>
        <div class="f"><label class="fl" for="w13Ver">API version</label><input type="text" id="w13Ver" value="v21.0"></div>
        <div class="f"><label class="fl" for="w13Lim">Limit per page · pages</label><div style="display:flex;gap:6px"><input type="number" id="w13Lim" value="100" min="10" max="500" style="width:80px"><input type="number" id="w13Pg" value="3" min="1" max="20" style="width:70px"></div></div></div>
        <div style="display:flex;gap:8px;margin-top:12px;flex-wrap:wrap;align-items:center"><button class="btn sm" id="w13Run">Run the request here</button><button class="btn sec sm" id="w13Copy">Copy request URL</button><a class="btn sec sm" id="w13Open" href="#" target="_blank" rel="noopener">Open request in a new tab</a><span class="mini" id="w13ApiNote"></span></div>
        <pre id="w13Url" style="margin-top:10px;max-height:120px"></pre>
        <div id="w13ApiOut"></div>`, 'mt')}
      <div class="split">
        ${card('Share of voice on record', 'Live ads in the ledger by company, all platforms. A company you have not swept has none; sweep before you read it as silence.', '<div id="w13Sov"></div>')}
        ${card('Ads logged by week and platform', 'First seen dates of ads in the ledger, the last 26 weeks.', '<div id="w13Week"></div><p class="chartnote" id="w13WeekN"></p>')}
      </div>
      <div class="split">
        ${card('Offers on record', 'Every offer by type, then the price points and financing terms behind them, with Satchel flags.', '<div id="w13Offers"></div>')}
        ${card('Hooks and lines', 'What the creative leans on, and which service lines the field is promoting.', '<div id="w13Hooks"></div>')}
      </div>
      ${card('Coverage: companies × service lines', 'Observations (ads, offers, signals) by company and line. Blank means nothing on record, not nothing running.', '<div class="tscroll" id="w13Cov"></div>', 'mt')}
      <div class="grid2">
        <div class="card mapcard"><div class="card-h" style="display:flex;gap:10px;align-items:center;flex-wrap:wrap"><h3 style="flex:1">Where the observed ads point</h3><select id="w13Geo"><option value="effb">Base: paid efficiency (module 05)</option><option value="sl_pri_replace">Base: replacement priority (module 12)</option><option value="sl_pri_repair">Base: repair priority</option><option value="comp_mass">Base: competitor review mass</option><option value="none">No base</option></select></div><div id="w13Map"></div><div class="legend" id="w13Leg"></div></div>
        <div class="card"><div class="card-h"><h3>Uncontested value</h3><p>High paid efficiency ZIPs where no logged ad names the ZIP or its city, and the selected company's locations.</p></div><div class="card-b" id="w13Geo2"></div></div>
      </div>
      ${card('Sweep planner', 'A weekly pass through the libraries. Mark a company checked when you have opened its links and logged what you saw; stale after 14 days.', '<div class="tscroll" id="w13SweepTbl"></div>', 'mt')}
      ${card('How the watch is built', '', '<ol class="meth" id="w13Meth"></ol>', 'mt')}
      <div class="split">${card('Judgment calls', '', '<div id="w13Judg"></div>')}${card('Library facts to keep in mind', 'Read this build; verify before relying on any single line.', '<div id="w13Facts"></div>')}</div>
      ${card('Source register', '', '<div id="w13Src"></div>', 'mt')}
      <div class="foot">DFW Thermal Debt Atlas, module 13. An observation is a dated record of what a person saw in a public library or on a public page; it is intelligence, not evidence, until the Satchel's evidentiary bar is met. The ledger never leaves this browser unless you export it.</div></div>`;
    /* ---------- helpers ---------- */
    const lineN = id => id ? SLM.lineName(id) : '';
    const platB = p => `<span class="pbadge p-${p}">${p === 'meta' ? 'M' : p === 'google' ? 'G' : p === 'lsa' ? 'LSA' : p === 'youtube' ? 'YT' : p === 'microsoft' ? 'MS' : p === 'nextdoor' ? 'ND' : p === 'yelp' ? 'Y' : p === 'site' ? 'Site' : p === 'mail' ? 'Mail' : p === 'tv' ? 'TV' : p.slice(0, 3)}</span>`;
    const compLinks = (c, m) => { const L = W.LINKS; const out = [['Meta Ad Library: active ads by name', L.metaKw(c.name)], ['Meta Ad Library: all ads by name', L.metaKwAll(c.name)]]; if (m.pageId) out.push(['Meta Ad Library: this Page (ID ' + m.pageId + ')', L.metaPage(m.pageId)]); if (c.domain) out.push(['Google Ads Transparency: by website', L.googleDomain(c.domain)]); if (m.advId) out.push(['Google Ads Transparency: advertiser ' + m.advId, L.googleAdv(m.advId)]); out.push(['Google Search: name and city (LSA badge check)', L.gSearch(c.name, c.cities[0])]); out.push(['Google Maps: profile and review count', L.gMaps(c.name, COMP[c.locs[0]].street ? COMP[c.locs[0]].street + ' ' + c.cities[0] : c.cities[0])]); if (c.domain) out.push(['Website', L.site(c.domain)]); return out; };
    const linkList = pairs => `<div class="links">${pairs.map(([l, u]) => `<a href="${esc(u)}" target="_blank" rel="noopener">${esc(l)} ↗</a>`).join('')}</div>`;
    const passes = c => { if (W.isBench(c)) return false; if (st.tier && c.tier !== st.tier) return false; if (st.city && !c.cities.includes(st.city)) return false; if (st.line) { const svc = SLM.LI[st.line].svc.map(s => s.toLowerCase()); if (!c.services.some(s => svc.includes(s.toLowerCase()))) return false; } if (st.q) { const hay = (c.name + ' ' + c.domain + ' ' + c.brands.join(' ') + ' ' + c.services.join(' ') + ' ' + c.cities.join(' ')).toLowerCase(); if (!hay.includes(st.q)) return false; }
      if (st.act) { const obs = W.forCompany(c.key); const live = obs.filter(o => o.kind === 'ad' && W.isLive(o)); if (st.act === 'live' && !live.length) return false; if (st.act === 'paid' && !(c.paid_kw > 0)) return false; if (st.act === 'fin' && !obs.some(o => o.offer && o.offer.type === 'financing')) return false; if (st.act === 'mem' && !obs.some(o => o.offer && o.offer.type === 'membership')) return false; if (st.act === 'promo' && !obs.some(o => o.kind === 'offer')) return false; if (st.act === 'none' && obs.some(o => o.src !== 'seed')) return false; if (st.act === 'lint' && !obs.some(o => (o.lint || []).length)) return false; } return true; };
    const sorter = (a, b) => { const la = W.forCompany(a.key).filter(o => o.kind === 'ad' && W.isLive(o)).length, lb = W.forCompany(b.key).filter(o => o.kind === 'ad' && W.isLive(o)).length; switch (st.sort) { case 'reviews': return b.reviews - a.reviews; case 'dr': return (b.dr || 0) - (a.dr || 0); case 'paid': return (b.paid_kw || 0) - (a.paid_kw || 0); case 'live': return lb - la || b.reviews - a.reviews; case 'checked': return String(W.meta(a.key).lastChecked || '').localeCompare(String(W.meta(b.key).lastChecked || '')) || b.reviews - a.reviews; case 'name': return a.name.localeCompare(b.name); default: return W.score(b) - W.score(a) || b.reviews - a.reviews; } };
    const visible = () => W.COMPANIES.filter(passes).sort(sorter);
    /* ---------- KPIs and digest ---------- */
    function kpis() {
      const s = W.stats(); const tracked = W.COMPANIES.filter(c => !W.isBench(c)); const tune = s.prices.filter(p => p.line === 'maint' && p.price > 0 && p.price < 400).map(p => p.price);
      $('#w13Kpis', root).innerHTML = kpiHTML([
        { l: 'Companies tracked', g: 'C', v: N(tracked.length), d: `${N(tracked.filter(c => c.tier === 'top40').length)} deep dive · ${N(COMP.length)} locations` },
        { l: 'Live ads on record', g: 'C', v: N(s.live), d: `${N(Object.keys(s.byComp).length)} companies · ${N(s.ads)} ads logged in all` },
        { l: 'Paid search (Ahrefs)', g: 'C', v: N(tracked.filter(c => c.paid_kw > 0).length), d: `companies with paid keywords on ${esc(W.ROSTER_DATE)}; LSA not visible` },
        { l: 'Offers on record', g: 'C', v: N(Object.values(s.byOffer).reduce((a, b) => a + b, 0)), d: `${N(s.fin.length)} financing · ${N(s.byOffer.membership || 0)} memberships` },
        { l: 'Median tune up price', g: 'C', v: tune.length ? M$(median(tune)) : '—', d: tune.length ? `${N(tune.length)} priced offers, ${M$(Math.min(...tune))} to ${M$(Math.max(...tune))}` : 'no priced maintenance offer yet' },
        { l: 'Satchel flags', g: 'B', v: N(s.lints), d: 'entries whose copy trips a rule' },
        { l: 'Last sweep', g: '', v: s.lastSweep ? esc(s.lastSweep) : 'none', d: s.lastObs ? `last observation ${esc(s.lastObs)}` : `seed only (${esc(W.ROSTER_DATE)} intel)` },
      ].map(k => k.g ? k : { ...k, g: '' }));
      $('#w13Digest', root).innerHTML = W.digest().map(d => `<li>${d}</li>`).join('');
    }
    /* ---------- board ---------- */
    function board() {
      const vis = visible(); const s = W.stats();
      if (st.view === 'cards') {
        $('#w13Board', root).hidden = false; $('#w13Table', root).hidden = true;
        st.limit = st.limit || 20; $('#w13Board', root).innerHTML = vis.slice(0, st.limit).map(c => { const obs = W.forCompany(c.key); const live = obs.filter(o => o.kind === 'ad' && W.isLive(o)); const plats = {}; live.forEach(o => plats[o.platform] = (plats[o.platform] || 0) + 1); const m = W.meta(c.key); const fin = obs.find(o => o.offer && o.offer.type === 'financing'), mem = obs.find(o => o.offer && o.offer.type === 'membership'), promo = obs.filter(o => o.kind === 'offer' && o.offer.type !== 'financing' && o.offer.type !== 'membership'); const stale = !m.lastChecked || W.daysAgo(m.lastChecked) > 14;
          return `<div class="wcard ${c.key === st.sel ? 'sel' : ''}" data-k="${esc(c.key)}"><div class="wtop"><div class="wname">${esc(c.name)}</div><div class="wscore" title="Activity score">${Math.round(W.score(c))}</div></div><div class="wmeta">${esc(c.cities.slice(0, 3).join(', '))}${c.cities.length > 3 ? ` +${c.cities.length - 3}` : ''}${c.locs.length > 1 ? ` · ${c.locs.length} locations` : ''} · ${c.tier === 'top40' ? 'deep dive' : 'roster'}</div>
            <div class="wstats"><span><b>${c.rating != null ? D(c.rating, 1) + '★' : '—'}</b> ${N(c.reviews)} rev</span><span><b>DR ${D(c.dr, 0)}</b></span><span><b>${N(c.org_traffic)}</b> org/mo</span><span class="${c.paid_kw > 0 ? 'hot' : ''}"><b>${N(c.paid_kw)}</b> paid kw</span></div>
            <div class="wbadges">${Object.entries(plats).map(([p, n]) => `${platB(p)}<em>${n}</em>`).join('')}${!live.length ? '<span class="mini">no live ads on record</span>' : ''}</div>
            <div class="wtags">${fin ? '<span class="tag on">financing</span>' : ''}${mem ? '<span class="tag on">membership</span>' : ''}${promo.length ? `<span class="tag">${promo.length} promo${promo.length > 1 ? 's' : ''}</span>` : ''}${SLM.adSignal(COMP[c.locs[0]]) ? '<span class="tag">tracking numbers</span>' : ''}${obs.some(o => (o.lint || []).length) ? '<span class="tag" style="border-color:var(--critical);color:var(--critical)">satchel flag</span>' : ''}</div>
            <div class="wlinks"><a href="${W.LINKS.metaKw(c.name)}" target="_blank" rel="noopener">Meta ↗</a>${c.domain ? `<a href="${W.LINKS.googleDomain(c.domain)}" target="_blank" rel="noopener">Google ↗</a>` : ''}<button class="lnk" data-log="${esc(c.key)}">Log</button><button class="lnk" data-chk="${esc(c.key)}" title="${m.lastChecked ? 'Checked ' + m.lastChecked : 'Never checked'}">${stale ? 'Mark checked' : 'Checked ' + m.lastChecked}</button></div></div>`; }).join('') || '<div class="card"><div class="card-b mini">No company matches these filters.</div></div>'; if (vis.length > st.limit) $('#w13Board', root).insertAdjacentHTML('beforeend', `<div class="wmore" style="grid-column:1/-1"><button class="btn sec sm" id="w13More">Show ${Math.min(40, vis.length - st.limit)} more of ${N(vis.length)} companies</button></div>`); const mb = $('#w13More', root); if (mb) mb.onclick = () => { st.limit += 40; board(); };
        $$('#w13Board .wcard', root).forEach(d => d.onclick = e => { if (e.target.closest('a,button')) return; select(d.dataset.k); $('#w13Detail', root).scrollIntoView({ behavior: 'smooth', block: 'start' }); });
        $$('#w13Board [data-log]', root).forEach(b => b.onclick = () => { select(b.dataset.log); st.formComp = b.dataset.log; form(); $('#w13Form', root).scrollIntoView({ behavior: 'smooth', block: 'center' }); });
        $$('#w13Board [data-chk]', root).forEach(b => b.onclick = () => { W.setMeta(b.dataset.chk, { lastChecked: W.today() }); });
      } else {
        $('#w13Board', root).hidden = true; $('#w13Table', root).hidden = false;
        dataTable($('#w13Tbl', root), [{ k: 'name', h: 'Company', l: 1 }, { k: 'cities', h: 'Cities', l: 1, v: c => c.cities.join(', ') }, { k: 'tier', h: 'Tier', l: 1 }, { k: 'score', h: 'Score', v: c => Math.round(W.score(c)) }, { k: 'live', h: 'Live ads', v: c => W.forCompany(c.key).filter(o => o.kind === 'ad' && W.isLive(o)).length }, { k: 'reviews', h: 'Reviews', f: v => N(v) }, { k: 'rating', h: 'Rating', f: v => D(v, 1) }, { k: 'dr', h: 'DR', f: v => D(v, 0) }, { k: 'paid_kw', h: 'Paid kw', f: v => N(v) }, { k: 'fin', h: 'Financing', l: 1, v: c => (W.forCompany(c.key).find(o => o.offer && o.offer.type === 'financing') || { offer: { fin: '' } }).offer.fin || '' }, { k: 'chk', h: 'Checked', l: 1, v: c => W.meta(c.key).lastChecked || '' }, { k: 'domain', h: 'Domain', l: 1 }], vis, { sortKey: 'score', id: c => c.key, onClick: k => select(k), rowClass: c => c.key === st.sel ? 'sel' : '' });
      }
    }
    function select(key) { st.sel = key; st.formComp = key; detail(); form(); geo(); $$('#w13Board .wcard', root).forEach(d => d.classList.toggle('sel', d.dataset.k === key)); }
    /* ---------- detail ---------- */
    function detail() {
      const c = W.CI[st.sel]; if (!c) { $('#w13DName', root).textContent = 'Select a company'; $('#w13DPill', root).textContent = ''; $('#w13Detail', root).innerHTML = '<p class="mini">The detail panel shows the roster profile, the identifiers you record, every library link and the observation timeline.</p>'; return; }
      const m = W.meta(c.key); const obs = W.forCompany(c.key); const I = c.intel;
      $('#w13DName', root).textContent = c.name; $('#w13DSub', root).innerHTML = `${esc(c.cities.join(', '))} · ${c.locs.length} location${c.locs.length > 1 ? 's' : ''} · ${esc(c.domain || 'no domain on file')}`; $('#w13DPill', root).textContent = c.tier === 'top40' ? 'Deep dive' : 'Roster';
      const kv = a => a.filter(x => x[1] != null && x[1] !== '' && x[1] !== '-').map(([k, v]) => `<div class="rowl"><span>${k}</span><b style="font-weight:500;text-align:right;max-width:60%">${v}</b></div>`).join('');
      $('#w13Detail', root).innerHTML = `<div class="dsec">Roster profile (${esc(W.ROSTER_DATE)})</div>${kv([['Google rating · reviews', `${c.rating != null ? D(c.rating, 1) + '★' : '—'} · ${N(c.reviews)}`], ['Domain rating · organic visits', `${D(c.dr, 0)} · ${N(c.org_traffic)} a month`], ['Paid keywords (Ahrefs)', N(c.paid_kw)], ['Founded', c.founded], ['Scope', esc(c.scope || '')], ['Brands', c.brands.length ? c.brands.map(b => `<span class="tag on">${esc(b)}</span>`).join('') : null]])}
        <div style="margin-top:6px">${c.services.map(s => `<span class="tag">${esc(s)}</span>`).join('')}</div>
        ${I ? `<div class="dsec">Website intel</div>${[['Tagline', I.tagline], ['Financing', I.financing], ['Promos', I.promos], ['Membership', I.membership], ['Ad signals', I.ad_signals], ['Notes', I.key_notes]].filter(x => x[1] && x[1] !== '-').map(([k, v]) => `<p class="mini" style="color:var(--ink-2)"><b style="color:var(--ink)">${k}:</b> ${esc(v)}</p>`).join('')}` : ''}
        <div class="dsec">Identifiers (yours to record)</div><div class="plan"><div class="f"><label class="fl" for="w13PageId">Meta Page ID</label><input type="text" id="w13PageId" value="${esc(m.pageId || '')}" placeholder="numeric, from the Page's About or an ad's details"></div><div class="f"><label class="fl" for="w13AdvId">Google advertiser ID</label><input type="text" id="w13AdvId" value="${esc(m.advId || '')}" placeholder="AR followed by digits"></div><div class="f wide"><label class="fl" for="w13Alias">Aliases and notes</label><input type="text" id="w13Alias" value="${esc(m.notes || '')}" placeholder="former names, Page names, agencies, anything that helps a match"></div></div>
        <div style="display:flex;gap:8px;margin-top:8px;flex-wrap:wrap"><button class="btn sm" id="w13SaveIds">Save identifiers</button><button class="btn sec sm" id="w13Chk">Mark checked today</button><button class="btn sec sm" id="w13ToSat">Screen in the Satchel</button><button class="btn sec sm" id="w13ToSup">Supply Line profile</button></div>
        <div class="dsec">Library links</div>${linkList(compLinks(c, m))}
        <div class="dsec">Observations (${obs.length})${m.lastChecked ? ` · checked ${esc(m.lastChecked)}` : ' · never checked'}</div>
        <div class="tl">${obs.map(o => `<div class="tli ${o.src === 'seed' ? 'seed' : ''}"><div class="tlh">${platB(o.platform)} <b>${esc(W.KINDS[o.kind] || o.kind)}</b>${o.line ? ` · ${esc(lineN(o.line))}` : ''} · <span class="mini">${esc(o.first)}${o.last && o.last !== o.first ? ' to ' + esc(o.last) : ''} · ${esc(o.status)}${o.src === 'seed' ? ' · seed' : o.src === 'meta-api' ? ' · API' : ''}</span></div><div class="tlt">${esc(o.text || o.offer.text || '')}${o.offer && o.offer.type !== 'none' && o.kind !== 'offer' ? ` <span class="tag">${esc(W.OFFERS[o.offer.type])}${isN(o.offer.price) ? ' ' + M$(o.offer.price) : ''}</span>` : ''}${o.reviews ? ` <span class="tag">${N(o.reviews.count)} reviews${o.reviews.rating ? ' · ' + D(o.reviews.rating, 1) + '★' : ''}</span>` : ''}${(o.lint || []).map(id => `<span class="tag" style="border-color:var(--critical);color:var(--critical)">${esc(id)}</span>`).join('')}</div><div class="tla">${o.snapshot ? `<a href="${esc(o.snapshot)}" target="_blank" rel="noopener">open ↗</a>` : ''}${o.url ? `<a href="${esc(/^https?:/.test(o.url) ? o.url : 'https://' + o.url)}" target="_blank" rel="noopener">landing ↗</a>` : ''}<button class="lnk" data-edit="${o.id}">edit</button><button class="lnk" data-del="${o.id}">delete</button></div></div>`).join('') || '<p class="mini">Nothing on record. Open the library links, then log what you see.</p>'}</div>`;
      $('#w13SaveIds', root).onclick = () => { W.setMeta(c.key, { pageId: $('#w13PageId', root).value.trim(), advId: $('#w13AdvId', root).value.trim(), notes: $('#w13Alias', root).value.trim() }); toast('Identifiers saved'); };
      $('#w13Chk', root).onclick = () => { W.setMeta(c.key, { lastChecked: W.today() }); toast(`${c.name} marked checked`); };
      $('#w13ToSat', root).onclick = () => goModule('satchel', { target: c.name, domain: c.domain, posture: 'comp' }); $('#w13ToSup', root).onclick = () => goModule('supply', { comp: c.locs[0] });
      $$('#w13Detail [data-edit]', root).forEach(b => b.onclick = () => { st.edit = b.dataset.edit; form(); $('#w13Form', root).scrollIntoView({ behavior: 'smooth', block: 'center' }); });
      $$('#w13Detail [data-del]', root).forEach(b => b.onclick = () => { if (b.dataset.confirm) { W.remove(b.dataset.del); toast('Deleted'); } else { b.dataset.confirm = '1'; b.textContent = 'confirm delete'; } });
    }
    /* ---------- form ---------- */
    function form() {
      const o = st.edit ? W.obs.find(x => x.id === st.edit) : null; const v = o || W.blankObs({ comp: st.formComp || '' }); $('#w13FTitle', root).textContent = o ? `Edit observation · ${o.compName}` : 'Log an observation';
      const opt = (obj, sel, blank) => (blank ? `<option value="">${blank}</option>` : '') + Object.entries(obj).map(([k, l]) => `<option value="${k}" ${k === sel ? 'selected' : ''}>${esc(l)}</option>`).join('');
      $('#w13Form', root).innerHTML = `<div class="plan">
        <div class="f wide"><label class="fl" for="wfComp">Company</label><select id="wfComp"><option value="">Not on the roster (name below)</option>${W.COMPANIES.filter(c => !W.isBench(c)).map(c => `<option value="${esc(c.key)}" ${c.key === v.comp ? 'selected' : ''}>${esc(c.name)} · ${esc(c.cities[0])}</option>`).join('')}</select></div>
        <div class="f"><label class="fl" for="wfName">Name if not on the roster</label><input type="text" id="wfName" value="${esc(v.comp ? '' : v.compName)}"></div>
        <div class="f"><label class="fl" for="wfKind">Kind</label><select id="wfKind">${opt(W.KINDS, v.kind)}</select></div>
        <div class="f"><label class="fl" for="wfPlat">Platform</label><select id="wfPlat">${opt(W.PLATFORMS, v.platform)}</select></div>
        <div class="f"><label class="fl" for="wfStatus">Status</label><select id="wfStatus">${['active', 'inactive', 'unknown'].map(s => `<option ${s === v.status ? 'selected' : ''}>${s}</option>`).join('')}</select></div>
        <div class="f"><label class="fl" for="wfFirst">First seen · last seen</label><div style="display:flex;gap:6px"><input type="date" id="wfFirst" value="${esc(v.first)}"><input type="date" id="wfLast" value="${esc(v.last)}"></div></div>
        <div class="f"><label class="fl" for="wfFormat">Format</label><select id="wfFormat">${W.FORMATS.map(f => `<option ${f === v.format ? 'selected' : ''}>${f}</option>`).join('')}</select></div>
        <div class="f"><label class="fl" for="wfLine">Service line</label><select id="wfLine">${lineOpts(v.line)}</select></div>
        <div class="f"><label class="fl" for="wfOffer">Offer type</label><select id="wfOffer">${opt(W.OFFERS, v.offer.type)}</select></div>
        <div class="f"><label class="fl" for="wfPrice">Price ($)</label><input type="number" id="wfPrice" value="${isN(v.offer.price) ? v.offer.price : ''}" step="1"></div>
        <div class="f wide"><label class="fl" for="wfOfferT">Offer text</label><input type="text" id="wfOfferT" value="${esc(v.offer.text)}" placeholder="$79 tune up, $500 off a new system, free second opinion"></div>
        <div class="f wide"><label class="fl" for="wfFin">Financing terms as stated</label><input type="text" id="wfFin" value="${esc(v.offer.fin)}" placeholder="0% for 60 months, no payments until spring"></div>
        <div class="f wide"><label class="fl" for="wfText">Creative copy or what you saw</label><textarea id="wfText" style="min-height:64px">${esc(v.text)}</textarea></div>
        <div class="f"><label class="fl" for="wfHook">Hook</label><select id="wfHook">${W.HOOKS.map(h => `<option ${h === v.hook ? 'selected' : ''}>${h}</option>`).join('')}</select></div>
        <div class="f"><label class="fl" for="wfCta">Call to action</label><input type="text" id="wfCta" value="${esc(v.cta)}" placeholder="Book now, Call today, Get a quote"></div>
        <div class="f"><label class="fl" for="wfLang">Language</label><select id="wfLang"><option value="en" ${v.lang === 'en' ? 'selected' : ''}>English</option><option value="es" ${v.lang === 'es' ? 'selected' : ''}>Spanish</option></select></div>
        <div class="f wide"><label class="fl" for="wfUrl">Landing URL</label><input type="url" id="wfUrl" value="${esc(v.url)}"></div>
        <div class="f"><label class="fl" for="wfGeo">Geography named</label><input type="text" id="wfGeo" value="${esc(v.geo)}" placeholder="Plano, Collin County, north Dallas"></div>
        <div class="f"><label class="fl" for="wfZips">ZIPs named or targeted</label><input type="text" id="wfZips" value="${esc((v.zips || []).join(' '))}" placeholder="75093 75024"></div>
        <div class="f"><label class="fl" for="wfLib">Meta Library ID · Page ID</label><div style="display:flex;gap:6px"><input type="text" id="wfLib" value="${esc(v.ids.lib)}"><input type="text" id="wfPage" value="${esc(v.ids.page)}"></div></div>
        <div class="f"><label class="fl" for="wfAdv">Google advertiser ID · creative ID</label><div style="display:flex;gap:6px"><input type="text" id="wfAdv" value="${esc(v.ids.adv)}"><input type="text" id="wfCr" value="${esc(v.ids.cr)}"></div></div>
        <div class="f wide"><label class="fl" for="wfSnap">Snapshot or library URL</label><input type="url" id="wfSnap" value="${esc(v.snapshot)}"></div>
        <div class="f"><label class="fl" for="wfRevN">Review snapshot: count · rating</label><div style="display:flex;gap:6px"><input type="number" id="wfRevN" value="${v.reviews ? v.reviews.count : ''}" style="width:100px"><input type="number" id="wfRevR" value="${v.reviews && v.reviews.rating ? v.reviews.rating : ''}" step="0.1" style="width:80px"></div></div>
        <div class="f wide"><label class="fl" for="wfNotes">Notes</label><input type="text" id="wfNotes" value="${esc(v.notes)}"></div>
      </div><div id="wfLint" style="margin-top:8px"></div>
      <div style="display:flex;gap:8px;margin-top:10px;flex-wrap:wrap"><button class="btn sm" id="wfSave">${o ? 'Save changes' : 'Add to the ledger'}</button>${o ? '<button class="btn sec sm" id="wfCancel">Cancel</button>' : ''}<button class="btn ghost sm" id="wfLinks">Library links for this company</button></div>`;
      const read = () => { const compKey = $('#wfComp', root).value; const c = W.CI[compKey]; return { comp: c ? c.key : '', compName: c ? c.name : ($('#wfName', root).value.trim() || 'Unnamed advertiser'), kind: $('#wfKind', root).value, platform: $('#wfPlat', root).value, status: $('#wfStatus', root).value, first: $('#wfFirst', root).value || W.today(), last: $('#wfLast', root).value || $('#wfFirst', root).value || W.today(), format: $('#wfFormat', root).value, line: $('#wfLine', root).value, offer: { type: $('#wfOffer', root).value, text: $('#wfOfferT', root).value.trim(), price: $('#wfPrice', root).value === '' ? null : +$('#wfPrice', root).value, fin: $('#wfFin', root).value.trim() }, text: $('#wfText', root).value.trim(), hook: $('#wfHook', root).value, cta: $('#wfCta', root).value.trim(), lang: $('#wfLang', root).value, url: $('#wfUrl', root).value.trim(), geo: $('#wfGeo', root).value.trim(), zips: $('#wfZips', root).value.split(/[\s,;]+/).filter(z => ZI[z]), ids: { lib: $('#wfLib', root).value.trim(), page: $('#wfPage', root).value.trim(), adv: $('#wfAdv', root).value.trim(), cr: $('#wfCr', root).value.trim() }, snapshot: $('#wfSnap', root).value.trim(), reviews: $('#wfRevN', root).value ? { count: +$('#wfRevN', root).value, rating: $('#wfRevR', root).value ? +$('#wfRevR', root).value : null } : null, notes: $('#wfNotes', root).value.trim(), src: o ? o.src : 'manual' }; };
      const lintNow = () => { const f = W.lintObs(read()); $('#wfLint', root).innerHTML = f.length ? f.map(id => { const r = SAT.rules.find(x => x.id === id); return `<div class="issue ${r.sev}"><b>${esc(r.id)} · ${esc(r.name)}</b> <span class="mini">${esc(r.cite)}</span></div>`; }).join('') : '<p class="mini">No Satchel rule tripped by this copy.</p>'; };
      ['wfText', 'wfOfferT', 'wfFin', 'wfCta'].forEach(id => $('#' + id, root).addEventListener('input', debounce(lintNow, 300))); lintNow();
      $('#wfComp', root).onchange = () => { st.formComp = $('#wfComp', root).value; };
      $('#wfSave', root).onclick = () => { const data = read(); if (o) { W.update(o.id, data); st.edit = null; toast('Observation updated'); } else { const ob = W.add(data); if (data.ids.page && ob.comp) W.setMeta(ob.comp, { pageId: data.ids.page }); if (data.ids.adv && ob.comp) W.setMeta(ob.comp, { advId: data.ids.adv }); toast('Added to the ledger'); if (ob.comp) { st.sel = ob.comp; } } form(); };
      if (o) $('#wfCancel', root).onclick = () => { st.edit = null; form(); };
      $('#wfLinks', root).onclick = () => { const c = W.CI[$('#wfComp', root).value]; if (!c) { toast('Pick a roster company first'); return; } select(c.key); $('#w13Detail', root).scrollIntoView({ behavior: 'smooth', block: 'start' }); };
    }
    /* ---------- import ---------- */
    function doImport(text) { const r = W.importText(text, st.formComp || st.sel || ''); if (r.obs.length || r.meta.pageId || r.meta.advId) { const key = st.formComp || st.sel || ''; W.addMany(r.obs, key, r.meta); $('#w13PasteNote', root).textContent = `Imported: ${r.note}.`; toast(`Imported ${r.obs.length} entries`); } else $('#w13PasteNote', root).textContent = r.note; }
    $('#w13PasteGo', root).onclick = () => doImport($('#w13Paste', root).value);
    $('#w13File', root).onchange = e => { const f = e.target.files && e.target.files[0]; if (!f) return; const rd = new FileReader(); rd.onload = () => { const t = String(rd.result || ''); let j = null; try { j = JSON.parse(t); } catch (_) { } if (j && Array.isArray(j.obs) && j.meta) { W.replaceAll(j); toast(`Ledger replaced: ${j.obs.length} entries`); } else doImport(t); e.target.value = ''; }; rd.readAsText(f); };
    $('#w13Import', root).onclick = () => $('#w13File', root).click();
    /* ---------- API bridge ---------- */
    function apiOpts() { const pages = $('#w13Pages', root).value.split(/[\s,;]+/).filter(Boolean); return { token: $('#w13Tok', root).value.trim(), terms: pages.length ? '' : $('#w13Terms', root).value.trim(), pageIds: pages, adType: $('#w13Type', root).value, status: $('#w13Status', root).value, since: $('#w13Since', root).value, version: $('#w13Ver', root).value.trim() || 'v21.0', limit: +$('#w13Lim', root).value || 100, maxPages: +$('#w13Pg', root).value || 3 }; }
    function apiUrlShow() { const o = apiOpts(); if (!o.terms && !o.pageIds.length) { $('#w13Url', root).textContent = 'Enter search terms or at least one Page ID.'; $('#w13ApiNote', root).textContent = ''; $('#w13Open', root).removeAttribute('href'); return; } const u = W.metaApiUrl(o); const shown = o.token ? u.replace(o.token, o.token.slice(0, 6) + '…') : u; $('#w13Url', root).textContent = shown; $('#w13Open', root).href = u; $('#w13ApiNote', root).textContent = W.canFetch() ? (o.token ? 'This page can call the Graph API directly from here.' : 'Add a token to run, or open the URL after adding it to the query.') : 'Inside the Claude viewer the platform call is blocked; open the URL in a new tab (with the token) and paste the JSON answer into the import box.'; }
    ['w13Tok', 'w13Terms', 'w13Pages', 'w13Type', 'w13Status', 'w13Since', 'w13Ver', 'w13Lim', 'w13Pg'].forEach(id => $('#' + id, root).addEventListener('input', apiUrlShow));
    $('#w13Keep', root).checked = !!W.settings().keepToken; if (W.settings().keepToken && W.settings().token) $('#w13Tok', root).value = W.settings().token;
    $('#w13Keep', root).onchange = e => W.setSettings({ keepToken: e.target.checked, token: e.target.checked ? $('#w13Tok', root).value.trim() : '' });
    $('#w13Tok', root).addEventListener('change', () => { if (W.settings().keepToken) W.setSettings({ token: $('#w13Tok', root).value.trim() }); });
    $('#w13Copy', root).onclick = () => copyText(W.metaApiUrl(apiOpts()));
    $('#w13Run', root).onclick = async () => { const o = apiOpts(); if (!o.token) { $('#w13ApiOut', root).innerHTML = '<div class="msg err">A token is required. Create an app at developers.facebook.com, open the Graph API Explorer, generate a user token and paste it above.</div>'; return; } if (!W.canFetch()) { $('#w13ApiOut', root).innerHTML = '<div class="msg err">The Claude viewer blocks calls to graph.facebook.com. Copy the request URL, open it in a new tab and paste the JSON into the import box, or open the downloaded atlas file in a browser where the request runs directly.</div>'; return; } $('#w13ApiOut', root).innerHTML = '<div class="status">Requesting…</div>'; try { const items = await W.metaApiRun(o); const r = W.importText(JSON.stringify({ data: items }), st.formComp || ''); W.addMany(r.obs); $('#w13ApiOut', root).innerHTML = `<div class="msg ok">${N(items.length)} ads returned; ${N(r.obs.filter(x => x.comp).length)} matched to roster companies by domain or name, ${N(r.obs.filter(x => !x.comp).length)} kept as unmatched pages.</div>`; } catch (e) { $('#w13ApiOut', root).innerHTML = `<div class="msg err">${esc(e.message || String(e))}. A network error here usually means the browser refused the cross origin call or the token lacks access; the URL still works in a new tab.</div>`; } };
    /* ---------- analytics ---------- */
    function analytics() {
      const s = W.stats(); const cols = CAT();
      const sov = Object.entries(s.byComp).map(([k, n]) => ({ l: (W.CI[k] || { name: k }).name, v: n })).sort((a, b) => b.v - a.v).slice(0, 15);
      if (sov.length) hbarChart($('#w13Sov', root), sov.map(r => ({ l: r.l.length > 30 ? r.l.slice(0, 29) + '…' : r.l, v: r.v, color: cssv('--s1'), t: N(r.v) })), { L: 210, W: 700, rowH: 22 }); else $('#w13Sov', root).innerHTML = '<p class="mini">No live ads on record yet. Log ads from the libraries and the chart fills.</p>';
      const wk = W.weekly(26); const lab = i => { const d = new Date(wk[i].t); return `${d.getMonth() + 1}/${d.getDate()}`; };
      lineChart($('#w13Week', root), { H: 220, series: [{ name: 'Meta', color: cssv('--s1'), pts: wk.map((w, i) => [i, w.meta]), area: true }, { name: 'Google, LSA, YouTube', color: cssv('--s2'), pts: wk.map((w, i) => [i, w.google]) }, { name: 'Other', color: cssv('--ink-3'), pts: wk.map((w, i) => [i, w.other]), dash: '4 3' }], x: { min: 0, max: 25, ticks: [0, 5, 10, 15, 20, 25], fmt: v => lab(v) }, y: { min: 0, max: Math.max(4, ...wk.map(w => Math.max(w.meta, w.google, w.other))), fmt: v => D(v, 0), n: 4 }, aria: 'Ads logged by week', tipTitle: i => 'Week of ' + lab(i) });
      $('#w13WeekN', root).innerHTML = legendRow([{ name: 'Meta', color: cssv('--s1') }, { name: 'Google, LSA, YouTube', color: cssv('--s2') }, { name: 'Other', color: cssv('--ink-3'), dash: true }]) + `${N(s.ads)} ads logged in all; the curve is your logging cadence as much as their launch cadence.`;
      const offers = Object.entries(s.byOffer).filter(([k]) => k !== 'none').map(([k, n]) => ({ l: W.OFFERS[k], v: n })).sort((a, b) => b.v - a.v);
      $('#w13Offers', root).innerHTML = (offers.length ? '<div id="w13OffC"></div>' : '<p class="mini">No offers on record.</p>') + `<div class="dsec">Price points</div>${s.prices.length ? `<div class="tscroll short"><table><thead><tr><th class="l">Company</th><th class="l">Line</th><th class="l">Type</th><th>Price</th><th class="l">Text</th><th class="l">Seen</th></tr></thead><tbody>${s.prices.sort((a, b) => a.price - b.price).map(p => `<tr><td class="l">${esc(p.comp)}</td><td class="l">${esc(lineN(p.line))}</td><td class="l">${esc(W.OFFERS[p.type] || p.type)}</td><td>${M$(p.price)}</td><td class="l" title="${esc(p.text)}">${esc(p.text.length > 48 ? p.text.slice(0, 47) + '…' : p.text)}</td><td class="l">${esc(p.last)}</td></tr>`).join('')}</tbody></table></div>` : '<p class="mini">No priced offer yet.</p>'}<div class="dsec">Financing terms</div>${s.fin.length ? `<div class="tscroll short"><table><thead><tr><th class="l">Company</th><th class="l">As stated</th><th class="l">Satchel</th><th class="l">Seen</th></tr></thead><tbody>${s.fin.map(f => `<tr><td class="l">${esc(f.comp)}</td><td class="l" title="${esc(f.text)}">${esc(f.text.length > 60 ? f.text.slice(0, 59) + '…' : f.text)}</td><td class="l">${f.lint.length ? f.lint.map(id => `<span class="disp ${id === 'REGZ1' || id === 'TAX1' ? 'c' : 'k'}">${esc(id)}</span>`).join(' ') : '<span class="disp n">clear</span>'}</td><td class="l">${esc(f.last)}</td></tr>`).join('')}</tbody></table></div>` : '<p class="mini">No financing offer on record.</p>'}`;
      if (offers.length) hbarChart($('#w13OffC', root), offers.map((r, i) => ({ l: r.l, v: r.v, color: cols[i % cols.length], t: N(r.v) })), { L: 190, W: 640, rowH: 22 });
      const hooks = Object.entries(s.byHook).sort((a, b) => b[1] - a[1]); const lines = Object.entries(s.byLine).sort((a, b) => b[1] - a[1]);
      $('#w13Hooks', root).innerHTML = `<div class="dsec">Hooks</div><div class="chips">${hooks.map(([k, v]) => `<span class="chip" style="cursor:default">${esc(k)} <b>${v}</b></span>`).join('') || '<span class="mini">none yet</span>'}</div><div class="dsec">Service lines promoted</div>${lines.length ? '<div id="w13LineC"></div>' : '<p class="mini">none yet</p>'}<p class="mini" style="margin-top:8px">Hooks are inferred from the copy on import and set by hand when you log. A hook that dominates the field is a hook the market has already priced; the quiet ones are where a distinct message still reads as new.</p>`;
      if (lines.length) hbarChart($('#w13LineC', root), lines.map((r, i) => ({ l: lineN(r[0]), v: r[1], color: cssv('--heat'), t: N(r[1]) })), { L: 150, W: 600, rowH: 22 });
      const compsObs = W.COMPANIES.filter(c => !W.isBench(c) && W.forCompany(c.key).length).sort((a, b) => W.score(b) - W.score(a)).slice(0, 40); const cell = n => { if (!n) return '<td style="color:var(--ink-3)">·</td>'; const t = clamp(n / 4, 0.15, 1); return `<td style="background:color-mix(in srgb, ${cssv('--heat')} ${Math.round(t * 70)}%, ${cssv('--card')});color:${t > .6 ? '#fff' : 'inherit'}">${n}</td>`; };
      $('#w13Cov', root).innerHTML = compsObs.length ? `<table class="cm"><thead><tr><th></th>${SLM.LINES.map(l => `<th>${esc(l.short)}</th>`).join('')}<th>Untyped</th></tr></thead><tbody>${compsObs.map(c => { const obs = W.forCompany(c.key); const m = {}; obs.forEach(o => m[o.line || '_'] = (m[o.line || '_'] || 0) + 1); return `<tr><th class="rh">${esc(c.name.length > 28 ? c.name.slice(0, 27) + '…' : c.name)}</th>${SLM.LINES.map(l => cell(m[l.id] || 0)).join('')}${cell(m._ || 0)}</tr>`; }).join('')}</tbody></table>` : '<p class="mini">No observations yet.</p>';
    }
    /* ---------- geography ---------- */
    const map = new ZipMap($('#w13Map', root), { onSelect: zip => { st.zip = st.zip === zip ? null : zip; geo(); }, onHover: (zip, e) => { const z = ZI[zip]; if (!z || z.occ < 200) return; const n = W.zipCounts()[zip] || 0; showTip(`<div class="tt">${zip} · ${esc(z.city)}</div>${tipRow('Observed ads naming this ZIP', N(n))}${tipRow('Paid efficiency', D(z.effb, 0))}${tipRow('Replacement priority', D(z.sl_pri_replace, 0))}${tipRow('Mapped competitors within 8 km', N(z.comp_n8))}`, e); }, onPin: id => { const sid = String(id); if (sid.startsWith('c')) { const k = SLM.compKey(COMP[+sid.slice(1)]); if (W.CI[k]) select(k); } else { st.zip = sid.slice(1); geo(); } }, onPinHover: (id, e) => { if (String(id).startsWith('c')) { const l = COMP[+String(id).slice(1)]; showTip(`<div class="tt">${esc(l.name)}</div><div class="ts">${esc(l.city)}</div>`, e); } else { const z = ZI[String(id).slice(1)]; showTip(`<div class="tt">${z.zip} · ${esc(z.city)}</div>${tipRow('Observed ads', N(W.zipCounts()[z.zip] || 0))}`, e); } } });
    function geo() {
      const zc = W.zipCounts(); const base = st.geoLayer;
      if (base === 'none') { map.fill(() => cssv('--sunk')); $('#w13Leg', root).innerHTML = '<div class="dn">Pins: orange squares are ZIPs named in logged ads (size = count); blue diamonds are the selected company\'s locations.</div>'; }
      else { const GL = { effb: { l: 'Paid efficiency percentile (module 05)', ramp: 'ember', f: v => D(v, 0) }, comp_mass: LAYERS.comp_mass }; const Lr = GL[base] || LAYERS[base] || { l: base, ramp: 'ember', f: v => D(v, 0) }; const sc = qScale(ZR.map(z => z[base]), Lr.ramp || 'ember', 1); map.fill(zip => { const z = ZI[zip]; return z && z.occ >= 200 && isN(z[base]) ? sc.f(z[base]) : null; }); const v = ZR.map(z => z[base]).filter(isN); $('#w13Leg', root).innerHTML = legendHTML({ title: Lr.l, R: sc.R, lo: (Lr.f || D)(Math.min(...v)), hi: (Lr.f || D)(Math.max(...v)), note: 'Pins: orange are ZIPs named in logged ads (size = count); blue diamonds are the selected company\'s locations.' }); }
      const pins = Object.entries(zc).filter(([z]) => ZI[z] && isN(ZI[z].lat)).map(([z, n]) => ({ id: 'z' + z, lat: ZI[z].lat, lon: ZI[z].lon, r: 3 + Math.min(9, n * 1.5), fill: cssv('--heat'), op: .85 }));
      const c = W.CI[st.sel]; if (c) c.locs.forEach(i => { const l = COMP[i]; if (isN(l.lat)) pins.push({ id: 'c' + i, lat: l.lat, lon: l.lon, r: 7, fill: cssv('--s1'), shape: 'diamond' }); });
      map.pins(pins); map.select(st.zip);
      const named = new Set(Object.keys(zc)); const namedCities = new Set(); W.obs.forEach(o => { if (o.geo) o.geo.split(/[,;]+/).forEach(g => namedCities.add(g.trim().toLowerCase())); });
      const unc = ZR.filter(z => z.effb >= 75 && !named.has(z.zip) && !namedCities.has(String(z.city).toLowerCase())).sort((a, b) => b.effb - a.effb).slice(0, 12);
      $('#w13Geo2', root).innerHTML = `${st.zip ? `<div class="dsec">${st.zip} · ${esc(ZI[st.zip].city)}</div><div class="rowl"><span>Observed ads naming this ZIP</span><b>${N(zc[st.zip] || 0)}</b></div><div class="rowl"><span>Paid efficiency · replacement priority</span><b>${D(ZI[st.zip].effb, 0)} · ${D(ZI[st.zip].sl_pri_replace, 0)}</b></div>${W.obs.filter(o => (o.zips || []).includes(st.zip)).slice(0, 6).map(o => `<p class="mini"><b>${esc(o.compName)}</b> · ${esc(W.PLATFORMS[o.platform] || o.platform)} · ${esc(o.text || o.offer.text || '').slice(0, 90)}</p>`).join('')}<div style="display:flex;gap:8px;margin:8px 0 4px;flex-wrap:wrap"><button class="btn sec sm" id="w13ZLines">Service Lines for ${st.zip}</button><button class="btn sec sm" id="w13ZDesk">Campaign Desk</button></div>` : ''}<div class="dsec">Uncontested value: top efficiency, no ad on record</div>${unc.map(z => `<div class="rowl"><span><b>${z.zip}</b> ${esc(z.city)}</span><b>eff ${D(z.effb, 0)} · ${QN[z.quad]}</b></div>`).join('') || '<p class="mini">Every top quartile ZIP has an ad on record, or no observation carries geography yet.</p>'}<p class="mini" style="margin-top:8px">${N(named.size)} ZIPs and ${N(namedCities.size)} place names appear in the ledger. Geography is what the ad named or the library showed, not where it was delivered.</p>`;
      if (st.zip) { $('#w13ZLines', root).onclick = () => goModule('lines', { zip: st.zip }); $('#w13ZDesk', root).onclick = () => goModule('desk', { zips: [st.zip] }); }
    }
    $('#w13Geo', root).onchange = e => { st.geoLayer = e.target.value; geo(); };
    /* ---------- sweep ---------- */
    function sweep() {
      const rows = W.sweepRows(); rows.sort((a, b) => String(a[3]).localeCompare(String(b[3])));
      $('#w13SweepTbl', root).innerHTML = `<table><thead><tr><th class="l">Company</th><th class="l">Cities</th><th class="l">Last checked</th><th>Days</th><th>Live ads</th><th class="l">Links</th><th></th></tr></thead><tbody>${rows.map(r => { const c = W.COMPANIES.find(x => x.name === r[0]); const stale = !r[3] || r[4] > 14; return `<tr class="${stale ? '' : 'ok'}"><td class="l"><b>${esc(r[0])}</b></td><td class="l">${esc(r[2])}</td><td class="l">${r[3] ? esc(r[3]) : '<span style="color:var(--critical)">never</span>'}</td><td>${r[4] !== '' ? (r[4] > 14 ? `<span style="color:var(--critical)">${r[4]}</span>` : r[4]) : '—'}</td><td>${N(r[10])}</td><td class="l"><a href="${esc(r[5])}" target="_blank" rel="noopener">Meta</a>${r[6] ? ` · <a href="${esc(r[6])}" target="_blank" rel="noopener">Page</a>` : ''}${r[7] ? ` · <a href="${esc(r[7])}" target="_blank" rel="noopener">Google</a>` : ''}${r[8] ? ` · <a href="${esc(r[8])}" target="_blank" rel="noopener">Advertiser</a>` : ''} · <a href="${esc(r[9])}" target="_blank" rel="noopener">SERP</a></td><td><button class="lnk" data-sw="${esc(c ? c.key : '')}">${stale ? 'Mark checked' : 'Checked'}</button></td></tr>`; }).join('')}</tbody></table>`;
      $$('#w13SweepTbl [data-sw]', root).forEach(b => b.onclick = () => { if (b.dataset.sw) W.setMeta(b.dataset.sw, { lastChecked: W.today() }); });
    }
    /* ---------- prose ---------- */
    $('#w13Meth', root).innerHTML = [
      `<b>Roster.</b> The ${N(COMP.length)} locations of the August 2026 heatmap collapse to ${N(W.COMPANIES.length - 1)} competitor companies plus the benchmark client, keyed by domain (or name where a company has no site), carrying reviews summed across locations, the best rating, Ahrefs domain rating, traffic and paid keywords, service and brand lists and the website intel fields.`,
      `<b>Links.</b> The Meta Ad Library accepts a keyword search over Page names and creative (q=, search_type=keyword_unordered, country=US) and a Page view (view_all_page_id=). The Google Ads Transparency Center accepts a website (domain=) and an advertiser (advertiser/AR…). The atlas builds those URLs from the roster and from the identifiers you record.`,
      `<b>Ledger.</b> An observation is a company, a kind (ad, offer, signal, event, review snapshot), a platform, a status, first and last seen dates, a format, a service line, an offer (type, text, price, financing terms), a hook, a call to action, a landing URL, the geography named, ZIPs, language, the library identifiers, a snapshot link and notes. Every entry is screened by the Emergency Satchel rules on save.`,
      `<b>Seed.</b> The ledger opens with the website intel collected for the heatmap: promotions, financing language, memberships, tracking numbers and Local Services badges, dated ${esc(W.ROSTER_DATE)} and marked as seed. Ahrefs paid keyword counts appear as Google signals. Seeds never raise the pressure readings in module 12; only logged or imported ads do.`,
      `<b>Import.</b> A Meta Ad Library API response is normalized: Page name and link caption domain are matched to the roster (domain first, then name tokens); start and stop dates set the status; the first body and title become the text; the service line, offer type, price and hook are inferred from the copy and can be corrected. Library and Transparency Center links are parsed for Library IDs, Page IDs, advertiser IDs and creative IDs. The ledger's own CSV and JSON round trip.`,
      `<b>Activity score.</b> Paid keywords in Ahrefs (25), tracking numbers or LSA signals (10), up to 40 for live ads on record, 5 per platform, 8 for a financing offer, 6 for a membership, a little for review mass. It ranks who is buying attention, not who is best.`,
      `<b>Pressure feedback.</b> Live ads logged in the last 120 days (kind ad, status active or unknown within 60 days) add up to 2 to a company's advertiser weight in module 12's paid pressure for the lines they promote; the module recomputes on every save.`,
      `<b>Storage.</b> The ledger, identifiers, sweep dates and settings live in this browser's storage under one key and can be exported as JSON (full) or CSV (ledger). Importing a JSON export replaces the ledger; importing a CSV appends. The API token is kept only if you say so.`,
    ].map(x => `<li>${x}</li>`).join('');
    $('#w13Judg', root).innerHTML = judgList([
      ['This browser, not a server', 'The ledger is stored locally so the atlas stays a single file that works offline and can be shared without exposing anyone\'s observations. Export the JSON to move it or to keep a backup; a shared team ledger would need a database behind the page.'],
      ['Deep links over scraping', 'Both libraries are built for people, not programs, and their terms say so. The tab opens them with the right parameters and records what you saw; it does not scrape them.'],
      ['The API is used for what it covers', 'In the United States the Meta Ad Library API returns political and issue ads and the housing, employment and credit special ad categories. A competitor\'s financing ad may sit in CREDIT_ADS; its tune up ad will not appear. The bridge says so rather than pretending.'],
      ['Silence is not evidence', 'A company with no ads on record has not been swept, or runs nothing you can see. The sweep planner records when you last looked so the two are not confused.'],
      ['Seeds are marked and clearable', 'Website intel from August 2026 is a good start and a stale one. Clear it when your own observations outnumber it.'],
      ['Companies, not locations', 'A brand with nine locations advertises as one Page and one Google advertiser, so the ledger keys on the company; the map still shows every location.'],
      ['Inference is provisional', 'Lines, offers, prices and hooks inferred from copy are labeled by the importer and meant to be corrected in the edit form.'],
    ]);
    $('#w13Facts', root).innerHTML = judgList([
      ['Meta Ad Library (web)', 'All active ads from any Page, in any country, with creative, start date, platforms and a Library ID; "See ad details" shows versions and the CTA. Inactive ads, spend and impressions only for political and social issue ads, and for ads shown in the EU (reach by country, targeting parameters).'],
      ['Meta Ad Library API', 'Endpoint ads_archive on graph.facebook.com; requires a developer app and a user access token (identity confirmation for political ads). Parameters: ad_reached_countries, ad_type (ALL, POLITICAL_AND_ISSUE_ADS, HOUSING_ADS, EMPLOYMENT_ADS, CREDIT_ADS), ad_active_status, search_terms or search_page_ids, fields. Rate limited per app.'],
      ['Google Ads Transparency Center', 'adstransparency.google.com; search by advertiser name or website; shows verified advertisers\' ads with format, first and last shown dates and regions; political ad spend only. Ads from unverified advertisers may be absent; Local Services Ads do not appear there. Political ads also ship as a BigQuery public dataset.'],
      ['Local Services Ads', 'No public library. The Google Guaranteed badge appears in the search results for the company name; the SERP link in each card is the check. Ahrefs paid data does not see LSA spend.'],
      ['Special ad categories', 'On Meta, financing creative belongs in the Financial products and services category (15 mile radius minimum, no ZIP, age or gender targeting). A competitor running financing ads with ZIP targeting is itself an observation worth logging.'],
    ]);
    $('#w13Src', root).innerHTML = srcRows([['Competitor roster and intel', 'DFW HVAC Competitive Heatmap, August 18, 2026: Google Business Profile via public listings; Ahrefs; company websites', 'C', 'Aug 2026', ''], ['Meta Ad Library', 'facebook.com/ads/library and the Ad Library API documentation (ads_archive)', 'B', 'read Sep 2026', 'https://www.facebook.com/ads/library/api/'], ['Google Ads Transparency Center', 'adstransparency.google.com and its help center', 'B', 'read Sep 2026', 'https://adstransparency.google.com/'], ['Advertising rules', 'Emergency Satchel rule pack (module 10): TDLR 16 TAC §75.71, Regulation Z §1026.24, FTC guides, DTPA, Meta and Google policies', 'B', '2026', '']]);
    /* ---------- wiring ---------- */
    $('#w13Q', root).addEventListener('input', debounce(e => { st.q = e.target.value.trim().toLowerCase(); st.limit = 20; board(); }, 200));
    $('#w13City', root).onchange = e => { st.city = e.target.value; st.limit = 20; board(); }; $('#w13Line', root).onchange = e => { st.line = e.target.value; st.limit = 20; board(); }; $('#w13Tier', root).onchange = e => { st.tier = e.target.value; st.limit = 20; board(); }; $('#w13Act', root).onchange = e => { st.act = e.target.value; st.limit = 20; board(); }; $('#w13Sort', root).onchange = e => { st.sort = e.target.value; st.limit = 20; board(); };
    wireSeg($('#w13View', root), v => { st.view = v; board(); });
    $('#w13Csv', root).onclick = () => saveFile('competitor-watch-ledger.csv', W.csv()); $('#w13Json', root).onclick = () => saveFile('competitor-watch-ledger.json', W.json());
    $('#w13Sweep', root).onclick = () => saveFile('competitor-sweep-checklist.csv', toCSV(['company', 'domain', 'cities', 'last_checked', 'days_since', 'meta_ad_library_by_name', 'meta_ad_library_page', 'google_transparency_by_domain', 'google_transparency_advertiser', 'google_serp_lsa_check', 'live_ads_on_record'], W.sweepRows(), `Weekly sweep, exported ${W.today()}. Open each link, log what you see in module 13, mark the company checked.`));
    $('#w13Roster', root).onclick = () => saveFile('competitor-watchlist.csv', toCSV(['company', 'domain', 'tier', 'locations', 'cities', 'rating', 'reviews', 'domain_rating', 'organic_visits_month', 'paid_keywords', 'services', 'brands', 'financing_intel', 'promos_intel', 'membership_intel', 'ad_signals_intel', 'meta_page_id', 'google_advertiser_id', 'activity_score', 'live_ads_on_record', 'meta_ad_library', 'google_transparency'], W.COMPANIES.filter(c => !W.isBench(c)).map(c => { const m = W.meta(c.key), I = c.intel || {}; return [c.name, c.domain, c.tier, c.locs.length, c.cities.join('; '), c.rating, c.reviews, c.dr, c.org_traffic, c.paid_kw, c.services.join('; '), c.brands.join('; '), I.financing || '', I.promos || '', I.membership || '', I.ad_signals || '', m.pageId || '', m.advId || '', Math.round(W.score(c)), W.forCompany(c.key).filter(o => o.kind === 'ad' && W.isLive(o)).length, W.LINKS.metaKw(c.name), c.domain ? W.LINKS.googleDomain(c.domain) : '']; }), `Watchlist from the ${W.ROSTER_DATE} roster with the identifiers and scores recorded in this browser.`));
    $('#w13Sat', root).onclick = () => { const c = W.CI[st.sel]; goModule('satchel', c ? { target: c.name, domain: c.domain, posture: 'comp' } : {}); };
    $('#w13Desk', root).onclick = () => goModule('desk', st.zip ? { zips: [st.zip] } : {});
    function renderAll() { kpis(); board(); detail(); analytics(); geo(); sweep(); }
    BUS.on('watch', () => { kpis(); board(); detail(); analytics(); geo(); sweep(); });
    BUS.on('theme', () => { analytics(); geo(); });
    this.receive = p => { if (!p) return; if (isN(p.comp) && COMP[p.comp]) { const k = SLM.compKey(COMP[p.comp]); if (W.CI[k]) select(k); } if (p.line && SLM.LI[p.line]) { st.line = p.line; $('#w13Line', root).value = p.line; board(); } if (p.zip && ZI[p.zip]) { st.zip = p.zip; map.fitTo([p.zip]); geo(); $('#w13Map', root).scrollIntoView({ behavior: 'smooth', block: 'center' }); } };
    apiUrlShow(); form(); renderAll();
  }
});
