/* ==== m14_weather ==== */
"use strict";
/* ============================ Module 14: Weather Desk ============================ */
registerModule({
  key: 'weather', num: '14', title: 'Weather Desk', desc: 'National Weather Service forecast, alerts, outlooks and observations for DFW, turned into hour by hour ad timing',
  mount(root) {
    const st = { line: 'repair', day: 0, hist: 'KDFW' };
    const NS = () => NWSX.state, D_ = () => NWSX.data;
    root.innerHTML = mastHTML({ eyebrow: 'Module 14 · Weather Desk · NWS Fort Worth, Storm Prediction Center, DFW area stations', title: 'Weather Desk', dek: 'Heating and cooling demand in Dallas Fort Worth is written by the thermometer. This desk reads the National Weather Service directly: the seven day and hourly forecasts for the Mesquite grid, the heat index hour by hour, every active alert touching the twelve counties, the Storm Prediction Center\'s severe and hail outlooks, the forecaster\'s own discussion, and what the airports are reporting right now. It turns them into the thing a media buyer needs: which hours to bid up on which service line, for the next seven days.',
      meta: ['<b>Source</b> api.weather.gov and spc.noaa.gov, no key', '<b>Grid</b> FWD 94,105 (Mesquite headquarters)', '<b>Refresh</b> live outside the Claude viewer, cached 30 minutes', '<b>Season</b> DFW Airport, 1953 to today'],
      bar: 'Weather Desk', barsub: 'Forecast, alerts, outlooks, observations, ad timing', actions: [{ id: 'w14Ref', label: '↻ Refresh live' }, { id: 'w14Sched', label: '↓ Ad schedule CSV', title: 'Bid adjustment windows for the selected line' }, { id: 'w14Hourly', label: '↓ Hourly plan CSV' }, { id: 'w14Snap', label: '↓ Weather JSON' }, { id: 'w14Lines', label: 'Service Lines ↗' }, { id: 'w14Desk', label: 'Campaign Desk ↗' }] }) +
      `<div class="wrap">
      <div id="w14Status"></div>
      ${callout('', 'Read this first: what is live, what is baked, and what the hours mean', `The forecast, hourly heat index, alerts, Storm Prediction Center outlooks, station observations and forecast discussion all come from public NWS endpoints. Opened as a file or inside the browser app, the desk fetches them itself and caches the answer for thirty minutes; inside the Claude viewer, whose network rules block page calls, it shows the snapshot baked when this build was compiled and says so at the top. The <b>hour by hour plan</b> multiplies each service line's daypart template (module 12) by a weather factor built from the forecast heat index, temperature, rain and thunder chances and any active alert, then rounds to the 5% steps an ad schedule accepts. It is a bid schedule, not a forecast of calls: the ServiceTitan heat wave finding (+20% calls, +55% revenue) is the size of the effect it is shaped to catch.`)}
      <div class="kpis" id="w14Kpis"></div>
      <div id="w14Alerts"></div>
      ${card('Seven days at the headquarters grid', 'Highs and lows from the NWS raw grid, heat index from the hourly grid, thunder and rain chances, and the line signals each day carries.', '<div class="daystrip" id="w14Days"></div>', 'mt')}
      <div class="split">
        ${card('Hourly heat index, next 72 hours', 'Temperature and heat index by hour with the 95, 100 and 105 lines that move repair demand.', '<div id="w14HourChart"></div><p class="chartnote" id="w14HourN"></p>')}
        ${card('When to run ads: the week in plain words', 'One line per day, plus alerts and the severe outlook on top.', '<ul class="digest" id="w14Narr"></ul>')}
      </div>
      <div class="card mt"><div class="card-h" style="display:flex;gap:12px;align-items:center;flex-wrap:wrap"><div style="flex:1"><h3>Hour by hour bid plan</h3><p>Daypart template × weather factor, rounded to 5%. Click a day to see its hours; the windows table below is what the ad schedule export contains.</p></div><div class="ctl"><label class="fl" for="w14Line">Service line</label><select id="w14Line">${SLM.LINES.map(l => `<option value="${l.id}" ${l.id === st.line ? 'selected' : ''}>${l.short}</option>`).join('')}</select></div></div>
        <div class="card-b"><div class="xscroll" id="w14Grid"></div><div class="dsec">Windows worth a bid adjustment</div><div class="tscroll short" id="w14Win"></div></div></div>
      <div class="split">
        ${card('What the airports are reporting now', 'Latest observations from the DFW area ASOS network, nearest to headquarters first.', '<div class="tscroll short" id="w14Obs"></div><p class="mini" id="w14ObsN"></p>')}
        ${card('The last three days', 'Observed temperature and heat index; the calls that arrive tomorrow were caused by this.', '<div class="seg" id="w14Hist" style="margin-bottom:8px"><button data-v="KDFW" aria-pressed="true">DFW Airport</button><button data-v="KHQZ" aria-pressed="false">Mesquite Metro</button><button data-v="KDAL" aria-pressed="false">Love Field</button></div><div id="w14HistChart"></div>')}
      </div>
      <div class="split">
        ${card('Heat season and freeze season', 'Where this year sits against the record, what the forecast adds, and the odds the climatology gives the coming weeks.', '<div id="w14Season"></div>')}
        ${card('Storm Prediction Center outlook', 'Categorical risk and hail probability over the twelve counties, days one to three. Hail is the replacement line that arrives in an afternoon.', '<div id="w14Spc"></div>')}
      </div>
      ${card('Forecast discussion, NWS Fort Worth', 'The forecaster\'s own words. Key messages first; short and long term below.', '<div id="w14Afd"></div>', 'mt')}
      ${card('How the desk is built', '', '<ol class="meth" id="w14Meth"></ol>', 'mt')}
      <div class="split">${card('Judgment calls', '', '<div id="w14Judg"></div>')}${card('Source register', '', '<div id="w14Src"></div>')}</div>
      <div class="foot">DFW Thermal Debt Atlas, module 14. Weather is the one input here that changes every hour; everything the desk derives from it is a starting bid schedule to be corrected by the account's own hour of day report.</div></div>`;
    const alertColor = a => a.severity === 'Extreme' ? 'var(--critical)' : a.severity === 'Severe' ? 'var(--serious)' : a.severity === 'Moderate' ? 'var(--warning)' : 'var(--ink-3)';
    const fmtT = iso => { const d = new Date(iso); return `${NWSX.DOW[d.getDay()]} ${d.getMonth() + 1}/${d.getDate()} ${NWSX.hh(d.getHours())}`; };
    function status() {
      const s = NS(); const d = D_(); if (!d) { $('#w14Status', root).innerHTML = callout('', 'No weather data', 'The build carries no snapshot and the page cannot reach the National Weather Service from here.'); return; }
      const age = (Date.now() - Date.parse(s.fetched)) / 36e5;
      $('#w14Status', root).innerHTML = callout(s.live ? 'note' : 'judg', s.live ? `Live: fetched ${fmtT(s.fetched)} (${D(age, 1)} h ago)` : `Build snapshot: fetched ${fmtT(s.fetched)} (${D(age, 1)} h ago)`, `${esc(d.source)}. ${s.loading ? 'Refreshing now…' : s.error === 'viewer' ? 'Live refresh is blocked inside the Claude viewer; open the downloaded atlas file or the browser app and the desk updates itself.' : s.error ? 'Last refresh failed: ' + esc(s.error) + '. Showing the most recent data held.' : NWSX.canFetch() ? 'Refreshes automatically every thirty minutes while open; use Refresh live to force it.' : 'Live refresh is blocked inside the Claude viewer; the downloaded atlas file and the browser app update themselves every thirty minutes.'} Forecast grid ${esc(d.point.office)} ${d.point.gridX},${d.point.gridY}, ${esc(d.point.city)}. Forecast updated ${fmtT(d.forecast.updated)}.`);
    }
    function kpis() {
      const d = D_(); if (!d) return; const days = NWSX.days(); const today = days[0] || {}; const al = NWSX.alertsNow(); const s = NWSX.spcNow(); const ss = NWSX.seasonStatus();
      const hq = d.obs.stations.find(x => x.id === 'KHQZ') || d.obs.stations[0] || {}; const h95 = sum(days.slice(0, 7).map(x => x.h95)), h100 = sum(days.slice(0, 7).map(x => x.h100)); const d100 = days.slice(0, 7).filter(x => x.high >= 100).length;
      $('#w14Kpis', root).innerHTML = kpiHTML([
        { l: 'Mesquite Metro now', g: 'A', v: hq.tempF != null ? D(hq.tempF, 0) + '°' : '—', d: `${hq.hiF != null ? 'feels like ' + D(hq.hiF, 0) + '° · ' : ''}${esc(hq.text || '')}${hq.time ? ' · ' + fmtT(hq.time) : ''}` },
        { l: 'Today', g: 'A', v: `${D(today.high, 0)}° / ${D(today.low, 0)}°`, d: `${esc(today.short || '')}${today.maxHI ? ' · heat index to ' + D(today.maxHI, 0) + '°' : ''}` },
        { l: 'Hours at 95°F+ heat index', g: 'A', v: N(h95), d: `next seven days · ${N(h100)} hours at 100°F or more` },
        { l: 'Days at 100°F, forecast', g: 'A', v: N(d100), d: d100 ? `${days.filter(x => x.high >= 100).map(x => x.dow).join(', ')}` : 'none in the seven day forecast' },
        { l: 'Active alerts', g: 'A', v: N(al.length), d: al.length ? esc(al[0].event) + (al.length > 1 ? ` and ${al.length - 1} more` : '') : 'none touching the twelve counties' },
        { l: 'Severe outlook, day 1', g: 'A', v: s && s.day1.cat.max ? esc(s.day1.cat.max) : 'None', d: s && s.day1.hail.max ? `hail ${Math.round(s.day1.hail.max * 100)}% over ${Object.keys(s.day1.hail.counties).length} counties` : (s && s.day1.cat.max ? `${Object.keys(s.day1.cat.counties).length} of 12 counties` : 'no thunderstorm risk drawn') },
        { l: `100°F days in ${String(ss.through).slice(0, 4)}`, g: 'A', v: N(ss.d100), d: `normal ${D(ss.norm, 1)} · record ${ss.record[0]} (${ss.record[1]}) · rank #${ss.rank} of the last century` },
      ]);
    }
    function alerts() {
      const acts = NWSX.alertActions(); const host = $('#w14Alerts', root);
      if (!acts.length) { host.innerHTML = `<div class="callout note" style="margin-top:16px"><span class="ct">No active alerts</span>Nothing from NWS Fort Worth touches the twelve counties right now. The desk checks alerts on every refresh; the browser app also checks in the background and notifies on a new heat, cold, air quality or severe storm product.</div>`; return; }
      host.innerHTML = `<div class="card mt"><div class="card-h"><h3>Active alerts and what they do to the plan</h3><p>Every NWS alert whose zones touch the twelve counties, most severe first, with the standing campaign rule it triggers.</p></div><div class="card-b">${acts.map(({ alert: a, line, action, kind }) => `<div class="alertrow" style="border-left-color:${alertColor(a)}"><div class="ah"><b>${esc(a.event)}</b> <span class="pill">${esc(a.severity || '')}</span> <span class="mini">${esc(a.sender || '')} · ${a.onset ? 'from ' + fmtT(a.onset) : ''}${a.ends ? ' to ' + fmtT(a.ends) : a.expires ? ' · expires ' + fmtT(a.expires) : ''}</span></div><div class="mini" style="margin:3px 0">${esc(a.headline || '')}</div><div class="mini" style="color:var(--ink-2)">${esc(a.counties.length === 12 ? 'All 12 counties' : a.counties.join(', '))}</div><div class="aact"><span class="tag on">${esc(kind)}</span> ${line ? `<span class="tag">${esc(SLM.lineName(line))}</span>` : ''} ${esc(action)}</div><details><summary class="mini">Alert text</summary><p class="mini" style="white-space:pre-wrap">${esc(a.description)}</p>${a.instruction ? `<p class="mini"><b>Instruction:</b> ${esc(a.instruction)}</p>` : ''}</details></div>`).join('')}</div></div>`;
    }
    function dayStrip() {
      const days = NWSX.days().slice(0, 7); const s = NWSX.spcNow();
      $('#w14Days', root).innerHTML = days.map((d, i) => { const sig = []; if (d.maxHI >= 100 || d.high >= 100) sig.push(['repair', 'Repair surge']); else if (d.maxHI >= 95) sig.push(['repair', 'Repair lift']); if (d.thunder >= 30 || (i === 0 && s && s.day1.cat.max) || (i === 1 && s && s.day2.cat.max && s.day2.cat.max !== 'TSTM')) sig.push(['hail', 'Hail watch']); if (d.high >= 62 && d.high <= 88 && d.pop < 40) sig.push(['maint', 'Tune up window']); if (d.low <= 32) sig.push(['heat', 'Heating surge']); if (d.pop >= 50) sig.push(['duct', 'Rain: reschedule attic work']); return `<div class="daycard ${i === st.day ? 'sel' : ''}" data-i="${i}"><div class="dd">${esc(d.dow)} <span class="mini">${d.date.slice(5).replace('-', '/')}</span></div><div class="dt"><b>${D(d.high, 0)}°</b> <span>${D(d.low, 0)}°</span></div><div class="dhi">${d.maxHI ? 'feels ' + D(d.maxHI, 0) + '°' : ''}</div><div class="ds">${esc(d.short)}</div><div class="dp">${d.pop ? '☂ ' + D(d.pop, 0) + '%' : ''}${d.thunder ? ' ⚡ ' + D(d.thunder, 0) + '%' : ''}${d.h100 ? ` · ${d.h100}h ≥100` : d.h95 ? ` · ${d.h95}h ≥95` : ''}</div><div class="dsig">${sig.map(([l, t]) => `<span class="tag ${l === 'repair' || l === 'heat' ? 'on' : ''}">${t}</span>`).join('') || '<span class="mini">quiet</span>'}</div>${d.partial ? '<div class="mini">partial day</div>' : ''}</div>`; }).join('');
      $$('#w14Days .daycard', root).forEach(c => c.onclick = () => { st.day = +c.dataset.i; dayStrip(); grid(); });
    }
    function hourChart() {
      const d = D_(); if (!d) return; const hs = d.hourly.slice(0, 72); const t0 = Date.parse(hs[0].t);
      const x = h => (Date.parse(h.t) - t0) / 36e5;
      const bands = []; hs.forEach((h, i) => { const hr = +h.t.slice(11, 13); if ((hr >= 21 || hr < 6) && (i === 0 || !(bands.length && bands[bands.length - 1].open))) bands.push({ x0: x(h), x1: x(h) + 1, open: true }); else if ((hr >= 21 || hr < 6) && bands.length) bands[bands.length - 1].x1 = x(h) + 1; else if (bands.length && bands[bands.length - 1].open) bands[bands.length - 1].open = false; });
      lineChart($('#w14HourChart', root), { H: 280, series: [{ name: 'Heat index', color: cssv('--heat'), pts: hs.map(h => [x(h), h.hi]), width: 2.6, area: true }, { name: 'Temperature', color: cssv('--cool'), pts: hs.map(h => [x(h), h.tempF]), width: 1.6 }], x: { min: 0, max: 72, ticks: [0, 12, 24, 36, 48, 60, 72], fmt: v => { const t = new Date(t0 + v * 36e5); return `${NWSX.DOW[t.getDay()]} ${NWSX.hh(t.getHours())}`; } }, y: { fmt: v => D(v, 0) + '°', label: '°F' }, bands: bands.map(b => ({ x0: b.x0, x1: b.x1 })), hlines: [{ y: 95, label: '95' }, { y: 100, label: '100' }, { y: 105, label: '105' }], aria: 'Hourly heat index and temperature', tipTitle: v => { const t = new Date(t0 + v * 36e5); return `${NWSX.DOW[t.getDay()]} ${t.getMonth() + 1}/${t.getDate()} ${NWSX.hh(t.getHours())}`; } });
      const svg = $('#w14HourChart svg', root); if (svg) { [95, 100, 105].forEach(v => { }); }
      const h95 = hs.filter(h => h.hi >= 95).length; $('#w14HourN', root).innerHTML = legendRow([{ name: 'Heat index', color: cssv('--heat') }, { name: 'Temperature', color: cssv('--cool') }]) + `${h95} of the next 72 hours carry a heat index of 95°F or more; shaded columns are 9 pm to 6 am. Heat index comes from the NWS raw grid where it publishes one and the Rothfusz regression otherwise.`;
    }
    function grid() {
      const p = NWSX.plan(st.line); const day = p.days[st.day] || p.days[0]; if (!day) { $('#w14Grid', root).innerHTML = '<p class="mini">No hours in the forecast for this day.</p>'; return; }
      const cell = r => { const t = clamp(r.adj / 60, -1, 1); return `<td style="background:color-mix(in srgb, ${t >= 0 ? cssv('--heat') : cssv('--cool')} ${Math.round(Math.abs(t) * 85)}%, ${cssv('--card')});color:${Math.abs(t) > .5 ? '#fff' : 'inherit'}" title="${r.hr}:00 · heat index ${D(r.hi, 0)}° · template ×${D(r.base, 2)} · weather ×${D(r.w, 2)}">${S(r.adj, 0)}%<div class="mini" style="font-size:9.5px;opacity:.85">${D(r.hi, 0)}°</div></td>`; };
      $('#w14Grid', root).innerHTML = `<table class="cm hourgrid"><thead><tr><th class="rh">${esc(day.dow)} ${day.date}</th>${day.rows.map(r => `<th>${NWSX.hh(r.hr)}</th>`).join('')}</tr></thead><tbody><tr><th class="rh">${esc(p.line.short)}</th>${day.rows.map(cell).join('')}</tr></tbody></table><p class="mini" style="margin-top:6px">Template: ${p.observed ? 'observed hour of day from the connected accounts (module 15)' : esc(p.line.dayparts)} · weather factor for ${esc(p.line.short)}: ${st.line === 'repair' ? 'heat index above 85 lifts, 100 and 105 add steps, an active heat alert adds 20%' : st.line === 'heat' ? 'temperature below 45 lifts, 25 and a cold weather alert add steps' : st.line === 'hail' ? 'Storm Prediction Center hail probability and severe thunderstorm products put the line on standby; thunder chance lifts it' : st.line === 'iaq' ? 'air quality alerts and the pollen calendar' : st.line === 'maint' ? 'pleasant dry days lift, very hot days trim (crews are on repairs)' : 'hot and cold extremes lift research modestly'}.</p>`;
      const w = NWSX.windows(st.line);
      $('#w14Win', root).innerHTML = w.length ? `<table><thead><tr><th class="l">Day</th><th class="l">Window</th><th>Bid</th><th>Peak feels like</th><th class="l">Direction</th></tr></thead><tbody>${w.map(x => `<tr><td class="l">${esc(x.dow)} ${x.date.slice(5)}</td><td class="l">${NWSX.hh(x.start)} to ${NWSX.hh(x.end % 24)}</td><td>${S(x.avg, 0)}%</td><td>${D(x.peak, 0)}°</td><td class="l">${x.kind === 'up' ? 'bid up' : 'bid down'}</td></tr>`).join('')}</tbody></table>` : '<p class="mini">No hour in the next seven days moves this line more than 15% either way.</p>';
    }
    function narr() { const n = NWSX.narrative(); $('#w14Narr', root).innerHTML = n.length ? n.map(x => `<li><b>${esc(x.dow)}${x.date && x.date !== 'SPC' && x.date !== 'Alert' ? ' ' + esc(x.date.slice(5).replace('-', '/')) : ''}.</b> ${esc(x.text)}</li>`).join('') : '<li>No forecast days held.</li>'; }
    function obs() {
      const d = D_(); if (!d) return; const rows = d.obs.stations.slice(); const hq = { lat: 32.8063, lon: -96.6609 }; const km = (a, b) => 6371 * Math.acos(Math.min(1, Math.sin(a.lat * Math.PI / 180) * Math.sin(b.lat * Math.PI / 180) + Math.cos(a.lat * Math.PI / 180) * Math.cos(b.lat * Math.PI / 180) * Math.cos((b.lon - a.lon) * Math.PI / 180)));
      rows.forEach(r => r.km = isN(r.lat) ? km(hq, r) : 999); rows.sort((a, b) => a.km - b.km);
      $('#w14Obs', root).innerHTML = `<table><thead><tr><th class="l">Station</th><th>Temp</th><th>Feels</th><th>RH</th><th>Wind</th><th class="l">Sky</th><th>From HQ</th><th class="l">As of</th></tr></thead><tbody>${rows.map(r => `<tr><td class="l"><b>${esc(r.id)}</b> ${esc(r.name)}</td><td>${r.tempF != null ? D(r.tempF, 0) + '°' : '—'}</td><td>${r.hiF != null ? D(r.hiF, 0) + '°' : '—'}</td><td>${r.rh != null ? r.rh + '%' : '—'}</td><td>${r.windMph != null ? D(r.windMph, 0) + ' mph' : '—'}</td><td class="l">${esc(r.text || '')}</td><td>${D(r.km * 0.621, 0)} mi</td><td class="l">${r.time ? fmtT(r.time) : '—'}</td></tr>`).join('')}</tbody></table>`;
      const hot = rows.filter(r => isN(r.hiF)).sort((a, b) => b.hiF - a.hiF)[0]; $('#w14ObsN', root).textContent = hot ? `Hottest right now: ${hot.name} at a heat index of ${D(hot.hiF, 0)}°. Repair calls track the station nearest each ZIP more closely than the airport average.` : '';
    }
    function hist() {
      const d = D_(); if (!d) return; const rows = d.obs.history[st.hist] || []; if (!rows.length) { $('#w14HistChart', root).innerHTML = '<p class="mini">No history held for this station.</p>'; return; }
      const t0 = Date.parse(rows[0].t + ':00Z'); const x = r => (Date.parse(r.t + ':00Z') - t0) / 36e5;
      lineChart($('#w14HistChart', root), { H: 240, series: [{ name: 'Heat index', color: cssv('--heat'), pts: rows.map(r => [x(r), r.hiF]), width: 2.2 }, { name: 'Temperature', color: cssv('--cool'), pts: rows.map(r => [x(r), r.tempF]), width: 1.6 }], x: { min: 0, max: Math.max(24, x(rows[rows.length - 1])), fmt: v => { const t = new Date(t0 + v * 36e5); return `${NWSX.DOW[t.getDay()]} ${NWSX.hh(t.getHours())}`; } }, y: { fmt: v => D(v, 0) + '°' }, hlines: [{ y: 95, label: '95' }, { y: 100, label: '100' }], aria: 'Observed temperature and heat index', tipTitle: v => { const t = new Date(t0 + v * 36e5); return `${NWSX.DOW[t.getDay()]} ${t.getMonth() + 1}/${t.getDate()} ${NWSX.hh(t.getHours())}`; } });
    }
    function season() {
      const ss = NWSX.seasonStatus(); const C = SLM.CLIM; const m = new Date().getMonth(); const nm = (m + 1) % 12; const M = SLM.MONTHS;
      $('#w14Season', root).innerHTML = `<div class="qbox"><div class="qb"><div class="qt">100°F days so far</div><div class="qv">${N(ss.d100)}</div><div class="qd">through ${esc(ss.through)} · normal full year ${D(ss.norm, 1)}</div></div><div class="qb"><div class="qt">Cooling degree days</div><div class="qv">${N(ss.cdd)}</div><div class="qd">normal to date ${N(ss.normCdd)} (${S((ss.cdd / ss.normCdd - 1) * 100, 0)}%)</div></div><div class="qb"><div class="qt">Rank</div><div class="qv">#${ss.rank}</div><div class="qd">record ${ss.record[0]} days in ${ss.record[1]}</div></div><div class="qb"><div class="qt">Next 100°F day</div><div class="qv">${ss.next100 ? esc(ss.next100.slice(5).replace('-', '/')) : 'None'}</div><div class="qd">${ss.forecastRun ? `${ss.forecastRun} consecutive forecast days at 100` : 'in the seven day forecast'}</div></div></div>
        <div class="dsec">Climatology for ${M[m]} and ${M[nm]} (1996 to 2025)</div><table><thead><tr><th class="l">Odds in the month</th><th>${M[m]}</th><th>${M[nm]}</th></tr></thead><tbody><tr><td class="l">At least one 100°F day</td><td>${P(C.p100[m], 0)}</td><td>${P(C.p100[nm], 0)}</td></tr><tr><td class="l">At least one 95°F day</td><td>${P(C.p95[m], 0)}</td><td>${P(C.p95[nm], 0)}</td></tr><tr><td class="l">Average 95°F days</td><td>${D(C.m95[m], 1)}</td><td>${D(C.m95[nm], 1)}</td></tr><tr><td class="l">Hard freeze (20°F or lower)</td><td>${P(C.pfr20[m], 0)}</td><td>${P(C.pfr20[nm], 0)}</td></tr><tr><td class="l">25°F or lower</td><td>${P(C.pfr25[m], 0)}</td><td>${P(C.pfr25[nm], 0)}</td></tr><tr><td class="l">Average high · low</td><td>${D(C.tmax[m], 0)}° · ${D(C.tmin[m], 0)}°</td><td>${D(C.tmax[nm], 0)}° · ${D(C.tmin[nm], 0)}°</td></tr></tbody></table><p class="mini" style="margin-top:8px">The heating campaigns open on the first forecast freeze; the odds above say when to have them built. Module 12 carries the full twelve month table.</p>`;
    }
    function spc() {
      const s = NWSX.spcNow(); if (!s) { $('#w14Spc', root).innerHTML = '<p class="mini">No outlook held.</p>'; return; }
      const CATN = { TSTM: 'General thunderstorms', MRGL: 'Marginal (1 of 5)', SLGT: 'Slight (2 of 5)', ENH: 'Enhanced (3 of 5)', MDT: 'Moderate (4 of 5)', HIGH: 'High (5 of 5)' };
      const byC = (o, fmt) => { if (!o || !o.counties) return ''; const e = Object.entries(o.counties); if (!e.length) return 'none'; const vals = [...new Set(e.map(x => String(x[1])))]; if (vals.length === 1) return `${e.length} of 12: ${e.map(x => x[0]).join(', ')}`; return e.map(([c, v]) => `${c} ${fmt(v)}`).join(', '); }; const row = (lab, o, fmt) => `<tr><td class="l">${lab}</td><td>${o && o.max != null ? fmt(o.max) : '—'}</td><td class="l wrap">${byC(o, fmt)}</td></tr>`;
      $('#w14Spc', root).innerHTML = `<table><thead><tr><th class="l">Product</th><th>Highest</th><th class="l">By county</th></tr></thead><tbody>${row('Day 1 categorical', s.day1.cat, v => CATN[v] || v)}${row('Day 1 hail probability', s.day1.hail, v => Math.round(v * 100) + '%')}${row('Day 1 wind probability', s.day1.wind, v => Math.round(v * 100) + '%')}${row('Day 1 tornado probability', s.day1.torn, v => Math.round(v * 100) + '%')}${row('Day 2 categorical', s.day2.cat, v => CATN[v] || v)}${row('Day 2 hail probability', s.day2.hail, v => Math.round(v * 100) + '%')}${row('Day 3 categorical', s.day3.cat, v => CATN[v] || v)}</tbody></table><p class="mini" style="margin-top:8px">Hail probability is the chance of 1 inch or larger hail within 25 miles of a point. The hail line's rule: at 15% or more, stage creative and geo fences; after the storm, launch inside the swath of 1.75 inch reports within 72 hours (module 12). ${s.day1.cat.valid ? 'Day 1 valid ' + esc(s.day1.cat.valid) + ' to ' + esc(s.day1.cat.expire) + ' UTC.' : ''}</p>`;
    }
    function afd() {
      const d = D_(); const a = d && d.afd; if (!a) { $('#w14Afd', root).innerHTML = '<p class="mini">No discussion held.</p>'; return; }
      $('#w14Afd', root).innerHTML = `<p class="mini">${esc(a.office)} · issued ${a.issued ? fmtT(a.issued) : ''}</p><ul class="digest">${(a.keyMessages || []).map(k => `<li>${esc(k)}</li>`).join('')}</ul><details style="margin-top:10px"><summary>Short term</summary><p class="body" style="white-space:pre-wrap;margin-top:8px">${esc(a.shortTerm)}</p></details><details style="margin-top:6px"><summary>Long term</summary><p class="body" style="white-space:pre-wrap;margin-top:8px">${esc(a.longTerm)}</p></details>`;
    }
    $('#w14Meth', root).innerHTML = [
      '<b>Point and grid.</b> The headquarters coordinates (32.8063, minus 96.6609) resolve to NWS Fort Worth grid FWD 94,105. The desk pulls the seven day forecast, the hourly forecast and the raw grid (maximum and minimum temperature, heat index, apparent temperature, thunder and rain probabilities, sky cover, wind gust, hazards, heat risk).',
      '<b>Heat index.</b> The raw grid\'s heatIndex series where it exists; otherwise the NWS Rothfusz regression on temperature and relative humidity, with the low and high humidity adjustments, applied only at 80°F and above.',
      '<b>Alerts.</b> All active Texas alerts, filtered to those whose UGC codes include one of the twelve forecast zones or county codes. Each event maps to a standing campaign rule: heat products to repair surges, air quality to indoor air, severe storm products to hail standby, winter products to heating surges, floods to a hold.',
      '<b>Outlooks.</b> Storm Prediction Center day 1 to 3 categorical polygons and day 1 and 2 hail, wind and tornado probabilities, evaluated at the twelve county centroids by point in polygon.',
      '<b>Observations.</b> Latest reports from fourteen ASOS stations in the metro and up to seventy two hours of history for DFW Airport, Mesquite Metro and Love Field.',
      '<b>Plan.</b> For each of the next 168 hours, the daypart template for the line (module 12) times a weather factor; the product minus one becomes a bid adjustment rounded to 5% and clamped to minus 50 to plus 90. Contiguous hours at plus 15 or more, or minus 25 or less, become the windows in the ad schedule export.',
      '<b>Refresh.</b> Outside the Claude viewer the desk fetches on open and every thirty minutes, keeps the last good answer in browser storage, and shows the snapshot from the build when nothing else is available. The browser app checks in the background and notifies on new alerts.',
    ].map(x => `<li>${x}</li>`).join('');
    $('#w14Judg', root).innerHTML = judgList([['One grid point for twelve counties', 'The headquarters grid stands in for the metro. Denton and Cleburne run two to four degrees apart from Mesquite on most afternoons; the station table shows the spread, and the browser app can be pointed at another grid in its options.'], ['Bid steps, not a demand model', 'The weather factor is shaped to the ServiceTitan heat wave finding and the atlas seasons; it is not fitted to this account\'s call log. Thirty days of hour of day data from the account should replace the template half of the product.'], ['Hail is a standby, not a bid', 'Severe weather is too local for a schedule. The desk stages the hail line when the outlook or a watch says so and leaves the launch to the 72 hour rule in module 12.'], ['Alerts filtered by zone, not by polygon', 'An alert is counted when its zones touch a county, even if its polygon covers a corner of it.']]);
    $('#w14Src', root).innerHTML = srcRows([['Forecast, grid, hourly', 'National Weather Service API, gridpoints FWD 94,105', 'A', 'live', 'https://api.weather.gov/'], ['Alerts', 'National Weather Service API, active alerts for Texas, filtered to the twelve counties', 'A', 'live', 'https://api.weather.gov/alerts/active?area=TX'], ['Observations', 'National Weather Service API, station observations (ASOS)', 'A', 'live', 'https://api.weather.gov/stations/KDFW/observations'], ['Convective outlooks', 'Storm Prediction Center day 1 to 3 outlook GeoJSON', 'A', 'live', 'https://www.spc.noaa.gov/products/outlook/'], ['Forecast discussion', 'NWS Fort Worth Area Forecast Discussion (AFD)', 'A', 'live', 'https://forecast.weather.gov/product.php?site=FWD&product=AFD&issuedby=FWD'], ['Heat index', 'NWS Weather Prediction Center heat index equation (Rothfusz 1990)', 'A', '', 'https://www.wpc.ncep.noaa.gov/html/heatindex_equation.shtml'], ['Season records', 'DFW Airport daily records 1953 to 2026 (atlas weather file)', 'A', 'Sep 2026', 'https://www.weather.gov/fwd/d100data']]);
    function renderAll() { status(); kpis(); alerts(); dayStrip(); hourChart(); narr(); grid(); obs(); hist(); season(); spc(); afd(); }
    $('#w14Line', root).onchange = e => { st.line = e.target.value; grid(); };
    wireSeg($('#w14Hist', root), v => { st.hist = v; hist(); });
    $('#w14Ref', root).onclick = () => { if (!NWSX.canFetch()) { toast('Live refresh is blocked inside the Claude viewer; open the atlas file or the browser app'); return; } toast('Refreshing from the National Weather Service…'); NWSX.refresh(true); };
    $('#w14Sched', root).onclick = () => saveFile(`ad-schedule_${st.line}_${new Date().toISOString().slice(0, 10)}.csv`, NWSX.scheduleCSV(st.line));
    $('#w14Hourly', root).onclick = () => saveFile(`hourly-bid-plan_${st.line}.csv`, NWSX.hourlyCSV(st.line));
    $('#w14Snap', root).onclick = () => saveFile('nws-dfw-weather.json', NWSX.snapshotJSON());
    $('#w14Lines', root).onclick = () => goModule('lines', { line: st.line }); $('#w14Desk', root).onclick = () => goModule('desk', { line: SLM.LI[st.line] && LINES[SLM.LI[st.line].desk] ? SLM.LI[st.line].desk : 'repair' });
    BUS.on('nws', () => { renderAll(); }); BUS.on('theme', () => { hourChart(); hist(); grid(); }); BUS.on('acct', () => { if (root.isConnected) grid(); });
    renderAll();
    if (NWSX.canFetch()) NWSX.refresh(false);
    this.receive = p => { if (p && p.line && SLM.LI[p.line]) { st.line = p.line; $('#w14Line', root).value = p.line; grid(); } };
  }
});
